<meta name="theme-color" content="#d6d2ca" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#1f1e1c" media="(prefers-color-scheme: dark)">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono:ital,wght@0,400;0,700;1,400&display=swap">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
<link rel="stylesheet" href="style.css">
<script src="hl.js" defer></script>
<script src="pop.js" defer></script>
<style>pre, pre.py { font-size: clamp(8px, 2.2vw, 11px); }</style>
