% CSCounselling  (node/2 edge/3 dep/2 dec/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
node(considerationOfFeedbackManagers,softgoal).
node(learnWebTechnologies,task).
leaf(learnWebTechnologies).
node(provideWrittenCounselling1,task).
node(promoteCS2,task).
node(increaseNumberOfCounsellors1,softgoal).
leaf(increaseNumberOfCounsellors1).
node(promoteCS,task).
node(enthusiasticWorkAtmosphere,softgoal).
node(reduceMonitoringOfActivities,softgoal).
node(cuttingAndPastingBeAddedToWebPostingSoftware,goal).
leaf(cuttingAndPastingBeAddedToWebPostingSoftware).
topgoal(cuttingAndPastingBeAddedToWebPostingSoftware).
node(getRidOfUnion,goal).
leaf(getRidOfUnion).
topgoal(getRidOfUnion).
node(completeResourceLinks4,softgoal).
node(decreaseClumsinessTechnology2,softgoal).
node(encourageKidsToTalkToDifferentCounsellors,task).
leaf(encourageKidsToTalkToDifferentCounsellors).
node(informationResourcesBeFound,goal).
topgoal(informationResourcesBeFound).
node(provideCounselling3,task).
node(supportIndividualityInCounsellingTechniques,softgoal).
node(moveOnToBetterJob,softgoal).
node(informationInELibrary,resource).
node(undergoClinicalReview1,task).
node(avoidPressureToPerformDutiesQuickly,softgoal).
node(receiveTrainingFromManagment,task).
leaf(receiveTrainingFromManagment).
node(exploreOptions,task).
leaf(exploreOptions).
node(signContract,task).
node(participateInEvents1,task).
leaf(participateInEvents1).
node(trainingCDs,resource).
leaf(trainingCDs).
node(implementEmailForCounsellors,task).
node(tapeRecordingTechnology,resource).
leaf(tapeRecordingTechnology).
node(patientCounselor,softgoal).
node(increaseFeedback,softgoal).
node(beConsultedAboutNewPolicies,goal).
leaf(beConsultedAboutNewPolicies).
topgoal(beConsultedAboutNewPolicies).
node(helpAsManyKidsAsPossible2,softgoal).
node(simpleTechnology1,softgoal).
leaf(simpleTechnology1).
node(provideInformationToOtherCounselloers,task).
leaf(provideInformationToOtherCounselloers).
node(logIntoActivityManager,task).
node(recognition2,softgoal).
node(findInformationInLibrary,task).
node(recordStories,task).
leaf(recordStories).
node(currentResourceLinks2,softgoal).
node(moderateDiscussionBoards,task).
node(increasedPeerSupport1,softgoal).
node(accommodateSchedules,softgoal).
node(provideSupportToCounsellors,task).
node(accessibleResourcesForCounselors,softgoal).
node(empoweringKidsToHelpThemselves2,softgoal).
node(improveCounsellingSkills1,softgoal).
node(provideResourcesInLibrary,task).
leaf(provideResourcesInLibrary).
node(acquirePublicSpeakingSkills,softgoal).
node(consistentResourceLinks,softgoal).
node(easierToFindPostsWebPostingTechnology1,softgoal).
leaf(easierToFindPostsWebPostingTechnology1).
node(accessibleResourcesForCounselors2,softgoal).
node(writeArticlesForMagazines,task).
node(improveITSkills3,softgoal).
node(avoidBeingLabelledAntiTechnology,softgoal).
node(performDutiesQuickly,softgoal).
node(improveQualityAssuranceTechnology2,softgoal).
node(listenForCues,task).
leaf(listenForCues).
node(speakAtSAConferences,task).
leaf(speakAtSAConferences).
node(webSiteContent,resource).
node(provideWebCounsellingWithVideo,task).
node(highQualityCounselling,softgoal).
node(rememberLocationsOfResouces2,softgoal).
node(counsellorsEngageEmotionallyInSession,softgoal).
node(controlOfCounsellingWork1,softgoal).
leaf(controlOfCounsellingWork1).
node(increasedCautionContentOfOnlineServices1,softgoal).
node(controlOfFloorOperations,softgoal).
leaf(controlOfFloorOperations).
node(participateInSponsorMeetings,task).
leaf(participateInSponsorMeetings).
node(improveWebPostingTechnology1,softgoal).
node(decreaseDifficultiesWithTechnology,softgoal).
node(toolsToBurnNegativeEnergyBePresent,goal).
topgoal(toolsToBurnNegativeEnergyBePresent).
node(completeResourceLinks1,softgoal).
node(provideWebCounsellingWithAudio,task).
node(counsellorsBeUnionized,goal).
topgoal(counsellorsBeUnionized).
node(allowUserToLogIn1,goal).
leaf(allowUserToLogIn1).
topgoal(allowUserToLogIn1).
node(itSystemsBeIntegrated1,goal).
topgoal(itSystemsBeIntegrated1).
node(highQualityResources2,softgoal).
node(retainJob,softgoal).
node(improveWebPostingTechnology,softgoal).
node(reduceStaggeringOfSchedules,softgoal).
node(performEmailCounselling1,task).
node(trainingBeReceived2,goal).
topgoal(trainingBeReceived2).
node(increaseITTrainingForCounsellors,softgoal).
leaf(increaseITTrainingForCounsellors).
node(acquirePublicSpeakingSkills2,softgoal).
node(happinessCounsellors,softgoal).
node(referParentsToPHL,task).
leaf(referParentsToPHL).
node(improveCounsellingSkills,softgoal).
node(resourcesInTheLibrary,resource).
node(avoidRelationshipsWithSpecificCounsellor1,softgoal).
node(acquireFeedback,task).
node(reducePrankCalls1,softgoal).
node(receiveAdditionalTrainingAsAnExperiencedCousnellor,task).
node(easilyAccessableTechnologyInstructions1,softgoal).
leaf(easilyAccessableTechnologyInstructions1).
node(recognition1,softgoal).
node(improveQualityAssuranceTechnology,softgoal).
node(accessibleResourcesForCounselors6,softgoal).
node(webCounsellingBePerformed1,task).
node(clinicalSupervisorsListenToCalls,goal).
topgoal(clinicalSupervisorsListenToCalls).
node(aResolutionFocusApproachBeUsed,goal).
leaf(aResolutionFocusApproachBeUsed).
topgoal(aResolutionFocusApproachBeUsed).
node(listenToCallsOfExperiencedCounsellors,task).
leaf(listenToCallsOfExperiencedCounsellors).
node(effectiveDebriefing,softgoal).
node(csStories,softgoal).
node(writeArticlesForWebsite1,task).
leaf(writeArticlesForWebsite1).
node(increasedCautionContentOfOnlineServices,softgoal).
node(performTheJobOfCounselling,task).
node(assessSituation,task).
leaf(assessSituation).
node(provideResourcesInELibrary,task).
leaf(provideResourcesInELibrary).
node(decreaseWorkDifficulty,softgoal).
node(voiceCounselling,softgoal).
leaf(voiceCounselling).
node(accessibleResourcesForCounselors1,softgoal).
node(feedbackOnCallsBeGiven,goal).
topgoal(feedbackOnCallsBeGiven).
node(manageCounsellingResources,task).
node(improvedWritingSkillsCounsellors,softgoal).
node(decreaseClumsinessTechnology1,softgoal).
leaf(decreaseClumsinessTechnology1).
node(receiveTrainingAsANewCounsellor,task).
node(facilitateFasterChangesInCounsellorDuties,softgoal).
node(iconsForCounsellingInformationBeOnDesktop,goal).
leaf(iconsForCounsellingInformationBeOnDesktop).
topgoal(iconsForCounsellingInformationBeOnDesktop).
node(easilyAccessableTechnologyInstructions,softgoal).
node(avoidLiabilityProblems1,softgoal).
node(receiveInformationFromOtherCounsellors,task).
node(kidsBePreparedForFormalAbuseReportingProcess,goal).
leaf(kidsBePreparedForFormalAbuseReportingProcess).
topgoal(kidsBePreparedForFormalAbuseReportingProcess).
node(consistentResourceLinks1,softgoal).
node(includeLegalInformationInCounsellingResources,task).
leaf(includeLegalInformationInCounsellingResources).
node(anonymityCounsellors,softgoal).
leaf(anonymityCounsellors).
node(avoidDialoguesWebServices1,softgoal).
node(reportOutdatedLinks1,task).
leaf(reportOutdatedLinks1).
node(rememberLocationsOfResouces1,softgoal).
node(improveWebPostingTechnology2,softgoal).
node(considerationOfFeedbackITProviders1,softgoal).
leaf(considerationOfFeedbackITProviders1).
node(completeResourceLinks2,softgoal).
node(performCounsellingAsInstructedBySupervisor,softgoal).
leaf(performCounsellingAsInstructedBySupervisor).
node(counsellingWorkshops,resource).
leaf(counsellingWorkshops).
node(prepareTechnicalPhoneEnvironment,task).
node(highDegreeOfSimilarityBetweenServicesProvided,softgoal).
node(helpAsManyKidsAsPossible3,softgoal).
node(engageInDialogWithCounselled,softgoal).
leaf(engageInDialogWithCounselled).
node(helpAsManyKidsAsPossible,softgoal).
node(acquireRecognizableEmploymentExperience,softgoal).
node(counsellingPoliciesBeFollowed,goal).
topgoal(counsellingPoliciesBeFollowed).
node(webModeratorMeetings,resource).
leaf(webModeratorMeetings).
node(considerationOfFeedbackITProviders,softgoal).
node(commentOnTechnologyUsabilityIssues,task).
leaf(commentOnTechnologyUsabilityIssues).
node(improveCommunicationBetweenCounsellors,softgoal).
node(consistentResourceLinks2,softgoal).
node(editOnlinePostsOfKids,task).
node(encourageKidsToCallCS,task).
leaf(encourageKidsToCallCS).
node(improveITSkills1,softgoal).
node(accessibleResourcesForCounselors5,softgoal).
node(decreaseFactoryWorkerAtmosphere,softgoal).
node(increaseNumberOfCounsellors,softgoal).
node(removeInappropriateMaterial,task).
node(passProbationWithinSixMonths,goal).
leaf(passProbationWithinSixMonths).
topgoal(passProbationWithinSixMonths).
node(comfortableWithPerceivedPurposeOfTechnology,softgoal).
node(happinessCounsellors1,softgoal).
node(writeArticlesForWebsite,task).
node(listenToCallsOfNewCounsellors,task).
node(promoteCounselling,task).
node(situationBeDealtWith,goal).
topgoal(situationBeDealtWith).
node(provideWebCounsellingWithVideo1,task).
node(avoidTensionConfrontationAnimosityAmongstEmployees,softgoal).
node(currentResourceLinks3,softgoal).
node(decreaseKidsIsolation,softgoal).
node(itSystemsBeIntegrated,goal).
leaf(itSystemsBeIntegrated).
topgoal(itSystemsBeIntegrated).
node(increasedCautionContentOfOnlineServices2,softgoal).
node(performCounsellingAsInstructedBySupervisor1,softgoal).
node(requestShifts,task).
leaf(requestShifts).
node(voiceCounsellingBePerformed,task).
node(beAMentorToNewCounsellors,goal).
leaf(beAMentorToNewCounsellors).
topgoal(beAMentorToNewCounsellors).
node(informationResources,resource).
node(receiveSalary,task).
node(helpKids1,softgoal).
node(improveCallRecordingEquipment,softgoal).
node(reduceNumberOfStepsWebPostingTechnology1,softgoal).
leaf(reduceNumberOfStepsWebPostingTechnology1).
node(highQualityCounselling1,softgoal).
node(counsellorExperience,resource).
node(avoidBeingDirective,softgoal).
node(counsellorsPoliceThemselves,softgoal).
leaf(counsellorsPoliceThemselves).
node(increasedPeerSupport,softgoal).
node(logIntoPhoneSystem,task).
node(haveClinicalSupervisorsListenToCalls,task).
node(clearerCallClassificationCatagories,softgoal).
node(highQualityResources3,softgoal).
node(counsellingPoliciesBeFollowed1,goal).
topgoal(counsellingPoliciesBeFollowed1).
node(increaseITMethodsToAcquireFeedback1,softgoal).
leaf(increaseITMethodsToAcquireFeedback1).
node(counsellingPolicies,resource).
leaf(counsellingPolicies).
node(increaseEmphasisOnOnlineFeedbackForm1,softgoal).
leaf(increaseEmphasisOnOnlineFeedbackForm1).
node(controlOfCounsellingWork,softgoal).
node(performCrisisIntervention,task).
leaf(performCrisisIntervention).
node(reduceContagionEffectOfHarmfulActions1,softgoal).
node(safety,softgoal).
node(acquirePublicSpeakingSkills1,softgoal).
node(attendPartTimeMeeting,task).
leaf(attendPartTimeMeeting).
node(categorizeCall,task).
node(performFirstReadingOfCounsellingPosts,task).
node(improveCallRecordingEquipment1,softgoal).
leaf(improveCallRecordingEquipment1).
node(webCounsellingBePerformed2,task).
node(performConferenceCallWithThirdParty,task).
leaf(performConferenceCallWithThirdParty).
node(highDegreeOfSimilarityBetweenServicesProvided2,softgoal).
node(considerationOfFeedbackManagers1,softgoal).
leaf(considerationOfFeedbackManagers1).
node(blockKidsWhoDisplayInappropriateBehavoir,task).
leaf(blockKidsWhoDisplayInappropriateBehavoir).
node(moderateDiscussionBoards1,task).
node(encourageKidsToTalkToOthers,task).
leaf(encourageKidsToTalkToOthers).
node(findInformationInBinders,task).
node(createWebSiteContent,task).
node(voiceCounsellingBePerformed1,task).
node(feedback,resource).
leaf(feedback).
node(includeDrugInformationInCounsellingResources,task).
leaf(includeDrugInformationInCounsellingResources).
node(implementCategorizationTool,task).
leaf(implementCategorizationTool).
node(undergoMediaTraining,task).
leaf(undergoMediaTraining).
node(improveITSkills,softgoal).
node(professionalWorkEnvironment,softgoal).
node(receiveFeedback,task).
node(consistentCounsellingResponses,softgoal).
node(performCounsellingAsInstructedBySupervisor2,softgoal).
node(participateInBoardMeetings,task).
leaf(participateInBoardMeetings).
node(prideInJob,softgoal).
node(reducePhysicalObservationHearingByStaffNotInCounsellingTeam,softgoal).
leaf(reducePhysicalObservationHearingByStaffNotInCounsellingTeam).
node(reduceContagionEffectOfHarmfulActions,softgoal).
node(signContractWithCounsellingUnion,task).
leaf(signContractWithCounsellingUnion).
node(situationBeDealtWith1,goal).
topgoal(situationBeDealtWith1).
node(assessSituation1,task).
leaf(assessSituation1).
node(receiveCallClassificationTraining,task).
leaf(receiveCallClassificationTraining).
node(effectiveUseOfTechnologyCounsellors1,softgoal).
node(positiveEmploymentEvaluation,softgoal).
node(simpleTechnology,softgoal).
node(briefTherapyCounsellingBeUsed,goal).
leaf(briefTherapyCounsellingBeUsed).
topgoal(briefTherapyCounsellingBeUsed).
node(highQualityCounselling2,softgoal).
node(reduceStaggeringOfSchedules1,softgoal).
leaf(reduceStaggeringOfSchedules1).
node(recognition,softgoal).
leaf(recognition).
node(completeResourceLinks3,softgoal).
node(salary,softgoal).
leaf(salary).
node(reducePrankCalls,softgoal).
leaf(reducePrankCalls).
node(increasedPeerSupport2,softgoal).
node(correctInterpretationOfCounsel,softgoal).
node(accountabilityOfServices,softgoal).
node(implementEmailForCounsellors2,task).
node(increaseITTraining,softgoal).
node(increasedPeerSupport3,softgoal).
node(webPostsBeReviewedByClinicalSupervisor,goal).
leaf(webPostsBeReviewedByClinicalSupervisor).
topgoal(webPostsBeReviewedByClinicalSupervisor).
node(editCounsellingPosts,task).
leaf(editCounsellingPosts).
node(allowUserToLogIn,goal).
leaf(allowUserToLogIn).
topgoal(allowUserToLogIn).
node(undergoClinicalReview,task).
node(diffuseConflictWithParent,task).
leaf(diffuseConflictWithParent).
node(decreaseWorkLoad,softgoal).
node(helpKids,softgoal).
node(reportAbuses,task).
leaf(reportAbuses).
node(highDegreeOfSimilarityBetweenServicesProvided1,softgoal).
node(provideWebCounsellingWithAudio1,task).
node(removeIdentifyingMaterial,task).
leaf(removeIdentifyingMaterial).
node(findEffectiveCues,softgoal).
node(improveCounsellingSkills3,softgoal).
node(professionalWorkEnvironment1,softgoal).
node(accessibleResourcesForCounselors4,softgoal).
node(tapes,resource).
leaf(tapes).
node(releaseTension,softgoal).
node(reportOutdatedLinks,task).
node(webResponsesBeGeneric1,softgoal).
node(currentResourceLinks4,softgoal).
node(trainingBeReceived,goal).
topgoal(trainingBeReceived).
node(mentoringBeReceivedFromExperiencedCounsellors,goal).
leaf(mentoringBeReceivedFromExperiencedCounsellors).
topgoal(mentoringBeReceivedFromExperiencedCounsellors).
node(increaseEmphasisOnOnlineFeedbackForm,softgoal).
node(meetingBeAttended,goal).
topgoal(meetingBeAttended).
node(provideWrittenCounselling,task).
node(callerStatistics,resource).
node(provideCounselling,task).
node(promoteCS1,task).
node(speakPubliclyAboutJob,task).
leaf(speakPubliclyAboutJob).
node(voiceCounsellingBePerformed3,task).
node(exploreOptions1,task).
leaf(exploreOptions1).
node(collectCallerSituationStatistics,task).
node(provideCounselling2,task).
node(accountabilityOfServices1,softgoal).
node(receiveTrainingFromCounsellors,task).
node(empoweringKidsToHelpThemselves,softgoal).
node(currentResourceLinks,softgoal).
node(decreaseClumsinessTechnology,softgoal).
node(attendWebModeratorMeetings,task).
node(effectiveUseOfTechnologyCounsellors2,softgoal).
node(increaseConnectionBetweenCounsellorsAndCounselled,softgoal).
node(debriefWithCounsellors,task).
leaf(debriefWithCounsellors).
node(accommodateSchedules1,softgoal).
leaf(accommodateSchedules1).
node(improvedWritingSkills,softgoal).
leaf(improvedWritingSkills).
node(undergoCDBasedTraining,task).
node(doubleHeadsets,resource).
leaf(doubleHeadsets).
node(moderateAChat1,task).
node(findInformationInELibrary,task).
node(implementBulletinBoard1,task).
leaf(implementBulletinBoard1).
node(provideInformation1,task).
node(createCounsellingPosts1,task).
node(provideInformation2,task).
node(currentResourceLinks1,softgoal).
node(webCounsellingBePerformed3,task).
node(avoidDialoguesWebServices,softgoal).
leaf(avoidDialoguesWebServices).
node(improveITSkills2,softgoal).
node(reduceNumberOfStepsWebPostingTechnology,softgoal).
node(provideInformationInBinders,task).
leaf(provideInformationInBinders).
node(diffuseConflictWithParent1,task).
node(voiceCounsellingBePerformed2,task).
node(empoweringKidsToHelpThemselves1,softgoal).
node(accessibleResourcesForCounselors3,softgoal).
node(varietyInWork,softgoal).
node(increaseITMethodsToAcquireFeedback,softgoal).
node(provideInformation,task).
node(avoidLiabilityProblems,softgoal).
node(webCounsellingBePerformed4,task).
node(clearerCallClassificationCatagories1,softgoal).
leaf(clearerCallClassificationCatagories1).
node(provideCounselling1,task).
node(improveQualityAssuranceTechnology1,softgoal).
node(completeResourceLinks,softgoal).
node(moderateAChat,task).
node(anonymity,softgoal).
node(avoidBurnout,softgoal).
node(performEmailCounselling,task).
node(webResponsesBeGeneric,softgoal).
leaf(webResponsesBeGeneric).
node(counselorSpeakOnKidsIssuesInGeneral1,task).
leaf(counselorSpeakOnKidsIssuesInGeneral1).
node(increaseCSAwareness1,softgoal).
leaf(increaseCSAwareness1).
node(resourcesBeProvided,goal).
topgoal(resourcesBeProvided).
node(createCounsellingPosts,task).
node(informationBindersAtStations,resource).
node(highQualityCounselling3,softgoal).
node(easierToFindPostsWebPostingTechnology,softgoal).
node(highQualityResources,softgoal).
node(increaseCSAwareness,softgoal).
node(effectiveUseOfTechnologyCounsellors,softgoal).
node(accountabilityOfServices2,softgoal).
node(facilitateFasterChangesInCounsellorDuties1,softgoal).
node(highQualityResources1,softgoal).
node(provideResourcesInOneSource,task).
leaf(provideResourcesInOneSource).
node(implementEmailForCounsellors1,task).
leaf(implementEmailForCounsellors1).
node(updateOutdatedLinks,task).
node(deepenCounsellingSession,softgoal).
leaf(deepenCounsellingSession).
node(helpAsManyKidsAsPossible1,softgoal).
node(trainingBeReceived1,goal).
topgoal(trainingBeReceived1).
node(correctInterpretationOfCounsel1,softgoal).
leaf(correctInterpretationOfCounsel1).
node(avoidShortStaffing,softgoal).
node(acquirePublicSpeakingSkills3,softgoal).
node(makeTapesForClinicalReview,task).
node(webCounsellingBePerformed,task).
node(improveCounsellingSkills2,softgoal).
node(undergoClinicalReview2,task).
node(implementBulletinBoard,task).
node(counselorSpeakOnKidsIssuesInGeneral,task).
node(provideTrainingToNewCounsellors,task).
node(attendCounsellingWorkshops,task).
node(avoidRelationshipsWithSpecificCounsellor,softgoal).
node(rememberLocationsOfResouces,softgoal).
leaf(rememberLocationsOfResouces).
node(provideResourcesAsCurrentlyDone,task).
node(writeArticlesForMagazines1,task).
leaf(writeArticlesForMagazines1).
node(patientCounselor1,softgoal).
node(webResponsesBeGeneric2,softgoal).
node(participateInEvents,task).
node(diffuseConflictWithParent2,task).
edge(professionalWorkEnvironment1,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(decreaseDifficultiesWithTechnology,performDutiesQuickly,0.5).
dep(increasedPeerSupport1,increasedPeerSupport3).
dec(trainingBeReceived2,performTheJobOfCounselling,or).
edge(deepenCounsellingSession,webCounsellingBePerformed,-0.5).
dec(reportAbuses,provideCounselling,or).
dep(writeArticlesForMagazines1,writeArticlesForMagazines).
edge(increaseFeedback,improveCounsellingSkills,0.5).
edge(undergoClinicalReview1,positiveEmploymentEvaluation,0.5).
edge(avoidPressureToPerformDutiesQuickly,decreaseFactoryWorkerAtmosphere,0.5).
edge(comfortableWithPerceivedPurposeOfTechnology,decreaseDifficultiesWithTechnology,0.5).
dec(assessSituation1,provideWrittenCounselling,or).
dep(empoweringKidsToHelpThemselves,empoweringKidsToHelpThemselves1).
dec(learnWebTechnologies,receiveAdditionalTrainingAsAnExperiencedCousnellor,or).
dec(participateInEvents1,promoteCS1,or).
dep(voiceCounsellingBePerformed2,voiceCounsellingBePerformed).
dep(performEmailCounselling,performEmailCounselling1).
edge(prideInJob,enthusiasticWorkAtmosphere,0.5).
edge(implementEmailForCounsellors2,happinessCounsellors,0.5).
dep(informationBindersAtStations,findInformationInBinders).
edge(counsellorsBeUnionized,performDutiesQuickly,0.5).
edge(highQualityResources1,highQualityCounselling,0.5).
dec(recordStories,provideCounselling,or).
dec(listenToCallsOfExperiencedCounsellors,receiveTrainingFromCounsellors,or).
edge(performDutiesQuickly,helpAsManyKidsAsPossible,0.5).
edge(helpAsManyKidsAsPossible,prideInJob,0.5).
dep(diffuseConflictWithParent,diffuseConflictWithParent1).
dec(provideCounselling1,voiceCounsellingBePerformed1,or).
dep(voiceCounsellingBePerformed1,voiceCounsellingBePerformed2).
dec(kidsBePreparedForFormalAbuseReportingProcess,provideCounselling,or).
dep(diffuseConflictWithParent1,diffuseConflictWithParent2).
dep(highDegreeOfSimilarityBetweenServicesProvided1,highDegreeOfSimilarityBetweenServicesProvided).
edge(performDutiesQuickly,enthusiasticWorkAtmosphere,-0.5).
dec(voiceCounsellingBePerformed,provideCounselling,or).
dep(highQualityResources,highQualityResources2).
edge(performEmailCounselling,increasedCautionContentOfOnlineServices2,-0.5).
dep(itSystemsBeIntegrated,itSystemsBeIntegrated1).
dep(webCounsellingBePerformed2,webCounsellingBePerformed).
edge(easierToFindPostsWebPostingTechnology,improveWebPostingTechnology1,0.5).
edge(counsellorsEngageEmotionallyInSession,highQualityCounselling,0.5).
dep(doubleHeadsets,haveClinicalSupervisorsListenToCalls).
dec(provideWebCounsellingWithAudio,webCounsellingBePerformed1,or).
dec(provideWebCounsellingWithAudio,webCounsellingBePerformed1,or).
edge(counsellorsBeUnionized,considerationOfFeedbackManagers,0.5).
edge(rememberLocationsOfResouces,performDutiesQuickly,0.5).
dec(attendCounsellingWorkshops,receiveAdditionalTrainingAsAnExperiencedCousnellor,or).
edge(completeResourceLinks,decreaseWorkDifficulty,0.5).
edge(increaseNumberOfCounsellors,avoidShortStaffing,0.5).
dep(webResponsesBeGeneric1,webResponsesBeGeneric2).
dep(implementEmailForCounsellors1,implementEmailForCounsellors2).
dep(accessibleResourcesForCounselors3,accessibleResourcesForCounselors4).
dec(performConferenceCallWithThirdParty,situationBeDealtWith,or).
edge(commentOnTechnologyUsabilityIssues,avoidBeingLabelledAntiTechnology,-0.5).
dec(prepareTechnicalPhoneEnvironment,voiceCounsellingBePerformed1,or).
dec(briefTherapyCounsellingBeUsed,provideCounselling,or).
dep(improveCounsellingSkills,improveCounsellingSkills3).
edge(cuttingAndPastingBeAddedToWebPostingSoftware,improveWebPostingTechnology1,0.5).
dec(receiveCallClassificationTraining,receiveTrainingAsANewCounsellor,or).
dep(clearerCallClassificationCatagories1,clearerCallClassificationCatagories).
edge(highQualityCounselling1,enthusiasticWorkAtmosphere,0.5).
dep(highQualityCounselling1,highQualityCounselling2).
dep(accessibleResourcesForCounselors3,accessibleResourcesForCounselors2).
edge(increaseITMethodsToAcquireFeedback,increaseFeedback,0.5).
edge(accessibleResourcesForCounselors,performDutiesQuickly,0.5).
edge(reduceNumberOfStepsWebPostingTechnology,increasedCautionContentOfOnlineServices2,-0.5).
edge(performDutiesQuickly,avoidPressureToPerformDutiesQuickly,0.5).
dep(considerationOfFeedbackManagers1,considerationOfFeedbackManagers).
dep(completeResourceLinks4,completeResourceLinks3).
edge(consistentResourceLinks,highQualityResources,0.5).
dec(receiveTrainingAsANewCounsellor,trainingBeReceived,or).
dep(implementCategorizationTool,categorizeCall).
edge(currentResourceLinks1,highQualityResources,0.5).
dep(provideCounselling,provideCounselling3).
edge(engageInDialogWithCounselled,increaseConnectionBetweenCounsellorsAndCounselled,0.5).
dep(reduceNumberOfStepsWebPostingTechnology1,reduceNumberOfStepsWebPostingTechnology).
edge(moderateDiscussionBoards,increasedCautionContentOfOnlineServices2,0.5).
edge(counsellorsPoliceThemselves,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
dep(doubleHeadsets,listenToCallsOfNewCounsellors).
edge(provideResourcesInOneSource,consistentResourceLinks2,0.5).
edge(reduceNumberOfStepsWebPostingTechnology,improveWebPostingTechnology1,0.5).
dep(webResponsesBeGeneric,webResponsesBeGeneric1).
edge(counsellorsBeUnionized,avoidTensionConfrontationAnimosityAmongstEmployees,-0.5).
dec(signContractWithCounsellingUnion,counsellorsBeUnionized,or).
dec(provideInformationToOtherCounselloers,provideSupportToCounsellors,or).
edge(listenForCues,findEffectiveCues,0.5).
edge(increaseConnectionBetweenCounsellorsAndCounselled,highQualityCounselling,0.5).
dep(promoteCS2,promoteCS).
dec(logIntoActivityManager,prepareTechnicalPhoneEnvironment,or).
dec(haveClinicalSupervisorsListenToCalls,clinicalSupervisorsListenToCalls,or).
dep(recognition,recognition1).
edge(avoidBeingLabelledAntiTechnology,positiveEmploymentEvaluation,0.5).
edge(avoidLiabilityProblems,happinessCounsellors,0.5).
edge(acquireFeedback,increaseFeedback,0.5).
edge(happinessCounsellors,moveOnToBetterJob,-0.5).
dep(decreaseClumsinessTechnology1,decreaseClumsinessTechnology).
edge(decreaseWorkDifficulty,happinessCounsellors,0.5).
dec(aResolutionFocusApproachBeUsed,provideCounselling,or).
dec(informationResourcesBeFound,provideInformation2,or).
edge(toolsToBurnNegativeEnergyBePresent,professionalWorkEnvironment1,-0.5).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,happinessCounsellors,0.5).
edge(reduceStaggeringOfSchedules,increasedPeerSupport1,0.5).
edge(webResponsesBeGeneric2,helpAsManyKidsAsPossible1,0.5).
edge(trainingBeReceived,improveCounsellingSkills,0.5).
edge(decreaseFactoryWorkerAtmosphere,happinessCounsellors,0.5).
edge(highQualityResources1,consistentCounsellingResponses,0.5).
dep(allowUserToLogIn1,logIntoActivityManager).
edge(increasedPeerSupport2,releaseTension,0.5).
dep(effectiveUseOfTechnologyCounsellors2,effectiveUseOfTechnologyCounsellors1).
dec(passProbationWithinSixMonths,receiveTrainingAsANewCounsellor,or).
edge(reduceMonitoringOfActivities,comfortableWithPerceivedPurposeOfTechnology,0.5).
edge(anonymity,safety,0.5).
edge(controlOfCounsellingWork,happinessCounsellors,0.5).
dep(increaseEmphasisOnOnlineFeedbackForm1,increaseEmphasisOnOnlineFeedbackForm).
dec(provideWrittenCounselling,createCounsellingPosts,or).
edge(controlOfCounsellingWork,avoidLiabilityProblems,0.5).
edge(counsellorsBeUnionized,facilitateFasterChangesInCounsellorDuties1,-0.5).
edge(performCounsellingAsInstructedBySupervisor,positiveEmploymentEvaluation,0.5).
edge(considerationOfFeedbackITProviders,decreaseFactoryWorkerAtmosphere,0.5).
dec(feedbackOnCallsBeGiven,provideTrainingToNewCounsellors,or).
dec(situationBeDealtWith,provideCounselling1,or).
dep(controlOfCounsellingWork1,controlOfCounsellingWork).
dep(currentResourceLinks4,currentResourceLinks3).
edge(releaseTension,professionalWorkEnvironment1,-0.5).
dep(webCounsellingBePerformed1,webCounsellingBePerformed2).
dec(updateOutdatedLinks,manageCounsellingResources,or).
dep(helpKids,helpKids1).
dec(meetingBeAttended,provideSupportToCounsellors,or).
edge(counsellorsBeUnionized,considerationOfFeedbackITProviders,0.5).
dep(improveQualityAssuranceTechnology,improveQualityAssuranceTechnology2).
edge(editOnlinePostsOfKids,increasedCautionContentOfOnlineServices2,0.5).
edge(decreaseClumsinessTechnology2,counsellorsEngageEmotionallyInSession,0.5).
edge(improveCallRecordingEquipment,improveQualityAssuranceTechnology,0.5).
edge(highQualityCounselling,patientCounselor,1).
dep(provideInformation2,provideInformation1).
edge(voiceCounsellingBePerformed,helpAsManyKidsAsPossible1,0.5).
edge(considerationOfFeedbackManagers,reduceMonitoringOfActivities,0.5).
edge(avoidBeingDirective,highQualityCounselling,0.5).
edge(webCounsellingBePerformed,findEffectiveCues,-0.5).
dep(avoidRelationshipsWithSpecificCounsellor1,avoidRelationshipsWithSpecificCounsellor).
edge(increaseEmphasisOnOnlineFeedbackForm,increaseFeedback,0.5).
edge(implementEmailForCounsellors,improveCommunicationBetweenCounsellors,0.5).
dep(patientCounselor,patientCounselor1).
edge(decreaseWorkLoad,avoidBurnout,0.5).
dec(promoteCS,performTheJobOfCounselling,or).
edge(performCounsellingAsInstructedBySupervisor1,supportIndividualityInCounsellingTechniques,-0.5).
edge(improveITSkills,positiveEmploymentEvaluation,0.5).
edge(improveWebPostingTechnology,decreaseDifficultiesWithTechnology,0.5).
dec(situationBeDealtWith1,provideWrittenCounselling,or).
edge(updateOutdatedLinks,currentResourceLinks4,0.5).
dec(performEmailCounselling,webCounsellingBePerformed1,or).
dec(provideWrittenCounselling,provideWebCounsellingWithVideo,or).
edge(consistentCounsellingResponses,highQualityCounselling,0.5).
dec(listenForCues,provideCounselling,or).
dep(highDegreeOfSimilarityBetweenServicesProvided2,highDegreeOfSimilarityBetweenServicesProvided1).
edge(accountabilityOfServices,prideInJob,0.5).
dep(considerationOfFeedbackITProviders1,considerationOfFeedbackITProviders).
edge(avoidDialoguesWebServices1,decreaseKidsIsolation,0.5).
edge(avoidBeingDirective,empoweringKidsToHelpThemselves2,0.5).
dec(undergoMediaTraining,receiveAdditionalTrainingAsAnExperiencedCousnellor,or).
edge(implementBulletinBoard,improveCommunicationBetweenCounsellors,0.5).
dep(provideWrittenCounselling,provideWrittenCounselling1).
edge(increaseITTraining,improveITSkills1,0.5).
edge(rememberLocationsOfResouces,decreaseWorkDifficulty,0.5).
dep(reduceStaggeringOfSchedules1,reduceStaggeringOfSchedules).
dec(provideResourcesInLibrary,provideResourcesAsCurrentlyDone,or).
dep(increaseCSAwareness1,increaseCSAwareness).
edge(decreaseClumsinessTechnology,decreaseDifficultiesWithTechnology,0.5).
edge(increasedPeerSupport,highQualityCounselling,0.5).
dec(makeTapesForClinicalReview,clinicalSupervisorsListenToCalls,or).
dec(performFirstReadingOfCounsellingPosts,webCounsellingBePerformed1,or).
dec(removeIdentifyingMaterial,removeInappropriateMaterial,or).
edge(professionalWorkEnvironment1,enthusiasticWorkAtmosphere,-0.5).
dep(accessibleResourcesForCounselors2,accessibleResourcesForCounselors).
dec(undergoMediaTraining,receiveTrainingAsANewCounsellor,or).
edge(consistentResourceLinks2,highQualityResources3,0.5).
edge(considerationOfFeedbackITProviders,decreaseDifficultiesWithTechnology,0.5).
dec(receiveInformationFromOtherCounsellors,provideInformation2,or).
edge(releaseTension,highQualityCounselling1,0.5).
dep(correctInterpretationOfCounsel1,correctInterpretationOfCounsel).
dec(blockKidsWhoDisplayInappropriateBehavoir,moderateAChat,or).
dec(undergoClinicalReview1,performTheJobOfCounselling,or).
edge(encourageKidsToTalkToDifferentCounsellors,avoidRelationshipsWithSpecificCounsellor1,0.5).
edge(undergoMediaTraining,acquirePublicSpeakingSkills,1).
dep(completeResourceLinks3,completeResourceLinks2).
edge(improveCounsellingSkills2,consistentCounsellingResponses,0.5).
dep(promoteCS1,promoteCS2).
dep(anonymityCounsellors,anonymity).
dec(writeArticlesForMagazines1,promoteCS1,or).
edge(simpleTechnology,decreaseDifficultiesWithTechnology,0.5).
dec(assessSituation,provideCounselling1,or).
dec(receiveFeedback,undergoClinicalReview,or).
dep(provideInformationInBinders,informationBindersAtStations).
dec(receiveTrainingFromManagment,receiveAdditionalTrainingAsAnExperiencedCousnellor,or).
dep(provideWebCounsellingWithVideo,provideWebCounsellingWithVideo1).
edge(getRidOfUnion,considerationOfFeedbackManagers,-0.5).
dec(writeArticlesForWebsite1,createWebSiteContent,or).
dep(completeResourceLinks1,completeResourceLinks).
edge(reducePhysicalObservationHearingByStaffNotInCounsellingTeam,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
dec(provideResourcesInOneSource,resourcesBeProvided,or).
dep(salary,receiveSalary).
dec(listenToCallsOfNewCounsellors,feedbackOnCallsBeGiven,or).
dep(increasedCautionContentOfOnlineServices2,increasedCautionContentOfOnlineServices1).
edge(beConsultedAboutNewPolicies,decreaseFactoryWorkerAtmosphere,0.5).
dec(removeInappropriateMaterial,editOnlinePostsOfKids,or).
dep(simpleTechnology1,simpleTechnology).
dep(improveQualityAssuranceTechnology2,improveQualityAssuranceTechnology1).
edge(reduceMonitoringOfActivities,happinessCounsellors,0.5).
dep(increasedCautionContentOfOnlineServices1,increasedCautionContentOfOnlineServices).
edge(webResponsesBeGeneric,increasedCautionContentOfOnlineServices2,0.5).
edge(increasedCautionContentOfOnlineServices,avoidLiabilityProblems,0.5).
dep(undergoClinicalReview,undergoClinicalReview2).
edge(completeResourceLinks4,highQualityResources3,0.5).
dep(allowUserToLogIn,logIntoPhoneSystem).
edge(webCounsellingBePerformed4,varietyInWork,0.5).
dec(logIntoPhoneSystem,prepareTechnicalPhoneEnvironment,or).
dep(reportOutdatedLinks1,reportOutdatedLinks).
dec(exploreOptions1,situationBeDealtWith1,or).
dep(collectCallerSituationStatistics,callerStatistics).
dep(provideResourcesInLibrary,resourcesInTheLibrary).
edge(webCounsellingBePerformed,helpAsManyKidsAsPossible1,0.5).
dep(decreaseClumsinessTechnology1,decreaseClumsinessTechnology2).
dep(recordStories,csStories).
dec(speakPubliclyAboutJob,promoteCS1,or).
dep(undergoClinicalReview2,undergoClinicalReview1).
dec(encourageKidsToTalkToOthers,provideCounselling,or).
dep(trainingBeReceived,trainingBeReceived1).
dep(recognition1,recognition2).
edge(recognition,enthusiasticWorkAtmosphere,0.5).
dep(avoidLiabilityProblems,avoidLiabilityProblems1).
edge(webCounsellingBePerformed,accountabilityOfServices2,0.5).
dec(requestShifts,performTheJobOfCounselling,or).
edge(provideInformation2,empoweringKidsToHelpThemselves,0.5).
edge(decreaseClumsinessTechnology,performDutiesQuickly,0.5).
dec(blockKidsWhoDisplayInappropriateBehavoir,moderateDiscussionBoards,or).
edge(reducePrankCalls1,avoidBurnout,0.5).
dec(moderateAChat,webCounsellingBePerformed1,or).
edge(deepenCounsellingSession,increaseConnectionBetweenCounsellorsAndCounselled,0.5).
dec(findInformationInELibrary,informationResourcesBeFound,or).
edge(improveCounsellingSkills2,highQualityCounselling,0.5).
edge(acquirePublicSpeakingSkills1,recognition2,0.5).
dec(createCounsellingPosts,webCounsellingBePerformed1,or).
dec(provideResourcesInELibrary,provideResourcesAsCurrentlyDone,or).
edge(toolsToBurnNegativeEnergyBePresent,releaseTension,0.5).
dep(accommodateSchedules1,accommodateSchedules).
edge(diffuseConflictWithParent2,avoidLiabilityProblems,0.5).
dec(clinicalSupervisorsListenToCalls,receiveFeedback,or).
dec(resourcesBeProvided,manageCounsellingResources,or).
dep(resourcesInTheLibrary,findInformationInLibrary).
edge(editOnlinePostsOfKids,reduceContagionEffectOfHarmfulActions,0.5).
dec(provideWrittenCounselling,provideWebCounsellingWithAudio,or).
edge(promoteCounselling,recognition2,0.5).
dep(counselorSpeakOnKidsIssuesInGeneral1,counselorSpeakOnKidsIssuesInGeneral).
edge(enthusiasticWorkAtmosphere,happinessCounsellors,0.5).
dep(improveITSkills3,improveITSkills).
dep(counsellingPolicies,counsellingPoliciesBeFollowed).
edge(happinessCounsellors,highQualityCounselling1,0.5).
edge(increasedPeerSupport2,happinessCounsellors,0.5).
dep(provideInformation1,provideInformation).
dec(participateInBoardMeetings,promoteCounselling,or).
edge(clearerCallClassificationCatagories,performDutiesQuickly,0.5).
dec(attendWebModeratorMeetings,meetingBeAttended,or).
dep(accountabilityOfServices1,accountabilityOfServices).
edge(releaseTension,happinessCounsellors,0.5).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,decreaseFactoryWorkerAtmosphere,0.5).
edge(improvedWritingSkills,positiveEmploymentEvaluation,0.5).
edge(positiveEmploymentEvaluation,acquireRecognizableEmploymentExperience,0.5).
dep(voiceCounsellingBePerformed1,voiceCounsellingBePerformed3).
dep(completeResourceLinks2,completeResourceLinks1).
dec(referParentsToPHL,provideCounselling,or).
dep(feedback,acquireFeedback).
edge(provideResourcesAsCurrentlyDone,consistentResourceLinks2,-0.5).
edge(provideResourcesAsCurrentlyDone,consistentResourceLinks2,-0.5).
edge(provideWebCounsellingWithVideo,highDegreeOfSimilarityBetweenServicesProvided2,0.5).
edge(webCounsellingBePerformed,decreaseKidsIsolation,-0.5).
edge(debriefWithCounsellors,effectiveDebriefing,0.5).
edge(improveQualityAssuranceTechnology1,decreaseDifficultiesWithTechnology,0.5).
dec(counselorSpeakOnKidsIssuesInGeneral1,promoteCS1,or).
dec(webPostsBeReviewedByClinicalSupervisor,receiveFeedback,or).
dec(speakAtSAConferences,promoteCS1,or).
dec(includeDrugInformationInCounsellingResources,manageCounsellingResources,or).
dep(improveCounsellingSkills3,improveCounsellingSkills1).
dep(improveITSkills1,improveITSkills3).
dec(provideInformation,performTheJobOfCounselling,or).
edge(iconsForCounsellingInformationBeOnDesktop,accessibleResourcesForCounselors3,0.5).
dec(provideWrittenCounselling,performEmailCounselling,or).
dep(createCounsellingPosts,createCounsellingPosts1).
edge(accessibleResourcesForCounselors1,highQualityCounselling,0.5).
dec(clinicalSupervisorsListenToCalls,undergoClinicalReview,or).
dec(debriefWithCounsellors,provideSupportToCounsellors,or).
dep(implementBulletinBoard1,implementBulletinBoard).
dep(increasedPeerSupport3,increasedPeerSupport).
dec(categorizeCall,collectCallerSituationStatistics,or).
edge(moderateDiscussionBoards,reduceContagionEffectOfHarmfulActions,0.5).
dec(mentoringBeReceivedFromExperiencedCounsellors,receiveTrainingFromCounsellors,or).
dec(moderateDiscussionBoards,webCounsellingBePerformed1,or).
dep(accessibleResourcesForCounselors5,accessibleResourcesForCounselors3).
edge(considerationOfFeedbackManagers,decreaseFactoryWorkerAtmosphere,0.5).
dep(improveCallRecordingEquipment1,improveCallRecordingEquipment).
edge(decreaseWorkLoad,happinessCounsellors,0.5).
edge(webCounsellingBePerformed,supportIndividualityInCounsellingTechniques,-0.5).
edge(increasedCautionContentOfOnlineServices,performDutiesQuickly,-0.5).
dep(provideInformationToOtherCounselloers,informationResources).
edge(encourageKidsToTalkToOthers,decreaseKidsIsolation,0.5).
edge(enthusiasticWorkAtmosphere,avoidBurnout,0.5).
dep(participateInEvents1,participateInEvents).
dec(webPostsBeReviewedByClinicalSupervisor,undergoClinicalReview,or).
edge(positiveEmploymentEvaluation,happinessCounsellors,0.5).
dep(provideWebCounsellingWithAudio,provideWebCounsellingWithAudio1).
dep(professionalWorkEnvironment1,professionalWorkEnvironment).
edge(resourcesBeProvided,completeResourceLinks4,0.5).
edge(supportIndividualityInCounsellingTechniques,highQualityCounselling,0.5).
dep(avoidDialoguesWebServices,avoidDialoguesWebServices1).
edge(improveITSkills,avoidBeingLabelledAntiTechnology,0.5).
edge(blockKidsWhoDisplayInappropriateBehavoir,increasedCautionContentOfOnlineServices2,0.5).
edge(highDegreeOfSimilarityBetweenServicesProvided,decreaseWorkDifficulty,0.5).
dec(encourageKidsToCallCS,createCounsellingPosts,or).
edge(improveCommunicationBetweenCounsellors,increasedPeerSupport1,0.5).
edge(highQualityCounselling1,prideInJob,0.5).
dep(writeArticlesForWebsite1,writeArticlesForWebsite).
dep(highQualityResources2,highQualityResources1).
dec(receiveTrainingFromCounsellors,receiveTrainingAsANewCounsellor,or).
edge(positiveEmploymentEvaluation,retainJob,0.5).
dep(highQualityCounselling,highQualityCounselling3).
dep(currentResourceLinks3,currentResourceLinks1).
edge(provideResourcesInOneSource,accessibleResourcesForCounselors6,0.5).
edge(acquirePublicSpeakingSkills3,positiveEmploymentEvaluation,0.5).
dec(receiveAdditionalTrainingAsAnExperiencedCousnellor,trainingBeReceived,or).
dec(learnWebTechnologies,receiveTrainingAsANewCounsellor,or).
dep(accessibleResourcesForCounselors4,accessibleResourcesForCounselors1).
dep(acquirePublicSpeakingSkills2,acquirePublicSpeakingSkills3).
dep(helpAsManyKidsAsPossible1,helpAsManyKidsAsPossible3).
dep(performCounsellingAsInstructedBySupervisor,performCounsellingAsInstructedBySupervisor2).
edge(improveCounsellingSkills1,positiveEmploymentEvaluation,0.5).
dec(exploreOptions,situationBeDealtWith,or).
edge(moderateAChat,increasedCautionContentOfOnlineServices2,-0.5).
dep(implementEmailForCounsellors1,implementEmailForCounsellors).
edge(getRidOfUnion,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(increaseCSAwareness,prideInJob,0.5).
dep(effectiveUseOfTechnologyCounsellors,effectiveUseOfTechnologyCounsellors2).
dep(easilyAccessableTechnologyInstructions1,easilyAccessableTechnologyInstructions).
dep(rememberLocationsOfResouces,rememberLocationsOfResouces1).
dep(createWebSiteContent,webSiteContent).
dec(attendPartTimeMeeting,meetingBeAttended,or).
edge(avoidShortStaffing,decreaseWorkLoad,0.5).
dep(empoweringKidsToHelpThemselves1,empoweringKidsToHelpThemselves2).
edge(aResolutionFocusApproachBeUsed,avoidBeingDirective,0.5).
dep(increaseITMethodsToAcquireFeedback1,increaseITMethodsToAcquireFeedback).
dec(findInformationInBinders,informationResourcesBeFound,or).
edge(participateInEvents1,recognition2,0.5).
dep(trainingBeReceived1,trainingBeReceived2).
dep(increaseITTrainingForCounsellors,increaseITTraining).
dep(currentResourceLinks2,currentResourceLinks).
edge(varietyInWork,happinessCounsellors,0.5).
dep(facilitateFasterChangesInCounsellorDuties1,facilitateFasterChangesInCounsellorDuties).
dep(webModeratorMeetings,attendWebModeratorMeetings).
dep(provideResourcesInELibrary,informationInELibrary).
edge(correctInterpretationOfCounsel,highQualityCounselling,0.5).
edge(updateOutdatedLinks,completeResourceLinks4,0.5).
edge(decreaseDifficultiesWithTechnology,decreaseWorkDifficulty,0.5).
edge(releaseTension,avoidBurnout,0.5).
edge(enthusiasticWorkAtmosphere,improveCounsellingSkills1,0.5).
dep(reducePrankCalls,reducePrankCalls1).
edge(controlOfFloorOperations,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
dec(encourageKidsToTalkToDifferentCounsellors,provideCounselling1,or).
dep(helpAsManyKidsAsPossible,helpAsManyKidsAsPossible2).
dep(informationResources,receiveInformationFromOtherCounsellors).
dep(consistentResourceLinks2,consistentResourceLinks1).
edge(provideSupportToCounsellors,improveCommunicationBetweenCounsellors,0.5).
dec(participateInSponsorMeetings,promoteCS1,or).
edge(findEffectiveCues,highQualityCounselling,0.5).
dep(signContractWithCounsellingUnion,signContract).
dec(provideCounselling2,performTheJobOfCounselling,or).
edge(commentOnTechnologyUsabilityIssues,decreaseDifficultiesWithTechnology,0.5).
dec(attendCounsellingWorkshops,receiveTrainingAsANewCounsellor,or).
edge(acquireRecognizableEmploymentExperience,moveOnToBetterJob,0.5).
edge(effectiveDebriefing,increasedPeerSupport1,0.5).
dep(performCounsellingAsInstructedBySupervisor2,performCounsellingAsInstructedBySupervisor1).
dep(webCounsellingBePerformed3,webCounsellingBePerformed4).
edge(happinessCounsellors,performDutiesQuickly,0.5).
dep(easierToFindPostsWebPostingTechnology1,easierToFindPostsWebPostingTechnology).
dec(findInformationInLibrary,informationResourcesBeFound,or).
dep(reportOutdatedLinks,updateOutdatedLinks).
dec(provideTrainingToNewCounsellors,provideSupportToCounsellors,or).
dec(removeInappropriateMaterial,moderateDiscussionBoards,or).
edge(decreaseWorkDifficulty,avoidBurnout,0.5).
edge(performFirstReadingOfCounsellingPosts,increasedCautionContentOfOnlineServices2,0.5).
dep(accessibleResourcesForCounselors6,accessibleResourcesForCounselors5).
dep(informationInELibrary,findInformationInELibrary).
dep(highQualityCounselling2,highQualityCounselling).
dec(performCrisisIntervention,situationBeDealtWith,or).
edge(beConsultedAboutNewPolicies,considerationOfFeedbackManagers,0.5).
edge(undergoClinicalReview1,improveCounsellingSkills1,0.5).
edge(removeInappropriateMaterial,increasedCautionContentOfOnlineServices2,0.5).
dep(tapes,makeTapesForClinicalReview).
dec(provideResourcesAsCurrentlyDone,resourcesBeProvided,or).
dep(acquirePublicSpeakingSkills,acquirePublicSpeakingSkills2).
dec(receiveTrainingFromManagment,receiveTrainingAsANewCounsellor,or).
edge(webCounsellingBePerformed,counsellorsEngageEmotionallyInSession,-0.5).
dep(happinessCounsellors,happinessCounsellors1).
dec(beAMentorToNewCounsellors,provideTrainingToNewCounsellors,or).
dep(improvedWritingSkills,improvedWritingSkillsCounsellors).
edge(empoweringKidsToHelpThemselves2,highQualityCounselling,0.5).
dep(provideCounselling,counsellorExperience).
edge(decreaseDifficultiesWithTechnology,happinessCounsellors,0.5).
dep(trainingCDs,undergoCDBasedTraining).
edge(avoidBurnout,happinessCounsellors,0.5).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,enthusiasticWorkAtmosphere,0.5).
edge(considerationOfFeedbackManagers,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
dep(increasedPeerSupport3,increasedPeerSupport2).
dec(undergoCDBasedTraining,receiveAdditionalTrainingAsAnExperiencedCousnellor,or).
dec(receiveSalary,performTheJobOfCounselling,or).
dep(rememberLocationsOfResouces1,rememberLocationsOfResouces2).
edge(prideInJob,happinessCounsellors,0.5).
edge(decreaseKidsIsolation,highQualityCounselling,0.5).
dep(improveWebPostingTechnology1,improveWebPostingTechnology2).
dep(tapeRecordingTechnology,haveClinicalSupervisorsListenToCalls).
edge(improveITSkills,decreaseDifficultiesWithTechnology,0.5).
edge(accommodateSchedules,happinessCounsellors,0.5).
dep(counsellingWorkshops,attendCounsellingWorkshops).
edge(counsellorsEngageEmotionallyInSession,supportIndividualityInCounsellingTechniques,0.5).
edge(reportOutdatedLinks1,currentResourceLinks1,0.5).
dep(provideCounselling3,provideCounselling2).
dec(editCounsellingPosts,performFirstReadingOfCounsellingPosts,or).
edge(counsellorsPoliceThemselves,reduceMonitoringOfActivities,0.5).
dec(collectCallerSituationStatistics,provideCounselling1,or).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,toolsToBurnNegativeEnergyBePresent,0.5).
dec(diffuseConflictWithParent,situationBeDealtWith,or).
edge(clearerCallClassificationCatagories,decreaseWorkDifficulty,0.5).
dep(improveITSkills1,improveITSkills2).
edge(easilyAccessableTechnologyInstructions,decreaseDifficultiesWithTechnology,0.5).
edge(reduceMonitoringOfActivities,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
dep(counsellingPoliciesBeFollowed,counsellingPoliciesBeFollowed1).
dep(acquirePublicSpeakingSkills2,acquirePublicSpeakingSkills1).
dep(accountabilityOfServices2,accountabilityOfServices1).
edge(provideWebCounsellingWithAudio,highDegreeOfSimilarityBetweenServicesProvided2,0.5).
dep(improveWebPostingTechnology2,improveWebPostingTechnology).
edge(getRidOfUnion,facilitateFasterChangesInCounsellorDuties1,0.5).
edge(currentResourceLinks,decreaseWorkDifficulty,0.5).
dep(consistentResourceLinks1,consistentResourceLinks).
dep(currentResourceLinks1,currentResourceLinks2).
edge(reducePrankCalls1,happinessCounsellors,0.5).
dep(increaseNumberOfCounsellors1,increaseNumberOfCounsellors).
edge(engageInDialogWithCounselled,webCounsellingBePerformed,-0.5).
dep(moderateDiscussionBoards,moderateDiscussionBoards1).
dec(provideInformationInBinders,provideResourcesAsCurrentlyDone,or).
edge(improveITSkills1,effectiveUseOfTechnologyCounsellors,0.5).
edge(itSystemsBeIntegrated,decreaseDifficultiesWithTechnology,0.5).
edge(decreaseKidsIsolation,helpKids,0.5).
dec(editOnlinePostsOfKids,moderateDiscussionBoards,or).
dep(moderateAChat,moderateAChat1).
edge(recognition,happinessCounsellors,0.5).
dec(includeLegalInformationInCounsellingResources,manageCounsellingResources,or).
dep(reduceContagionEffectOfHarmfulActions,reduceContagionEffectOfHarmfulActions1).
dep(helpAsManyKidsAsPossible2,helpAsManyKidsAsPossible1).
edge(safety,happinessCounsellors,0.5).
edge(accessibleResourcesForCounselors,decreaseWorkDifficulty,0.5).
dec(undergoCDBasedTraining,receiveTrainingAsANewCounsellor,or).
dep(improveCounsellingSkills3,improveCounsellingSkills2).
edge(effectiveUseOfTechnologyCounsellors1,highQualityCounselling,0.5).
edge(accessibleResourcesForCounselors6,highQualityResources3,0.5).
edge(moderateAChat,reduceContagionEffectOfHarmfulActions,0.5).
edge(speakPubliclyAboutJob,recognition2,0.5).
dep(webCounsellingBePerformed1,webCounsellingBePerformed3).
