% CSCounselling  (edit me: node/2 edge/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, leaf/1, topgoal/1.
node(considerationOfFeedbackManagers,softgoal).
node(learnWebTechnologies,task).
leaf(learnWebTechnologies).
node(provideWrittenCounselling1,task).
node(promoteCS2,task).
node(increaseNumberOfCounsellors1,softgoal).
leaf(increaseNumberOfCounsellors1).
node(promoteCS,task).
node(enthusiasticWorkAtmosphere,softgoal).
node(reduceMonitoringOfActivities,softgoal).
node(cuttingAndPastingBeAddedToWebPostingSoftware,goal).
leaf(cuttingAndPastingBeAddedToWebPostingSoftware).
topgoal(cuttingAndPastingBeAddedToWebPostingSoftware).
node(getRidOfUnion,goal).
leaf(getRidOfUnion).
topgoal(getRidOfUnion).
node(completeResourceLinks4,softgoal).
node(decreaseClumsinessTechnology2,softgoal).
node(encourageKidsToTalkToDifferentCounsellors,task).
leaf(encourageKidsToTalkToDifferentCounsellors).
node(informationResourcesBeFound,goal).
topgoal(informationResourcesBeFound).
node(provideCounselling3,task).
node(supportIndividualityInCounsellingTechniques,softgoal).
node(moveOnToBetterJob,softgoal).
node(informationInELibrary,resource).
node(undergoClinicalReview1,task).
node(avoidPressureToPerformDutiesQuickly,softgoal).
node(receiveTrainingFromManagment,task).
leaf(receiveTrainingFromManagment).
node(exploreOptions,task).
leaf(exploreOptions).
node(signContract,task).
node(participateInEvents1,task).
leaf(participateInEvents1).
node(trainingCDs,resource).
leaf(trainingCDs).
node(implementEmailForCounsellors,task).
node(tapeRecordingTechnology,resource).
leaf(tapeRecordingTechnology).
node(patientCounselor,softgoal).
node(increaseFeedback,softgoal).
node(beConsultedAboutNewPolicies,goal).
leaf(beConsultedAboutNewPolicies).
topgoal(beConsultedAboutNewPolicies).
node(helpAsManyKidsAsPossible2,softgoal).
node(simpleTechnology1,softgoal).
leaf(simpleTechnology1).
node(provideInformationToOtherCounselloers,task).
leaf(provideInformationToOtherCounselloers).
node(logIntoActivityManager,task).
node(recognition2,softgoal).
node(findInformationInLibrary,task).
node(recordStories,task).
leaf(recordStories).
node(currentResourceLinks2,softgoal).
node(moderateDiscussionBoards,task).
node(increasedPeerSupport1,softgoal).
node(accommodateSchedules,softgoal).
node(provideSupportToCounsellors,task).
node(accessibleResourcesForCounselors,softgoal).
node(empoweringKidsToHelpThemselves2,softgoal).
node(improveCounsellingSkills1,softgoal).
node(provideResourcesInLibrary,task).
leaf(provideResourcesInLibrary).
node(acquirePublicSpeakingSkills,softgoal).
node(consistentResourceLinks,softgoal).
node(easierToFindPostsWebPostingTechnology1,softgoal).
leaf(easierToFindPostsWebPostingTechnology1).
node(accessibleResourcesForCounselors2,softgoal).
node(writeArticlesForMagazines,task).
node(improveITSkills3,softgoal).
node(avoidBeingLabelledAntiTechnology,softgoal).
node(performDutiesQuickly,softgoal).
node(improveQualityAssuranceTechnology2,softgoal).
node(listenForCues,task).
leaf(listenForCues).
node(speakAtSAConferences,task).
leaf(speakAtSAConferences).
node(webSiteContent,resource).
node(provideWebCounsellingWithVideo,task).
node(highQualityCounselling,softgoal).
node(rememberLocationsOfResouces2,softgoal).
node(counsellorsEngageEmotionallyInSession,softgoal).
node(controlOfCounsellingWork1,softgoal).
leaf(controlOfCounsellingWork1).
node(increasedCautionContentOfOnlineServices1,softgoal).
node(controlOfFloorOperations,softgoal).
leaf(controlOfFloorOperations).
node(participateInSponsorMeetings,task).
leaf(participateInSponsorMeetings).
node(improveWebPostingTechnology1,softgoal).
node(decreaseDifficultiesWithTechnology,softgoal).
node(toolsToBurnNegativeEnergyBePresent,goal).
topgoal(toolsToBurnNegativeEnergyBePresent).
node(completeResourceLinks1,softgoal).
node(provideWebCounsellingWithAudio,task).
node(counsellorsBeUnionized,goal).
topgoal(counsellorsBeUnionized).
node(allowUserToLogIn1,goal).
leaf(allowUserToLogIn1).
topgoal(allowUserToLogIn1).
node(itSystemsBeIntegrated1,goal).
topgoal(itSystemsBeIntegrated1).
node(highQualityResources2,softgoal).
node(retainJob,softgoal).
node(improveWebPostingTechnology,softgoal).
node(reduceStaggeringOfSchedules,softgoal).
node(performEmailCounselling1,task).
node(trainingBeReceived2,goal).
topgoal(trainingBeReceived2).
node(increaseITTrainingForCounsellors,softgoal).
leaf(increaseITTrainingForCounsellors).
node(acquirePublicSpeakingSkills2,softgoal).
node(happinessCounsellors,softgoal).
node(referParentsToPHL,task).
leaf(referParentsToPHL).
node(improveCounsellingSkills,softgoal).
node(resourcesInTheLibrary,resource).
node(avoidRelationshipsWithSpecificCounsellor1,softgoal).
node(acquireFeedback,task).
node(reducePrankCalls1,softgoal).
node(receiveAdditionalTrainingAsAnExperiencedCousnellor,task).
node(easilyAccessableTechnologyInstructions1,softgoal).
leaf(easilyAccessableTechnologyInstructions1).
node(recognition1,softgoal).
node(improveQualityAssuranceTechnology,softgoal).
node(accessibleResourcesForCounselors6,softgoal).
node(webCounsellingBePerformed1,task).
node(clinicalSupervisorsListenToCalls,goal).
topgoal(clinicalSupervisorsListenToCalls).
node(aResolutionFocusApproachBeUsed,goal).
leaf(aResolutionFocusApproachBeUsed).
topgoal(aResolutionFocusApproachBeUsed).
node(listenToCallsOfExperiencedCounsellors,task).
leaf(listenToCallsOfExperiencedCounsellors).
node(effectiveDebriefing,softgoal).
node(csStories,softgoal).
node(writeArticlesForWebsite1,task).
leaf(writeArticlesForWebsite1).
node(increasedCautionContentOfOnlineServices,softgoal).
node(performTheJobOfCounselling,task).
node(assessSituation,task).
leaf(assessSituation).
node(provideResourcesInELibrary,task).
leaf(provideResourcesInELibrary).
node(decreaseWorkDifficulty,softgoal).
node(voiceCounselling,softgoal).
leaf(voiceCounselling).
node(accessibleResourcesForCounselors1,softgoal).
node(feedbackOnCallsBeGiven,goal).
topgoal(feedbackOnCallsBeGiven).
node(manageCounsellingResources,task).
node(improvedWritingSkillsCounsellors,softgoal).
node(decreaseClumsinessTechnology1,softgoal).
leaf(decreaseClumsinessTechnology1).
node(receiveTrainingAsANewCounsellor,task).
node(facilitateFasterChangesInCounsellorDuties,softgoal).
node(iconsForCounsellingInformationBeOnDesktop,goal).
leaf(iconsForCounsellingInformationBeOnDesktop).
topgoal(iconsForCounsellingInformationBeOnDesktop).
node(easilyAccessableTechnologyInstructions,softgoal).
node(avoidLiabilityProblems1,softgoal).
node(receiveInformationFromOtherCounsellors,task).
node(kidsBePreparedForFormalAbuseReportingProcess,goal).
leaf(kidsBePreparedForFormalAbuseReportingProcess).
topgoal(kidsBePreparedForFormalAbuseReportingProcess).
node(consistentResourceLinks1,softgoal).
node(includeLegalInformationInCounsellingResources,task).
leaf(includeLegalInformationInCounsellingResources).
node(anonymityCounsellors,softgoal).
leaf(anonymityCounsellors).
node(avoidDialoguesWebServices1,softgoal).
node(reportOutdatedLinks1,task).
leaf(reportOutdatedLinks1).
node(rememberLocationsOfResouces1,softgoal).
node(improveWebPostingTechnology2,softgoal).
node(considerationOfFeedbackITProviders1,softgoal).
leaf(considerationOfFeedbackITProviders1).
node(completeResourceLinks2,softgoal).
node(performCounsellingAsInstructedBySupervisor,softgoal).
leaf(performCounsellingAsInstructedBySupervisor).
node(counsellingWorkshops,resource).
leaf(counsellingWorkshops).
node(prepareTechnicalPhoneEnvironment,task).
node(highDegreeOfSimilarityBetweenServicesProvided,softgoal).
node(helpAsManyKidsAsPossible3,softgoal).
node(engageInDialogWithCounselled,softgoal).
leaf(engageInDialogWithCounselled).
node(helpAsManyKidsAsPossible,softgoal).
node(acquireRecognizableEmploymentExperience,softgoal).
node(counsellingPoliciesBeFollowed,goal).
topgoal(counsellingPoliciesBeFollowed).
node(webModeratorMeetings,resource).
leaf(webModeratorMeetings).
node(considerationOfFeedbackITProviders,softgoal).
node(commentOnTechnologyUsabilityIssues,task).
leaf(commentOnTechnologyUsabilityIssues).
node(improveCommunicationBetweenCounsellors,softgoal).
node(consistentResourceLinks2,softgoal).
node(editOnlinePostsOfKids,task).
node(encourageKidsToCallCS,task).
leaf(encourageKidsToCallCS).
node(improveITSkills1,softgoal).
node(accessibleResourcesForCounselors5,softgoal).
node(decreaseFactoryWorkerAtmosphere,softgoal).
node(increaseNumberOfCounsellors,softgoal).
node(removeInappropriateMaterial,task).
node(passProbationWithinSixMonths,goal).
leaf(passProbationWithinSixMonths).
topgoal(passProbationWithinSixMonths).
node(comfortableWithPerceivedPurposeOfTechnology,softgoal).
node(happinessCounsellors1,softgoal).
node(writeArticlesForWebsite,task).
node(listenToCallsOfNewCounsellors,task).
node(promoteCounselling,task).
node(situationBeDealtWith,goal).
topgoal(situationBeDealtWith).
node(provideWebCounsellingWithVideo1,task).
node(avoidTensionConfrontationAnimosityAmongstEmployees,softgoal).
node(currentResourceLinks3,softgoal).
node(decreaseKidsIsolation,softgoal).
node(itSystemsBeIntegrated,goal).
leaf(itSystemsBeIntegrated).
topgoal(itSystemsBeIntegrated).
node(increasedCautionContentOfOnlineServices2,softgoal).
node(performCounsellingAsInstructedBySupervisor1,softgoal).
node(requestShifts,task).
leaf(requestShifts).
node(voiceCounsellingBePerformed,task).
node(beAMentorToNewCounsellors,goal).
leaf(beAMentorToNewCounsellors).
topgoal(beAMentorToNewCounsellors).
node(informationResources,resource).
node(receiveSalary,task).
node(helpKids1,softgoal).
node(improveCallRecordingEquipment,softgoal).
node(reduceNumberOfStepsWebPostingTechnology1,softgoal).
leaf(reduceNumberOfStepsWebPostingTechnology1).
node(highQualityCounselling1,softgoal).
node(counsellorExperience,resource).
node(avoidBeingDirective,softgoal).
node(counsellorsPoliceThemselves,softgoal).
leaf(counsellorsPoliceThemselves).
node(increasedPeerSupport,softgoal).
node(logIntoPhoneSystem,task).
node(haveClinicalSupervisorsListenToCalls,task).
node(clearerCallClassificationCatagories,softgoal).
node(highQualityResources3,softgoal).
node(counsellingPoliciesBeFollowed1,goal).
topgoal(counsellingPoliciesBeFollowed1).
node(increaseITMethodsToAcquireFeedback1,softgoal).
leaf(increaseITMethodsToAcquireFeedback1).
node(counsellingPolicies,resource).
leaf(counsellingPolicies).
node(increaseEmphasisOnOnlineFeedbackForm1,softgoal).
leaf(increaseEmphasisOnOnlineFeedbackForm1).
node(controlOfCounsellingWork,softgoal).
node(performCrisisIntervention,task).
leaf(performCrisisIntervention).
node(reduceContagionEffectOfHarmfulActions1,softgoal).
node(safety,softgoal).
node(acquirePublicSpeakingSkills1,softgoal).
node(attendPartTimeMeeting,task).
leaf(attendPartTimeMeeting).
node(categorizeCall,task).
node(performFirstReadingOfCounsellingPosts,task).
node(improveCallRecordingEquipment1,softgoal).
leaf(improveCallRecordingEquipment1).
node(webCounsellingBePerformed2,task).
node(performConferenceCallWithThirdParty,task).
leaf(performConferenceCallWithThirdParty).
node(highDegreeOfSimilarityBetweenServicesProvided2,softgoal).
node(considerationOfFeedbackManagers1,softgoal).
leaf(considerationOfFeedbackManagers1).
node(blockKidsWhoDisplayInappropriateBehavoir,task).
leaf(blockKidsWhoDisplayInappropriateBehavoir).
node(moderateDiscussionBoards1,task).
node(encourageKidsToTalkToOthers,task).
leaf(encourageKidsToTalkToOthers).
node(findInformationInBinders,task).
node(createWebSiteContent,task).
node(voiceCounsellingBePerformed1,task).
node(feedback,resource).
leaf(feedback).
node(includeDrugInformationInCounsellingResources,task).
leaf(includeDrugInformationInCounsellingResources).
node(implementCategorizationTool,task).
leaf(implementCategorizationTool).
node(undergoMediaTraining,task).
leaf(undergoMediaTraining).
node(improveITSkills,softgoal).
node(professionalWorkEnvironment,softgoal).
node(receiveFeedback,task).
node(consistentCounsellingResponses,softgoal).
node(performCounsellingAsInstructedBySupervisor2,softgoal).
node(participateInBoardMeetings,task).
leaf(participateInBoardMeetings).
node(prideInJob,softgoal).
node(reducePhysicalObservationHearingByStaffNotInCounsellingTeam,softgoal).
leaf(reducePhysicalObservationHearingByStaffNotInCounsellingTeam).
node(reduceContagionEffectOfHarmfulActions,softgoal).
node(signContractWithCounsellingUnion,task).
leaf(signContractWithCounsellingUnion).
node(situationBeDealtWith1,goal).
topgoal(situationBeDealtWith1).
node(assessSituation1,task).
leaf(assessSituation1).
node(receiveCallClassificationTraining,task).
leaf(receiveCallClassificationTraining).
node(effectiveUseOfTechnologyCounsellors1,softgoal).
node(positiveEmploymentEvaluation,softgoal).
node(simpleTechnology,softgoal).
node(briefTherapyCounsellingBeUsed,goal).
leaf(briefTherapyCounsellingBeUsed).
topgoal(briefTherapyCounsellingBeUsed).
node(highQualityCounselling2,softgoal).
node(reduceStaggeringOfSchedules1,softgoal).
leaf(reduceStaggeringOfSchedules1).
node(recognition,softgoal).
leaf(recognition).
node(completeResourceLinks3,softgoal).
node(salary,softgoal).
leaf(salary).
node(reducePrankCalls,softgoal).
leaf(reducePrankCalls).
node(increasedPeerSupport2,softgoal).
node(correctInterpretationOfCounsel,softgoal).
node(accountabilityOfServices,softgoal).
node(implementEmailForCounsellors2,task).
node(increaseITTraining,softgoal).
node(increasedPeerSupport3,softgoal).
node(webPostsBeReviewedByClinicalSupervisor,goal).
leaf(webPostsBeReviewedByClinicalSupervisor).
topgoal(webPostsBeReviewedByClinicalSupervisor).
node(editCounsellingPosts,task).
leaf(editCounsellingPosts).
node(allowUserToLogIn,goal).
leaf(allowUserToLogIn).
topgoal(allowUserToLogIn).
node(undergoClinicalReview,task).
node(diffuseConflictWithParent,task).
leaf(diffuseConflictWithParent).
node(decreaseWorkLoad,softgoal).
node(helpKids,softgoal).
node(reportAbuses,task).
leaf(reportAbuses).
node(highDegreeOfSimilarityBetweenServicesProvided1,softgoal).
node(provideWebCounsellingWithAudio1,task).
node(removeIdentifyingMaterial,task).
leaf(removeIdentifyingMaterial).
node(findEffectiveCues,softgoal).
node(improveCounsellingSkills3,softgoal).
node(professionalWorkEnvironment1,softgoal).
node(accessibleResourcesForCounselors4,softgoal).
node(tapes,resource).
leaf(tapes).
node(releaseTension,softgoal).
node(reportOutdatedLinks,task).
node(webResponsesBeGeneric1,softgoal).
node(currentResourceLinks4,softgoal).
node(trainingBeReceived,goal).
topgoal(trainingBeReceived).
node(mentoringBeReceivedFromExperiencedCounsellors,goal).
leaf(mentoringBeReceivedFromExperiencedCounsellors).
topgoal(mentoringBeReceivedFromExperiencedCounsellors).
node(increaseEmphasisOnOnlineFeedbackForm,softgoal).
node(meetingBeAttended,goal).
topgoal(meetingBeAttended).
node(provideWrittenCounselling,task).
node(callerStatistics,resource).
node(provideCounselling,task).
node(promoteCS1,task).
node(speakPubliclyAboutJob,task).
leaf(speakPubliclyAboutJob).
node(voiceCounsellingBePerformed3,task).
node(exploreOptions1,task).
leaf(exploreOptions1).
node(collectCallerSituationStatistics,task).
node(provideCounselling2,task).
node(accountabilityOfServices1,softgoal).
node(receiveTrainingFromCounsellors,task).
node(empoweringKidsToHelpThemselves,softgoal).
node(currentResourceLinks,softgoal).
node(decreaseClumsinessTechnology,softgoal).
node(attendWebModeratorMeetings,task).
node(effectiveUseOfTechnologyCounsellors2,softgoal).
node(increaseConnectionBetweenCounsellorsAndCounselled,softgoal).
node(debriefWithCounsellors,task).
leaf(debriefWithCounsellors).
node(accommodateSchedules1,softgoal).
leaf(accommodateSchedules1).
node(improvedWritingSkills,softgoal).
leaf(improvedWritingSkills).
node(undergoCDBasedTraining,task).
node(doubleHeadsets,resource).
leaf(doubleHeadsets).
node(moderateAChat1,task).
node(findInformationInELibrary,task).
node(implementBulletinBoard1,task).
leaf(implementBulletinBoard1).
node(provideInformation1,task).
node(createCounsellingPosts1,task).
node(provideInformation2,task).
node(currentResourceLinks1,softgoal).
node(webCounsellingBePerformed3,task).
node(avoidDialoguesWebServices,softgoal).
leaf(avoidDialoguesWebServices).
node(improveITSkills2,softgoal).
node(reduceNumberOfStepsWebPostingTechnology,softgoal).
node(provideInformationInBinders,task).
leaf(provideInformationInBinders).
node(diffuseConflictWithParent1,task).
node(voiceCounsellingBePerformed2,task).
node(empoweringKidsToHelpThemselves1,softgoal).
node(accessibleResourcesForCounselors3,softgoal).
node(varietyInWork,softgoal).
node(increaseITMethodsToAcquireFeedback,softgoal).
node(provideInformation,task).
node(avoidLiabilityProblems,softgoal).
node(webCounsellingBePerformed4,task).
node(clearerCallClassificationCatagories1,softgoal).
leaf(clearerCallClassificationCatagories1).
node(provideCounselling1,task).
node(improveQualityAssuranceTechnology1,softgoal).
node(completeResourceLinks,softgoal).
node(moderateAChat,task).
node(anonymity,softgoal).
node(avoidBurnout,softgoal).
node(performEmailCounselling,task).
node(webResponsesBeGeneric,softgoal).
leaf(webResponsesBeGeneric).
node(counselorSpeakOnKidsIssuesInGeneral1,task).
leaf(counselorSpeakOnKidsIssuesInGeneral1).
node(increaseCSAwareness1,softgoal).
leaf(increaseCSAwareness1).
node(resourcesBeProvided,goal).
topgoal(resourcesBeProvided).
node(createCounsellingPosts,task).
node(informationBindersAtStations,resource).
node(highQualityCounselling3,softgoal).
node(easierToFindPostsWebPostingTechnology,softgoal).
node(highQualityResources,softgoal).
node(increaseCSAwareness,softgoal).
node(effectiveUseOfTechnologyCounsellors,softgoal).
node(accountabilityOfServices2,softgoal).
node(facilitateFasterChangesInCounsellorDuties1,softgoal).
node(highQualityResources1,softgoal).
node(provideResourcesInOneSource,task).
leaf(provideResourcesInOneSource).
node(implementEmailForCounsellors1,task).
leaf(implementEmailForCounsellors1).
node(updateOutdatedLinks,task).
node(deepenCounsellingSession,softgoal).
leaf(deepenCounsellingSession).
node(helpAsManyKidsAsPossible1,softgoal).
node(trainingBeReceived1,goal).
topgoal(trainingBeReceived1).
node(correctInterpretationOfCounsel1,softgoal).
leaf(correctInterpretationOfCounsel1).
node(avoidShortStaffing,softgoal).
node(acquirePublicSpeakingSkills3,softgoal).
node(makeTapesForClinicalReview,task).
node(webCounsellingBePerformed,task).
node(improveCounsellingSkills2,softgoal).
node(undergoClinicalReview2,task).
node(implementBulletinBoard,task).
node(counselorSpeakOnKidsIssuesInGeneral,task).
node(provideTrainingToNewCounsellors,task).
node(attendCounsellingWorkshops,task).
node(avoidRelationshipsWithSpecificCounsellor,softgoal).
node(rememberLocationsOfResouces,softgoal).
leaf(rememberLocationsOfResouces).
node(provideResourcesAsCurrentlyDone,task).
node(writeArticlesForMagazines1,task).
leaf(writeArticlesForMagazines1).
node(patientCounselor1,softgoal).
node(webResponsesBeGeneric2,softgoal).
node(participateInEvents,task).
node(diffuseConflictWithParent2,task).
edge(professionalWorkEnvironment1,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(decreaseDifficultiesWithTechnology,performDutiesQuickly,0.5).
edge(increasedPeerSupport1,increasedPeerSupport3,1).
edge(trainingBeReceived2,performTheJobOfCounselling,1).
edge(deepenCounsellingSession,webCounsellingBePerformed,-0.5).
edge(reportAbuses,provideCounselling,1).
edge(writeArticlesForMagazines1,writeArticlesForMagazines,1).
edge(increaseFeedback,improveCounsellingSkills,0.5).
edge(undergoClinicalReview1,positiveEmploymentEvaluation,0.5).
edge(avoidPressureToPerformDutiesQuickly,decreaseFactoryWorkerAtmosphere,0.5).
edge(comfortableWithPerceivedPurposeOfTechnology,decreaseDifficultiesWithTechnology,0.5).
edge(assessSituation1,provideWrittenCounselling,1).
edge(empoweringKidsToHelpThemselves,empoweringKidsToHelpThemselves1,1).
edge(learnWebTechnologies,receiveAdditionalTrainingAsAnExperiencedCousnellor,1).
edge(participateInEvents1,promoteCS1,1).
edge(voiceCounsellingBePerformed2,voiceCounsellingBePerformed,1).
edge(performEmailCounselling,performEmailCounselling1,1).
edge(prideInJob,enthusiasticWorkAtmosphere,0.5).
edge(implementEmailForCounsellors2,happinessCounsellors,0.5).
edge(informationBindersAtStations,findInformationInBinders,1).
edge(counsellorsBeUnionized,performDutiesQuickly,0.5).
edge(highQualityResources1,highQualityCounselling,0.5).
edge(recordStories,provideCounselling,1).
edge(listenToCallsOfExperiencedCounsellors,receiveTrainingFromCounsellors,1).
edge(performDutiesQuickly,helpAsManyKidsAsPossible,0.5).
edge(helpAsManyKidsAsPossible,prideInJob,0.5).
edge(diffuseConflictWithParent,diffuseConflictWithParent1,1).
edge(provideCounselling1,voiceCounsellingBePerformed1,1).
edge(voiceCounsellingBePerformed1,voiceCounsellingBePerformed2,1).
edge(kidsBePreparedForFormalAbuseReportingProcess,provideCounselling,1).
edge(diffuseConflictWithParent1,diffuseConflictWithParent2,1).
edge(highDegreeOfSimilarityBetweenServicesProvided1,highDegreeOfSimilarityBetweenServicesProvided,1).
edge(performDutiesQuickly,enthusiasticWorkAtmosphere,-0.5).
edge(voiceCounsellingBePerformed,provideCounselling,1).
edge(highQualityResources,highQualityResources2,1).
edge(performEmailCounselling,increasedCautionContentOfOnlineServices2,-0.5).
edge(itSystemsBeIntegrated,itSystemsBeIntegrated1,1).
edge(webCounsellingBePerformed2,webCounsellingBePerformed,1).
edge(easierToFindPostsWebPostingTechnology,improveWebPostingTechnology1,0.5).
edge(counsellorsEngageEmotionallyInSession,highQualityCounselling,0.5).
edge(doubleHeadsets,haveClinicalSupervisorsListenToCalls,1).
edge(provideWebCounsellingWithAudio,webCounsellingBePerformed1,1).
edge(provideWebCounsellingWithAudio,webCounsellingBePerformed1,1).
edge(counsellorsBeUnionized,considerationOfFeedbackManagers,0.5).
edge(rememberLocationsOfResouces,performDutiesQuickly,0.5).
edge(attendCounsellingWorkshops,receiveAdditionalTrainingAsAnExperiencedCousnellor,1).
edge(completeResourceLinks,decreaseWorkDifficulty,0.5).
edge(increaseNumberOfCounsellors,avoidShortStaffing,0.5).
edge(webResponsesBeGeneric1,webResponsesBeGeneric2,1).
edge(implementEmailForCounsellors1,implementEmailForCounsellors2,1).
edge(accessibleResourcesForCounselors3,accessibleResourcesForCounselors4,1).
edge(performConferenceCallWithThirdParty,situationBeDealtWith,1).
edge(commentOnTechnologyUsabilityIssues,avoidBeingLabelledAntiTechnology,-0.5).
edge(prepareTechnicalPhoneEnvironment,voiceCounsellingBePerformed1,1).
edge(briefTherapyCounsellingBeUsed,provideCounselling,1).
edge(improveCounsellingSkills,improveCounsellingSkills3,1).
edge(cuttingAndPastingBeAddedToWebPostingSoftware,improveWebPostingTechnology1,0.5).
edge(receiveCallClassificationTraining,receiveTrainingAsANewCounsellor,1).
edge(clearerCallClassificationCatagories1,clearerCallClassificationCatagories,1).
edge(highQualityCounselling1,enthusiasticWorkAtmosphere,0.5).
edge(highQualityCounselling1,highQualityCounselling2,1).
edge(accessibleResourcesForCounselors3,accessibleResourcesForCounselors2,1).
edge(increaseITMethodsToAcquireFeedback,increaseFeedback,0.5).
edge(accessibleResourcesForCounselors,performDutiesQuickly,0.5).
edge(reduceNumberOfStepsWebPostingTechnology,increasedCautionContentOfOnlineServices2,-0.5).
edge(performDutiesQuickly,avoidPressureToPerformDutiesQuickly,0.5).
edge(considerationOfFeedbackManagers1,considerationOfFeedbackManagers,1).
edge(completeResourceLinks4,completeResourceLinks3,1).
edge(consistentResourceLinks,highQualityResources,0.5).
edge(receiveTrainingAsANewCounsellor,trainingBeReceived,1).
edge(implementCategorizationTool,categorizeCall,1).
edge(currentResourceLinks1,highQualityResources,0.5).
edge(provideCounselling,provideCounselling3,1).
edge(engageInDialogWithCounselled,increaseConnectionBetweenCounsellorsAndCounselled,0.5).
edge(reduceNumberOfStepsWebPostingTechnology1,reduceNumberOfStepsWebPostingTechnology,1).
edge(moderateDiscussionBoards,increasedCautionContentOfOnlineServices2,0.5).
edge(counsellorsPoliceThemselves,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(doubleHeadsets,listenToCallsOfNewCounsellors,1).
edge(provideResourcesInOneSource,consistentResourceLinks2,0.5).
edge(reduceNumberOfStepsWebPostingTechnology,improveWebPostingTechnology1,0.5).
edge(webResponsesBeGeneric,webResponsesBeGeneric1,1).
edge(counsellorsBeUnionized,avoidTensionConfrontationAnimosityAmongstEmployees,-0.5).
edge(signContractWithCounsellingUnion,counsellorsBeUnionized,1).
edge(provideInformationToOtherCounselloers,provideSupportToCounsellors,1).
edge(listenForCues,findEffectiveCues,0.5).
edge(increaseConnectionBetweenCounsellorsAndCounselled,highQualityCounselling,0.5).
edge(promoteCS2,promoteCS,1).
edge(logIntoActivityManager,prepareTechnicalPhoneEnvironment,1).
edge(haveClinicalSupervisorsListenToCalls,clinicalSupervisorsListenToCalls,1).
edge(recognition,recognition1,1).
edge(avoidBeingLabelledAntiTechnology,positiveEmploymentEvaluation,0.5).
edge(avoidLiabilityProblems,happinessCounsellors,0.5).
edge(acquireFeedback,increaseFeedback,0.5).
edge(happinessCounsellors,moveOnToBetterJob,-0.5).
edge(decreaseClumsinessTechnology1,decreaseClumsinessTechnology,1).
edge(decreaseWorkDifficulty,happinessCounsellors,0.5).
edge(aResolutionFocusApproachBeUsed,provideCounselling,1).
edge(informationResourcesBeFound,provideInformation2,1).
edge(toolsToBurnNegativeEnergyBePresent,professionalWorkEnvironment1,-0.5).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,happinessCounsellors,0.5).
edge(reduceStaggeringOfSchedules,increasedPeerSupport1,0.5).
edge(webResponsesBeGeneric2,helpAsManyKidsAsPossible1,0.5).
edge(trainingBeReceived,improveCounsellingSkills,0.5).
edge(decreaseFactoryWorkerAtmosphere,happinessCounsellors,0.5).
edge(highQualityResources1,consistentCounsellingResponses,0.5).
edge(allowUserToLogIn1,logIntoActivityManager,1).
edge(increasedPeerSupport2,releaseTension,0.5).
edge(effectiveUseOfTechnologyCounsellors2,effectiveUseOfTechnologyCounsellors1,1).
edge(passProbationWithinSixMonths,receiveTrainingAsANewCounsellor,1).
edge(reduceMonitoringOfActivities,comfortableWithPerceivedPurposeOfTechnology,0.5).
edge(anonymity,safety,0.5).
edge(controlOfCounsellingWork,happinessCounsellors,0.5).
edge(increaseEmphasisOnOnlineFeedbackForm1,increaseEmphasisOnOnlineFeedbackForm,1).
edge(provideWrittenCounselling,createCounsellingPosts,1).
edge(controlOfCounsellingWork,avoidLiabilityProblems,0.5).
edge(counsellorsBeUnionized,facilitateFasterChangesInCounsellorDuties1,-0.5).
edge(performCounsellingAsInstructedBySupervisor,positiveEmploymentEvaluation,0.5).
edge(considerationOfFeedbackITProviders,decreaseFactoryWorkerAtmosphere,0.5).
edge(feedbackOnCallsBeGiven,provideTrainingToNewCounsellors,1).
edge(situationBeDealtWith,provideCounselling1,1).
edge(controlOfCounsellingWork1,controlOfCounsellingWork,1).
edge(currentResourceLinks4,currentResourceLinks3,1).
edge(releaseTension,professionalWorkEnvironment1,-0.5).
edge(webCounsellingBePerformed1,webCounsellingBePerformed2,1).
edge(updateOutdatedLinks,manageCounsellingResources,1).
edge(helpKids,helpKids1,1).
edge(meetingBeAttended,provideSupportToCounsellors,1).
edge(counsellorsBeUnionized,considerationOfFeedbackITProviders,0.5).
edge(improveQualityAssuranceTechnology,improveQualityAssuranceTechnology2,1).
edge(editOnlinePostsOfKids,increasedCautionContentOfOnlineServices2,0.5).
edge(decreaseClumsinessTechnology2,counsellorsEngageEmotionallyInSession,0.5).
edge(improveCallRecordingEquipment,improveQualityAssuranceTechnology,0.5).
edge(highQualityCounselling,patientCounselor,1).
edge(provideInformation2,provideInformation1,1).
edge(voiceCounsellingBePerformed,helpAsManyKidsAsPossible1,0.5).
edge(considerationOfFeedbackManagers,reduceMonitoringOfActivities,0.5).
edge(avoidBeingDirective,highQualityCounselling,0.5).
edge(webCounsellingBePerformed,findEffectiveCues,-0.5).
edge(avoidRelationshipsWithSpecificCounsellor1,avoidRelationshipsWithSpecificCounsellor,1).
edge(increaseEmphasisOnOnlineFeedbackForm,increaseFeedback,0.5).
edge(implementEmailForCounsellors,improveCommunicationBetweenCounsellors,0.5).
edge(patientCounselor,patientCounselor1,1).
edge(decreaseWorkLoad,avoidBurnout,0.5).
edge(promoteCS,performTheJobOfCounselling,1).
edge(performCounsellingAsInstructedBySupervisor1,supportIndividualityInCounsellingTechniques,-0.5).
edge(improveITSkills,positiveEmploymentEvaluation,0.5).
edge(improveWebPostingTechnology,decreaseDifficultiesWithTechnology,0.5).
edge(situationBeDealtWith1,provideWrittenCounselling,1).
edge(updateOutdatedLinks,currentResourceLinks4,0.5).
edge(performEmailCounselling,webCounsellingBePerformed1,1).
edge(provideWrittenCounselling,provideWebCounsellingWithVideo,1).
edge(consistentCounsellingResponses,highQualityCounselling,0.5).
edge(listenForCues,provideCounselling,1).
edge(highDegreeOfSimilarityBetweenServicesProvided2,highDegreeOfSimilarityBetweenServicesProvided1,1).
edge(accountabilityOfServices,prideInJob,0.5).
edge(considerationOfFeedbackITProviders1,considerationOfFeedbackITProviders,1).
edge(avoidDialoguesWebServices1,decreaseKidsIsolation,0.5).
edge(avoidBeingDirective,empoweringKidsToHelpThemselves2,0.5).
edge(undergoMediaTraining,receiveAdditionalTrainingAsAnExperiencedCousnellor,1).
edge(implementBulletinBoard,improveCommunicationBetweenCounsellors,0.5).
edge(provideWrittenCounselling,provideWrittenCounselling1,1).
edge(increaseITTraining,improveITSkills1,0.5).
edge(rememberLocationsOfResouces,decreaseWorkDifficulty,0.5).
edge(reduceStaggeringOfSchedules1,reduceStaggeringOfSchedules,1).
edge(provideResourcesInLibrary,provideResourcesAsCurrentlyDone,1).
edge(increaseCSAwareness1,increaseCSAwareness,1).
edge(decreaseClumsinessTechnology,decreaseDifficultiesWithTechnology,0.5).
edge(increasedPeerSupport,highQualityCounselling,0.5).
edge(makeTapesForClinicalReview,clinicalSupervisorsListenToCalls,1).
edge(performFirstReadingOfCounsellingPosts,webCounsellingBePerformed1,1).
edge(removeIdentifyingMaterial,removeInappropriateMaterial,1).
edge(professionalWorkEnvironment1,enthusiasticWorkAtmosphere,-0.5).
edge(accessibleResourcesForCounselors2,accessibleResourcesForCounselors,1).
edge(undergoMediaTraining,receiveTrainingAsANewCounsellor,1).
edge(consistentResourceLinks2,highQualityResources3,0.5).
edge(considerationOfFeedbackITProviders,decreaseDifficultiesWithTechnology,0.5).
edge(receiveInformationFromOtherCounsellors,provideInformation2,1).
edge(releaseTension,highQualityCounselling1,0.5).
edge(correctInterpretationOfCounsel1,correctInterpretationOfCounsel,1).
edge(blockKidsWhoDisplayInappropriateBehavoir,moderateAChat,1).
edge(undergoClinicalReview1,performTheJobOfCounselling,1).
edge(encourageKidsToTalkToDifferentCounsellors,avoidRelationshipsWithSpecificCounsellor1,0.5).
edge(undergoMediaTraining,acquirePublicSpeakingSkills,1).
edge(completeResourceLinks3,completeResourceLinks2,1).
edge(improveCounsellingSkills2,consistentCounsellingResponses,0.5).
edge(promoteCS1,promoteCS2,1).
edge(anonymityCounsellors,anonymity,1).
edge(writeArticlesForMagazines1,promoteCS1,1).
edge(simpleTechnology,decreaseDifficultiesWithTechnology,0.5).
edge(assessSituation,provideCounselling1,1).
edge(receiveFeedback,undergoClinicalReview,1).
edge(provideInformationInBinders,informationBindersAtStations,1).
edge(receiveTrainingFromManagment,receiveAdditionalTrainingAsAnExperiencedCousnellor,1).
edge(provideWebCounsellingWithVideo,provideWebCounsellingWithVideo1,1).
edge(getRidOfUnion,considerationOfFeedbackManagers,-0.5).
edge(writeArticlesForWebsite1,createWebSiteContent,1).
edge(completeResourceLinks1,completeResourceLinks,1).
edge(reducePhysicalObservationHearingByStaffNotInCounsellingTeam,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(provideResourcesInOneSource,resourcesBeProvided,1).
edge(salary,receiveSalary,1).
edge(listenToCallsOfNewCounsellors,feedbackOnCallsBeGiven,1).
edge(increasedCautionContentOfOnlineServices2,increasedCautionContentOfOnlineServices1,1).
edge(beConsultedAboutNewPolicies,decreaseFactoryWorkerAtmosphere,0.5).
edge(removeInappropriateMaterial,editOnlinePostsOfKids,1).
edge(simpleTechnology1,simpleTechnology,1).
edge(improveQualityAssuranceTechnology2,improveQualityAssuranceTechnology1,1).
edge(reduceMonitoringOfActivities,happinessCounsellors,0.5).
edge(increasedCautionContentOfOnlineServices1,increasedCautionContentOfOnlineServices,1).
edge(webResponsesBeGeneric,increasedCautionContentOfOnlineServices2,0.5).
edge(increasedCautionContentOfOnlineServices,avoidLiabilityProblems,0.5).
edge(undergoClinicalReview,undergoClinicalReview2,1).
edge(completeResourceLinks4,highQualityResources3,0.5).
edge(allowUserToLogIn,logIntoPhoneSystem,1).
edge(webCounsellingBePerformed4,varietyInWork,0.5).
edge(logIntoPhoneSystem,prepareTechnicalPhoneEnvironment,1).
edge(reportOutdatedLinks1,reportOutdatedLinks,1).
edge(exploreOptions1,situationBeDealtWith1,1).
edge(collectCallerSituationStatistics,callerStatistics,1).
edge(provideResourcesInLibrary,resourcesInTheLibrary,1).
edge(webCounsellingBePerformed,helpAsManyKidsAsPossible1,0.5).
edge(decreaseClumsinessTechnology1,decreaseClumsinessTechnology2,1).
edge(recordStories,csStories,1).
edge(speakPubliclyAboutJob,promoteCS1,1).
edge(undergoClinicalReview2,undergoClinicalReview1,1).
edge(encourageKidsToTalkToOthers,provideCounselling,1).
edge(trainingBeReceived,trainingBeReceived1,1).
edge(recognition1,recognition2,1).
edge(recognition,enthusiasticWorkAtmosphere,0.5).
edge(avoidLiabilityProblems,avoidLiabilityProblems1,1).
edge(webCounsellingBePerformed,accountabilityOfServices2,0.5).
edge(requestShifts,performTheJobOfCounselling,1).
edge(provideInformation2,empoweringKidsToHelpThemselves,0.5).
edge(decreaseClumsinessTechnology,performDutiesQuickly,0.5).
edge(blockKidsWhoDisplayInappropriateBehavoir,moderateDiscussionBoards,1).
edge(reducePrankCalls1,avoidBurnout,0.5).
edge(moderateAChat,webCounsellingBePerformed1,1).
edge(deepenCounsellingSession,increaseConnectionBetweenCounsellorsAndCounselled,0.5).
edge(findInformationInELibrary,informationResourcesBeFound,1).
edge(improveCounsellingSkills2,highQualityCounselling,0.5).
edge(acquirePublicSpeakingSkills1,recognition2,0.5).
edge(createCounsellingPosts,webCounsellingBePerformed1,1).
edge(provideResourcesInELibrary,provideResourcesAsCurrentlyDone,1).
edge(toolsToBurnNegativeEnergyBePresent,releaseTension,0.5).
edge(accommodateSchedules1,accommodateSchedules,1).
edge(diffuseConflictWithParent2,avoidLiabilityProblems,0.5).
edge(clinicalSupervisorsListenToCalls,receiveFeedback,1).
edge(resourcesBeProvided,manageCounsellingResources,1).
edge(resourcesInTheLibrary,findInformationInLibrary,1).
edge(editOnlinePostsOfKids,reduceContagionEffectOfHarmfulActions,0.5).
edge(provideWrittenCounselling,provideWebCounsellingWithAudio,1).
edge(promoteCounselling,recognition2,0.5).
edge(counselorSpeakOnKidsIssuesInGeneral1,counselorSpeakOnKidsIssuesInGeneral,1).
edge(enthusiasticWorkAtmosphere,happinessCounsellors,0.5).
edge(improveITSkills3,improveITSkills,1).
edge(counsellingPolicies,counsellingPoliciesBeFollowed,1).
edge(happinessCounsellors,highQualityCounselling1,0.5).
edge(increasedPeerSupport2,happinessCounsellors,0.5).
edge(provideInformation1,provideInformation,1).
edge(participateInBoardMeetings,promoteCounselling,1).
edge(clearerCallClassificationCatagories,performDutiesQuickly,0.5).
edge(attendWebModeratorMeetings,meetingBeAttended,1).
edge(accountabilityOfServices1,accountabilityOfServices,1).
edge(releaseTension,happinessCounsellors,0.5).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,decreaseFactoryWorkerAtmosphere,0.5).
edge(improvedWritingSkills,positiveEmploymentEvaluation,0.5).
edge(positiveEmploymentEvaluation,acquireRecognizableEmploymentExperience,0.5).
edge(voiceCounsellingBePerformed1,voiceCounsellingBePerformed3,1).
edge(completeResourceLinks2,completeResourceLinks1,1).
edge(referParentsToPHL,provideCounselling,1).
edge(feedback,acquireFeedback,1).
edge(provideResourcesAsCurrentlyDone,consistentResourceLinks2,-0.5).
edge(provideResourcesAsCurrentlyDone,consistentResourceLinks2,-0.5).
edge(provideWebCounsellingWithVideo,highDegreeOfSimilarityBetweenServicesProvided2,0.5).
edge(webCounsellingBePerformed,decreaseKidsIsolation,-0.5).
edge(debriefWithCounsellors,effectiveDebriefing,0.5).
edge(improveQualityAssuranceTechnology1,decreaseDifficultiesWithTechnology,0.5).
edge(counselorSpeakOnKidsIssuesInGeneral1,promoteCS1,1).
edge(webPostsBeReviewedByClinicalSupervisor,receiveFeedback,1).
edge(speakAtSAConferences,promoteCS1,1).
edge(includeDrugInformationInCounsellingResources,manageCounsellingResources,1).
edge(improveCounsellingSkills3,improveCounsellingSkills1,1).
edge(improveITSkills1,improveITSkills3,1).
edge(provideInformation,performTheJobOfCounselling,1).
edge(iconsForCounsellingInformationBeOnDesktop,accessibleResourcesForCounselors3,0.5).
edge(provideWrittenCounselling,performEmailCounselling,1).
edge(createCounsellingPosts,createCounsellingPosts1,1).
edge(accessibleResourcesForCounselors1,highQualityCounselling,0.5).
edge(clinicalSupervisorsListenToCalls,undergoClinicalReview,1).
edge(debriefWithCounsellors,provideSupportToCounsellors,1).
edge(implementBulletinBoard1,implementBulletinBoard,1).
edge(increasedPeerSupport3,increasedPeerSupport,1).
edge(categorizeCall,collectCallerSituationStatistics,1).
edge(moderateDiscussionBoards,reduceContagionEffectOfHarmfulActions,0.5).
edge(mentoringBeReceivedFromExperiencedCounsellors,receiveTrainingFromCounsellors,1).
edge(moderateDiscussionBoards,webCounsellingBePerformed1,1).
edge(accessibleResourcesForCounselors5,accessibleResourcesForCounselors3,1).
edge(considerationOfFeedbackManagers,decreaseFactoryWorkerAtmosphere,0.5).
edge(improveCallRecordingEquipment1,improveCallRecordingEquipment,1).
edge(decreaseWorkLoad,happinessCounsellors,0.5).
edge(webCounsellingBePerformed,supportIndividualityInCounsellingTechniques,-0.5).
edge(increasedCautionContentOfOnlineServices,performDutiesQuickly,-0.5).
edge(provideInformationToOtherCounselloers,informationResources,1).
edge(encourageKidsToTalkToOthers,decreaseKidsIsolation,0.5).
edge(enthusiasticWorkAtmosphere,avoidBurnout,0.5).
edge(participateInEvents1,participateInEvents,1).
edge(webPostsBeReviewedByClinicalSupervisor,undergoClinicalReview,1).
edge(positiveEmploymentEvaluation,happinessCounsellors,0.5).
edge(provideWebCounsellingWithAudio,provideWebCounsellingWithAudio1,1).
edge(professionalWorkEnvironment1,professionalWorkEnvironment,1).
edge(resourcesBeProvided,completeResourceLinks4,0.5).
edge(supportIndividualityInCounsellingTechniques,highQualityCounselling,0.5).
edge(avoidDialoguesWebServices,avoidDialoguesWebServices1,1).
edge(improveITSkills,avoidBeingLabelledAntiTechnology,0.5).
edge(blockKidsWhoDisplayInappropriateBehavoir,increasedCautionContentOfOnlineServices2,0.5).
edge(highDegreeOfSimilarityBetweenServicesProvided,decreaseWorkDifficulty,0.5).
edge(encourageKidsToCallCS,createCounsellingPosts,1).
edge(improveCommunicationBetweenCounsellors,increasedPeerSupport1,0.5).
edge(highQualityCounselling1,prideInJob,0.5).
edge(writeArticlesForWebsite1,writeArticlesForWebsite,1).
edge(highQualityResources2,highQualityResources1,1).
edge(receiveTrainingFromCounsellors,receiveTrainingAsANewCounsellor,1).
edge(positiveEmploymentEvaluation,retainJob,0.5).
edge(highQualityCounselling,highQualityCounselling3,1).
edge(currentResourceLinks3,currentResourceLinks1,1).
edge(provideResourcesInOneSource,accessibleResourcesForCounselors6,0.5).
edge(acquirePublicSpeakingSkills3,positiveEmploymentEvaluation,0.5).
edge(receiveAdditionalTrainingAsAnExperiencedCousnellor,trainingBeReceived,1).
edge(learnWebTechnologies,receiveTrainingAsANewCounsellor,1).
edge(accessibleResourcesForCounselors4,accessibleResourcesForCounselors1,1).
edge(acquirePublicSpeakingSkills2,acquirePublicSpeakingSkills3,1).
edge(helpAsManyKidsAsPossible1,helpAsManyKidsAsPossible3,1).
edge(performCounsellingAsInstructedBySupervisor,performCounsellingAsInstructedBySupervisor2,1).
edge(improveCounsellingSkills1,positiveEmploymentEvaluation,0.5).
edge(exploreOptions,situationBeDealtWith,1).
edge(moderateAChat,increasedCautionContentOfOnlineServices2,-0.5).
edge(implementEmailForCounsellors1,implementEmailForCounsellors,1).
edge(getRidOfUnion,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(increaseCSAwareness,prideInJob,0.5).
edge(effectiveUseOfTechnologyCounsellors,effectiveUseOfTechnologyCounsellors2,1).
edge(easilyAccessableTechnologyInstructions1,easilyAccessableTechnologyInstructions,1).
edge(rememberLocationsOfResouces,rememberLocationsOfResouces1,1).
edge(createWebSiteContent,webSiteContent,1).
edge(attendPartTimeMeeting,meetingBeAttended,1).
edge(avoidShortStaffing,decreaseWorkLoad,0.5).
edge(empoweringKidsToHelpThemselves1,empoweringKidsToHelpThemselves2,1).
edge(aResolutionFocusApproachBeUsed,avoidBeingDirective,0.5).
edge(increaseITMethodsToAcquireFeedback1,increaseITMethodsToAcquireFeedback,1).
edge(findInformationInBinders,informationResourcesBeFound,1).
edge(participateInEvents1,recognition2,0.5).
edge(trainingBeReceived1,trainingBeReceived2,1).
edge(increaseITTrainingForCounsellors,increaseITTraining,1).
edge(currentResourceLinks2,currentResourceLinks,1).
edge(varietyInWork,happinessCounsellors,0.5).
edge(facilitateFasterChangesInCounsellorDuties1,facilitateFasterChangesInCounsellorDuties,1).
edge(webModeratorMeetings,attendWebModeratorMeetings,1).
edge(provideResourcesInELibrary,informationInELibrary,1).
edge(correctInterpretationOfCounsel,highQualityCounselling,0.5).
edge(updateOutdatedLinks,completeResourceLinks4,0.5).
edge(decreaseDifficultiesWithTechnology,decreaseWorkDifficulty,0.5).
edge(releaseTension,avoidBurnout,0.5).
edge(enthusiasticWorkAtmosphere,improveCounsellingSkills1,0.5).
edge(reducePrankCalls,reducePrankCalls1,1).
edge(controlOfFloorOperations,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(encourageKidsToTalkToDifferentCounsellors,provideCounselling1,1).
edge(helpAsManyKidsAsPossible,helpAsManyKidsAsPossible2,1).
edge(informationResources,receiveInformationFromOtherCounsellors,1).
edge(consistentResourceLinks2,consistentResourceLinks1,1).
edge(provideSupportToCounsellors,improveCommunicationBetweenCounsellors,0.5).
edge(participateInSponsorMeetings,promoteCS1,1).
edge(findEffectiveCues,highQualityCounselling,0.5).
edge(signContractWithCounsellingUnion,signContract,1).
edge(provideCounselling2,performTheJobOfCounselling,1).
edge(commentOnTechnologyUsabilityIssues,decreaseDifficultiesWithTechnology,0.5).
edge(attendCounsellingWorkshops,receiveTrainingAsANewCounsellor,1).
edge(acquireRecognizableEmploymentExperience,moveOnToBetterJob,0.5).
edge(effectiveDebriefing,increasedPeerSupport1,0.5).
edge(performCounsellingAsInstructedBySupervisor2,performCounsellingAsInstructedBySupervisor1,1).
edge(webCounsellingBePerformed3,webCounsellingBePerformed4,1).
edge(happinessCounsellors,performDutiesQuickly,0.5).
edge(easierToFindPostsWebPostingTechnology1,easierToFindPostsWebPostingTechnology,1).
edge(findInformationInLibrary,informationResourcesBeFound,1).
edge(reportOutdatedLinks,updateOutdatedLinks,1).
edge(provideTrainingToNewCounsellors,provideSupportToCounsellors,1).
edge(removeInappropriateMaterial,moderateDiscussionBoards,1).
edge(decreaseWorkDifficulty,avoidBurnout,0.5).
edge(performFirstReadingOfCounsellingPosts,increasedCautionContentOfOnlineServices2,0.5).
edge(accessibleResourcesForCounselors6,accessibleResourcesForCounselors5,1).
edge(informationInELibrary,findInformationInELibrary,1).
edge(highQualityCounselling2,highQualityCounselling,1).
edge(performCrisisIntervention,situationBeDealtWith,1).
edge(beConsultedAboutNewPolicies,considerationOfFeedbackManagers,0.5).
edge(undergoClinicalReview1,improveCounsellingSkills1,0.5).
edge(removeInappropriateMaterial,increasedCautionContentOfOnlineServices2,0.5).
edge(tapes,makeTapesForClinicalReview,1).
edge(provideResourcesAsCurrentlyDone,resourcesBeProvided,1).
edge(acquirePublicSpeakingSkills,acquirePublicSpeakingSkills2,1).
edge(receiveTrainingFromManagment,receiveTrainingAsANewCounsellor,1).
edge(webCounsellingBePerformed,counsellorsEngageEmotionallyInSession,-0.5).
edge(happinessCounsellors,happinessCounsellors1,1).
edge(beAMentorToNewCounsellors,provideTrainingToNewCounsellors,1).
edge(improvedWritingSkills,improvedWritingSkillsCounsellors,1).
edge(empoweringKidsToHelpThemselves2,highQualityCounselling,0.5).
edge(provideCounselling,counsellorExperience,1).
edge(decreaseDifficultiesWithTechnology,happinessCounsellors,0.5).
edge(trainingCDs,undergoCDBasedTraining,1).
edge(avoidBurnout,happinessCounsellors,0.5).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,enthusiasticWorkAtmosphere,0.5).
edge(considerationOfFeedbackManagers,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(increasedPeerSupport3,increasedPeerSupport2,1).
edge(undergoCDBasedTraining,receiveAdditionalTrainingAsAnExperiencedCousnellor,1).
edge(receiveSalary,performTheJobOfCounselling,1).
edge(rememberLocationsOfResouces1,rememberLocationsOfResouces2,1).
edge(prideInJob,happinessCounsellors,0.5).
edge(decreaseKidsIsolation,highQualityCounselling,0.5).
edge(improveWebPostingTechnology1,improveWebPostingTechnology2,1).
edge(tapeRecordingTechnology,haveClinicalSupervisorsListenToCalls,1).
edge(improveITSkills,decreaseDifficultiesWithTechnology,0.5).
edge(accommodateSchedules,happinessCounsellors,0.5).
edge(counsellingWorkshops,attendCounsellingWorkshops,1).
edge(counsellorsEngageEmotionallyInSession,supportIndividualityInCounsellingTechniques,0.5).
edge(reportOutdatedLinks1,currentResourceLinks1,0.5).
edge(provideCounselling3,provideCounselling2,1).
edge(editCounsellingPosts,performFirstReadingOfCounsellingPosts,1).
edge(counsellorsPoliceThemselves,reduceMonitoringOfActivities,0.5).
edge(collectCallerSituationStatistics,provideCounselling1,1).
edge(avoidTensionConfrontationAnimosityAmongstEmployees,toolsToBurnNegativeEnergyBePresent,0.5).
edge(diffuseConflictWithParent,situationBeDealtWith,1).
edge(clearerCallClassificationCatagories,decreaseWorkDifficulty,0.5).
edge(improveITSkills1,improveITSkills2,1).
edge(easilyAccessableTechnologyInstructions,decreaseDifficultiesWithTechnology,0.5).
edge(reduceMonitoringOfActivities,avoidTensionConfrontationAnimosityAmongstEmployees,0.5).
edge(counsellingPoliciesBeFollowed,counsellingPoliciesBeFollowed1,1).
edge(acquirePublicSpeakingSkills2,acquirePublicSpeakingSkills1,1).
edge(accountabilityOfServices2,accountabilityOfServices1,1).
edge(provideWebCounsellingWithAudio,highDegreeOfSimilarityBetweenServicesProvided2,0.5).
edge(improveWebPostingTechnology2,improveWebPostingTechnology,1).
edge(getRidOfUnion,facilitateFasterChangesInCounsellorDuties1,0.5).
edge(currentResourceLinks,decreaseWorkDifficulty,0.5).
edge(consistentResourceLinks1,consistentResourceLinks,1).
edge(currentResourceLinks1,currentResourceLinks2,1).
edge(reducePrankCalls1,happinessCounsellors,0.5).
edge(increaseNumberOfCounsellors1,increaseNumberOfCounsellors,1).
edge(engageInDialogWithCounselled,webCounsellingBePerformed,-0.5).
edge(moderateDiscussionBoards,moderateDiscussionBoards1,1).
edge(provideInformationInBinders,provideResourcesAsCurrentlyDone,1).
edge(improveITSkills1,effectiveUseOfTechnologyCounsellors,0.5).
edge(itSystemsBeIntegrated,decreaseDifficultiesWithTechnology,0.5).
edge(decreaseKidsIsolation,helpKids,0.5).
edge(editOnlinePostsOfKids,moderateDiscussionBoards,1).
edge(moderateAChat,moderateAChat1,1).
edge(recognition,happinessCounsellors,0.5).
edge(includeLegalInformationInCounsellingResources,manageCounsellingResources,1).
edge(reduceContagionEffectOfHarmfulActions,reduceContagionEffectOfHarmfulActions1,1).
edge(helpAsManyKidsAsPossible2,helpAsManyKidsAsPossible1,1).
edge(safety,happinessCounsellors,0.5).
edge(accessibleResourcesForCounselors,decreaseWorkDifficulty,0.5).
edge(undergoCDBasedTraining,receiveTrainingAsANewCounsellor,1).
edge(improveCounsellingSkills3,improveCounsellingSkills2,1).
edge(effectiveUseOfTechnologyCounsellors1,highQualityCounselling,0.5).
edge(accessibleResourcesForCounselors6,highQualityResources3,0.5).
edge(moderateAChat,reduceContagionEffectOfHarmfulActions,0.5).
edge(speakPubliclyAboutJob,recognition2,0.5).
edge(webCounsellingBePerformed1,webCounsellingBePerformed3,1).
