;;;; models/CSCounselling.lisp : GENERATED from models/CSCounselling.py by to-lisp.py
(<- accessibleResourcesForCounselors accessibleResourcesForCounselors2)
(<- accessibleResourcesForCounselors1 accessibleResourcesForCounselors4)
(<- accessibleResourcesForCounselors2 accessibleResourcesForCounselors3)
(<- accessibleResourcesForCounselors3 (or accessibleResourcesForCounselors5 (helps iconsForCounsellingInformationBeOnDesktop)))
(<- accessibleResourcesForCounselors4 accessibleResourcesForCounselors3)
(<- accessibleResourcesForCounselors5 accessibleResourcesForCounselors6)
(<- accommodateSchedules accommodateSchedules1)
(<- accountabilityOfServices accountabilityOfServices1)
(<- accountabilityOfServices1 accountabilityOfServices2)
(<- acquireFeedback feedback)
(<- acquirePublicSpeakingSkills1 acquirePublicSpeakingSkills2)
(<- acquirePublicSpeakingSkills2 acquirePublicSpeakingSkills)
(<- acquirePublicSpeakingSkills3 acquirePublicSpeakingSkills2)
(<- anonymity anonymityCounsellors)
(<- attendCounsellingWorkshops counsellingWorkshops)
(<- attendWebModeratorMeetings webModeratorMeetings)
(<- avoidDialoguesWebServices1 avoidDialoguesWebServices)
(<- avoidLiabilityProblems1 avoidLiabilityProblems)
(<- avoidRelationshipsWithSpecificCounsellor avoidRelationshipsWithSpecificCounsellor1)
(<- callerStatistics collectCallerSituationStatistics)
(<- categorizeCall implementCategorizationTool)
(<- clearerCallClassificationCatagories clearerCallClassificationCatagories1)
(<- clinicalSupervisorsListenToCalls (or haveClinicalSupervisorsListenToCalls makeTapesForClinicalReview))
(<- collectCallerSituationStatistics categorizeCall)
(<- completeResourceLinks completeResourceLinks1)
(<- completeResourceLinks1 completeResourceLinks2)
(<- completeResourceLinks2 completeResourceLinks3)
(<- completeResourceLinks3 completeResourceLinks4)
(<- considerationOfFeedbackITProviders (or considerationOfFeedbackITProviders1 (helps counsellorsBeUnionized)))
(<- considerationOfFeedbackManagers (or considerationOfFeedbackManagers1 (and (helps counsellorsBeUnionized) (hurts getRidOfUnion) (helps beConsultedAboutNewPolicies))))
(<- consistentResourceLinks consistentResourceLinks1)
(<- consistentResourceLinks1 consistentResourceLinks2)
(<- controlOfCounsellingWork controlOfCounsellingWork1)
(<- correctInterpretationOfCounsel correctInterpretationOfCounsel1)
(<- counsellingPoliciesBeFollowed counsellingPolicies)
(<- counsellingPoliciesBeFollowed1 counsellingPoliciesBeFollowed)
(<- counsellorExperience provideCounselling)
(<- counsellorsBeUnionized signContractWithCounsellingUnion)
(<- counselorSpeakOnKidsIssuesInGeneral counselorSpeakOnKidsIssuesInGeneral1)
(<- createCounsellingPosts (or provideWrittenCounselling encourageKidsToCallCS))
(<- createCounsellingPosts1 createCounsellingPosts)
(<- createWebSiteContent writeArticlesForWebsite1)
(<- csStories recordStories)
(<- currentResourceLinks currentResourceLinks2)
(<- currentResourceLinks1 (or currentResourceLinks3 (helps reportOutdatedLinks1)))
(<- currentResourceLinks2 currentResourceLinks1)
(<- currentResourceLinks3 currentResourceLinks4)
(<- decreaseClumsinessTechnology decreaseClumsinessTechnology1)
(<- decreaseClumsinessTechnology2 decreaseClumsinessTechnology1)
(<- diffuseConflictWithParent1 diffuseConflictWithParent)
(<- diffuseConflictWithParent2 diffuseConflictWithParent1)
(<- easierToFindPostsWebPostingTechnology easierToFindPostsWebPostingTechnology1)
(<- easilyAccessableTechnologyInstructions easilyAccessableTechnologyInstructions1)
(<- editOnlinePostsOfKids removeInappropriateMaterial)
(<- effectiveUseOfTechnologyCounsellors1 effectiveUseOfTechnologyCounsellors2)
(<- effectiveUseOfTechnologyCounsellors2 effectiveUseOfTechnologyCounsellors)
(<- empoweringKidsToHelpThemselves1 empoweringKidsToHelpThemselves)
(<- empoweringKidsToHelpThemselves2 (or empoweringKidsToHelpThemselves1 (helps avoidBeingDirective)))
(<- facilitateFasterChangesInCounsellorDuties facilitateFasterChangesInCounsellorDuties1)
(<- feedbackOnCallsBeGiven listenToCallsOfNewCounsellors)
(<- findInformationInBinders informationBindersAtStations)
(<- findInformationInELibrary informationInELibrary)
(<- findInformationInLibrary resourcesInTheLibrary)
(<- happinessCounsellors1 happinessCounsellors)
(<- haveClinicalSupervisorsListenToCalls (and doubleHeadsets tapeRecordingTechnology))
(<- helpAsManyKidsAsPossible1 (or helpAsManyKidsAsPossible2 (and (helps webResponsesBeGeneric2) (helps voiceCounsellingBePerformed) (helps webCounsellingBePerformed))))
(<- helpAsManyKidsAsPossible2 helpAsManyKidsAsPossible)
(<- helpAsManyKidsAsPossible3 helpAsManyKidsAsPossible1)
(<- helpKids1 helpKids)
(<- highDegreeOfSimilarityBetweenServicesProvided highDegreeOfSimilarityBetweenServicesProvided1)
(<- highDegreeOfSimilarityBetweenServicesProvided1 highDegreeOfSimilarityBetweenServicesProvided2)
(<- highQualityCounselling (or highQualityCounselling2 (and (helps highQualityResources1) (helps counsellorsEngageEmotionallyInSession) (helps increaseConnectionBetweenCounsellorsAndCounselled) (helps avoidBeingDirective) (helps consistentCounsellingResponses) (helps increasedPeerSupport) (helps improveCounsellingSkills2) (helps accessibleResourcesForCounselors1) (helps supportIndividualityInCounsellingTechniques) (helps correctInterpretationOfCounsel) (helps findEffectiveCues) (helps empoweringKidsToHelpThemselves2) (helps decreaseKidsIsolation) (helps effectiveUseOfTechnologyCounsellors1))))
(<- highQualityCounselling2 highQualityCounselling1)
(<- highQualityCounselling3 highQualityCounselling)
(<- highQualityResources1 highQualityResources2)
(<- highQualityResources2 highQualityResources)
(<- implementBulletinBoard implementBulletinBoard1)
(<- implementEmailForCounsellors implementEmailForCounsellors1)
(<- implementEmailForCounsellors2 implementEmailForCounsellors1)
(<- improveCallRecordingEquipment improveCallRecordingEquipment1)
(<- improveCounsellingSkills1 (or improveCounsellingSkills3 (and (helps enthusiasticWorkAtmosphere) (helps undergoClinicalReview1))))
(<- improveCounsellingSkills2 improveCounsellingSkills3)
(<- improveCounsellingSkills3 improveCounsellingSkills)
(<- improveITSkills improveITSkills3)
(<- improveITSkills2 improveITSkills1)
(<- improveITSkills3 improveITSkills1)
(<- improveQualityAssuranceTechnology1 improveQualityAssuranceTechnology2)
(<- improveQualityAssuranceTechnology2 improveQualityAssuranceTechnology)
(<- improveWebPostingTechnology improveWebPostingTechnology2)
(<- improveWebPostingTechnology2 improveWebPostingTechnology1)
(<- improvedWritingSkillsCounsellors improvedWritingSkills)
(<- increaseCSAwareness increaseCSAwareness1)
(<- increaseEmphasisOnOnlineFeedbackForm increaseEmphasisOnOnlineFeedbackForm1)
(<- increaseITMethodsToAcquireFeedback increaseITMethodsToAcquireFeedback1)
(<- increaseITTraining increaseITTrainingForCounsellors)
(<- increaseNumberOfCounsellors increaseNumberOfCounsellors1)
(<- increasedCautionContentOfOnlineServices increasedCautionContentOfOnlineServices1)
(<- increasedCautionContentOfOnlineServices1 increasedCautionContentOfOnlineServices2)
(<- increasedPeerSupport increasedPeerSupport3)
(<- increasedPeerSupport2 increasedPeerSupport3)
(<- increasedPeerSupport3 increasedPeerSupport1)
(<- informationBindersAtStations provideInformationInBinders)
(<- informationInELibrary provideResourcesInELibrary)
(<- informationResources provideInformationToOtherCounselloers)
(<- informationResourcesBeFound (or findInformationInELibrary findInformationInBinders findInformationInLibrary))
(<- itSystemsBeIntegrated1 itSystemsBeIntegrated)
(<- listenToCallsOfNewCounsellors doubleHeadsets)
(<- logIntoActivityManager allowUserToLogIn1)
(<- logIntoPhoneSystem allowUserToLogIn)
(<- makeTapesForClinicalReview tapes)
(<- manageCounsellingResources (or updateOutdatedLinks resourcesBeProvided includeDrugInformationInCounsellingResources includeLegalInformationInCounsellingResources))
(<- meetingBeAttended (or attendWebModeratorMeetings attendPartTimeMeeting))
(<- moderateAChat blockKidsWhoDisplayInappropriateBehavoir)
(<- moderateAChat1 moderateAChat)
(<- moderateDiscussionBoards (or blockKidsWhoDisplayInappropriateBehavoir removeInappropriateMaterial editOnlinePostsOfKids))
(<- moderateDiscussionBoards1 moderateDiscussionBoards)
(<- participateInEvents participateInEvents1)
(<- patientCounselor1 patientCounselor)
(<- performCounsellingAsInstructedBySupervisor1 performCounsellingAsInstructedBySupervisor2)
(<- performCounsellingAsInstructedBySupervisor2 performCounsellingAsInstructedBySupervisor)
(<- performEmailCounselling provideWrittenCounselling)
(<- performEmailCounselling1 performEmailCounselling)
(<- performFirstReadingOfCounsellingPosts editCounsellingPosts)
(<- performTheJobOfCounselling (or trainingBeReceived2 promoteCS undergoClinicalReview1 requestShifts provideInformation provideCounselling2 receiveSalary))
(<- prepareTechnicalPhoneEnvironment (or logIntoActivityManager logIntoPhoneSystem))
(<- professionalWorkEnvironment professionalWorkEnvironment1)
(<- promoteCS promoteCS2)
(<- promoteCS1 (or participateInEvents1 writeArticlesForMagazines1 speakPubliclyAboutJob counselorSpeakOnKidsIssuesInGeneral1 speakAtSAConferences participateInSponsorMeetings))
(<- promoteCS2 promoteCS1)
(<- promoteCounselling participateInBoardMeetings)
(<- provideCounselling (or reportAbuses recordStories kidsBePreparedForFormalAbuseReportingProcess voiceCounsellingBePerformed briefTherapyCounsellingBeUsed aResolutionFocusApproachBeUsed listenForCues encourageKidsToTalkToOthers referParentsToPHL))
(<- provideCounselling1 (or situationBeDealtWith assessSituation encourageKidsToTalkToDifferentCounsellors collectCallerSituationStatistics))
(<- provideCounselling2 provideCounselling3)
(<- provideCounselling3 provideCounselling)
(<- provideInformation provideInformation1)
(<- provideInformation1 provideInformation2)
(<- provideInformation2 (or informationResourcesBeFound receiveInformationFromOtherCounsellors))
(<- provideResourcesAsCurrentlyDone (or provideResourcesInLibrary provideResourcesInELibrary provideInformationInBinders))
(<- provideSupportToCounsellors (or provideInformationToOtherCounselloers meetingBeAttended debriefWithCounsellors provideTrainingToNewCounsellors))
(<- provideTrainingToNewCounsellors (or feedbackOnCallsBeGiven beAMentorToNewCounsellors))
(<- provideWebCounsellingWithAudio provideWrittenCounselling)
(<- provideWebCounsellingWithAudio1 provideWebCounsellingWithAudio)
(<- provideWebCounsellingWithVideo provideWrittenCounselling)
(<- provideWebCounsellingWithVideo1 provideWebCounsellingWithVideo)
(<- provideWrittenCounselling (or assessSituation1 situationBeDealtWith1))
(<- provideWrittenCounselling1 provideWrittenCounselling)
(<- receiveAdditionalTrainingAsAnExperiencedCousnellor (or learnWebTechnologies attendCounsellingWorkshops undergoMediaTraining receiveTrainingFromManagment undergoCDBasedTraining))
(<- receiveFeedback (or clinicalSupervisorsListenToCalls webPostsBeReviewedByClinicalSupervisor))
(<- receiveInformationFromOtherCounsellors informationResources)
(<- receiveSalary salary)
(<- receiveTrainingAsANewCounsellor (or receiveCallClassificationTraining passProbationWithinSixMonths undergoMediaTraining receiveTrainingFromCounsellors learnWebTechnologies attendCounsellingWorkshops receiveTrainingFromManagment undergoCDBasedTraining))
(<- receiveTrainingFromCounsellors (or listenToCallsOfExperiencedCounsellors mentoringBeReceivedFromExperiencedCounsellors))
(<- recognition1 recognition)
(<- recognition2 (or recognition1 (and (helps acquirePublicSpeakingSkills1) (helps promoteCounselling) (helps participateInEvents1) (helps speakPubliclyAboutJob))))
(<- reduceContagionEffectOfHarmfulActions1 reduceContagionEffectOfHarmfulActions)
(<- reduceNumberOfStepsWebPostingTechnology reduceNumberOfStepsWebPostingTechnology1)
(<- reducePrankCalls1 reducePrankCalls)
(<- reduceStaggeringOfSchedules reduceStaggeringOfSchedules1)
(<- rememberLocationsOfResouces1 rememberLocationsOfResouces)
(<- rememberLocationsOfResouces2 rememberLocationsOfResouces1)
(<- removeInappropriateMaterial removeIdentifyingMaterial)
(<- reportOutdatedLinks reportOutdatedLinks1)
(<- resourcesBeProvided (or provideResourcesInOneSource provideResourcesAsCurrentlyDone))
(<- resourcesInTheLibrary provideResourcesInLibrary)
(<- signContract signContractWithCounsellingUnion)
(<- simpleTechnology simpleTechnology1)
(<- situationBeDealtWith (or performConferenceCallWithThirdParty exploreOptions performCrisisIntervention diffuseConflictWithParent))
(<- situationBeDealtWith1 exploreOptions1)
(<- trainingBeReceived (or receiveTrainingAsANewCounsellor receiveAdditionalTrainingAsAnExperiencedCousnellor))
(<- trainingBeReceived1 trainingBeReceived)
(<- trainingBeReceived2 trainingBeReceived1)
(<- undergoCDBasedTraining trainingCDs)
(<- undergoClinicalReview (or receiveFeedback clinicalSupervisorsListenToCalls webPostsBeReviewedByClinicalSupervisor))
(<- undergoClinicalReview1 undergoClinicalReview2)
(<- undergoClinicalReview2 undergoClinicalReview)
(<- updateOutdatedLinks reportOutdatedLinks)
(<- voiceCounsellingBePerformed voiceCounsellingBePerformed2)
(<- voiceCounsellingBePerformed1 (or provideCounselling1 prepareTechnicalPhoneEnvironment))
(<- voiceCounsellingBePerformed2 voiceCounsellingBePerformed1)
(<- voiceCounsellingBePerformed3 voiceCounsellingBePerformed1)
(<- webCounsellingBePerformed (or webCounsellingBePerformed2 (and (hurts deepenCounsellingSession) (hurts engageInDialogWithCounselled))))
(<- webCounsellingBePerformed1 (or provideWebCounsellingWithAudio provideWebCounsellingWithAudio performEmailCounselling performFirstReadingOfCounsellingPosts moderateAChat createCounsellingPosts moderateDiscussionBoards))
(<- webCounsellingBePerformed2 webCounsellingBePerformed1)
(<- webCounsellingBePerformed3 webCounsellingBePerformed1)
(<- webCounsellingBePerformed4 webCounsellingBePerformed3)
(<- webResponsesBeGeneric1 webResponsesBeGeneric)
(<- webResponsesBeGeneric2 webResponsesBeGeneric1)
(<- webSiteContent createWebSiteContent)
(<- writeArticlesForMagazines writeArticlesForMagazines1)
(<- writeArticlesForWebsite writeArticlesForWebsite1)
(<- accessibleResourcesForCounselors6 (helps provideResourcesInOneSource))
(<- accountabilityOfServices2 (helps webCounsellingBePerformed))
(<- acquirePublicSpeakingSkills (makes undergoMediaTraining))
(<- acquireRecognizableEmploymentExperience (helps positiveEmploymentEvaluation))
(<- avoidBeingDirective (helps aResolutionFocusApproachBeUsed))
(<- avoidBeingLabelledAntiTechnology (and (hurts commentOnTechnologyUsabilityIssues) (helps improveITSkills)))
(<- avoidBurnout (and (helps decreaseWorkLoad) (helps reducePrankCalls1) (helps enthusiasticWorkAtmosphere) (helps releaseTension) (helps decreaseWorkDifficulty)))
(<- avoidLiabilityProblems (and (helps controlOfCounsellingWork) (helps increasedCautionContentOfOnlineServices) (helps diffuseConflictWithParent2)))
(<- avoidPressureToPerformDutiesQuickly (helps performDutiesQuickly))
(<- avoidRelationshipsWithSpecificCounsellor1 (helps encourageKidsToTalkToDifferentCounsellors))
(<- avoidShortStaffing (helps increaseNumberOfCounsellors))
(<- avoidTensionConfrontationAnimosityAmongstEmployees (and (helps professionalWorkEnvironment1) (helps counsellorsPoliceThemselves) (hurts counsellorsBeUnionized) (helps reducePhysicalObservationHearingByStaffNotInCounsellingTeam) (helps getRidOfUnion) (helps controlOfFloorOperations) (helps considerationOfFeedbackManagers) (helps reduceMonitoringOfActivities)))
(<- comfortableWithPerceivedPurposeOfTechnology (helps reduceMonitoringOfActivities))
(<- completeResourceLinks4 (and (helps resourcesBeProvided) (helps updateOutdatedLinks)))
(<- consistentCounsellingResponses (and (helps highQualityResources1) (helps improveCounsellingSkills2)))
(<- consistentResourceLinks2 (and (helps provideResourcesInOneSource) (hurts provideResourcesAsCurrentlyDone) (hurts provideResourcesAsCurrentlyDone)))
(<- counsellorsEngageEmotionallyInSession (and (helps decreaseClumsinessTechnology2) (hurts webCounsellingBePerformed)))
(<- currentResourceLinks4 (helps updateOutdatedLinks))
(<- decreaseDifficultiesWithTechnology (and (helps comfortableWithPerceivedPurposeOfTechnology) (helps improveWebPostingTechnology) (helps decreaseClumsinessTechnology) (helps considerationOfFeedbackITProviders) (helps simpleTechnology) (helps improveQualityAssuranceTechnology1) (helps commentOnTechnologyUsabilityIssues) (helps improveITSkills) (helps easilyAccessableTechnologyInstructions) (helps itSystemsBeIntegrated)))
(<- decreaseFactoryWorkerAtmosphere (and (helps avoidPressureToPerformDutiesQuickly) (helps considerationOfFeedbackITProviders) (helps beConsultedAboutNewPolicies) (helps avoidTensionConfrontationAnimosityAmongstEmployees) (helps considerationOfFeedbackManagers)))
(<- decreaseKidsIsolation (and (helps avoidDialoguesWebServices1) (hurts webCounsellingBePerformed) (helps encourageKidsToTalkToOthers)))
(<- decreaseWorkDifficulty (and (helps completeResourceLinks) (helps rememberLocationsOfResouces) (helps highDegreeOfSimilarityBetweenServicesProvided) (helps decreaseDifficultiesWithTechnology) (helps clearerCallClassificationCatagories) (helps currentResourceLinks) (helps accessibleResourcesForCounselors)))
(<- decreaseWorkLoad (helps avoidShortStaffing))
(<- effectiveDebriefing (helps debriefWithCounsellors))
(<- effectiveUseOfTechnologyCounsellors (helps improveITSkills1))
(<- empoweringKidsToHelpThemselves (helps provideInformation2))
(<- enthusiasticWorkAtmosphere (and (helps prideInJob) (hurts performDutiesQuickly) (helps highQualityCounselling1) (hurts professionalWorkEnvironment1) (helps recognition) (helps avoidTensionConfrontationAnimosityAmongstEmployees)))
(<- facilitateFasterChangesInCounsellorDuties1 (and (hurts counsellorsBeUnionized) (helps getRidOfUnion)))
(<- findEffectiveCues (and (helps listenForCues) (hurts webCounsellingBePerformed)))
(<- happinessCounsellors (and (helps implementEmailForCounsellors2) (helps avoidLiabilityProblems) (helps decreaseWorkDifficulty) (helps avoidTensionConfrontationAnimosityAmongstEmployees) (helps decreaseFactoryWorkerAtmosphere) (helps controlOfCounsellingWork) (helps reduceMonitoringOfActivities) (helps enthusiasticWorkAtmosphere) (helps increasedPeerSupport2) (helps releaseTension) (helps decreaseWorkLoad) (helps positiveEmploymentEvaluation) (helps varietyInWork) (helps decreaseDifficultiesWithTechnology) (helps avoidBurnout) (helps prideInJob) (helps accommodateSchedules) (helps reducePrankCalls1) (helps recognition) (helps safety)))
(<- helpAsManyKidsAsPossible (helps performDutiesQuickly))
(<- helpKids (helps decreaseKidsIsolation))
(<- highDegreeOfSimilarityBetweenServicesProvided2 (and (helps provideWebCounsellingWithVideo) (helps provideWebCounsellingWithAudio)))
(<- highQualityCounselling1 (and (helps releaseTension) (helps happinessCounsellors)))
(<- highQualityResources (and (helps consistentResourceLinks) (helps currentResourceLinks1)))
(<- highQualityResources3 (and (helps consistentResourceLinks2) (helps completeResourceLinks4) (helps accessibleResourcesForCounselors6)))
(<- improveCommunicationBetweenCounsellors (and (helps implementEmailForCounsellors) (helps implementBulletinBoard) (helps provideSupportToCounsellors)))
(<- improveCounsellingSkills (and (helps increaseFeedback) (helps trainingBeReceived)))
(<- improveITSkills1 (helps increaseITTraining))
(<- improveQualityAssuranceTechnology (helps improveCallRecordingEquipment))
(<- improveWebPostingTechnology1 (and (helps easierToFindPostsWebPostingTechnology) (helps cuttingAndPastingBeAddedToWebPostingSoftware) (helps reduceNumberOfStepsWebPostingTechnology)))
(<- increaseConnectionBetweenCounsellorsAndCounselled (and (helps engageInDialogWithCounselled) (helps deepenCounsellingSession)))
(<- increaseFeedback (and (helps increaseITMethodsToAcquireFeedback) (helps acquireFeedback) (helps increaseEmphasisOnOnlineFeedbackForm)))
(<- increasedCautionContentOfOnlineServices2 (and (hurts performEmailCounselling) (hurts reduceNumberOfStepsWebPostingTechnology) (helps moderateDiscussionBoards) (helps editOnlinePostsOfKids) (helps webResponsesBeGeneric) (helps blockKidsWhoDisplayInappropriateBehavoir) (hurts moderateAChat) (helps performFirstReadingOfCounsellingPosts) (helps removeInappropriateMaterial)))
(<- increasedPeerSupport1 (and (helps reduceStaggeringOfSchedules) (helps improveCommunicationBetweenCounsellors) (helps effectiveDebriefing)))
(<- moveOnToBetterJob (and (hurts happinessCounsellors) (helps acquireRecognizableEmploymentExperience)))
(<- patientCounselor (makes highQualityCounselling))
(<- performDutiesQuickly (and (helps decreaseDifficultiesWithTechnology) (helps counsellorsBeUnionized) (helps rememberLocationsOfResouces) (helps accessibleResourcesForCounselors) (helps decreaseClumsinessTechnology) (helps clearerCallClassificationCatagories) (hurts increasedCautionContentOfOnlineServices) (helps happinessCounsellors)))
(<- positiveEmploymentEvaluation (and (helps undergoClinicalReview1) (helps avoidBeingLabelledAntiTechnology) (helps performCounsellingAsInstructedBySupervisor) (helps improveITSkills) (helps improvedWritingSkills) (helps acquirePublicSpeakingSkills3) (helps improveCounsellingSkills1)))
(<- prideInJob (and (helps helpAsManyKidsAsPossible) (helps accountabilityOfServices) (helps highQualityCounselling1) (helps increaseCSAwareness)))
(<- professionalWorkEnvironment1 (and (hurts toolsToBurnNegativeEnergyBePresent) (hurts releaseTension)))
(<- reduceContagionEffectOfHarmfulActions (and (helps editOnlinePostsOfKids) (helps moderateDiscussionBoards) (helps moderateAChat)))
(<- reduceMonitoringOfActivities (and (helps considerationOfFeedbackManagers) (helps counsellorsPoliceThemselves)))
(<- releaseTension (and (helps increasedPeerSupport2) (helps toolsToBurnNegativeEnergyBePresent)))
(<- retainJob (helps positiveEmploymentEvaluation))
(<- safety (helps anonymity))
(<- supportIndividualityInCounsellingTechniques (and (hurts performCounsellingAsInstructedBySupervisor1) (hurts webCounsellingBePerformed) (helps counsellorsEngageEmotionallyInSession)))
(<- toolsToBurnNegativeEnergyBePresent (helps avoidTensionConfrontationAnimosityAmongstEmployees))
(<- varietyInWork (helps webCounsellingBePerformed4))
(defparameter *hard* '(cuttingAndPastingBeAddedToWebPostingSoftware getRidOfUnion informationResourcesBeFound beConsultedAboutNewPolicies toolsToBurnNegativeEnergyBePresent counsellorsBeUnionized allowUserToLogIn1 itSystemsBeIntegrated1 trainingBeReceived2 clinicalSupervisorsListenToCalls aResolutionFocusApproachBeUsed feedbackOnCallsBeGiven iconsForCounsellingInformationBeOnDesktop kidsBePreparedForFormalAbuseReportingProcess counsellingPoliciesBeFollowed passProbationWithinSixMonths situationBeDealtWith itSystemsBeIntegrated beAMentorToNewCounsellors counsellingPoliciesBeFollowed1 situationBeDealtWith1 briefTherapyCounsellingBeUsed webPostsBeReviewedByClinicalSupervisor allowUserToLogIn trainingBeReceived mentoringBeReceivedFromExperiencedCounsellors meetingBeAttended resourcesBeProvided trainingBeReceived1))
(defparameter *soft* '(considerationOfFeedbackManagers increaseNumberOfCounsellors1 enthusiasticWorkAtmosphere reduceMonitoringOfActivities completeResourceLinks4 decreaseClumsinessTechnology2 supportIndividualityInCounsellingTechniques moveOnToBetterJob avoidPressureToPerformDutiesQuickly patientCounselor increaseFeedback helpAsManyKidsAsPossible2 simpleTechnology1 recognition2 currentResourceLinks2 increasedPeerSupport1 accommodateSchedules accessibleResourcesForCounselors empoweringKidsToHelpThemselves2 improveCounsellingSkills1 acquirePublicSpeakingSkills consistentResourceLinks easierToFindPostsWebPostingTechnology1 accessibleResourcesForCounselors2 improveITSkills3 avoidBeingLabelledAntiTechnology performDutiesQuickly improveQualityAssuranceTechnology2 highQualityCounselling rememberLocationsOfResouces2 counsellorsEngageEmotionallyInSession controlOfCounsellingWork1 increasedCautionContentOfOnlineServices1 controlOfFloorOperations improveWebPostingTechnology1 decreaseDifficultiesWithTechnology completeResourceLinks1 highQualityResources2 retainJob improveWebPostingTechnology reduceStaggeringOfSchedules increaseITTrainingForCounsellors acquirePublicSpeakingSkills2 happinessCounsellors improveCounsellingSkills avoidRelationshipsWithSpecificCounsellor1 reducePrankCalls1 easilyAccessableTechnologyInstructions1 recognition1 improveQualityAssuranceTechnology accessibleResourcesForCounselors6 effectiveDebriefing csStories increasedCautionContentOfOnlineServices decreaseWorkDifficulty voiceCounselling accessibleResourcesForCounselors1 improvedWritingSkillsCounsellors decreaseClumsinessTechnology1 facilitateFasterChangesInCounsellorDuties easilyAccessableTechnologyInstructions avoidLiabilityProblems1 consistentResourceLinks1 anonymityCounsellors avoidDialoguesWebServices1 rememberLocationsOfResouces1 improveWebPostingTechnology2 considerationOfFeedbackITProviders1 completeResourceLinks2 performCounsellingAsInstructedBySupervisor highDegreeOfSimilarityBetweenServicesProvided helpAsManyKidsAsPossible3 engageInDialogWithCounselled helpAsManyKidsAsPossible acquireRecognizableEmploymentExperience considerationOfFeedbackITProviders improveCommunicationBetweenCounsellors consistentResourceLinks2 improveITSkills1 accessibleResourcesForCounselors5 decreaseFactoryWorkerAtmosphere increaseNumberOfCounsellors comfortableWithPerceivedPurposeOfTechnology happinessCounsellors1 avoidTensionConfrontationAnimosityAmongstEmployees currentResourceLinks3 decreaseKidsIsolation increasedCautionContentOfOnlineServices2 performCounsellingAsInstructedBySupervisor1 helpKids1 improveCallRecordingEquipment reduceNumberOfStepsWebPostingTechnology1 highQualityCounselling1 avoidBeingDirective counsellorsPoliceThemselves increasedPeerSupport clearerCallClassificationCatagories highQualityResources3 increaseITMethodsToAcquireFeedback1 increaseEmphasisOnOnlineFeedbackForm1 controlOfCounsellingWork reduceContagionEffectOfHarmfulActions1 safety acquirePublicSpeakingSkills1 improveCallRecordingEquipment1 highDegreeOfSimilarityBetweenServicesProvided2 considerationOfFeedbackManagers1 improveITSkills professionalWorkEnvironment consistentCounsellingResponses performCounsellingAsInstructedBySupervisor2 prideInJob reducePhysicalObservationHearingByStaffNotInCounsellingTeam reduceContagionEffectOfHarmfulActions effectiveUseOfTechnologyCounsellors1 positiveEmploymentEvaluation simpleTechnology highQualityCounselling2 reduceStaggeringOfSchedules1 recognition completeResourceLinks3 salary reducePrankCalls increasedPeerSupport2 correctInterpretationOfCounsel accountabilityOfServices increaseITTraining increasedPeerSupport3 decreaseWorkLoad helpKids highDegreeOfSimilarityBetweenServicesProvided1 findEffectiveCues improveCounsellingSkills3 professionalWorkEnvironment1 accessibleResourcesForCounselors4 releaseTension webResponsesBeGeneric1 currentResourceLinks4 increaseEmphasisOnOnlineFeedbackForm accountabilityOfServices1 empoweringKidsToHelpThemselves currentResourceLinks decreaseClumsinessTechnology effectiveUseOfTechnologyCounsellors2 increaseConnectionBetweenCounsellorsAndCounselled accommodateSchedules1 improvedWritingSkills currentResourceLinks1 avoidDialoguesWebServices improveITSkills2 reduceNumberOfStepsWebPostingTechnology empoweringKidsToHelpThemselves1 accessibleResourcesForCounselors3 varietyInWork increaseITMethodsToAcquireFeedback avoidLiabilityProblems clearerCallClassificationCatagories1 improveQualityAssuranceTechnology1 completeResourceLinks anonymity avoidBurnout webResponsesBeGeneric increaseCSAwareness1 highQualityCounselling3 easierToFindPostsWebPostingTechnology highQualityResources increaseCSAwareness effectiveUseOfTechnologyCounsellors accountabilityOfServices2 facilitateFasterChangesInCounsellorDuties1 highQualityResources1 deepenCounsellingSession helpAsManyKidsAsPossible1 correctInterpretationOfCounsel1 avoidShortStaffing acquirePublicSpeakingSkills3 improveCounsellingSkills2 avoidRelationshipsWithSpecificCounsellor rememberLocationsOfResouces patientCounselor1 webResponsesBeGeneric2))
