% CSFDandMarketing  (node/2 edge/3 dep/2 dec/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
node(sponsorshipBeBeneficial,softgoal).
node(marketFundraisingEvents2,softgoal).
node(provideOnlineDonorTechnology,task).
leaf(provideOnlineDonorTechnology).
node(counselorsAttendFundraisingEvents,goal).
topgoal(counselorsAttendFundraisingEvents).
node(manageNprojects,task).
node(acquireNCSStories,softgoal).
node(upToDateCorporatePartnerInformation,softgoal).
node(regionalStaffFeelIncluded,softgoal).
node(bringRegionalFundraisingStaffTogetherOnceAYear,task).
leaf(bringRegionalFundraisingStaffTogetherOnceAYear).
node(proactiveMediaRelationship,softgoal).
node(csNServices,softgoal).
leaf(csNServices).
node(highResponseIndividualDonors,softgoal).
node(recordDonorInformation,task).
node(accountabilityOfServices1,softgoal).
leaf(accountabilityOfServices1).
node(providePromotionalMaterialToStudentAmbassadors,task).
leaf(providePromotionalMaterialToStudentAmbassadors).
node(contributeOnline,task).
node(happinessStaff,softgoal).
node(csStories,softgoal).
leaf(csStories).
node(contributeToACause,goal).
topgoal(contributeToACause).
node(exclusiveRelationshipsOfficialPartners,softgoal).
node(conflictsBeManaged,task).
leaf(conflictsBeManaged).
node(receiptBeProvided,goal).
topgoal(receiptBeProvided).
node(reachMoreKidsSponsors,softgoal).
node(manageProjects,task).
node(attendFundraisingEvent,task).
node(useVolunteerServices,task).
leaf(useVolunteerServices).
node(pledgesBeCollected,goal).
topgoal(pledgesBeCollected).
node(sponsorshipProposal,task).
node(followHighestEthicalGuidelines,softgoal).
node(reduceInternalCommunicationConfusion,softgoal).
node(projectDeadlinesBeMet1,goal).
topgoal(projectDeadlinesBeMet1).
node(provideCompiledCallData,task).
leaf(provideCompiledCallData).
node(payFundDevelopmentAndMarketingStaff,task).
leaf(payFundDevelopmentAndMarketingStaff).
node(useSponsorMarketingChannels,task).
node(getCorporatePartnerInformationFromDL,task).
node(manageReceivables,task).
leaf(manageReceivables).
node(becomeAMajorPatron,task).
node(createThankYouAds,task).
leaf(createThankYouAds).
node(reachAgreement,task).
leaf(reachAgreement).
node(getWebEventTechnology1,task).
leaf(getWebEventTechnology1).
node(provideMoneyForServices,task).
leaf(provideMoneyForServices).
node(commitmentToCSCauseFromSponsorsEmployees,softgoal).
node(presentProposalConvincinglyToSponsors,softgoal).
node(successfulEvents,softgoal).
node(collectDonationsOnline,task).
node(createPostersFlyersAndInformationalMaterial,task).
leaf(createPostersFlyersAndInformationalMaterial).
node(goodMediaExposure,softgoal).
node(quickResponseToQuestionsAndConcerns,softgoal).
node(positiveInternalOpinion,softgoal).
node(provideDocumentLibrarySystem,task).
leaf(provideDocumentLibrarySystem).
node(credibilityCSBrand,softgoal).
node(elaborateFundraisingTargets,task).
node(engageEmployeesInEvents1,softgoal).
node(sponsorsForEventsBeFound,goal).
topgoal(sponsorsForEventsBeFound).
node(sponsorPartnerNcontacts2,softgoal).
leaf(sponsorPartnerNcontacts2).
node(marketingFromGovernmentBeAcquired,goal).
topgoal(marketingFromGovernmentBeAcquired).
node(becomeAPatron,task).
node(becomeAOfficialPartner,task).
node(presentationSkills1,softgoal).
leaf(presentationSkills1).
node(providePartnerContactsToCS,task).
node(createBrandedProducts,task).
leaf(createBrandedProducts).
node(runFundraiserInSchools,task).
leaf(runFundraiserInSchools).
node(recognition,softgoal).
node(sponsorsMarketingChannelsBeUsed,goal).
topgoal(sponsorsMarketingChannelsBeUsed).
node(credibilityCSBrand2,softgoal).
node(sponsorPartnerNcontacts,softgoal).
node(reallocateResources,task).
leaf(reallocateResources).
node(createLifeLongVolunteerSpirit1,softgoal).
node(acquirePublicSpeakingSkills,softgoal).
node(companyRelationshipBeRetainedAfterMergers,goal).
topgoal(companyRelationshipBeRetainedAfterMergers).
node(increaseAwareness,softgoal).
node(notForProfitPartnersBeInvolvedInEvents,goal).
leaf(notForProfitPartnersBeInvolvedInEvents).
topgoal(notForProfitPartnersBeInvolvedInEvents).
node(engagementStudentAmbassadorsInPromotingAwareness,softgoal).
node(responsibleUsageSponsorFunds,softgoal).
node(happinessStaff3,softgoal).
node(saGiveCSPresentations,task).
node(putOnFundraisingWebEvents,task).
node(highResponseIndividualDonors1,softgoal).
node(elaborateFundraisingTargets1,task).
leaf(elaborateFundraisingTargets1).
node(staffBeSupported,goal).
topgoal(staffBeSupported).
node(giveCSPresentations,task).
leaf(giveCSPresentations).
node(speakAtFundraisers,task).
leaf(speakAtFundraisers).
node(avoidOverMarketingServices,softgoal).
node(getCorporatePartnerInformationFromDocumentLibrary1,task).
node(engagementSponsorsInTheCauseOfCS,softgoal).
node(positiveReputation,softgoal).
node(agreement,resource).
node(singleCharitableRegistrationNumber,resource).
node(nationalEventCalendar,softgoal).
node(informSponsorsOfProgress,task).
leaf(informSponsorsOfProgress).
node(getDonorDatabase,task).
leaf(getDonorDatabase).
node(singleCharitableRegistrationNumberBeUsed,goal).
topgoal(singleCharitableRegistrationNumberBeUsed).
node(freeAdvertisement,resource).
leaf(freeAdvertisement).
node(useSponsorLogo,task).
node(implementStayInTouchProgram,task).
leaf(implementStayInTouchProgram).
node(involvementNotForProfitPartnersInEvents,softgoal).
node(engagementOfSponsorEmployeesInFundDevelopment,softgoal).
node(credibilityCSBrand1,softgoal).
leaf(credibilityCSBrand1).
node(reallocateResources1,task).
leaf(reallocateResources1).
node(exclusiveRelationshipsOfficialPartners1,softgoal).
node(contributionBeMade,goal).
topgoal(contributionBeMade).
node(quickResponseToSponsors1,softgoal).
node(appearAsGoodCorporateCitizens,softgoal).
node(engageEmployeesInEvents,softgoal).
node(goodProjectManagement,softgoal).
node(putOnOrientationProcessForFundDevelopmentAndMarketingStaff,task).
leaf(putOnOrientationProcessForFundDevelopmentAndMarketingStaff).
node(cobranding,softgoal).
node(organizeDiscussionsWithSponsors,task).
leaf(organizeDiscussionsWithSponsors).
node(providePAPToStaffNUsingTheDocumentLibrary,task).
node(matchFundraisingTargets,softgoal).
node(fundsBeRaised,goal).
topgoal(fundsBeRaised).
node(provideCompiledCallDataToMedia,task).
node(nationalMarketingStrategy,resource).
leaf(nationalMarketingStrategy).
node(marketCSBrand,softgoal).
node(longTermFunding,softgoal).
node(freeServices,resource).
node(improveImageToKids,softgoal).
node(acquireGovernmentFunding,softgoal).
node(marketFundraisingEvents1,softgoal).
node(engageEmployeesInFundraisingEvents,softgoal).
node(getPAPInformation1,task).
node(meetCorporateSponsorsNeeds,softgoal).
node(provideFundraisingServices,task).
node(trustOfSponsorsTowardsCS2,softgoal).
node(getDonorAccountingDatabase,task).
node(collectPledgeOnline,task).
node(makeContributionToCharity,goal).
topgoal(makeContributionToCharity).
node(contributeToAGoodCause,softgoal).
node(increaseVolunteers1,softgoal).
leaf(increaseVolunteers1).
node(collectDonorInformation,task).
leaf(collectDonorInformation).
node(getSponsorshipProposal,task).
node(writeArticlesForWebsite1,task).
leaf(writeArticlesForWebsite1).
node(agreementStaffOverCorporatePartnerExpectations,softgoal).
node(projectDeadlinesBeMet,goal).
topgoal(projectDeadlinesBeMet).
node(provideFreeServices,task).
leaf(provideFreeServices).
node(manageAccounts1,task).
node(matchFundraisingTargets2,softgoal).
node(engagementSponsorEmployeesInPromotingAwareness1,softgoal).
leaf(engagementSponsorEmployeesInPromotingAwareness1).
node(workWithTheRegionsToImplementEvents,task).
leaf(workWithTheRegionsToImplementEvents).
node(projectManagementSkills,softgoal).
leaf(projectManagementSkills).
node(createGeneralLedgers1,task).
node(positiveInternalOpinion1,softgoal).
leaf(positiveInternalOpinion1).
node(retainSponsors1,softgoal).
node(upToDateInformationOnPrograms1,softgoal).
node(getSponsorsForEvents,task).
node(increasedInvolvementCounselorsInEvents,softgoal).
node(uniteVolunteersAndSponsors,softgoal).
node(goodProjectManagement2,softgoal).
node(putOnFundraisingEvents,task).
node(donorAccountingDatabase,resource).
leaf(donorAccountingDatabase).
node(presentationSkills,softgoal).
node(getWebTechnology,task).
node(marketCSService,task).
node(qualityServices1,softgoal).
node(involveNotForProfitPartnersInEvents,goal).
topgoal(involveNotForProfitPartnersInEvents).
node(reachAgreement1,task).
node(increasedInvolvementCounselorsInEvents1,softgoal).
node(corporateSponsorsFeelIncluded,softgoal).
node(recognizeNSponsorContribution1,softgoal).
node(happinessStaff1,softgoal).
node(quickResponseToSponsors,softgoal).
leaf(quickResponseToSponsors).
node(provideLogoToCS,task).
leaf(provideLogoToCS).
node(increaseConnectionCounselorsAndCommunity,softgoal).
node(timelyServices,softgoal).
leaf(timelyServices).
node(sharePAPInDocumentLibrary,task).
leaf(sharePAPInDocumentLibrary).
node(longTermFunding1,softgoal).
node(getCorporatePartnerInformationFromDL1,task).
leaf(getCorporatePartnerInformationFromDL1).
node(retainSponsors2,softgoal).
leaf(retainSponsors2).
node(experiencedMarketingPartners,softgoal).
node(sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts,task).
leaf(sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts).
node(regionalStaffFeelIncluded1,softgoal).
node(biWeeklyConferenceCalls,task).
leaf(biWeeklyConferenceCalls).
node(recognizeNSponsorContribution,softgoal).
node(marketingBeMadeUsingDedicatedCounselor,goal).
topgoal(marketingBeMadeUsingDedicatedCounselor).
node(givePhilanthropicDonation,task).
leaf(givePhilanthropicDonation).
node(writeArticlesForMagazines,task).
node(exclusiveBrandAndLogoUse,resource).
leaf(exclusiveBrandAndLogoUse).
node(qualityServices,softgoal).
leaf(qualityServices).
node(putOnFundraisingEventsOnTheWeb,task).
node(saRunFundraiserInSchools,task).
node(responsibleUsageSponsorFunds2,softgoal).
node(collectPledgeDuringEvent,task).
node(getCorporateSponsorFunds,task).
node(managePAP,task).
node(involvementNotForProfitPartnersInEvents1,softgoal).
leaf(involvementNotForProfitPartnersInEvents1).
node(eventsBeMarketed,goal).
topgoal(eventsBeMarketed).
node(createGeneralLedgers,task).
leaf(createGeneralLedgers).
node(increaseAccessSpeedRegionalOfficesToDocumentLibrary,softgoal).
leaf(increaseAccessSpeedRegionalOfficesToDocumentLibrary).
node(developExternalComunications,task).
node(increasedAvailabilityToSponsors,softgoal).
leaf(increasedAvailabilityToSponsors).
node(accountabilityOfServices,softgoal).
node(highResponseIndividualDonors2,softgoal).
node(beInformedOfFundraisingEvents,goal).
topgoal(beInformedOfFundraisingEvents).
node(saSpeakAtFundraisers,task).
node(happinessStaff2,softgoal).
node(eventCoordination,task).
node(getCorporatePartnerInformationFromDocumentLibrary,task).
node(increaseFreeServices,softgoal).
node(trustOfDonor,softgoal).
node(positiveImageToEmployees,softgoal).
node(recognizeNSponsorContribution2,softgoal).
node(engagementSponsorEmployeesInPromotingAwareness2,softgoal).
node(collectPledgeOnline2,task).
node(promotionResources,resource).
node(includeCorporatePartnersInTheDevelopmentOfPressReleases,softgoal).
leaf(includeCorporatePartnersInTheDevelopmentOfPressReleases).
node(manageReceivables1,task).
node(provideFreeServices1,task).
leaf(provideFreeServices1).
node(placeSponsorLogosInEvents,task).
leaf(placeSponsorLogosInEvents).
node(followHighestEthicalGuidelines1,softgoal).
leaf(followHighestEthicalGuidelines1).
node(getPAPInformation,task).
node(answersBeProvidedToMediaQueries,goal).
leaf(answersBeProvidedToMediaQueries).
topgoal(answersBeProvidedToMediaQueries).
node(contributeToAGoodCause1,softgoal).
node(trustOfSponsorsTowardsCS1,softgoal).
node(pledgeNonline,task).
leaf(pledgeNonline).
node(increasePhilanthropicDonations,softgoal).
node(increasedInteractionCounselorsWithMedia,softgoal).
node(sharePAPInDocumentLibrary1,task).
leaf(sharePAPInDocumentLibrary1).
node(storeDonorTransactionsIntoDatabase,task).
leaf(storeDonorTransactionsIntoDatabase).
node(sponsorPartnerNcontacts1,softgoal).
leaf(sponsorPartnerNcontacts1).
node(provincialGovernment,softgoal).
node(responsibleUsageSponsorFunds1,softgoal).
leaf(responsibleUsageSponsorFunds1).
node(minimizeExpenses,softgoal).
node(trackBudgets,task).
leaf(trackBudgets).
node(accountabilityOfServices2,softgoal).
node(marketPHLBrand,softgoal).
node(improveImageToKids1,softgoal).
node(pledgeOnline,task).
node(counselorsWhoWantAPublicVoiceBeTrained,goal).
topgoal(counselorsWhoWantAPublicVoiceBeTrained).
node(increaseAwareness1,softgoal).
node(emailCorporatePartnersInterestingAndRelevantNewsPieces,task).
leaf(emailCorporatePartnersInterestingAndRelevantNewsPieces).
node(sendRecognitionLetters,task).
leaf(sendRecognitionLetters).
node(philanthropicDonations,task).
node(manageNPartnerRelationship,task).
node(writeArticlesForWebsite,task).
node(upToDateInformationOnPrograms,softgoal).
node(increaseNAwareness,softgoal).
node(increaseAwareness2,softgoal).
leaf(increaseAwareness2).
node(informationBeSharedWithSponsors,goal).
topgoal(informationBeSharedWithSponsors).
node(regionalStaffFeelIncluded2,softgoal).
node(increaseInvolvementSponsorsInPuttingOnEvents,softgoal).
node(exclusiveRelationshipsOfficialPartners2,softgoal).
leaf(exclusiveRelationshipsOfficialPartners2).
node(singleCharitableRegistrationNumber1,resource).
leaf(singleCharitableRegistrationNumber1).
node(maintain20CostsAgainstRevenuesRatio,goal).
topgoal(maintain20CostsAgainstRevenuesRatio).
node(acquireFreeServices,softgoal).
node(marketFundraisingEvents,softgoal).
node(timelyProvisionOfFreeServices1,softgoal).
leaf(timelyProvisionOfFreeServices1).
node(pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents,task).
leaf(pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents).
node(providePhilanthropicDonation,task).
leaf(providePhilanthropicDonation).
node(successfulMarketingCampaign,softgoal).
node(engagementOfSponsorEmployeesInFundDevelopment1,softgoal).
node(pledgeNDuringEvent,task).
leaf(pledgeNDuringEvent).
node(corporateSponsorFeelIncluded,softgoal).
node(grantExclusiveUseOfBrandAndLogo,task).
node(corporatePartnerFundraisingExpectationsBeKnown,goal).
topgoal(corporatePartnerFundraisingExpectationsBeKnown).
node(putTogetherProposalsForCorporateSponsors,task).
leaf(putTogetherProposalsForCorporateSponsors).
node(manageNPartnerRelationship1,task).
node(communicateWithHeadOffice,task).
node(subscribeToDocumentLibraryFolders2,task).
node(followHighestEthicalGuidelines2,softgoal).
node(engageEmployeesInEvents2,softgoal).
leaf(engageEmployeesInEvents2).
node(counselorSpeakOnKidsIssuesInGeneral1,task).
leaf(counselorSpeakOnKidsIssuesInGeneral1).
node(provideRealTimeTaxReceipts,task).
leaf(provideRealTimeTaxReceipts).
node(provideReceipts,task).
node(useNationalEventCalendar,task).
node(demonstrableServices1,softgoal).
node(collectPledgeOnline3,task).
node(increasedAvailabilityCounselorsToPublicSponsors,softgoal).
node(availabilityForAdministrationAndAccountingPurposesAcrossCS,softgoal).
node(publishedCSStories,softgoal).
node(attractSponsors1,softgoal).
node(attractSponsors,softgoal).
node(funds,resource).
node(increaseVolunteers,softgoal).
node(upToDateCorporatePartnerInformation2,softgoal).
leaf(upToDateCorporatePartnerInformation2).
node(subscribeToDocumentLibraryFolders,task).
node(getWebEventTechnology,task).
node(engagementSponsorEmployeesInPromotingAwareness,softgoal).
node(putOnOrientationForVolunteers,task).
leaf(putOnOrientationForVolunteers).
node(writeDownCorporateSponsorsObjectives,task).
leaf(writeDownCorporateSponsorsObjectives).
node(timelyProvisionOfFreeServices,softgoal).
node(getDonorTechnology,task).
node(engageEmployeesInPromotingAwareness,softgoal).
node(corporatePartnerMarketingExpectationsBeKnown,goal).
topgoal(corporatePartnerMarketingExpectationsBeKnown).
node(sponsorLogo,resource).
node(developNationalEventCalendar,task).
leaf(developNationalEventCalendar).
node(demonstrableServices,softgoal).
node(periodicalCommunicationWithRegionalStaffBeMaintained,goal).
topgoal(periodicalCommunicationWithRegionalStaffBeMaintained).
node(provideFunds1,task).
node(attractEventParticipants,softgoal).
node(hearCSStories,softgoal).
node(manageAccounts,task).
leaf(manageAccounts).
node(counselorSpeakOnKidsIssuesInGeneral,task).
node(createLifeLongVolunteerSpirit,softgoal).
leaf(createLifeLongVolunteerSpirit).
node(communicateThroughInternetAndPhone,task).
leaf(communicateThroughInternetAndPhone).
node(sponsorRelationshipsBeManaged,goal).
topgoal(sponsorRelationshipsBeManaged).
node(provideFunds,task).
leaf(provideFunds).
node(frontEndForIncomeRecordingBeSupported,goal).
topgoal(frontEndForIncomeRecordingBeSupported).
node(minimizeCostOfEvents,softgoal).
node(pledgeNDuringEvent1,task).
node(corporatePartnerExpectationsBeSharedWithStaff,goal).
topgoal(corporatePartnerExpectationsBeSharedWithStaff).
node(subscribeToDocumentLibraryFolders1,task).
node(trustOfSponsorsTowardsCS,softgoal).
node(servicesBeProvidedForKidsBullyingLine,goal).
leaf(servicesBeProvidedForKidsBullyingLine).
topgoal(servicesBeProvidedForKidsBullyingLine).
node(marketOnlyForSeriousIssues,task).
leaf(marketOnlyForSeriousIssues).
node(retainSponsors,softgoal).
node(experiencedMarketingPartners2,softgoal).
leaf(experiencedMarketingPartners2).
node(trainCounselorsOnPublicSpeaking,task).
leaf(trainCounselorsOnPublicSpeaking).
node(demonstrableServices2,softgoal).
node(writeArticlesForMagazines1,task).
leaf(writeArticlesForMagazines1).
node(storeDonorInformationIntoDatabase,task).
leaf(storeDonorInformationIntoDatabase).
node(engagementStudentAmbassadorsInPromotingAwareness1,softgoal).
leaf(engagementStudentAmbassadorsInPromotingAwareness1).
node(qualityServices2,softgoal).
node(getFreeAdvertisement,task).
node(positiveReputationOfCS,softgoal).
leaf(positiveReputationOfCS).
node(marketThroughOwnChannels,task).
leaf(marketThroughOwnChannels).
node(upToDateInformationOnCorporateSponsors,softgoal).
node(positiveAssociationNByConsumers,softgoal).
node(attractSponsors2,softgoal).
node(getPhilanthropicDonations,task).
leaf(getPhilanthropicDonations).
node(useFreeServices,task).
node(positiveReputationOfCS2,softgoal).
node(inspiredStaff,softgoal).
node(donorInformationBeRecorded,goal).
topgoal(donorInformationBeRecorded).
node(increasedCorporateSponsorFunds,softgoal).
node(avoidOverMarketingServices1,softgoal).
node(participateInEvents,task).
leaf(participateInEvents).
edge(meetCorporateSponsorsNeeds,corporateSponsorsFeelIncluded,1).
dec(writeArticlesForWebsite,marketingBeMadeUsingDedicatedCounselor,or).
edge(increasedInteractionCounselorsWithMedia,proactiveMediaRelationship,0.5).
dec(implementStayInTouchProgram,staffBeSupported,or).
edge(goodProjectManagement,successfulMarketingCampaign,0.5).
dec(informSponsorsOfProgress,informationBeSharedWithSponsors,or).
dep(writeArticlesForMagazines1,writeArticlesForMagazines).
edge(createThankYouAds,recognizeNSponsorContribution2,0.5).
edge(saSpeakAtFundraisers,improveImageToKids,0.5).
dep(recognizeNSponsorContribution2,recognizeNSponsorContribution).
dec(getCorporatePartnerInformationFromDocumentLibrary1,corporatePartnerMarketingExpectationsBeKnown,or).
edge(counselorsWhoWantAPublicVoiceBeTrained,increasedInteractionCounselorsWithMedia,0.5).
dep(demonstrableServices1,demonstrableServices2).
edge(accountabilityOfServices,trustOfSponsorsTowardsCS,0.5).
edge(attractEventParticipants,engagementOfSponsorEmployeesInFundDevelopment,0.5).
dec(putTogetherProposalsForCorporateSponsors,managePAP,or).
edge(sponsorPartnerNcontacts2,getFreeAdvertisement,0.5).
edge(sponsorPartnerNcontacts1,increaseFreeServices,0.5).
edge(trustOfSponsorsTowardsCS2,retainSponsors1,0.5).
dec(createBrandedProducts,developExternalComunications,or).
dep(happinessStaff,happinessStaff3).
dec(useNationalEventCalendar,managePAP,or).
edge(highResponseIndividualDonors2,increasePhilanthropicDonations,0.5).
edge(useSponsorLogo,attractSponsors2,0.5).
edge(goodMediaExposure,attractSponsors2,0.5).
dep(provideDocumentLibrarySystem,subscribeToDocumentLibraryFolders2).
dep(singleCharitableRegistrationNumber,singleCharitableRegistrationNumberBeUsed).
edge(getFreeAdvertisement,marketPHLBrand,0.5).
edge(periodicalCommunicationWithRegionalStaffBeMaintained,regionalStaffFeelIncluded,0.5).
edge(agreementStaffOverCorporatePartnerExpectations,reduceInternalCommunicationConfusion,0.5).
dec(manageProjects,projectDeadlinesBeMet1,or).
dep(csNServices,demonstrableServices1).
dec(getDonorAccountingDatabase,putOnFundraisingEventsOnTheWeb,or).
dec(timelyProvisionOfFreeServices,manageProjects,or).
dep(developNationalEventCalendar,nationalEventCalendar).
dep(upToDateCorporatePartnerInformation2,upToDateInformationOnCorporateSponsors).
dep(highResponseIndividualDonors2,highResponseIndividualDonors1).
dep(presentProposalConvincinglyToSponsors,sponsorshipProposal).
dec(collectPledgeDuringEvent,putOnFundraisingEvents,or).
edge(createLifeLongVolunteerSpirit1,increaseVolunteers,0.5).
edge(increaseNAwareness,attractEventParticipants,0.5).
edge(companyRelationshipBeRetainedAfterMergers,retainSponsors1,0.5).
edge(sponsorsForEventsBeFound,increaseInvolvementSponsorsInPuttingOnEvents,1).
dec(putOnFundraisingEventsOnTheWeb,fundsBeRaised,or).
edge(attractSponsors,successfulEvents,0.5).
edge(upToDateCorporatePartnerInformation,retainSponsors1,0.5).
edge(marketPHLBrand,increaseAwareness,0.5).
dec(getPAPInformation,getCorporatePartnerInformationFromDocumentLibrary1,or).
edge(trustOfSponsorsTowardsCS,contributeToAGoodCause,0.5).
edge(recognition,reachMoreKidsSponsors,0.5).
dep(useVolunteerServices,provideFundraisingServices).
dep(engagementStudentAmbassadorsInPromotingAwareness1,engagementStudentAmbassadorsInPromotingAwareness).
edge(saGiveCSPresentations,improveImageToKids,0.5).
edge(demonstrableServices2,trustOfDonor,0.5).
dec(givePhilanthropicDonation,contributionBeMade,or).
dep(providePromotionalMaterialToStudentAmbassadors,promotionResources).
dep(marketThroughOwnChannels,useSponsorMarketingChannels).
edge(regionalStaffFeelIncluded1,happinessStaff,0.5).
dec(provideFunds,makeContributionToCharity,or).
edge(successfulMarketingCampaign,marketPHLBrand,0.5).
dec(informationBeSharedWithSponsors,manageNPartnerRelationship,or).
edge(engagementSponsorEmployeesInPromotingAwareness,marketCSBrand,0.5).
dep(retainSponsors2,retainSponsors).
dep(giveCSPresentations,saGiveCSPresentations).
dep(increaseAwareness,increaseAwareness1).
dep(workWithTheRegionsToImplementEvents,eventCoordination).
dep(pledgeNonline,pledgeOnline).
edge(eventsBeMarketed,attractEventParticipants,0.5).
edge(reachMoreKidsSponsors,sponsorshipBeBeneficial,0.5).
dep(freeServices,useFreeServices).
dep(timelyServices,timelyProvisionOfFreeServices).
edge(followHighestEthicalGuidelines,trustOfSponsorsTowardsCS,0.5).
edge(sponsorPartnerNcontacts2,attractSponsors2,0.5).
edge(sponsorPartnerNcontacts2,attractSponsors2,0.5).
dep(runFundraiserInSchools,saRunFundraiserInSchools).
edge(increaseInvolvementSponsorsInPuttingOnEvents,minimizeCostOfEvents,0.5).
edge(informationBeSharedWithSponsors,upToDateCorporatePartnerInformation,1).
edge(credibilityCSBrand2,trustOfDonor,0.5).
edge(experiencedMarketingPartners,marketPHLBrand,0.5).
dec(manageNprojects,projectDeadlinesBeMet,or).
edge(receiptBeProvided,trustOfDonor,0.5).
dep(provideDocumentLibrarySystem,subscribeToDocumentLibraryFolders1).
edge(uniteVolunteersAndSponsors,increaseVolunteers,0.5).
edge(credibilityCSBrand,trustOfSponsorsTowardsCS,0.5).
dec(pledgeNDuringEvent,attendFundraisingEvent,or).
dep(acquireNCSStories,publishedCSStories).
dep(regionalStaffFeelIncluded2,regionalStaffFeelIncluded1).
edge(increasedInvolvementCounselorsInEvents1,inspiredStaff,0.5).
edge(sponsorRelationshipsBeManaged,retainSponsors,0.5).
dep(marketFundraisingEvents,eventsBeMarketed).
dep(experiencedMarketingPartners2,experiencedMarketingPartners).
dep(createLifeLongVolunteerSpirit,createLifeLongVolunteerSpirit1).
dec(getPAPInformation1,getCorporatePartnerInformationFromDocumentLibrary,or).
dec(beInformedOfFundraisingEvents,contributeOnline,or).
dec(subscribeToDocumentLibraryFolders,providePAPToStaffNUsingTheDocumentLibrary,or).
dep(marketFundraisingEvents2,beInformedOfFundraisingEvents).
dep(increasedAvailabilityToSponsors,increasedAvailabilityCounselorsToPublicSponsors).
edge(attractEventParticipants,uniteVolunteersAndSponsors,0.5).
dep(exclusiveRelationshipsOfficialPartners1,exclusiveRelationshipsOfficialPartners).
dec(reachAgreement1,becomeAPatron,or).
edge(trustOfDonor,contributeToAGoodCause1,0.5).
dep(matchFundraisingTargets,matchFundraisingTargets2).
dep(upToDateInformationOnPrograms1,upToDateInformationOnPrograms).
dep(marketFundraisingEvents1,marketFundraisingEvents2).
dep(getPhilanthropicDonations,philanthropicDonations).
edge(increasedInvolvementCounselorsInEvents,increaseConnectionCounselorsAndCommunity,0.5).
edge(timelyProvisionOfFreeServices1,successfulEvents,0.5).
edge(qualityServices2,trustOfSponsorsTowardsCS,0.5).
edge(cobranding,reachMoreKidsSponsors,0.5).
edge(saSpeakAtFundraisers,marketFundraisingEvents1,0.5).
dec(maintain20CostsAgainstRevenuesRatio,putOnFundraisingEvents,or).
dep(recognizeNSponsorContribution,recognizeNSponsorContribution1).
edge(saSpeakAtFundraisers,increaseAwareness,0.5).
dep(engagementOfSponsorEmployeesInFundDevelopment,engageEmployeesInEvents).
edge(communicateThroughInternetAndPhone,upToDateInformationOnCorporateSponsors,0.5).
edge(frontEndForIncomeRecordingBeSupported,availabilityForAdministrationAndAccountingPurposesAcrossCS,0.5).
dep(periodicalCommunicationWithRegionalStaffBeMaintained,communicateWithHeadOffice).
dec(managePAP,manageNPartnerRelationship,or).
edge(corporateSponsorsFeelIncluded,retainSponsors1,0.5).
edge(recognition,appearAsGoodCorporateCitizens,0.5).
edge(recognition,appearAsGoodCorporateCitizens,0.5).
dep(provideFreeServices1,freeServices).
edge(getCorporateSponsorFunds,increasedCorporateSponsorFunds,0.5).
dep(involvementNotForProfitPartnersInEvents1,involvementNotForProfitPartnersInEvents).
edge(retainSponsors,matchFundraisingTargets,0.5).
dec(marketThroughOwnChannels,makeContributionToCharity,or).
edge(increasePhilanthropicDonations,matchFundraisingTargets,0.5).
edge(increaseConnectionCounselorsAndCommunity,highResponseIndividualDonors,0.5).
edge(elaborateFundraisingTargets,inspiredStaff,0.5).
edge(happinessStaff1,successfulMarketingCampaign,0.5).
dec(biWeeklyConferenceCalls,periodicalCommunicationWithRegionalStaffBeMaintained,or).
edge(marketOnlyForSeriousIssues,avoidOverMarketingServices,1).
dep(engageEmployeesInEvents,engageEmployeesInFundraisingEvents).
edge(sponsorRelationshipsBeManaged,increaseInvolvementSponsorsInPuttingOnEvents,0.5).
dec(counselorSpeakOnKidsIssuesInGeneral,marketingBeMadeUsingDedicatedCounselor,or).
dep(quickResponseToSponsors,quickResponseToSponsors1).
edge(useSponsorLogo,positiveReputationOfCS2,0.5).
edge(cobranding,positiveAssociationNByConsumers,0.5).
dec(getSponsorshipProposal,becomeAMajorPatron,or).
dep(responsibleUsageSponsorFunds1,responsibleUsageSponsorFunds).
dep(positiveReputationOfCS,positiveReputationOfCS2).
dep(manageReceivables,manageReceivables1).
dec(collectPledgeOnline,pledgesBeCollected,or).
dep(provideOnlineDonorTechnology,getDonorTechnology).
dec(collectPledgeDuringEvent,pledgesBeCollected,or).
edge(accountabilityOfServices2,trustOfDonor,0.5).
edge(positiveReputation,retainSponsors,0.5).
edge(donorInformationBeRecorded,availabilityForAdministrationAndAccountingPurposesAcrossCS,0.5).
edge(acquireFreeServices,minimizeExpenses,0.5).
edge(conflictsBeManaged,happinessStaff,0.5).
dec(getWebEventTechnology,putOnFundraisingEventsOnTheWeb,or).
dec(reallocateResources,manageNprojects,or).
dep(givePhilanthropicDonation,philanthropicDonations).
edge(manageNprojects,goodProjectManagement2,0.5).
edge(provideLogoToCS,cobranding,0.5).
edge(attractSponsors2,minimizeExpenses,0.5).
edge(singleCharitableRegistrationNumber1,positiveReputation,0.5).
dep(improveImageToKids,improveImageToKids1).
edge(pledgesBeCollected,matchFundraisingTargets,0.5).
edge(meetCorporateSponsorsNeeds,engagementSponsorsInTheCauseOfCS,0.5).
dec(createPostersFlyersAndInformationalMaterial,developExternalComunications,or).
edge(contributeToAGoodCause,recognition,0.5).
edge(exclusiveRelationshipsOfficialPartners2,meetCorporateSponsorsNeeds,0.5).
dec(sponsorsForEventsBeFound,putOnFundraisingEvents,or).
dec(makeContributionToCharity,becomeAPatron,or).
dec(beInformedOfFundraisingEvents,attendFundraisingEvent,or).
dep(engagementOfSponsorEmployeesInFundDevelopment,engagementOfSponsorEmployeesInFundDevelopment1).
dec(communicateThroughInternetAndPhone,periodicalCommunicationWithRegionalStaffBeMaintained,or).
dec(developNationalEventCalendar,putOnFundraisingEvents,or).
dep(engagementSponsorEmployeesInPromotingAwareness1,engagementSponsorEmployeesInPromotingAwareness).
dep(credibilityCSBrand1,credibilityCSBrand2).
dep(freeAdvertisement,getFreeAdvertisement).
edge(increaseInvolvementSponsorsInPuttingOnEvents,matchFundraisingTargets,0.5).
dep(followHighestEthicalGuidelines1,followHighestEthicalGuidelines2).
edge(successfulMarketingCampaign,positiveReputationOfCS2,0.5).
edge(presentationSkills,presentProposalConvincinglyToSponsors,0.5).
edge(increaseInvolvementSponsorsInPuttingOnEvents,uniteVolunteersAndSponsors,0.5).
dec(useFreeServices,maintain20CostsAgainstRevenuesRatio,or).
edge(involvementNotForProfitPartnersInEvents,positiveReputationOfCS2,0.5).
edge(demonstrableServices,trustOfSponsorsTowardsCS,0.5).
edge(proactiveMediaRelationship,marketFundraisingEvents1,0.5).
edge(getCorporateSponsorFunds,matchFundraisingTargets,0.5).
dec(timelyProvisionOfFreeServices1,manageNprojects,or).
dep(collectPledgeOnline3,collectPledgeOnline).
dep(reachAgreement,agreement).
dec(recordDonorInformation,donorInformationBeRecorded,or).
dep(qualityServices,qualityServices2).
edge(commitmentToCSCauseFromSponsorsEmployees,retainSponsors1,0.5).
dep(collectPledgeOnline2,collectPledgeOnline3).
edge(attractSponsors2,acquireFreeServices,0.5).
dep(speakAtFundraisers,saSpeakAtFundraisers).
edge(marketingFromGovernmentBeAcquired,minimizeExpenses,0.5).
edge(projectDeadlinesBeMet,successfulEvents,0.5).
dep(reachAgreement,getSponsorsForEvents).
edge(successfulMarketingCampaign,marketCSBrand,0.5).
edge(increaseInvolvementSponsorsInPuttingOnEvents,engagementOfSponsorEmployeesInFundDevelopment,0.5).
dec(storeDonorTransactionsIntoDatabase,recordDonorInformation,or).
dep(donorAccountingDatabase,getDonorAccountingDatabase).
dep(marketFundraisingEvents1,marketFundraisingEvents).
dec(putOnFundraisingEvents,fundsBeRaised,or).
dep(provideFreeServices1,acquireFreeServices).
dec(saRunFundraiserInSchools,fundsBeRaised,or).
dec(getDonorTechnology,putOnFundraisingEventsOnTheWeb,or).
dep(provideLogoToCS,sponsorLogo).
dec(collectDonationsOnline,putOnFundraisingWebEvents,or).
edge(increasedCorporateSponsorFunds,matchFundraisingTargets,0.5).
dep(provideDocumentLibrarySystem,subscribeToDocumentLibraryFolders).
edge(increaseVolunteers,successfulEvents,0.5).
edge(developExternalComunications,improveImageToKids,0.5).
edge(engageEmployeesInEvents2,positiveImageToEmployees,0.5).
edge(positiveImageToEmployees,sponsorshipBeBeneficial,0.5).
edge(cobranding,appearAsGoodCorporateCitizens,0.5).
dep(manageNPartnerRelationship1,sponsorRelationshipsBeManaged).
edge(getPhilanthropicDonations,matchFundraisingTargets,0.5).
dep(longTermFunding,longTermFunding1).
dep(participateInEvents,counselorsAttendFundraisingEvents).
dec(pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents,managePAP,or).
dep(attractSponsors1,attractSponsors).
dep(provincialGovernment,marketCSService).
dep(counselorSpeakOnKidsIssuesInGeneral1,counselorSpeakOnKidsIssuesInGeneral).
edge(getPhilanthropicDonations,increasePhilanthropicDonations,0.5).
dec(providePhilanthropicDonation,makeContributionToCharity,or).
dep(getSponsorsForEvents,sponsorsForEventsBeFound).
edge(increasedAvailabilityCounselorsToPublicSponsors,retainSponsors,0.5).
edge(increaseNAwareness,retainSponsors,0.5).
edge(sponsorsMarketingChannelsBeUsed,marketPHLBrand,0.5).
dec(reachAgreement,managePAP,or).
edge(developExternalComunications,marketFundraisingEvents1,0.5).
dep(regionalStaffFeelIncluded,regionalStaffFeelIncluded2).
edge(payFundDevelopmentAndMarketingStaff,happinessStaff,0.5).
dep(responsibleUsageSponsorFunds1,responsibleUsageSponsorFunds2).
dep(manageAccounts,manageAccounts1).
edge(recognition,positiveAssociationNByConsumers,0.5).
dep(projectManagementSkills,goodProjectManagement).
edge(happinessStaff3,inspiredStaff,0.5).
dep(followHighestEthicalGuidelines1,followHighestEthicalGuidelines).
dep(accountabilityOfServices1,accountabilityOfServices).
dec(providePromotionalMaterialToStudentAmbassadors,developExternalComunications,or).
dec(collectDonorInformation,recordDonorInformation,or).
edge(increasedAvailabilityCounselorsToPublicSponsors,attractSponsors,0.5).
edge(increaseInvolvementSponsorsInPuttingOnEvents,successfulEvents,0.5).
edge(periodicalCommunicationWithRegionalStaffBeMaintained,agreementStaffOverCorporatePartnerExpectations,0.5).
dec(writeDownCorporateSponsorsObjectives,managePAP,or).
edge(contributeToACause,recognition,0.5).
edge(experiencedMarketingPartners,marketCSBrand,0.5).
edge(uniteVolunteersAndSponsors,successfulEvents,0.5).
edge(credibilityCSBrand,positiveAssociationNByConsumers,0.5).
dec(subscribeToDocumentLibraryFolders2,getCorporatePartnerInformationFromDocumentLibrary,or).
edge(retainSponsors,longTermFunding,0.5).
dec(contributeOnline,contributionBeMade,or).
edge(attractEventParticipants,successfulEvents,0.5).
edge(engagementOfSponsorEmployeesInFundDevelopment,successfulEvents,0.5).
edge(upToDateInformationOnPrograms,corporateSponsorFeelIncluded,0.5).
edge(involveNotForProfitPartnersInEvents,successfulEvents,0.5).
dec(trackBudgets,manageNprojects,or).
dec(providePAPToStaffNUsingTheDocumentLibrary,corporatePartnerExpectationsBeSharedWithStaff,or).
edge(increasedInvolvementCounselorsInEvents1,highResponseIndividualDonors2,0.5).
edge(acquireGovernmentFunding,matchFundraisingTargets,0.5).
dec(collectPledgeOnline,putOnFundraisingEventsOnTheWeb,or).
edge(answersBeProvidedToMediaQueries,goodMediaExposure,0.5).
dec(storeDonorTransactionsIntoDatabase,frontEndForIncomeRecordingBeSupported,or).
dec(useVolunteerServices,maintain20CostsAgainstRevenuesRatio,or).
dep(provideFunds1,getCorporateSponsorFunds).
edge(marketingBeMadeUsingDedicatedCounselor,proactiveMediaRelationship,0.5).
edge(corporatePartnerExpectationsBeSharedWithStaff,meetCorporateSponsorsNeeds,0.5).
edge(attractSponsors,increasedCorporateSponsorFunds,0.5).
dep(servicesBeProvidedForKidsBullyingLine,provincialGovernment).
dep(recognizeNSponsorContribution,recognition).
edge(increasedInvolvementCounselorsInEvents1,increasedAvailabilityCounselorsToPublicSponsors,0.5).
edge(sponsorsMarketingChannelsBeUsed,minimizeExpenses,0.5).
edge(experiencedMarketingPartners,successfulMarketingCampaign,0.5).
dec(maintain20CostsAgainstRevenuesRatio,putOnFundraisingEventsOnTheWeb,or).
dec(nationalMarketingStrategy,manageProjects,or).
dep(credibilityCSBrand1,credibilityCSBrand).
dec(reachAgreement1,becomeAOfficialPartner,or).
dep(getCorporatePartnerInformationFromDL1,getCorporatePartnerInformationFromDL).
dep(sponsorLogo,useSponsorLogo).
dep(sponsorPartnerNcontacts,providePartnerContactsToCS).
dep(writeArticlesForWebsite1,writeArticlesForWebsite).
dec(pledgeNonline,contributeOnline,or).
dec(becomeAMajorPatron,contributeToACause,or).
dep(getDonorDatabase,getDonorAccountingDatabase).
dec(eventsBeMarketed,putOnFundraisingEvents,or).
dec(bringRegionalFundraisingStaffTogetherOnceAYear,periodicalCommunicationWithRegionalStaffBeMaintained,or).
edge(becomeAOfficialPartner,exclusiveRelationshipsOfficialPartners,1).
edge(increaseInvolvementSponsorsInPuttingOnEvents,increasedCorporateSponsorFunds,0.5).
dec(makeContributionToCharity,becomeAOfficialPartner,or).
dec(reallocateResources1,manageProjects,or).
dec(trainCounselorsOnPublicSpeaking,counselorsWhoWantAPublicVoiceBeTrained,or).
dep(demonstrableServices1,demonstrableServices).
edge(positiveInternalOpinion,happinessStaff,0.5).
dep(engagementSponsorEmployeesInPromotingAwareness2,engageEmployeesInPromotingAwareness).
edge(contributeToAGoodCause,positiveAssociationNByConsumers,0.5).
edge(workWithTheRegionsToImplementEvents,regionalStaffFeelIncluded,0.5).
dep(exclusiveBrandAndLogoUse,grantExclusiveUseOfBrandAndLogo).
edge(proactiveMediaRelationship,goodMediaExposure,0.5).
edge(counselorSpeakOnKidsIssuesInGeneral,increasedInvolvementCounselorsInEvents,0.5).
edge(manageProjects,goodProjectManagement,0.5).
edge(sponsorsMarketingChannelsBeUsed,marketCSBrand,0.5).
edge(contributeToAGoodCause,positiveImageToEmployees,0.5).
dec(reachAgreement1,becomeAMajorPatron,or).
edge(fundsBeRaised,successfulEvents,0.5).
dep(provideRealTimeTaxReceipts,provideReceipts).
dep(provideMoneyForServices,acquireGovernmentFunding).
dep(positiveInternalOpinion1,positiveInternalOpinion).
dec(putOnOrientationProcessForFundDevelopmentAndMarketingStaff,staffBeSupported,or).
edge(positiveReputationOfCS2,marketPHLBrand,0.5).
edge(projectDeadlinesBeMet1,successfulMarketingCampaign,0.5).
edge(successfulMarketingCampaign,attractSponsors2,0.5).
dep(createGeneralLedgers,createGeneralLedgers1).
edge(counselorSpeakOnKidsIssuesInGeneral,increasedInteractionCounselorsWithMedia,0.5).
edge(corporatePartnerFundraisingExpectationsBeKnown,retainSponsors,0.5).
edge(successfulEvents,retainSponsors,0.5).
dep(attractSponsors2,attractSponsors1).
dec(storeDonorInformationIntoDatabase,recordDonorInformation,or).
edge(fundsBeRaised,matchFundraisingTargets,0.5).
dec(sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts,sponsorsMarketingChannelsBeUsed,or).
dec(attendFundraisingEvent,contributionBeMade,or).
dec(manageReceivables,frontEndForIncomeRecordingBeSupported,or).
dep(qualityServices,qualityServices1).
edge(quickResponseToSponsors,meetCorporateSponsorsNeeds,0.5).
dep(sharePAPInDocumentLibrary1,getPAPInformation).
dec(presentProposalConvincinglyToSponsors,managePAP,or).
edge(hearCSStories,trustOfDonor,0.5).
edge(recognizeNSponsorContribution1,meetCorporateSponsorsNeeds,0.5).
dec(receiptBeProvided,contributeOnline,or).
dep(trainCounselorsOnPublicSpeaking,acquirePublicSpeakingSkills).
dep(increaseVolunteers1,increaseVolunteers).
dec(provideRealTimeTaxReceipts,collectDonationsOnline,or).
dep(pledgeNDuringEvent1,collectPledgeDuringEvent).
dec(getDonorDatabase,recordDonorInformation,or).
dec(becomeAOfficialPartner,contributeToACause,or).
edge(positiveReputation,attractEventParticipants,0.5).
edge(goodMediaExposure,increaseAwareness,0.5).
edge(engageEmployeesInFundraisingEvents,commitmentToCSCauseFromSponsorsEmployees,0.5).
dec(manageAccounts,frontEndForIncomeRecordingBeSupported,or).
dec(manageNPartnerRelationship,companyRelationshipBeRetainedAfterMergers,or).
dep(provideFreeServices,freeServices).
edge(engageEmployeesInPromotingAwareness,commitmentToCSCauseFromSponsorsEmployees,0.5).
dec(writeArticlesForMagazines,marketingBeMadeUsingDedicatedCounselor,or).
edge(responsibleUsageSponsorFunds,trustOfSponsorsTowardsCS,0.5).
dep(csStories,acquireNCSStories).
dep(engagementSponsorEmployeesInPromotingAwareness,engagementSponsorEmployeesInPromotingAwareness2).
dec(emailCorporatePartnersInterestingAndRelevantNewsPieces,informationBeSharedWithSponsors,or).
dep(marketCSService,marketingFromGovernmentBeAcquired).
dep(increaseAwareness2,increaseNAwareness).
dec(provideFreeServices,makeContributionToCharity,or).
dep(trustOfSponsorsTowardsCS1,trustOfSponsorsTowardsCS2).
dep(projectManagementSkills,goodProjectManagement2).
edge(maintain20CostsAgainstRevenuesRatio,minimizeCostOfEvents,0.5).
edge(positiveReputationOfCS2,marketCSBrand,0.5).
dec(createGeneralLedgers,frontEndForIncomeRecordingBeSupported,or).
dep(notForProfitPartnersBeInvolvedInEvents,involveNotForProfitPartnersInEvents).
edge(quickResponseToQuestionsAndConcerns,corporateSponsorFeelIncluded,0.5).
dec(collectPledgeOnline2,collectDonationsOnline,or).
dep(agreement,reachAgreement1).
edge(appearAsGoodCorporateCitizens,sponsorshipBeBeneficial,0.5).
dec(getCorporatePartnerInformationFromDocumentLibrary,corporatePartnerFundraisingExpectationsBeKnown,or).
edge(grantExclusiveUseOfBrandAndLogo,recognizeNSponsorContribution2,0.5).
dep(provideReceipts,receiptBeProvided).
dep(getWebEventTechnology1,getWebEventTechnology).
dec(getWebTechnology,putOnFundraisingWebEvents,or).
edge(increaseFreeServices,minimizeCostOfEvents,0.5).
dep(sponsorPartnerNcontacts1,sponsorPartnerNcontacts).
dec(eventsBeMarketed,putOnFundraisingEventsOnTheWeb,or).
dep(sponsorshipProposal,getSponsorshipProposal).
edge(developExternalComunications,successfulMarketingCampaign,0.5).
dec(putOnOrientationForVolunteers,staffBeSupported,or).
dec(subscribeToDocumentLibraryFolders1,getCorporatePartnerInformationFromDocumentLibrary1,or).
dep(positiveReputationOfCS,positiveReputation).
dec(getSponsorshipProposal,becomeAPatron,or).
dep(exclusiveBrandAndLogoUse,cobranding).
edge(biWeeklyConferenceCalls,upToDateInformationOnCorporateSponsors,0.5).
edge(sponsorPartnerNcontacts1,attractSponsors,0.5).
edge(saGiveCSPresentations,increaseAwareness,0.5).
dec(organizeDiscussionsWithSponsors,managePAP,or).
dep(singleCharitableRegistrationNumber1,singleCharitableRegistrationNumber).
edge(getCorporatePartnerInformationFromDL,agreementStaffOverCorporatePartnerExpectations,0.5).
edge(responsibleUsageSponsorFunds2,trustOfDonor,0.5).
dec(getSponsorshipProposal,becomeAOfficialPartner,or).
edge(getFreeAdvertisement,minimizeExpenses,0.5).
dep(fundsBeRaised,funds).
edge(projectDeadlinesBeMet1,marketFundraisingEvents1,0.5).
edge(happinessStaff3,successfulEvents,0.5).
dep(nationalEventCalendar,useNationalEventCalendar).
dep(happinessStaff,happinessStaff2).
dep(happinessStaff2,happinessStaff1).
dep(upToDateCorporatePartnerInformation,upToDateInformationOnPrograms1).
edge(successfulMarketingCampaign,improveImageToKids,0.5).
dep(accountabilityOfServices1,accountabilityOfServices2).
edge(sendRecognitionLetters,recognizeNSponsorContribution2,0.5).
dep(highResponseIndividualDonors,highResponseIndividualDonors1).
dep(provideCompiledCallData,provideCompiledCallDataToMedia).
dec(becomeAPatron,contributeToACause,or).
dep(sharePAPInDocumentLibrary1,getPAPInformation1).
dep(elaborateFundraisingTargets1,elaborateFundraisingTargets).
dep(pledgeOnline,collectPledgeOnline2).
dec(makeContributionToCharity,becomeAMajorPatron,or).
edge(developExternalComunications,minimizeExpenses,-0.5).
edge(followHighestEthicalGuidelines2,trustOfDonor,0.5).
dep(providePhilanthropicDonation,philanthropicDonations).
dep(getWebEventTechnology,getWebTechnology).
edge(becomeAOfficialPartner,cobranding,1).
dep(presentationSkills1,presentationSkills).
edge(informationBeSharedWithSponsors,corporateSponsorsFeelIncluded,0.5).
dep(trustOfSponsorsTowardsCS,trustOfSponsorsTowardsCS1).
dep(publishedCSStories,hearCSStories).
dep(provideFunds,provideFunds1).
dep(engagementOfSponsorEmployeesInFundDevelopment,engageEmployeesInEvents1).
dep(pledgeNDuringEvent,pledgeNDuringEvent1).
dep(exclusiveRelationshipsOfficialPartners2,exclusiveRelationshipsOfficialPartners1).
edge(staffBeSupported,happinessStaff,0.5).
dep(avoidOverMarketingServices,avoidOverMarketingServices1).
dec(sharePAPInDocumentLibrary,providePAPToStaffNUsingTheDocumentLibrary,or).
edge(counselorsAttendFundraisingEvents,increasedInvolvementCounselorsInEvents1,0.5).
dep(manageNPartnerRelationship,manageNPartnerRelationship1).
edge(sponsorPartnerNcontacts2,acquireFreeServices,0.5).
dep(engageEmployeesInEvents2,engageEmployeesInEvents1).
edge(corporatePartnerMarketingExpectationsBeKnown,successfulMarketingCampaign,0.5).
dep(quickResponseToSponsors1,quickResponseToQuestionsAndConcerns).
edge(goodProjectManagement2,successfulEvents,0.5).
edge(commitmentToCSCauseFromSponsorsEmployees,engagementSponsorsInTheCauseOfCS,0.5).
