;;;; models/CSFDandMarketing.lisp : GENERATED from models/CSFDandMarketing.py by to-lisp.py
(<- accountabilityOfServices accountabilityOfServices1)
(<- accountabilityOfServices2 accountabilityOfServices1)
(<- acquireFreeServices (or provideFreeServices1 (and (helps attractSponsors2) (helps sponsorPartnerNcontacts2))))
(<- acquireGovernmentFunding provideMoneyForServices)
(<- acquireNCSStories csStories)
(<- acquirePublicSpeakingSkills trainCounselorsOnPublicSpeaking)
(<- agreement reachAgreement)
(<- attendFundraisingEvent (or pledgeNDuringEvent beInformedOfFundraisingEvents))
(<- attractSponsors (or attractSponsors1 (and (helps increasedAvailabilityCounselorsToPublicSponsors) (helps sponsorPartnerNcontacts1))))
(<- attractSponsors1 attractSponsors2)
(<- avoidOverMarketingServices1 avoidOverMarketingServices)
(<- beInformedOfFundraisingEvents marketFundraisingEvents2)
(<- becomeAMajorPatron (or getSponsorshipProposal reachAgreement1 makeContributionToCharity))
(<- becomeAOfficialPartner (or reachAgreement1 makeContributionToCharity getSponsorshipProposal))
(<- becomeAPatron (or reachAgreement1 makeContributionToCharity getSponsorshipProposal))
(<- cobranding (or exclusiveBrandAndLogoUse (and (helps provideLogoToCS) (makes becomeAOfficialPartner))))
(<- collectDonationsOnline (or provideRealTimeTaxReceipts collectPledgeOnline2))
(<- collectPledgeDuringEvent pledgeNDuringEvent1)
(<- collectPledgeOnline collectPledgeOnline3)
(<- collectPledgeOnline2 pledgeOnline)
(<- collectPledgeOnline3 collectPledgeOnline2)
(<- communicateWithHeadOffice periodicalCommunicationWithRegionalStaffBeMaintained)
(<- companyRelationshipBeRetainedAfterMergers manageNPartnerRelationship)
(<- contributeOnline (or beInformedOfFundraisingEvents pledgeNonline receiptBeProvided))
(<- contributeToACause (or becomeAMajorPatron becomeAOfficialPartner becomeAPatron))
(<- contributionBeMade (or givePhilanthropicDonation contributeOnline attendFundraisingEvent))
(<- corporatePartnerExpectationsBeSharedWithStaff providePAPToStaffNUsingTheDocumentLibrary)
(<- corporatePartnerFundraisingExpectationsBeKnown getCorporatePartnerInformationFromDocumentLibrary)
(<- corporatePartnerMarketingExpectationsBeKnown getCorporatePartnerInformationFromDocumentLibrary1)
(<- counselorSpeakOnKidsIssuesInGeneral counselorSpeakOnKidsIssuesInGeneral1)
(<- counselorsAttendFundraisingEvents participateInEvents)
(<- counselorsWhoWantAPublicVoiceBeTrained trainCounselorsOnPublicSpeaking)
(<- createGeneralLedgers1 createGeneralLedgers)
(<- createLifeLongVolunteerSpirit1 createLifeLongVolunteerSpirit)
(<- credibilityCSBrand credibilityCSBrand1)
(<- credibilityCSBrand2 credibilityCSBrand1)
(<- demonstrableServices demonstrableServices1)
(<- demonstrableServices1 csNServices)
(<- demonstrableServices2 demonstrableServices1)
(<- developExternalComunications (or createBrandedProducts createPostersFlyersAndInformationalMaterial providePromotionalMaterialToStudentAmbassadors))
(<- donorInformationBeRecorded recordDonorInformation)
(<- elaborateFundraisingTargets elaborateFundraisingTargets1)
(<- engageEmployeesInEvents engagementOfSponsorEmployeesInFundDevelopment)
(<- engageEmployeesInEvents1 (and engagementOfSponsorEmployeesInFundDevelopment engageEmployeesInEvents2))
(<- engageEmployeesInFundraisingEvents engageEmployeesInEvents)
(<- engageEmployeesInPromotingAwareness engagementSponsorEmployeesInPromotingAwareness2)
(<- engagementOfSponsorEmployeesInFundDevelopment1 engagementOfSponsorEmployeesInFundDevelopment)
(<- engagementSponsorEmployeesInPromotingAwareness engagementSponsorEmployeesInPromotingAwareness1)
(<- engagementSponsorEmployeesInPromotingAwareness2 engagementSponsorEmployeesInPromotingAwareness)
(<- engagementStudentAmbassadorsInPromotingAwareness engagementStudentAmbassadorsInPromotingAwareness1)
(<- eventCoordination workWithTheRegionsToImplementEvents)
(<- eventsBeMarketed marketFundraisingEvents)
(<- exclusiveRelationshipsOfficialPartners (or exclusiveRelationshipsOfficialPartners1 (makes becomeAOfficialPartner)))
(<- exclusiveRelationshipsOfficialPartners1 exclusiveRelationshipsOfficialPartners2)
(<- experiencedMarketingPartners experiencedMarketingPartners2)
(<- followHighestEthicalGuidelines followHighestEthicalGuidelines1)
(<- followHighestEthicalGuidelines2 followHighestEthicalGuidelines1)
(<- freeServices (and provideFreeServices1 provideFreeServices))
(<- frontEndForIncomeRecordingBeSupported (or storeDonorTransactionsIntoDatabase manageReceivables manageAccounts createGeneralLedgers))
(<- funds fundsBeRaised)
(<- fundsBeRaised (or putOnFundraisingEventsOnTheWeb putOnFundraisingEvents saRunFundraiserInSchools))
(<- getCorporatePartnerInformationFromDL getCorporatePartnerInformationFromDL1)
(<- getCorporatePartnerInformationFromDocumentLibrary (or getPAPInformation1 subscribeToDocumentLibraryFolders2))
(<- getCorporatePartnerInformationFromDocumentLibrary1 (or getPAPInformation subscribeToDocumentLibraryFolders1))
(<- getCorporateSponsorFunds provideFunds1)
(<- getDonorAccountingDatabase (and donorAccountingDatabase getDonorDatabase))
(<- getDonorTechnology provideOnlineDonorTechnology)
(<- getFreeAdvertisement (or freeAdvertisement (helps sponsorPartnerNcontacts2)))
(<- getPAPInformation sharePAPInDocumentLibrary1)
(<- getPAPInformation1 sharePAPInDocumentLibrary1)
(<- getSponsorsForEvents reachAgreement)
(<- getSponsorshipProposal sponsorshipProposal)
(<- getWebEventTechnology getWebEventTechnology1)
(<- getWebTechnology getWebEventTechnology)
(<- goodProjectManagement (or projectManagementSkills (helps manageProjects)))
(<- goodProjectManagement2 (or projectManagementSkills (helps manageNprojects)))
(<- grantExclusiveUseOfBrandAndLogo exclusiveBrandAndLogoUse)
(<- happinessStaff1 happinessStaff2)
(<- happinessStaff2 happinessStaff)
(<- happinessStaff3 happinessStaff)
(<- hearCSStories publishedCSStories)
(<- highResponseIndividualDonors1 (and highResponseIndividualDonors2 highResponseIndividualDonors))
(<- improveImageToKids1 improveImageToKids)
(<- increaseAwareness1 increaseAwareness)
(<- increaseNAwareness increaseAwareness2)
(<- increaseVolunteers (or increaseVolunteers1 (and (helps createLifeLongVolunteerSpirit1) (helps uniteVolunteersAndSponsors))))
(<- increasedAvailabilityCounselorsToPublicSponsors (or increasedAvailabilityToSponsors (helps increasedInvolvementCounselorsInEvents1)))
(<- informationBeSharedWithSponsors (or informSponsorsOfProgress emailCorporatePartnersInterestingAndRelevantNewsPieces))
(<- involveNotForProfitPartnersInEvents notForProfitPartnersBeInvolvedInEvents)
(<- involvementNotForProfitPartnersInEvents involvementNotForProfitPartnersInEvents1)
(<- longTermFunding1 longTermFunding)
(<- maintain20CostsAgainstRevenuesRatio (or useFreeServices useVolunteerServices))
(<- makeContributionToCharity (or provideFunds marketThroughOwnChannels providePhilanthropicDonation provideFreeServices))
(<- manageAccounts1 manageAccounts)
(<- manageNPartnerRelationship (or informationBeSharedWithSponsors managePAP))
(<- manageNPartnerRelationship1 manageNPartnerRelationship)
(<- manageNprojects (or reallocateResources timelyProvisionOfFreeServices1 trackBudgets))
(<- managePAP (or putTogetherProposalsForCorporateSponsors useNationalEventCalendar pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents reachAgreement writeDownCorporateSponsorsObjectives presentProposalConvincinglyToSponsors organizeDiscussionsWithSponsors))
(<- manageProjects (or timelyProvisionOfFreeServices nationalMarketingStrategy reallocateResources1))
(<- manageReceivables1 manageReceivables)
(<- marketCSService provincialGovernment)
(<- marketFundraisingEvents marketFundraisingEvents1)
(<- marketFundraisingEvents2 marketFundraisingEvents1)
(<- marketingBeMadeUsingDedicatedCounselor (or writeArticlesForWebsite counselorSpeakOnKidsIssuesInGeneral writeArticlesForMagazines))
(<- marketingFromGovernmentBeAcquired marketCSService)
(<- matchFundraisingTargets2 matchFundraisingTargets)
(<- nationalEventCalendar developNationalEventCalendar)
(<- periodicalCommunicationWithRegionalStaffBeMaintained (or biWeeklyConferenceCalls communicateThroughInternetAndPhone bringRegionalFundraisingStaffTogetherOnceAYear))
(<- philanthropicDonations (and getPhilanthropicDonations givePhilanthropicDonation providePhilanthropicDonation))
(<- pledgeNDuringEvent1 pledgeNDuringEvent)
(<- pledgeOnline pledgeNonline)
(<- pledgesBeCollected (or collectPledgeOnline collectPledgeDuringEvent))
(<- positiveInternalOpinion positiveInternalOpinion1)
(<- positiveReputation (or positiveReputationOfCS (helps singleCharitableRegistrationNumber1)))
(<- positiveReputationOfCS2 (or positiveReputationOfCS (and (helps useSponsorLogo) (helps successfulMarketingCampaign) (helps involvementNotForProfitPartnersInEvents))))
(<- presentationSkills presentationSkills1)
(<- projectDeadlinesBeMet manageNprojects)
(<- projectDeadlinesBeMet1 manageProjects)
(<- promotionResources providePromotionalMaterialToStudentAmbassadors)
(<- provideCompiledCallDataToMedia provideCompiledCallData)
(<- provideFundraisingServices useVolunteerServices)
(<- provideFunds1 provideFunds)
(<- providePAPToStaffNUsingTheDocumentLibrary (or subscribeToDocumentLibraryFolders sharePAPInDocumentLibrary))
(<- providePartnerContactsToCS sponsorPartnerNcontacts)
(<- provideReceipts provideRealTimeTaxReceipts)
(<- provincialGovernment servicesBeProvidedForKidsBullyingLine)
(<- publishedCSStories acquireNCSStories)
(<- putOnFundraisingEvents (or collectPledgeDuringEvent maintain20CostsAgainstRevenuesRatio sponsorsForEventsBeFound developNationalEventCalendar eventsBeMarketed))
(<- putOnFundraisingEventsOnTheWeb (or getDonorAccountingDatabase getWebEventTechnology getDonorTechnology collectPledgeOnline maintain20CostsAgainstRevenuesRatio eventsBeMarketed))
(<- putOnFundraisingWebEvents (or collectDonationsOnline getWebTechnology))
(<- qualityServices1 qualityServices)
(<- qualityServices2 qualityServices)
(<- quickResponseToQuestionsAndConcerns quickResponseToSponsors1)
(<- quickResponseToSponsors1 quickResponseToSponsors)
(<- reachAgreement1 agreement)
(<- receiptBeProvided provideReceipts)
(<- recognition (or recognizeNSponsorContribution (and (helps contributeToAGoodCause) (helps contributeToACause))))
(<- recognizeNSponsorContribution recognizeNSponsorContribution2)
(<- recognizeNSponsorContribution1 recognizeNSponsorContribution)
(<- recordDonorInformation (or storeDonorTransactionsIntoDatabase collectDonorInformation storeDonorInformationIntoDatabase getDonorDatabase))
(<- regionalStaffFeelIncluded1 regionalStaffFeelIncluded2)
(<- regionalStaffFeelIncluded2 regionalStaffFeelIncluded)
(<- responsibleUsageSponsorFunds responsibleUsageSponsorFunds1)
(<- responsibleUsageSponsorFunds2 responsibleUsageSponsorFunds1)
(<- retainSponsors (or retainSponsors2 (and (helps sponsorRelationshipsBeManaged) (helps positiveReputation) (helps increasedAvailabilityCounselorsToPublicSponsors) (helps increaseNAwareness) (helps corporatePartnerFundraisingExpectationsBeKnown) (helps successfulEvents))))
(<- saGiveCSPresentations giveCSPresentations)
(<- saRunFundraiserInSchools runFundraiserInSchools)
(<- saSpeakAtFundraisers speakAtFundraisers)
(<- singleCharitableRegistrationNumber singleCharitableRegistrationNumber1)
(<- singleCharitableRegistrationNumberBeUsed singleCharitableRegistrationNumber)
(<- sponsorLogo provideLogoToCS)
(<- sponsorPartnerNcontacts sponsorPartnerNcontacts1)
(<- sponsorRelationshipsBeManaged manageNPartnerRelationship1)
(<- sponsorsForEventsBeFound getSponsorsForEvents)
(<- sponsorsMarketingChannelsBeUsed sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts)
(<- sponsorshipProposal presentProposalConvincinglyToSponsors)
(<- staffBeSupported (or implementStayInTouchProgram putOnOrientationProcessForFundDevelopmentAndMarketingStaff putOnOrientationForVolunteers))
(<- subscribeToDocumentLibraryFolders provideDocumentLibrarySystem)
(<- subscribeToDocumentLibraryFolders1 provideDocumentLibrarySystem)
(<- subscribeToDocumentLibraryFolders2 provideDocumentLibrarySystem)
(<- timelyProvisionOfFreeServices timelyServices)
(<- trustOfSponsorsTowardsCS1 trustOfSponsorsTowardsCS)
(<- trustOfSponsorsTowardsCS2 trustOfSponsorsTowardsCS1)
(<- upToDateInformationOnCorporateSponsors (or upToDateCorporatePartnerInformation2 (and (helps communicateThroughInternetAndPhone) (helps biWeeklyConferenceCalls))))
(<- upToDateInformationOnPrograms upToDateInformationOnPrograms1)
(<- upToDateInformationOnPrograms1 upToDateCorporatePartnerInformation)
(<- useFreeServices freeServices)
(<- useNationalEventCalendar nationalEventCalendar)
(<- useSponsorLogo sponsorLogo)
(<- useSponsorMarketingChannels marketThroughOwnChannels)
(<- writeArticlesForMagazines writeArticlesForMagazines1)
(<- writeArticlesForWebsite writeArticlesForWebsite1)
(<- agreementStaffOverCorporatePartnerExpectations (and (helps periodicalCommunicationWithRegionalStaffBeMaintained) (helps getCorporatePartnerInformationFromDL)))
(<- appearAsGoodCorporateCitizens (and (helps recognition) (helps recognition) (helps cobranding)))
(<- attractEventParticipants (and (helps increaseNAwareness) (helps eventsBeMarketed) (helps positiveReputation)))
(<- attractSponsors2 (and (helps useSponsorLogo) (helps goodMediaExposure) (helps sponsorPartnerNcontacts2) (helps sponsorPartnerNcontacts2) (helps successfulMarketingCampaign)))
(<- availabilityForAdministrationAndAccountingPurposesAcrossCS (and (helps frontEndForIncomeRecordingBeSupported) (helps donorInformationBeRecorded)))
(<- avoidOverMarketingServices (makes marketOnlyForSeriousIssues))
(<- commitmentToCSCauseFromSponsorsEmployees (and (helps engageEmployeesInFundraisingEvents) (helps engageEmployeesInPromotingAwareness)))
(<- contributeToAGoodCause (helps trustOfSponsorsTowardsCS))
(<- contributeToAGoodCause1 (helps trustOfDonor))
(<- corporateSponsorFeelIncluded (and (helps upToDateInformationOnPrograms) (helps quickResponseToQuestionsAndConcerns)))
(<- corporateSponsorsFeelIncluded (and (makes meetCorporateSponsorsNeeds) (helps informationBeSharedWithSponsors)))
(<- engagementOfSponsorEmployeesInFundDevelopment (and (helps attractEventParticipants) (helps increaseInvolvementSponsorsInPuttingOnEvents)))
(<- engagementSponsorsInTheCauseOfCS (and (helps meetCorporateSponsorsNeeds) (helps commitmentToCSCauseFromSponsorsEmployees)))
(<- goodMediaExposure (and (helps answersBeProvidedToMediaQueries) (helps proactiveMediaRelationship)))
(<- happinessStaff (and (helps regionalStaffFeelIncluded1) (helps conflictsBeManaged) (helps payFundDevelopmentAndMarketingStaff) (helps positiveInternalOpinion) (helps staffBeSupported)))
(<- highResponseIndividualDonors (helps increaseConnectionCounselorsAndCommunity))
(<- highResponseIndividualDonors2 (helps increasedInvolvementCounselorsInEvents1))
(<- improveImageToKids (and (helps saSpeakAtFundraisers) (helps saGiveCSPresentations) (helps developExternalComunications) (helps successfulMarketingCampaign)))
(<- increaseAwareness (and (helps marketPHLBrand) (helps saSpeakAtFundraisers) (helps goodMediaExposure) (helps saGiveCSPresentations)))
(<- increaseConnectionCounselorsAndCommunity (helps increasedInvolvementCounselorsInEvents))
(<- increaseFreeServices (helps sponsorPartnerNcontacts1))
(<- increaseInvolvementSponsorsInPuttingOnEvents (and (makes sponsorsForEventsBeFound) (helps sponsorRelationshipsBeManaged)))
(<- increasePhilanthropicDonations (and (helps highResponseIndividualDonors2) (helps getPhilanthropicDonations)))
(<- increasedCorporateSponsorFunds (and (helps getCorporateSponsorFunds) (helps attractSponsors) (helps increaseInvolvementSponsorsInPuttingOnEvents)))
(<- increasedInteractionCounselorsWithMedia (and (helps counselorsWhoWantAPublicVoiceBeTrained) (helps counselorSpeakOnKidsIssuesInGeneral)))
(<- increasedInvolvementCounselorsInEvents (helps counselorSpeakOnKidsIssuesInGeneral))
(<- increasedInvolvementCounselorsInEvents1 (helps counselorsAttendFundraisingEvents))
(<- inspiredStaff (and (helps increasedInvolvementCounselorsInEvents1) (helps elaborateFundraisingTargets) (helps happinessStaff3)))
(<- longTermFunding (helps retainSponsors))
(<- marketCSBrand (and (helps engagementSponsorEmployeesInPromotingAwareness) (helps successfulMarketingCampaign) (helps experiencedMarketingPartners) (helps sponsorsMarketingChannelsBeUsed) (helps positiveReputationOfCS2)))
(<- marketFundraisingEvents1 (and (helps saSpeakAtFundraisers) (helps proactiveMediaRelationship) (helps developExternalComunications) (helps projectDeadlinesBeMet1)))
(<- marketPHLBrand (and (helps getFreeAdvertisement) (helps successfulMarketingCampaign) (helps experiencedMarketingPartners) (helps sponsorsMarketingChannelsBeUsed) (helps positiveReputationOfCS2)))
(<- matchFundraisingTargets (and (helps retainSponsors) (helps increasePhilanthropicDonations) (helps pledgesBeCollected) (helps increaseInvolvementSponsorsInPuttingOnEvents) (helps getCorporateSponsorFunds) (helps increasedCorporateSponsorFunds) (helps getPhilanthropicDonations) (helps acquireGovernmentFunding) (helps fundsBeRaised)))
(<- meetCorporateSponsorsNeeds (and (helps exclusiveRelationshipsOfficialPartners2) (helps corporatePartnerExpectationsBeSharedWithStaff) (helps quickResponseToSponsors) (helps recognizeNSponsorContribution1)))
(<- minimizeCostOfEvents (and (helps increaseInvolvementSponsorsInPuttingOnEvents) (helps maintain20CostsAgainstRevenuesRatio) (helps increaseFreeServices)))
(<- minimizeExpenses (and (helps acquireFreeServices) (helps attractSponsors2) (helps marketingFromGovernmentBeAcquired) (helps sponsorsMarketingChannelsBeUsed) (helps getFreeAdvertisement) (hurts developExternalComunications)))
(<- positiveAssociationNByConsumers (and (helps cobranding) (helps recognition) (helps credibilityCSBrand) (helps contributeToAGoodCause)))
(<- positiveImageToEmployees (and (helps engageEmployeesInEvents2) (helps contributeToAGoodCause)))
(<- presentProposalConvincinglyToSponsors (helps presentationSkills))
(<- proactiveMediaRelationship (and (helps increasedInteractionCounselorsWithMedia) (helps marketingBeMadeUsingDedicatedCounselor)))
(<- reachMoreKidsSponsors (and (helps recognition) (helps cobranding)))
(<- recognizeNSponsorContribution2 (and (helps createThankYouAds) (helps grantExclusiveUseOfBrandAndLogo) (helps sendRecognitionLetters)))
(<- reduceInternalCommunicationConfusion (helps agreementStaffOverCorporatePartnerExpectations))
(<- regionalStaffFeelIncluded (and (helps periodicalCommunicationWithRegionalStaffBeMaintained) (helps workWithTheRegionsToImplementEvents)))
(<- retainSponsors1 (and (helps trustOfSponsorsTowardsCS2) (helps companyRelationshipBeRetainedAfterMergers) (helps upToDateCorporatePartnerInformation) (helps corporateSponsorsFeelIncluded) (helps commitmentToCSCauseFromSponsorsEmployees)))
(<- sponsorshipBeBeneficial (and (helps reachMoreKidsSponsors) (helps positiveImageToEmployees) (helps appearAsGoodCorporateCitizens)))
(<- successfulEvents (and (helps attractSponsors) (helps timelyProvisionOfFreeServices1) (helps projectDeadlinesBeMet) (helps increaseVolunteers) (helps increaseInvolvementSponsorsInPuttingOnEvents) (helps uniteVolunteersAndSponsors) (helps attractEventParticipants) (helps engagementOfSponsorEmployeesInFundDevelopment) (helps involveNotForProfitPartnersInEvents) (helps fundsBeRaised) (helps happinessStaff3) (helps goodProjectManagement2)))
(<- successfulMarketingCampaign (and (helps goodProjectManagement) (helps happinessStaff1) (helps experiencedMarketingPartners) (helps projectDeadlinesBeMet1) (helps developExternalComunications) (helps corporatePartnerMarketingExpectationsBeKnown)))
(<- trustOfDonor (and (helps demonstrableServices2) (helps credibilityCSBrand2) (helps receiptBeProvided) (helps accountabilityOfServices2) (helps hearCSStories) (helps responsibleUsageSponsorFunds2) (helps followHighestEthicalGuidelines2)))
(<- trustOfSponsorsTowardsCS (and (helps accountabilityOfServices) (helps followHighestEthicalGuidelines) (helps credibilityCSBrand) (helps qualityServices2) (helps demonstrableServices) (helps responsibleUsageSponsorFunds)))
(<- uniteVolunteersAndSponsors (and (helps attractEventParticipants) (helps increaseInvolvementSponsorsInPuttingOnEvents)))
(<- upToDateCorporatePartnerInformation (makes informationBeSharedWithSponsors))
(defparameter *hard* '(counselorsAttendFundraisingEvents contributeToACause receiptBeProvided pledgesBeCollected projectDeadlinesBeMet1 sponsorsForEventsBeFound marketingFromGovernmentBeAcquired sponsorsMarketingChannelsBeUsed companyRelationshipBeRetainedAfterMergers notForProfitPartnersBeInvolvedInEvents staffBeSupported singleCharitableRegistrationNumberBeUsed contributionBeMade fundsBeRaised makeContributionToCharity projectDeadlinesBeMet involveNotForProfitPartnersInEvents marketingBeMadeUsingDedicatedCounselor eventsBeMarketed beInformedOfFundraisingEvents answersBeProvidedToMediaQueries counselorsWhoWantAPublicVoiceBeTrained informationBeSharedWithSponsors maintain20CostsAgainstRevenuesRatio corporatePartnerFundraisingExpectationsBeKnown corporatePartnerMarketingExpectationsBeKnown periodicalCommunicationWithRegionalStaffBeMaintained sponsorRelationshipsBeManaged frontEndForIncomeRecordingBeSupported corporatePartnerExpectationsBeSharedWithStaff servicesBeProvidedForKidsBullyingLine donorInformationBeRecorded))
(defparameter *soft* '(sponsorshipBeBeneficial marketFundraisingEvents2 acquireNCSStories upToDateCorporatePartnerInformation regionalStaffFeelIncluded proactiveMediaRelationship csNServices highResponseIndividualDonors accountabilityOfServices1 happinessStaff csStories exclusiveRelationshipsOfficialPartners reachMoreKidsSponsors followHighestEthicalGuidelines reduceInternalCommunicationConfusion commitmentToCSCauseFromSponsorsEmployees presentProposalConvincinglyToSponsors successfulEvents goodMediaExposure quickResponseToQuestionsAndConcerns positiveInternalOpinion credibilityCSBrand engageEmployeesInEvents1 sponsorPartnerNcontacts2 presentationSkills1 recognition credibilityCSBrand2 sponsorPartnerNcontacts createLifeLongVolunteerSpirit1 acquirePublicSpeakingSkills increaseAwareness engagementStudentAmbassadorsInPromotingAwareness responsibleUsageSponsorFunds happinessStaff3 highResponseIndividualDonors1 avoidOverMarketingServices engagementSponsorsInTheCauseOfCS positiveReputation nationalEventCalendar involvementNotForProfitPartnersInEvents engagementOfSponsorEmployeesInFundDevelopment credibilityCSBrand1 exclusiveRelationshipsOfficialPartners1 quickResponseToSponsors1 appearAsGoodCorporateCitizens engageEmployeesInEvents goodProjectManagement cobranding matchFundraisingTargets marketCSBrand longTermFunding improveImageToKids acquireGovernmentFunding marketFundraisingEvents1 engageEmployeesInFundraisingEvents meetCorporateSponsorsNeeds trustOfSponsorsTowardsCS2 contributeToAGoodCause increaseVolunteers1 agreementStaffOverCorporatePartnerExpectations matchFundraisingTargets2 engagementSponsorEmployeesInPromotingAwareness1 projectManagementSkills positiveInternalOpinion1 retainSponsors1 upToDateInformationOnPrograms1 increasedInvolvementCounselorsInEvents uniteVolunteersAndSponsors goodProjectManagement2 presentationSkills qualityServices1 increasedInvolvementCounselorsInEvents1 corporateSponsorsFeelIncluded recognizeNSponsorContribution1 happinessStaff1 quickResponseToSponsors increaseConnectionCounselorsAndCommunity timelyServices longTermFunding1 retainSponsors2 experiencedMarketingPartners regionalStaffFeelIncluded1 recognizeNSponsorContribution qualityServices responsibleUsageSponsorFunds2 involvementNotForProfitPartnersInEvents1 increaseAccessSpeedRegionalOfficesToDocumentLibrary increasedAvailabilityToSponsors accountabilityOfServices highResponseIndividualDonors2 happinessStaff2 increaseFreeServices trustOfDonor positiveImageToEmployees recognizeNSponsorContribution2 engagementSponsorEmployeesInPromotingAwareness2 includeCorporatePartnersInTheDevelopmentOfPressReleases followHighestEthicalGuidelines1 contributeToAGoodCause1 trustOfSponsorsTowardsCS1 increasePhilanthropicDonations increasedInteractionCounselorsWithMedia sponsorPartnerNcontacts1 provincialGovernment responsibleUsageSponsorFunds1 minimizeExpenses accountabilityOfServices2 marketPHLBrand improveImageToKids1 increaseAwareness1 upToDateInformationOnPrograms increaseNAwareness increaseAwareness2 regionalStaffFeelIncluded2 increaseInvolvementSponsorsInPuttingOnEvents exclusiveRelationshipsOfficialPartners2 acquireFreeServices marketFundraisingEvents timelyProvisionOfFreeServices1 successfulMarketingCampaign engagementOfSponsorEmployeesInFundDevelopment1 corporateSponsorFeelIncluded followHighestEthicalGuidelines2 engageEmployeesInEvents2 demonstrableServices1 increasedAvailabilityCounselorsToPublicSponsors availabilityForAdministrationAndAccountingPurposesAcrossCS publishedCSStories attractSponsors1 attractSponsors increaseVolunteers upToDateCorporatePartnerInformation2 engagementSponsorEmployeesInPromotingAwareness timelyProvisionOfFreeServices engageEmployeesInPromotingAwareness demonstrableServices attractEventParticipants hearCSStories createLifeLongVolunteerSpirit minimizeCostOfEvents trustOfSponsorsTowardsCS retainSponsors experiencedMarketingPartners2 demonstrableServices2 engagementStudentAmbassadorsInPromotingAwareness1 qualityServices2 positiveReputationOfCS upToDateInformationOnCorporateSponsors positiveAssociationNByConsumers attractSponsors2 positiveReputationOfCS2 inspiredStaff increasedCorporateSponsorFunds avoidOverMarketingServices1))
