% CSFDandMarketing  (edit me: node/2 edge/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, leaf/1, topgoal/1.
node(sponsorshipBeBeneficial,softgoal).
node(marketFundraisingEvents2,softgoal).
node(provideOnlineDonorTechnology,task).
leaf(provideOnlineDonorTechnology).
node(counselorsAttendFundraisingEvents,goal).
topgoal(counselorsAttendFundraisingEvents).
node(manageNprojects,task).
node(acquireNCSStories,softgoal).
node(upToDateCorporatePartnerInformation,softgoal).
node(regionalStaffFeelIncluded,softgoal).
node(bringRegionalFundraisingStaffTogetherOnceAYear,task).
leaf(bringRegionalFundraisingStaffTogetherOnceAYear).
node(proactiveMediaRelationship,softgoal).
node(csNServices,softgoal).
leaf(csNServices).
node(highResponseIndividualDonors,softgoal).
node(recordDonorInformation,task).
node(accountabilityOfServices1,softgoal).
leaf(accountabilityOfServices1).
node(providePromotionalMaterialToStudentAmbassadors,task).
leaf(providePromotionalMaterialToStudentAmbassadors).
node(contributeOnline,task).
node(happinessStaff,softgoal).
node(csStories,softgoal).
leaf(csStories).
node(contributeToACause,goal).
topgoal(contributeToACause).
node(exclusiveRelationshipsOfficialPartners,softgoal).
node(conflictsBeManaged,task).
leaf(conflictsBeManaged).
node(receiptBeProvided,goal).
topgoal(receiptBeProvided).
node(reachMoreKidsSponsors,softgoal).
node(manageProjects,task).
node(attendFundraisingEvent,task).
node(useVolunteerServices,task).
leaf(useVolunteerServices).
node(pledgesBeCollected,goal).
topgoal(pledgesBeCollected).
node(sponsorshipProposal,task).
node(followHighestEthicalGuidelines,softgoal).
node(reduceInternalCommunicationConfusion,softgoal).
node(projectDeadlinesBeMet1,goal).
topgoal(projectDeadlinesBeMet1).
node(provideCompiledCallData,task).
leaf(provideCompiledCallData).
node(payFundDevelopmentAndMarketingStaff,task).
leaf(payFundDevelopmentAndMarketingStaff).
node(useSponsorMarketingChannels,task).
node(getCorporatePartnerInformationFromDL,task).
node(manageReceivables,task).
leaf(manageReceivables).
node(becomeAMajorPatron,task).
node(createThankYouAds,task).
leaf(createThankYouAds).
node(reachAgreement,task).
leaf(reachAgreement).
node(getWebEventTechnology1,task).
leaf(getWebEventTechnology1).
node(provideMoneyForServices,task).
leaf(provideMoneyForServices).
node(commitmentToCSCauseFromSponsorsEmployees,softgoal).
node(presentProposalConvincinglyToSponsors,softgoal).
node(successfulEvents,softgoal).
node(collectDonationsOnline,task).
node(createPostersFlyersAndInformationalMaterial,task).
leaf(createPostersFlyersAndInformationalMaterial).
node(goodMediaExposure,softgoal).
node(quickResponseToQuestionsAndConcerns,softgoal).
node(positiveInternalOpinion,softgoal).
node(provideDocumentLibrarySystem,task).
leaf(provideDocumentLibrarySystem).
node(credibilityCSBrand,softgoal).
node(elaborateFundraisingTargets,task).
node(engageEmployeesInEvents1,softgoal).
node(sponsorsForEventsBeFound,goal).
topgoal(sponsorsForEventsBeFound).
node(sponsorPartnerNcontacts2,softgoal).
leaf(sponsorPartnerNcontacts2).
node(marketingFromGovernmentBeAcquired,goal).
topgoal(marketingFromGovernmentBeAcquired).
node(becomeAPatron,task).
node(becomeAOfficialPartner,task).
node(presentationSkills1,softgoal).
leaf(presentationSkills1).
node(providePartnerContactsToCS,task).
node(createBrandedProducts,task).
leaf(createBrandedProducts).
node(runFundraiserInSchools,task).
leaf(runFundraiserInSchools).
node(recognition,softgoal).
node(sponsorsMarketingChannelsBeUsed,goal).
topgoal(sponsorsMarketingChannelsBeUsed).
node(credibilityCSBrand2,softgoal).
node(sponsorPartnerNcontacts,softgoal).
node(reallocateResources,task).
leaf(reallocateResources).
node(createLifeLongVolunteerSpirit1,softgoal).
node(acquirePublicSpeakingSkills,softgoal).
node(companyRelationshipBeRetainedAfterMergers,goal).
topgoal(companyRelationshipBeRetainedAfterMergers).
node(increaseAwareness,softgoal).
node(notForProfitPartnersBeInvolvedInEvents,goal).
leaf(notForProfitPartnersBeInvolvedInEvents).
topgoal(notForProfitPartnersBeInvolvedInEvents).
node(engagementStudentAmbassadorsInPromotingAwareness,softgoal).
node(responsibleUsageSponsorFunds,softgoal).
node(happinessStaff3,softgoal).
node(saGiveCSPresentations,task).
node(putOnFundraisingWebEvents,task).
node(highResponseIndividualDonors1,softgoal).
node(elaborateFundraisingTargets1,task).
leaf(elaborateFundraisingTargets1).
node(staffBeSupported,goal).
topgoal(staffBeSupported).
node(giveCSPresentations,task).
leaf(giveCSPresentations).
node(speakAtFundraisers,task).
leaf(speakAtFundraisers).
node(avoidOverMarketingServices,softgoal).
node(getCorporatePartnerInformationFromDocumentLibrary1,task).
node(engagementSponsorsInTheCauseOfCS,softgoal).
node(positiveReputation,softgoal).
node(agreement,resource).
node(singleCharitableRegistrationNumber,resource).
node(nationalEventCalendar,softgoal).
node(informSponsorsOfProgress,task).
leaf(informSponsorsOfProgress).
node(getDonorDatabase,task).
leaf(getDonorDatabase).
node(singleCharitableRegistrationNumberBeUsed,goal).
topgoal(singleCharitableRegistrationNumberBeUsed).
node(freeAdvertisement,resource).
leaf(freeAdvertisement).
node(useSponsorLogo,task).
node(implementStayInTouchProgram,task).
leaf(implementStayInTouchProgram).
node(involvementNotForProfitPartnersInEvents,softgoal).
node(engagementOfSponsorEmployeesInFundDevelopment,softgoal).
node(credibilityCSBrand1,softgoal).
leaf(credibilityCSBrand1).
node(reallocateResources1,task).
leaf(reallocateResources1).
node(exclusiveRelationshipsOfficialPartners1,softgoal).
node(contributionBeMade,goal).
topgoal(contributionBeMade).
node(quickResponseToSponsors1,softgoal).
node(appearAsGoodCorporateCitizens,softgoal).
node(engageEmployeesInEvents,softgoal).
node(goodProjectManagement,softgoal).
node(putOnOrientationProcessForFundDevelopmentAndMarketingStaff,task).
leaf(putOnOrientationProcessForFundDevelopmentAndMarketingStaff).
node(cobranding,softgoal).
node(organizeDiscussionsWithSponsors,task).
leaf(organizeDiscussionsWithSponsors).
node(providePAPToStaffNUsingTheDocumentLibrary,task).
node(matchFundraisingTargets,softgoal).
node(fundsBeRaised,goal).
topgoal(fundsBeRaised).
node(provideCompiledCallDataToMedia,task).
node(nationalMarketingStrategy,resource).
leaf(nationalMarketingStrategy).
node(marketCSBrand,softgoal).
node(longTermFunding,softgoal).
node(freeServices,resource).
node(improveImageToKids,softgoal).
node(acquireGovernmentFunding,softgoal).
node(marketFundraisingEvents1,softgoal).
node(engageEmployeesInFundraisingEvents,softgoal).
node(getPAPInformation1,task).
node(meetCorporateSponsorsNeeds,softgoal).
node(provideFundraisingServices,task).
node(trustOfSponsorsTowardsCS2,softgoal).
node(getDonorAccountingDatabase,task).
node(collectPledgeOnline,task).
node(makeContributionToCharity,goal).
topgoal(makeContributionToCharity).
node(contributeToAGoodCause,softgoal).
node(increaseVolunteers1,softgoal).
leaf(increaseVolunteers1).
node(collectDonorInformation,task).
leaf(collectDonorInformation).
node(getSponsorshipProposal,task).
node(writeArticlesForWebsite1,task).
leaf(writeArticlesForWebsite1).
node(agreementStaffOverCorporatePartnerExpectations,softgoal).
node(projectDeadlinesBeMet,goal).
topgoal(projectDeadlinesBeMet).
node(provideFreeServices,task).
leaf(provideFreeServices).
node(manageAccounts1,task).
node(matchFundraisingTargets2,softgoal).
node(engagementSponsorEmployeesInPromotingAwareness1,softgoal).
leaf(engagementSponsorEmployeesInPromotingAwareness1).
node(workWithTheRegionsToImplementEvents,task).
leaf(workWithTheRegionsToImplementEvents).
node(projectManagementSkills,softgoal).
leaf(projectManagementSkills).
node(createGeneralLedgers1,task).
node(positiveInternalOpinion1,softgoal).
leaf(positiveInternalOpinion1).
node(retainSponsors1,softgoal).
node(upToDateInformationOnPrograms1,softgoal).
node(getSponsorsForEvents,task).
node(increasedInvolvementCounselorsInEvents,softgoal).
node(uniteVolunteersAndSponsors,softgoal).
node(goodProjectManagement2,softgoal).
node(putOnFundraisingEvents,task).
node(donorAccountingDatabase,resource).
leaf(donorAccountingDatabase).
node(presentationSkills,softgoal).
node(getWebTechnology,task).
node(marketCSService,task).
node(qualityServices1,softgoal).
node(involveNotForProfitPartnersInEvents,goal).
topgoal(involveNotForProfitPartnersInEvents).
node(reachAgreement1,task).
node(increasedInvolvementCounselorsInEvents1,softgoal).
node(corporateSponsorsFeelIncluded,softgoal).
node(recognizeNSponsorContribution1,softgoal).
node(happinessStaff1,softgoal).
node(quickResponseToSponsors,softgoal).
leaf(quickResponseToSponsors).
node(provideLogoToCS,task).
leaf(provideLogoToCS).
node(increaseConnectionCounselorsAndCommunity,softgoal).
node(timelyServices,softgoal).
leaf(timelyServices).
node(sharePAPInDocumentLibrary,task).
leaf(sharePAPInDocumentLibrary).
node(longTermFunding1,softgoal).
node(getCorporatePartnerInformationFromDL1,task).
leaf(getCorporatePartnerInformationFromDL1).
node(retainSponsors2,softgoal).
leaf(retainSponsors2).
node(experiencedMarketingPartners,softgoal).
node(sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts,task).
leaf(sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts).
node(regionalStaffFeelIncluded1,softgoal).
node(biWeeklyConferenceCalls,task).
leaf(biWeeklyConferenceCalls).
node(recognizeNSponsorContribution,softgoal).
node(marketingBeMadeUsingDedicatedCounselor,goal).
topgoal(marketingBeMadeUsingDedicatedCounselor).
node(givePhilanthropicDonation,task).
leaf(givePhilanthropicDonation).
node(writeArticlesForMagazines,task).
node(exclusiveBrandAndLogoUse,resource).
leaf(exclusiveBrandAndLogoUse).
node(qualityServices,softgoal).
leaf(qualityServices).
node(putOnFundraisingEventsOnTheWeb,task).
node(saRunFundraiserInSchools,task).
node(responsibleUsageSponsorFunds2,softgoal).
node(collectPledgeDuringEvent,task).
node(getCorporateSponsorFunds,task).
node(managePAP,task).
node(involvementNotForProfitPartnersInEvents1,softgoal).
leaf(involvementNotForProfitPartnersInEvents1).
node(eventsBeMarketed,goal).
topgoal(eventsBeMarketed).
node(createGeneralLedgers,task).
leaf(createGeneralLedgers).
node(increaseAccessSpeedRegionalOfficesToDocumentLibrary,softgoal).
leaf(increaseAccessSpeedRegionalOfficesToDocumentLibrary).
node(developExternalComunications,task).
node(increasedAvailabilityToSponsors,softgoal).
leaf(increasedAvailabilityToSponsors).
node(accountabilityOfServices,softgoal).
node(highResponseIndividualDonors2,softgoal).
node(beInformedOfFundraisingEvents,goal).
topgoal(beInformedOfFundraisingEvents).
node(saSpeakAtFundraisers,task).
node(happinessStaff2,softgoal).
node(eventCoordination,task).
node(getCorporatePartnerInformationFromDocumentLibrary,task).
node(increaseFreeServices,softgoal).
node(trustOfDonor,softgoal).
node(positiveImageToEmployees,softgoal).
node(recognizeNSponsorContribution2,softgoal).
node(engagementSponsorEmployeesInPromotingAwareness2,softgoal).
node(collectPledgeOnline2,task).
node(promotionResources,resource).
node(includeCorporatePartnersInTheDevelopmentOfPressReleases,softgoal).
leaf(includeCorporatePartnersInTheDevelopmentOfPressReleases).
node(manageReceivables1,task).
node(provideFreeServices1,task).
leaf(provideFreeServices1).
node(placeSponsorLogosInEvents,task).
leaf(placeSponsorLogosInEvents).
node(followHighestEthicalGuidelines1,softgoal).
leaf(followHighestEthicalGuidelines1).
node(getPAPInformation,task).
node(answersBeProvidedToMediaQueries,goal).
leaf(answersBeProvidedToMediaQueries).
topgoal(answersBeProvidedToMediaQueries).
node(contributeToAGoodCause1,softgoal).
node(trustOfSponsorsTowardsCS1,softgoal).
node(pledgeNonline,task).
leaf(pledgeNonline).
node(increasePhilanthropicDonations,softgoal).
node(increasedInteractionCounselorsWithMedia,softgoal).
node(sharePAPInDocumentLibrary1,task).
leaf(sharePAPInDocumentLibrary1).
node(storeDonorTransactionsIntoDatabase,task).
leaf(storeDonorTransactionsIntoDatabase).
node(sponsorPartnerNcontacts1,softgoal).
leaf(sponsorPartnerNcontacts1).
node(provincialGovernment,softgoal).
node(responsibleUsageSponsorFunds1,softgoal).
leaf(responsibleUsageSponsorFunds1).
node(minimizeExpenses,softgoal).
node(trackBudgets,task).
leaf(trackBudgets).
node(accountabilityOfServices2,softgoal).
node(marketPHLBrand,softgoal).
node(improveImageToKids1,softgoal).
node(pledgeOnline,task).
node(counselorsWhoWantAPublicVoiceBeTrained,goal).
topgoal(counselorsWhoWantAPublicVoiceBeTrained).
node(increaseAwareness1,softgoal).
node(emailCorporatePartnersInterestingAndRelevantNewsPieces,task).
leaf(emailCorporatePartnersInterestingAndRelevantNewsPieces).
node(sendRecognitionLetters,task).
leaf(sendRecognitionLetters).
node(philanthropicDonations,task).
node(manageNPartnerRelationship,task).
node(writeArticlesForWebsite,task).
node(upToDateInformationOnPrograms,softgoal).
node(increaseNAwareness,softgoal).
node(increaseAwareness2,softgoal).
leaf(increaseAwareness2).
node(informationBeSharedWithSponsors,goal).
topgoal(informationBeSharedWithSponsors).
node(regionalStaffFeelIncluded2,softgoal).
node(increaseInvolvementSponsorsInPuttingOnEvents,softgoal).
node(exclusiveRelationshipsOfficialPartners2,softgoal).
leaf(exclusiveRelationshipsOfficialPartners2).
node(singleCharitableRegistrationNumber1,resource).
leaf(singleCharitableRegistrationNumber1).
node(maintain20CostsAgainstRevenuesRatio,goal).
topgoal(maintain20CostsAgainstRevenuesRatio).
node(acquireFreeServices,softgoal).
node(marketFundraisingEvents,softgoal).
node(timelyProvisionOfFreeServices1,softgoal).
leaf(timelyProvisionOfFreeServices1).
node(pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents,task).
leaf(pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents).
node(providePhilanthropicDonation,task).
leaf(providePhilanthropicDonation).
node(successfulMarketingCampaign,softgoal).
node(engagementOfSponsorEmployeesInFundDevelopment1,softgoal).
node(pledgeNDuringEvent,task).
leaf(pledgeNDuringEvent).
node(corporateSponsorFeelIncluded,softgoal).
node(grantExclusiveUseOfBrandAndLogo,task).
node(corporatePartnerFundraisingExpectationsBeKnown,goal).
topgoal(corporatePartnerFundraisingExpectationsBeKnown).
node(putTogetherProposalsForCorporateSponsors,task).
leaf(putTogetherProposalsForCorporateSponsors).
node(manageNPartnerRelationship1,task).
node(communicateWithHeadOffice,task).
node(subscribeToDocumentLibraryFolders2,task).
node(followHighestEthicalGuidelines2,softgoal).
node(engageEmployeesInEvents2,softgoal).
leaf(engageEmployeesInEvents2).
node(counselorSpeakOnKidsIssuesInGeneral1,task).
leaf(counselorSpeakOnKidsIssuesInGeneral1).
node(provideRealTimeTaxReceipts,task).
leaf(provideRealTimeTaxReceipts).
node(provideReceipts,task).
node(useNationalEventCalendar,task).
node(demonstrableServices1,softgoal).
node(collectPledgeOnline3,task).
node(increasedAvailabilityCounselorsToPublicSponsors,softgoal).
node(availabilityForAdministrationAndAccountingPurposesAcrossCS,softgoal).
node(publishedCSStories,softgoal).
node(attractSponsors1,softgoal).
node(attractSponsors,softgoal).
node(funds,resource).
node(increaseVolunteers,softgoal).
node(upToDateCorporatePartnerInformation2,softgoal).
leaf(upToDateCorporatePartnerInformation2).
node(subscribeToDocumentLibraryFolders,task).
node(getWebEventTechnology,task).
node(engagementSponsorEmployeesInPromotingAwareness,softgoal).
node(putOnOrientationForVolunteers,task).
leaf(putOnOrientationForVolunteers).
node(writeDownCorporateSponsorsObjectives,task).
leaf(writeDownCorporateSponsorsObjectives).
node(timelyProvisionOfFreeServices,softgoal).
node(getDonorTechnology,task).
node(engageEmployeesInPromotingAwareness,softgoal).
node(corporatePartnerMarketingExpectationsBeKnown,goal).
topgoal(corporatePartnerMarketingExpectationsBeKnown).
node(sponsorLogo,resource).
node(developNationalEventCalendar,task).
leaf(developNationalEventCalendar).
node(demonstrableServices,softgoal).
node(periodicalCommunicationWithRegionalStaffBeMaintained,goal).
topgoal(periodicalCommunicationWithRegionalStaffBeMaintained).
node(provideFunds1,task).
node(attractEventParticipants,softgoal).
node(hearCSStories,softgoal).
node(manageAccounts,task).
leaf(manageAccounts).
node(counselorSpeakOnKidsIssuesInGeneral,task).
node(createLifeLongVolunteerSpirit,softgoal).
leaf(createLifeLongVolunteerSpirit).
node(communicateThroughInternetAndPhone,task).
leaf(communicateThroughInternetAndPhone).
node(sponsorRelationshipsBeManaged,goal).
topgoal(sponsorRelationshipsBeManaged).
node(provideFunds,task).
leaf(provideFunds).
node(frontEndForIncomeRecordingBeSupported,goal).
topgoal(frontEndForIncomeRecordingBeSupported).
node(minimizeCostOfEvents,softgoal).
node(pledgeNDuringEvent1,task).
node(corporatePartnerExpectationsBeSharedWithStaff,goal).
topgoal(corporatePartnerExpectationsBeSharedWithStaff).
node(subscribeToDocumentLibraryFolders1,task).
node(trustOfSponsorsTowardsCS,softgoal).
node(servicesBeProvidedForKidsBullyingLine,goal).
leaf(servicesBeProvidedForKidsBullyingLine).
topgoal(servicesBeProvidedForKidsBullyingLine).
node(marketOnlyForSeriousIssues,task).
leaf(marketOnlyForSeriousIssues).
node(retainSponsors,softgoal).
node(experiencedMarketingPartners2,softgoal).
leaf(experiencedMarketingPartners2).
node(trainCounselorsOnPublicSpeaking,task).
leaf(trainCounselorsOnPublicSpeaking).
node(demonstrableServices2,softgoal).
node(writeArticlesForMagazines1,task).
leaf(writeArticlesForMagazines1).
node(storeDonorInformationIntoDatabase,task).
leaf(storeDonorInformationIntoDatabase).
node(engagementStudentAmbassadorsInPromotingAwareness1,softgoal).
leaf(engagementStudentAmbassadorsInPromotingAwareness1).
node(qualityServices2,softgoal).
node(getFreeAdvertisement,task).
node(positiveReputationOfCS,softgoal).
leaf(positiveReputationOfCS).
node(marketThroughOwnChannels,task).
leaf(marketThroughOwnChannels).
node(upToDateInformationOnCorporateSponsors,softgoal).
node(positiveAssociationNByConsumers,softgoal).
node(attractSponsors2,softgoal).
node(getPhilanthropicDonations,task).
leaf(getPhilanthropicDonations).
node(useFreeServices,task).
node(positiveReputationOfCS2,softgoal).
node(inspiredStaff,softgoal).
node(donorInformationBeRecorded,goal).
topgoal(donorInformationBeRecorded).
node(increasedCorporateSponsorFunds,softgoal).
node(avoidOverMarketingServices1,softgoal).
node(participateInEvents,task).
leaf(participateInEvents).
edge(meetCorporateSponsorsNeeds,corporateSponsorsFeelIncluded,1).
edge(writeArticlesForWebsite,marketingBeMadeUsingDedicatedCounselor,1).
edge(increasedInteractionCounselorsWithMedia,proactiveMediaRelationship,0.5).
edge(implementStayInTouchProgram,staffBeSupported,1).
edge(goodProjectManagement,successfulMarketingCampaign,0.5).
edge(informSponsorsOfProgress,informationBeSharedWithSponsors,1).
edge(writeArticlesForMagazines1,writeArticlesForMagazines,1).
edge(createThankYouAds,recognizeNSponsorContribution2,0.5).
edge(saSpeakAtFundraisers,improveImageToKids,0.5).
edge(recognizeNSponsorContribution2,recognizeNSponsorContribution,1).
edge(getCorporatePartnerInformationFromDocumentLibrary1,corporatePartnerMarketingExpectationsBeKnown,1).
edge(counselorsWhoWantAPublicVoiceBeTrained,increasedInteractionCounselorsWithMedia,0.5).
edge(demonstrableServices1,demonstrableServices2,1).
edge(accountabilityOfServices,trustOfSponsorsTowardsCS,0.5).
edge(attractEventParticipants,engagementOfSponsorEmployeesInFundDevelopment,0.5).
edge(putTogetherProposalsForCorporateSponsors,managePAP,1).
edge(sponsorPartnerNcontacts2,getFreeAdvertisement,0.5).
edge(sponsorPartnerNcontacts1,increaseFreeServices,0.5).
edge(trustOfSponsorsTowardsCS2,retainSponsors1,0.5).
edge(createBrandedProducts,developExternalComunications,1).
edge(happinessStaff,happinessStaff3,1).
edge(useNationalEventCalendar,managePAP,1).
edge(highResponseIndividualDonors2,increasePhilanthropicDonations,0.5).
edge(useSponsorLogo,attractSponsors2,0.5).
edge(goodMediaExposure,attractSponsors2,0.5).
edge(provideDocumentLibrarySystem,subscribeToDocumentLibraryFolders2,1).
edge(singleCharitableRegistrationNumber,singleCharitableRegistrationNumberBeUsed,1).
edge(getFreeAdvertisement,marketPHLBrand,0.5).
edge(periodicalCommunicationWithRegionalStaffBeMaintained,regionalStaffFeelIncluded,0.5).
edge(agreementStaffOverCorporatePartnerExpectations,reduceInternalCommunicationConfusion,0.5).
edge(manageProjects,projectDeadlinesBeMet1,1).
edge(csNServices,demonstrableServices1,1).
edge(getDonorAccountingDatabase,putOnFundraisingEventsOnTheWeb,1).
edge(timelyProvisionOfFreeServices,manageProjects,1).
edge(developNationalEventCalendar,nationalEventCalendar,1).
edge(upToDateCorporatePartnerInformation2,upToDateInformationOnCorporateSponsors,1).
edge(highResponseIndividualDonors2,highResponseIndividualDonors1,1).
edge(presentProposalConvincinglyToSponsors,sponsorshipProposal,1).
edge(collectPledgeDuringEvent,putOnFundraisingEvents,1).
edge(createLifeLongVolunteerSpirit1,increaseVolunteers,0.5).
edge(increaseNAwareness,attractEventParticipants,0.5).
edge(companyRelationshipBeRetainedAfterMergers,retainSponsors1,0.5).
edge(sponsorsForEventsBeFound,increaseInvolvementSponsorsInPuttingOnEvents,1).
edge(putOnFundraisingEventsOnTheWeb,fundsBeRaised,1).
edge(attractSponsors,successfulEvents,0.5).
edge(upToDateCorporatePartnerInformation,retainSponsors1,0.5).
edge(marketPHLBrand,increaseAwareness,0.5).
edge(getPAPInformation,getCorporatePartnerInformationFromDocumentLibrary1,1).
edge(trustOfSponsorsTowardsCS,contributeToAGoodCause,0.5).
edge(recognition,reachMoreKidsSponsors,0.5).
edge(useVolunteerServices,provideFundraisingServices,1).
edge(engagementStudentAmbassadorsInPromotingAwareness1,engagementStudentAmbassadorsInPromotingAwareness,1).
edge(saGiveCSPresentations,improveImageToKids,0.5).
edge(demonstrableServices2,trustOfDonor,0.5).
edge(givePhilanthropicDonation,contributionBeMade,1).
edge(providePromotionalMaterialToStudentAmbassadors,promotionResources,1).
edge(marketThroughOwnChannels,useSponsorMarketingChannels,1).
edge(regionalStaffFeelIncluded1,happinessStaff,0.5).
edge(provideFunds,makeContributionToCharity,1).
edge(successfulMarketingCampaign,marketPHLBrand,0.5).
edge(informationBeSharedWithSponsors,manageNPartnerRelationship,1).
edge(engagementSponsorEmployeesInPromotingAwareness,marketCSBrand,0.5).
edge(retainSponsors2,retainSponsors,1).
edge(giveCSPresentations,saGiveCSPresentations,1).
edge(increaseAwareness,increaseAwareness1,1).
edge(workWithTheRegionsToImplementEvents,eventCoordination,1).
edge(pledgeNonline,pledgeOnline,1).
edge(eventsBeMarketed,attractEventParticipants,0.5).
edge(reachMoreKidsSponsors,sponsorshipBeBeneficial,0.5).
edge(freeServices,useFreeServices,1).
edge(timelyServices,timelyProvisionOfFreeServices,1).
edge(followHighestEthicalGuidelines,trustOfSponsorsTowardsCS,0.5).
edge(sponsorPartnerNcontacts2,attractSponsors2,0.5).
edge(sponsorPartnerNcontacts2,attractSponsors2,0.5).
edge(runFundraiserInSchools,saRunFundraiserInSchools,1).
edge(increaseInvolvementSponsorsInPuttingOnEvents,minimizeCostOfEvents,0.5).
edge(informationBeSharedWithSponsors,upToDateCorporatePartnerInformation,1).
edge(credibilityCSBrand2,trustOfDonor,0.5).
edge(experiencedMarketingPartners,marketPHLBrand,0.5).
edge(manageNprojects,projectDeadlinesBeMet,1).
edge(receiptBeProvided,trustOfDonor,0.5).
edge(provideDocumentLibrarySystem,subscribeToDocumentLibraryFolders1,1).
edge(uniteVolunteersAndSponsors,increaseVolunteers,0.5).
edge(credibilityCSBrand,trustOfSponsorsTowardsCS,0.5).
edge(pledgeNDuringEvent,attendFundraisingEvent,1).
edge(acquireNCSStories,publishedCSStories,1).
edge(regionalStaffFeelIncluded2,regionalStaffFeelIncluded1,1).
edge(increasedInvolvementCounselorsInEvents1,inspiredStaff,0.5).
edge(sponsorRelationshipsBeManaged,retainSponsors,0.5).
edge(marketFundraisingEvents,eventsBeMarketed,1).
edge(experiencedMarketingPartners2,experiencedMarketingPartners,1).
edge(createLifeLongVolunteerSpirit,createLifeLongVolunteerSpirit1,1).
edge(getPAPInformation1,getCorporatePartnerInformationFromDocumentLibrary,1).
edge(beInformedOfFundraisingEvents,contributeOnline,1).
edge(subscribeToDocumentLibraryFolders,providePAPToStaffNUsingTheDocumentLibrary,1).
edge(marketFundraisingEvents2,beInformedOfFundraisingEvents,1).
edge(increasedAvailabilityToSponsors,increasedAvailabilityCounselorsToPublicSponsors,1).
edge(attractEventParticipants,uniteVolunteersAndSponsors,0.5).
edge(exclusiveRelationshipsOfficialPartners1,exclusiveRelationshipsOfficialPartners,1).
edge(reachAgreement1,becomeAPatron,1).
edge(trustOfDonor,contributeToAGoodCause1,0.5).
edge(matchFundraisingTargets,matchFundraisingTargets2,1).
edge(upToDateInformationOnPrograms1,upToDateInformationOnPrograms,1).
edge(marketFundraisingEvents1,marketFundraisingEvents2,1).
edge(getPhilanthropicDonations,philanthropicDonations,1).
edge(increasedInvolvementCounselorsInEvents,increaseConnectionCounselorsAndCommunity,0.5).
edge(timelyProvisionOfFreeServices1,successfulEvents,0.5).
edge(qualityServices2,trustOfSponsorsTowardsCS,0.5).
edge(cobranding,reachMoreKidsSponsors,0.5).
edge(saSpeakAtFundraisers,marketFundraisingEvents1,0.5).
edge(maintain20CostsAgainstRevenuesRatio,putOnFundraisingEvents,1).
edge(recognizeNSponsorContribution,recognizeNSponsorContribution1,1).
edge(saSpeakAtFundraisers,increaseAwareness,0.5).
edge(engagementOfSponsorEmployeesInFundDevelopment,engageEmployeesInEvents,1).
edge(communicateThroughInternetAndPhone,upToDateInformationOnCorporateSponsors,0.5).
edge(frontEndForIncomeRecordingBeSupported,availabilityForAdministrationAndAccountingPurposesAcrossCS,0.5).
edge(periodicalCommunicationWithRegionalStaffBeMaintained,communicateWithHeadOffice,1).
edge(managePAP,manageNPartnerRelationship,1).
edge(corporateSponsorsFeelIncluded,retainSponsors1,0.5).
edge(recognition,appearAsGoodCorporateCitizens,0.5).
edge(recognition,appearAsGoodCorporateCitizens,0.5).
edge(provideFreeServices1,freeServices,1).
edge(getCorporateSponsorFunds,increasedCorporateSponsorFunds,0.5).
edge(involvementNotForProfitPartnersInEvents1,involvementNotForProfitPartnersInEvents,1).
edge(retainSponsors,matchFundraisingTargets,0.5).
edge(marketThroughOwnChannels,makeContributionToCharity,1).
edge(increasePhilanthropicDonations,matchFundraisingTargets,0.5).
edge(increaseConnectionCounselorsAndCommunity,highResponseIndividualDonors,0.5).
edge(elaborateFundraisingTargets,inspiredStaff,0.5).
edge(happinessStaff1,successfulMarketingCampaign,0.5).
edge(biWeeklyConferenceCalls,periodicalCommunicationWithRegionalStaffBeMaintained,1).
edge(marketOnlyForSeriousIssues,avoidOverMarketingServices,1).
edge(engageEmployeesInEvents,engageEmployeesInFundraisingEvents,1).
edge(sponsorRelationshipsBeManaged,increaseInvolvementSponsorsInPuttingOnEvents,0.5).
edge(counselorSpeakOnKidsIssuesInGeneral,marketingBeMadeUsingDedicatedCounselor,1).
edge(quickResponseToSponsors,quickResponseToSponsors1,1).
edge(useSponsorLogo,positiveReputationOfCS2,0.5).
edge(cobranding,positiveAssociationNByConsumers,0.5).
edge(getSponsorshipProposal,becomeAMajorPatron,1).
edge(responsibleUsageSponsorFunds1,responsibleUsageSponsorFunds,1).
edge(positiveReputationOfCS,positiveReputationOfCS2,1).
edge(manageReceivables,manageReceivables1,1).
edge(collectPledgeOnline,pledgesBeCollected,1).
edge(provideOnlineDonorTechnology,getDonorTechnology,1).
edge(collectPledgeDuringEvent,pledgesBeCollected,1).
edge(accountabilityOfServices2,trustOfDonor,0.5).
edge(positiveReputation,retainSponsors,0.5).
edge(donorInformationBeRecorded,availabilityForAdministrationAndAccountingPurposesAcrossCS,0.5).
edge(acquireFreeServices,minimizeExpenses,0.5).
edge(conflictsBeManaged,happinessStaff,0.5).
edge(getWebEventTechnology,putOnFundraisingEventsOnTheWeb,1).
edge(reallocateResources,manageNprojects,1).
edge(givePhilanthropicDonation,philanthropicDonations,1).
edge(manageNprojects,goodProjectManagement2,0.5).
edge(provideLogoToCS,cobranding,0.5).
edge(attractSponsors2,minimizeExpenses,0.5).
edge(singleCharitableRegistrationNumber1,positiveReputation,0.5).
edge(improveImageToKids,improveImageToKids1,1).
edge(pledgesBeCollected,matchFundraisingTargets,0.5).
edge(meetCorporateSponsorsNeeds,engagementSponsorsInTheCauseOfCS,0.5).
edge(createPostersFlyersAndInformationalMaterial,developExternalComunications,1).
edge(contributeToAGoodCause,recognition,0.5).
edge(exclusiveRelationshipsOfficialPartners2,meetCorporateSponsorsNeeds,0.5).
edge(sponsorsForEventsBeFound,putOnFundraisingEvents,1).
edge(makeContributionToCharity,becomeAPatron,1).
edge(beInformedOfFundraisingEvents,attendFundraisingEvent,1).
edge(engagementOfSponsorEmployeesInFundDevelopment,engagementOfSponsorEmployeesInFundDevelopment1,1).
edge(communicateThroughInternetAndPhone,periodicalCommunicationWithRegionalStaffBeMaintained,1).
edge(developNationalEventCalendar,putOnFundraisingEvents,1).
edge(engagementSponsorEmployeesInPromotingAwareness1,engagementSponsorEmployeesInPromotingAwareness,1).
edge(credibilityCSBrand1,credibilityCSBrand2,1).
edge(freeAdvertisement,getFreeAdvertisement,1).
edge(increaseInvolvementSponsorsInPuttingOnEvents,matchFundraisingTargets,0.5).
edge(followHighestEthicalGuidelines1,followHighestEthicalGuidelines2,1).
edge(successfulMarketingCampaign,positiveReputationOfCS2,0.5).
edge(presentationSkills,presentProposalConvincinglyToSponsors,0.5).
edge(increaseInvolvementSponsorsInPuttingOnEvents,uniteVolunteersAndSponsors,0.5).
edge(useFreeServices,maintain20CostsAgainstRevenuesRatio,1).
edge(involvementNotForProfitPartnersInEvents,positiveReputationOfCS2,0.5).
edge(demonstrableServices,trustOfSponsorsTowardsCS,0.5).
edge(proactiveMediaRelationship,marketFundraisingEvents1,0.5).
edge(getCorporateSponsorFunds,matchFundraisingTargets,0.5).
edge(timelyProvisionOfFreeServices1,manageNprojects,1).
edge(collectPledgeOnline3,collectPledgeOnline,1).
edge(reachAgreement,agreement,1).
edge(recordDonorInformation,donorInformationBeRecorded,1).
edge(qualityServices,qualityServices2,1).
edge(commitmentToCSCauseFromSponsorsEmployees,retainSponsors1,0.5).
edge(collectPledgeOnline2,collectPledgeOnline3,1).
edge(attractSponsors2,acquireFreeServices,0.5).
edge(speakAtFundraisers,saSpeakAtFundraisers,1).
edge(marketingFromGovernmentBeAcquired,minimizeExpenses,0.5).
edge(projectDeadlinesBeMet,successfulEvents,0.5).
edge(reachAgreement,getSponsorsForEvents,1).
edge(successfulMarketingCampaign,marketCSBrand,0.5).
edge(increaseInvolvementSponsorsInPuttingOnEvents,engagementOfSponsorEmployeesInFundDevelopment,0.5).
edge(storeDonorTransactionsIntoDatabase,recordDonorInformation,1).
edge(donorAccountingDatabase,getDonorAccountingDatabase,1).
edge(marketFundraisingEvents1,marketFundraisingEvents,1).
edge(putOnFundraisingEvents,fundsBeRaised,1).
edge(provideFreeServices1,acquireFreeServices,1).
edge(saRunFundraiserInSchools,fundsBeRaised,1).
edge(getDonorTechnology,putOnFundraisingEventsOnTheWeb,1).
edge(provideLogoToCS,sponsorLogo,1).
edge(collectDonationsOnline,putOnFundraisingWebEvents,1).
edge(increasedCorporateSponsorFunds,matchFundraisingTargets,0.5).
edge(provideDocumentLibrarySystem,subscribeToDocumentLibraryFolders,1).
edge(increaseVolunteers,successfulEvents,0.5).
edge(developExternalComunications,improveImageToKids,0.5).
edge(engageEmployeesInEvents2,positiveImageToEmployees,0.5).
edge(positiveImageToEmployees,sponsorshipBeBeneficial,0.5).
edge(cobranding,appearAsGoodCorporateCitizens,0.5).
edge(manageNPartnerRelationship1,sponsorRelationshipsBeManaged,1).
edge(getPhilanthropicDonations,matchFundraisingTargets,0.5).
edge(longTermFunding,longTermFunding1,1).
edge(participateInEvents,counselorsAttendFundraisingEvents,1).
edge(pitchToNationalCorporateSponsorsTheSponsorshipOfRegionalEvents,managePAP,1).
edge(attractSponsors1,attractSponsors,1).
edge(provincialGovernment,marketCSService,1).
edge(counselorSpeakOnKidsIssuesInGeneral1,counselorSpeakOnKidsIssuesInGeneral,1).
edge(getPhilanthropicDonations,increasePhilanthropicDonations,0.5).
edge(providePhilanthropicDonation,makeContributionToCharity,1).
edge(getSponsorsForEvents,sponsorsForEventsBeFound,1).
edge(increasedAvailabilityCounselorsToPublicSponsors,retainSponsors,0.5).
edge(increaseNAwareness,retainSponsors,0.5).
edge(sponsorsMarketingChannelsBeUsed,marketPHLBrand,0.5).
edge(reachAgreement,managePAP,1).
edge(developExternalComunications,marketFundraisingEvents1,0.5).
edge(regionalStaffFeelIncluded,regionalStaffFeelIncluded2,1).
edge(payFundDevelopmentAndMarketingStaff,happinessStaff,0.5).
edge(responsibleUsageSponsorFunds1,responsibleUsageSponsorFunds2,1).
edge(manageAccounts,manageAccounts1,1).
edge(recognition,positiveAssociationNByConsumers,0.5).
edge(projectManagementSkills,goodProjectManagement,1).
edge(happinessStaff3,inspiredStaff,0.5).
edge(followHighestEthicalGuidelines1,followHighestEthicalGuidelines,1).
edge(accountabilityOfServices1,accountabilityOfServices,1).
edge(providePromotionalMaterialToStudentAmbassadors,developExternalComunications,1).
edge(collectDonorInformation,recordDonorInformation,1).
edge(increasedAvailabilityCounselorsToPublicSponsors,attractSponsors,0.5).
edge(increaseInvolvementSponsorsInPuttingOnEvents,successfulEvents,0.5).
edge(periodicalCommunicationWithRegionalStaffBeMaintained,agreementStaffOverCorporatePartnerExpectations,0.5).
edge(writeDownCorporateSponsorsObjectives,managePAP,1).
edge(contributeToACause,recognition,0.5).
edge(experiencedMarketingPartners,marketCSBrand,0.5).
edge(uniteVolunteersAndSponsors,successfulEvents,0.5).
edge(credibilityCSBrand,positiveAssociationNByConsumers,0.5).
edge(subscribeToDocumentLibraryFolders2,getCorporatePartnerInformationFromDocumentLibrary,1).
edge(retainSponsors,longTermFunding,0.5).
edge(contributeOnline,contributionBeMade,1).
edge(attractEventParticipants,successfulEvents,0.5).
edge(engagementOfSponsorEmployeesInFundDevelopment,successfulEvents,0.5).
edge(upToDateInformationOnPrograms,corporateSponsorFeelIncluded,0.5).
edge(involveNotForProfitPartnersInEvents,successfulEvents,0.5).
edge(trackBudgets,manageNprojects,1).
edge(providePAPToStaffNUsingTheDocumentLibrary,corporatePartnerExpectationsBeSharedWithStaff,1).
edge(increasedInvolvementCounselorsInEvents1,highResponseIndividualDonors2,0.5).
edge(acquireGovernmentFunding,matchFundraisingTargets,0.5).
edge(collectPledgeOnline,putOnFundraisingEventsOnTheWeb,1).
edge(answersBeProvidedToMediaQueries,goodMediaExposure,0.5).
edge(storeDonorTransactionsIntoDatabase,frontEndForIncomeRecordingBeSupported,1).
edge(useVolunteerServices,maintain20CostsAgainstRevenuesRatio,1).
edge(provideFunds1,getCorporateSponsorFunds,1).
edge(marketingBeMadeUsingDedicatedCounselor,proactiveMediaRelationship,0.5).
edge(corporatePartnerExpectationsBeSharedWithStaff,meetCorporateSponsorsNeeds,0.5).
edge(attractSponsors,increasedCorporateSponsorFunds,0.5).
edge(servicesBeProvidedForKidsBullyingLine,provincialGovernment,1).
edge(recognizeNSponsorContribution,recognition,1).
edge(increasedInvolvementCounselorsInEvents1,increasedAvailabilityCounselorsToPublicSponsors,0.5).
edge(sponsorsMarketingChannelsBeUsed,minimizeExpenses,0.5).
edge(experiencedMarketingPartners,successfulMarketingCampaign,0.5).
edge(maintain20CostsAgainstRevenuesRatio,putOnFundraisingEventsOnTheWeb,1).
edge(nationalMarketingStrategy,manageProjects,1).
edge(credibilityCSBrand1,credibilityCSBrand,1).
edge(reachAgreement1,becomeAOfficialPartner,1).
edge(getCorporatePartnerInformationFromDL1,getCorporatePartnerInformationFromDL,1).
edge(sponsorLogo,useSponsorLogo,1).
edge(sponsorPartnerNcontacts,providePartnerContactsToCS,1).
edge(writeArticlesForWebsite1,writeArticlesForWebsite,1).
edge(pledgeNonline,contributeOnline,1).
edge(becomeAMajorPatron,contributeToACause,1).
edge(getDonorDatabase,getDonorAccountingDatabase,1).
edge(eventsBeMarketed,putOnFundraisingEvents,1).
edge(bringRegionalFundraisingStaffTogetherOnceAYear,periodicalCommunicationWithRegionalStaffBeMaintained,1).
edge(becomeAOfficialPartner,exclusiveRelationshipsOfficialPartners,1).
edge(increaseInvolvementSponsorsInPuttingOnEvents,increasedCorporateSponsorFunds,0.5).
edge(makeContributionToCharity,becomeAOfficialPartner,1).
edge(reallocateResources1,manageProjects,1).
edge(trainCounselorsOnPublicSpeaking,counselorsWhoWantAPublicVoiceBeTrained,1).
edge(demonstrableServices1,demonstrableServices,1).
edge(positiveInternalOpinion,happinessStaff,0.5).
edge(engagementSponsorEmployeesInPromotingAwareness2,engageEmployeesInPromotingAwareness,1).
edge(contributeToAGoodCause,positiveAssociationNByConsumers,0.5).
edge(workWithTheRegionsToImplementEvents,regionalStaffFeelIncluded,0.5).
edge(exclusiveBrandAndLogoUse,grantExclusiveUseOfBrandAndLogo,1).
edge(proactiveMediaRelationship,goodMediaExposure,0.5).
edge(counselorSpeakOnKidsIssuesInGeneral,increasedInvolvementCounselorsInEvents,0.5).
edge(manageProjects,goodProjectManagement,0.5).
edge(sponsorsMarketingChannelsBeUsed,marketCSBrand,0.5).
edge(contributeToAGoodCause,positiveImageToEmployees,0.5).
edge(reachAgreement1,becomeAMajorPatron,1).
edge(fundsBeRaised,successfulEvents,0.5).
edge(provideRealTimeTaxReceipts,provideReceipts,1).
edge(provideMoneyForServices,acquireGovernmentFunding,1).
edge(positiveInternalOpinion1,positiveInternalOpinion,1).
edge(putOnOrientationProcessForFundDevelopmentAndMarketingStaff,staffBeSupported,1).
edge(positiveReputationOfCS2,marketPHLBrand,0.5).
edge(projectDeadlinesBeMet1,successfulMarketingCampaign,0.5).
edge(successfulMarketingCampaign,attractSponsors2,0.5).
edge(createGeneralLedgers,createGeneralLedgers1,1).
edge(counselorSpeakOnKidsIssuesInGeneral,increasedInteractionCounselorsWithMedia,0.5).
edge(corporatePartnerFundraisingExpectationsBeKnown,retainSponsors,0.5).
edge(successfulEvents,retainSponsors,0.5).
edge(attractSponsors2,attractSponsors1,1).
edge(storeDonorInformationIntoDatabase,recordDonorInformation,1).
edge(fundsBeRaised,matchFundraisingTargets,0.5).
edge(sponsorsIncludeCSLogosAndDescriptionsOnTheirProducts,sponsorsMarketingChannelsBeUsed,1).
edge(attendFundraisingEvent,contributionBeMade,1).
edge(manageReceivables,frontEndForIncomeRecordingBeSupported,1).
edge(qualityServices,qualityServices1,1).
edge(quickResponseToSponsors,meetCorporateSponsorsNeeds,0.5).
edge(sharePAPInDocumentLibrary1,getPAPInformation,1).
edge(presentProposalConvincinglyToSponsors,managePAP,1).
edge(hearCSStories,trustOfDonor,0.5).
edge(recognizeNSponsorContribution1,meetCorporateSponsorsNeeds,0.5).
edge(receiptBeProvided,contributeOnline,1).
edge(trainCounselorsOnPublicSpeaking,acquirePublicSpeakingSkills,1).
edge(increaseVolunteers1,increaseVolunteers,1).
edge(provideRealTimeTaxReceipts,collectDonationsOnline,1).
edge(pledgeNDuringEvent1,collectPledgeDuringEvent,1).
edge(getDonorDatabase,recordDonorInformation,1).
edge(becomeAOfficialPartner,contributeToACause,1).
edge(positiveReputation,attractEventParticipants,0.5).
edge(goodMediaExposure,increaseAwareness,0.5).
edge(engageEmployeesInFundraisingEvents,commitmentToCSCauseFromSponsorsEmployees,0.5).
edge(manageAccounts,frontEndForIncomeRecordingBeSupported,1).
edge(manageNPartnerRelationship,companyRelationshipBeRetainedAfterMergers,1).
edge(provideFreeServices,freeServices,1).
edge(engageEmployeesInPromotingAwareness,commitmentToCSCauseFromSponsorsEmployees,0.5).
edge(writeArticlesForMagazines,marketingBeMadeUsingDedicatedCounselor,1).
edge(responsibleUsageSponsorFunds,trustOfSponsorsTowardsCS,0.5).
edge(csStories,acquireNCSStories,1).
edge(engagementSponsorEmployeesInPromotingAwareness,engagementSponsorEmployeesInPromotingAwareness2,1).
edge(emailCorporatePartnersInterestingAndRelevantNewsPieces,informationBeSharedWithSponsors,1).
edge(marketCSService,marketingFromGovernmentBeAcquired,1).
edge(increaseAwareness2,increaseNAwareness,1).
edge(provideFreeServices,makeContributionToCharity,1).
edge(trustOfSponsorsTowardsCS1,trustOfSponsorsTowardsCS2,1).
edge(projectManagementSkills,goodProjectManagement2,1).
edge(maintain20CostsAgainstRevenuesRatio,minimizeCostOfEvents,0.5).
edge(positiveReputationOfCS2,marketCSBrand,0.5).
edge(createGeneralLedgers,frontEndForIncomeRecordingBeSupported,1).
edge(notForProfitPartnersBeInvolvedInEvents,involveNotForProfitPartnersInEvents,1).
edge(quickResponseToQuestionsAndConcerns,corporateSponsorFeelIncluded,0.5).
edge(collectPledgeOnline2,collectDonationsOnline,1).
edge(agreement,reachAgreement1,1).
edge(appearAsGoodCorporateCitizens,sponsorshipBeBeneficial,0.5).
edge(getCorporatePartnerInformationFromDocumentLibrary,corporatePartnerFundraisingExpectationsBeKnown,1).
edge(grantExclusiveUseOfBrandAndLogo,recognizeNSponsorContribution2,0.5).
edge(provideReceipts,receiptBeProvided,1).
edge(getWebEventTechnology1,getWebEventTechnology,1).
edge(getWebTechnology,putOnFundraisingWebEvents,1).
edge(increaseFreeServices,minimizeCostOfEvents,0.5).
edge(sponsorPartnerNcontacts1,sponsorPartnerNcontacts,1).
edge(eventsBeMarketed,putOnFundraisingEventsOnTheWeb,1).
edge(sponsorshipProposal,getSponsorshipProposal,1).
edge(developExternalComunications,successfulMarketingCampaign,0.5).
edge(putOnOrientationForVolunteers,staffBeSupported,1).
edge(subscribeToDocumentLibraryFolders1,getCorporatePartnerInformationFromDocumentLibrary1,1).
edge(positiveReputationOfCS,positiveReputation,1).
edge(getSponsorshipProposal,becomeAPatron,1).
edge(exclusiveBrandAndLogoUse,cobranding,1).
edge(biWeeklyConferenceCalls,upToDateInformationOnCorporateSponsors,0.5).
edge(sponsorPartnerNcontacts1,attractSponsors,0.5).
edge(saGiveCSPresentations,increaseAwareness,0.5).
edge(organizeDiscussionsWithSponsors,managePAP,1).
edge(singleCharitableRegistrationNumber1,singleCharitableRegistrationNumber,1).
edge(getCorporatePartnerInformationFromDL,agreementStaffOverCorporatePartnerExpectations,0.5).
edge(responsibleUsageSponsorFunds2,trustOfDonor,0.5).
edge(getSponsorshipProposal,becomeAOfficialPartner,1).
edge(getFreeAdvertisement,minimizeExpenses,0.5).
edge(fundsBeRaised,funds,1).
edge(projectDeadlinesBeMet1,marketFundraisingEvents1,0.5).
edge(happinessStaff3,successfulEvents,0.5).
edge(nationalEventCalendar,useNationalEventCalendar,1).
edge(happinessStaff,happinessStaff2,1).
edge(happinessStaff2,happinessStaff1,1).
edge(upToDateCorporatePartnerInformation,upToDateInformationOnPrograms1,1).
edge(successfulMarketingCampaign,improveImageToKids,0.5).
edge(accountabilityOfServices1,accountabilityOfServices2,1).
edge(sendRecognitionLetters,recognizeNSponsorContribution2,0.5).
edge(highResponseIndividualDonors,highResponseIndividualDonors1,1).
edge(provideCompiledCallData,provideCompiledCallDataToMedia,1).
edge(becomeAPatron,contributeToACause,1).
edge(sharePAPInDocumentLibrary1,getPAPInformation1,1).
edge(elaborateFundraisingTargets1,elaborateFundraisingTargets,1).
edge(pledgeOnline,collectPledgeOnline2,1).
edge(makeContributionToCharity,becomeAMajorPatron,1).
edge(developExternalComunications,minimizeExpenses,-0.5).
edge(followHighestEthicalGuidelines2,trustOfDonor,0.5).
edge(providePhilanthropicDonation,philanthropicDonations,1).
edge(getWebEventTechnology,getWebTechnology,1).
edge(becomeAOfficialPartner,cobranding,1).
edge(presentationSkills1,presentationSkills,1).
edge(informationBeSharedWithSponsors,corporateSponsorsFeelIncluded,0.5).
edge(trustOfSponsorsTowardsCS,trustOfSponsorsTowardsCS1,1).
edge(publishedCSStories,hearCSStories,1).
edge(provideFunds,provideFunds1,1).
edge(engagementOfSponsorEmployeesInFundDevelopment,engageEmployeesInEvents1,1).
edge(pledgeNDuringEvent,pledgeNDuringEvent1,1).
edge(exclusiveRelationshipsOfficialPartners2,exclusiveRelationshipsOfficialPartners1,1).
edge(staffBeSupported,happinessStaff,0.5).
edge(avoidOverMarketingServices,avoidOverMarketingServices1,1).
edge(sharePAPInDocumentLibrary,providePAPToStaffNUsingTheDocumentLibrary,1).
edge(counselorsAttendFundraisingEvents,increasedInvolvementCounselorsInEvents1,0.5).
edge(manageNPartnerRelationship,manageNPartnerRelationship1,1).
edge(sponsorPartnerNcontacts2,acquireFreeServices,0.5).
edge(engageEmployeesInEvents2,engageEmployeesInEvents1,1).
edge(corporatePartnerMarketingExpectationsBeKnown,successfulMarketingCampaign,0.5).
edge(quickResponseToSponsors1,quickResponseToQuestionsAndConcerns,1).
edge(goodProjectManagement2,successfulEvents,0.5).
edge(commitmentToCSCauseFromSponsorsEmployees,engagementSponsorsInTheCauseOfCS,0.5).
