% CSITDepartment  (edit me: node/2 edge/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, leaf/1, topgoal/1.
node(easilyAccessableTechnologyInstructions1,softgoal).
leaf(easilyAccessableTechnologyInstructions1).
node(properlyAndSuitablyEquippedInITToAccomplishCSNeeds1,softgoal).
node(freeUpgrades,resource).
leaf(freeUpgrades).
node(provideOnlineDonorTechnology,task).
node(increaseAccessSpeedRegionalOfficesToDL,softgoal).
node(putContentOntoWebsite1,task).
leaf(putContentOntoWebsite1).
node(improveQualityAssuranceTechnology,softgoal).
node(hardwareBeAcquiredForFree,task).
node(useVPN,task).
leaf(useVPN).
node(sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,softgoal).
node(callsBeRecordedIntoADataBase1,goal).
leaf(callsBeRecordedIntoADataBase1).
topgoal(callsBeRecordedIntoADataBase1).
node(implementMaintainComputerSystemsForEmployeeUse,task).
node(itTrainingSupportBeGivenToEmployees,goal).
topgoal(itTrainingSupportBeGivenToEmployees).
node(itResources,resource).
leaf(itResources).
node(properlyAndSuitablyEquippedInITToAccomplishServiceGoals,softgoal).
node(oracle,resource).
leaf(oracle).
node(decreaseClumsinessTechnology,softgoal).
node(useOracleForDataBase,task).
node(provideDocumentLibrarySystem1,task).
node(costEffectiveTechnology,softgoal).
node(manageAndImplementWebSite,task).
node(provideCompiledCallData,task).
node(payForUpgrades,task).
node(callCenterServerAndSchedulingSystemBeIntegrated,goal).
leaf(callCenterServerAndSchedulingSystemBeIntegrated).
topgoal(callCenterServerAndSchedulingSystemBeIntegrated).
node(improveCallRecordingEquipment1,softgoal).
leaf(improveCallRecordingEquipment1).
node(fitBetweenSystemCapabilitiesAndCSRequirements,softgoal).
node(properlyAndSuitablyEquippedInITToAccomplishCSNeeds,softgoal).
node(integrateITSystems,goal).
topgoal(integrateITSystems).
node(feedbackFormSoftware,resource).
node(performanceReviewInformationBeCollectedInDataBase,goal).
topgoal(performanceReviewInformationBeCollectedInDataBase).
node(csBeNotForProfit,goal).
leaf(csBeNotForProfit).
topgoal(csBeNotForProfit).
node(webServer,resource).
node(acquireUpgradesForFree,task).
node(increaseITTrainingForCounsellors1,softgoal).
node(implementBulletinBoard1,task).
node(anITTrainerBePresent1,goal).
leaf(anITTrainerBePresent1).
topgoal(anITTrainerBePresent1).
node(costEffectiveTraining,softgoal).
node(itProvidersHaveKnowledgeOfFundraisingAndMarketing,goal).
leaf(itProvidersHaveKnowledgeOfFundraisingAndMarketing).
topgoal(itProvidersHaveKnowledgeOfFundraisingAndMarketing).
node(freeWebServer,resource).
leaf(freeWebServer).
node(easilyAccessableTechnologyInstructions,softgoal).
node(hardwareBeAcquired,goal).
topgoal(hardwareBeAcquired).
node(implementPhoneFeedback,task).
node(implementCategorizationTool,task).
node(anITTrainerBePresent,goal).
topgoal(anITTrainerBePresent).
node(feedbackFormBeImplemented,task).
node(implementPhoneFeedback1,task).
leaf(implementPhoneFeedback1).
node(supportAnalysisCounsellorsTime1,softgoal).
node(implementCategorizationTool1,task).
node(provideTechnologyToCreateAndSendDocuments,task).
leaf(provideTechnologyToCreateAndSendDocuments).
node(networkPCs,task).
leaf(networkPCs).
node(getWebEventTechnology1,task).
node(freeSoftware,resource).
leaf(freeSoftware).
node(simpleTechnology1,softgoal).
node(increaseITMethodsToAcquireFeedback,softgoal).
node(payForSoftware,task).
node(implementDirectorEnterpriseThroughBluePumpkin,task).
node(telephonyBeImplementedAndManaged1,goal).
topgoal(telephonyBeImplementedAndManaged1).
node(implementActivityManager,task).
node(adequatelyCustomizableCSTechnology,softgoal).
leaf(adequatelyCustomizableCSTechnology).
node(implementIVR,task).
node(simpleTechnology,softgoal).
node(useCurrentMethod,task).
leaf(useCurrentMethod).
node(properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,softgoal).
node(improveQualityAssuranceTechnology1,softgoal).
node(putContentOntoWebsite,task).
node(increasedEmphasisOnITInHiringProcessOfCounsellors,softgoal).
leaf(increasedEmphasisOnITInHiringProcessOfCounsellors).
node(increaseAccessSpeedRegionalOfficesToDL1,softgoal).
node(implementEmailForCounsellors,task).
leaf(implementEmailForCounsellors).
node(keepUpWithNewTechnology,softgoal).
node(acquireITResources,task).
node(useT1,task).
leaf(useT1).
node(effectiveITTraining,softgoal).
node(installDesktopSoftware,task).
node(decreaseClumsinessTechnology1,softgoal).
leaf(decreaseClumsinessTechnology1).
node(useInformalBuddySystemForTraining,task).
leaf(useInformalBuddySystemForTraining).
node(acquireSoftwareForFree,task).
node(aTrainingComputerBePresent1,goal).
leaf(aTrainingComputerBePresent1).
topgoal(aTrainingComputerBePresent1).
node(adjustToSoftwareChanges,softgoal).
node(freeHardware,resource).
leaf(freeHardware).
node(implementAndManageTechnologyInRegionalOffices,task).
node(acquireAndImplementEmployeeSoftware,task).
node(considerationOfFeedbackITProviders,softgoal).
node(donorAccountingDataBase,resource).
node(increaseITResources1,softgoal).
leaf(increaseITResources1).
node(implementDesktops,task).
node(telephonyBeImplementedAndManaged,task).
node(implementSymposiumSystem,task).
node(software,resource).
leaf(software).
node(payForHardware,task).
node(provideDocumentLibrarySystem,task).
node(manageDonorAccountingDataBase,task).
node(webServer1,resource).
leaf(webServer1).
node(implementEmailForCounsellors1,task).
node(itProvidersHaveKnowledgeOfCounselling,goal).
leaf(itProvidersHaveKnowledgeOfCounselling).
topgoal(itProvidersHaveKnowledgeOfCounselling).
node(performanceReviewInformationBeCollectedInDataBase1,goal).
leaf(performanceReviewInformationBeCollectedInDataBase1).
topgoal(performanceReviewInformationBeCollectedInDataBase1).
node(itSystemsBeIntegrated,goal).
topgoal(itSystemsBeIntegrated).
node(expandITDepartment,softgoal).
node(acquireSoftware,goal).
topgoal(acquireSoftware).
node(webServerBeAcquired,goal).
topgoal(webServerBeAcquired).
node(csBeNotForProfit1,goal).
leaf(csBeNotForProfit1).
topgoal(csBeNotForProfit1).
node(increasedEmphasisOnITInHiringProcessOfCounsellors1,softgoal).
node(webSoftware,resource).
node(webCounsellingSoftwareBeImplemented,task).
node(increaseITResources,softgoal).
node(acquireWebServerForFree,task).
node(improveCallRecordingEquipment,softgoal).
node(hardware,resource).
leaf(hardware).
node(upgrades,resource).
leaf(upgrades).
node(callsBeRecordedIntoADataBase,goal).
topgoal(callsBeRecordedIntoADataBase).
node(getWebEventTechnology,task).
node(implementBulletinBoard,task).
node(itBeUpgraded,goal).
topgoal(itBeUpgraded).
node(satisfyCSITNeeds,task).
node(performDonorAccountingDataBaseMaintenance,task).
leaf(performDonorAccountingDataBaseMaintenance).
node(acquireTelephoneSwitch,task).
node(considerationOfFeedbackFromCounsellors,softgoal).
leaf(considerationOfFeedbackFromCounsellors).
node(increaseITTrainingForCounsellors,softgoal).
node(payForWebServer,task).
node(supportAnalysisCounsellorsTime,softgoal).
node(provideOnlineDonorTechnology1,task).
leaf(provideOnlineDonorTechnology1).
node(itDeptProvidesOrientationAndTraining,task).
node(webSoftwareBeAcquired,goal).
topgoal(webSoftwareBeAcquired).
node(aTrainingComputerBePresent,goal).
topgoal(aTrainingComputerBePresent).
node(increaseITTrainingResources,softgoal).
node(providePeerToPeerAccessRegionalOffices,goal).
topgoal(providePeerToPeerAccessRegionalOffices).
node(increaseITMethodsToAcquireFeedback1,softgoal).
edge(properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(implementEmailForCounsellors,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(installDesktopSoftware,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(acquireAndImplementEmployeeSoftware,implementMaintainComputerSystemsForEmployeeUse,1).
edge(acquireSoftware,implementBulletinBoard,1).
edge(integrateITSystems,itSystemsBeIntegrated,1).
edge(manageAndImplementWebSite,satisfyCSITNeeds,1).
edge(effectiveITTraining,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(hardwareBeAcquiredForFree,costEffectiveTechnology,0.5).
edge(freeHardware,hardwareBeAcquiredForFree,1).
edge(hardwareBeAcquired,acquireTelephoneSwitch,1).
edge(increaseITMethodsToAcquireFeedback1,improveQualityAssuranceTechnology1,0.5).
edge(performanceReviewInformationBeCollectedInDataBase1,improveQualityAssuranceTechnology1,0.5).
edge(feedbackFormBeImplemented,feedbackFormSoftware,1).
edge(telephonyBeImplementedAndManaged,satisfyCSITNeeds,1).
edge(improveQualityAssuranceTechnology1,improveQualityAssuranceTechnology,1).
edge(acquireSoftware,implementActivityManager,1).
edge(acquireITResources,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(acquireSoftware,implementDirectorEnterpriseThroughBluePumpkin,1).
edge(webServer1,payForWebServer,1).
edge(implementDirectorEnterpriseThroughBluePumpkin,supportAnalysisCounsellorsTime1,0.5).
edge(acquireSoftwareForFree,costEffectiveTechnology,0.5).
edge(acquireSoftware,provideDocumentLibrarySystem1,1).
edge(implementDirectorEnterpriseThroughBluePumpkin,acquireAndImplementEmployeeSoftware,1).
edge(anITTrainerBePresent1,itDeptProvidesOrientationAndTraining,1).
edge(acquireSoftware,implementSymposiumSystem,1).
edge(implementMaintainComputerSystemsForEmployeeUse,satisfyCSITNeeds,1).
edge(anITTrainerBePresent1,anITTrainerBePresent,1).
edge(implementEmailForCounsellors,implementEmailForCounsellors1,1).
edge(payForSoftware,webSoftwareBeAcquired,1).
edge(hardwareBeAcquiredForFree,hardwareBeAcquired,1).
edge(useVPN,implementAndManageTechnologyInRegionalOffices,1).
edge(aTrainingComputerBePresent1,costEffectiveTraining,-0.5).
edge(useInformalBuddySystemForTraining,costEffectiveTraining,0.5).
edge(itResources,acquireITResources,1).
edge(freeWebServer,acquireWebServerForFree,1).
edge(putContentOntoWebsite1,putContentOntoWebsite,1).
edge(increaseITTrainingResources,increaseITTrainingForCounsellors1,0.5).
edge(adequatelyCustomizableCSTechnology,fitBetweenSystemCapabilitiesAndCSRequirements,0.5).
edge(hardware,payForHardware,1).
edge(increaseITResources,keepUpWithNewTechnology,0.5).
edge(acquireSoftware,implementIVR,1).
edge(payForHardware,costEffectiveTechnology,-0.5).
edge(itProvidersHaveKnowledgeOfCounselling,sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,0.5).
edge(manageDonorAccountingDataBase,satisfyCSITNeeds,1).
edge(itProvidersHaveKnowledgeOfFundraisingAndMarketing,sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,0.5).
edge(performDonorAccountingDataBaseMaintenance,manageDonorAccountingDataBase,1).
edge(anITTrainerBePresent1,costEffectiveTraining,-0.5).
edge(implementCategorizationTool,implementCategorizationTool1,1).
edge(performanceReviewInformationBeCollectedInDataBase1,performanceReviewInformationBeCollectedInDataBase,1).
edge(properlyAndSuitablyEquippedInITToAccomplishCSNeeds,properlyAndSuitablyEquippedInITToAccomplishCSNeeds1,1).
edge(provideDocumentLibrarySystem1,properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,0.5).
edge(increaseAccessSpeedRegionalOfficesToDL1,increaseAccessSpeedRegionalOfficesToDL,1).
edge(webCounsellingSoftwareBeImplemented,manageAndImplementWebSite,1).
edge(fitBetweenSystemCapabilitiesAndCSRequirements,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(itTrainingSupportBeGivenToEmployees,satisfyCSITNeeds,1).
edge(expandITDepartment,increaseITTrainingResources,0.5).
edge(increasedEmphasisOnITInHiringProcessOfCounsellors1,effectiveITTraining,0.5).
edge(itDeptProvidesOrientationAndTraining,itTrainingSupportBeGivenToEmployees,1).
edge(itBeUpgraded,keepUpWithNewTechnology,0.5).
edge(adjustToSoftwareChanges,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(provideOnlineDonorTechnology1,manageAndImplementWebSite,1).
edge(payForUpgrades,itBeUpgraded,1).
edge(implementActivityManager,acquireAndImplementEmployeeSoftware,1).
edge(implementEmailForCounsellors,acquireAndImplementEmployeeSoftware,1).
edge(implementDirectorEnterpriseThroughBluePumpkin,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,-0.5).
edge(implementIVR,telephonyBeImplementedAndManaged,1).
edge(implementCategorizationTool,acquireAndImplementEmployeeSoftware,1).
edge(useT1,increaseAccessSpeedRegionalOfficesToDL1,1).
edge(aTrainingComputerBePresent1,aTrainingComputerBePresent,1).
edge(properlyAndSuitablyEquippedInITToAccomplishServiceGoals,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(aTrainingComputerBePresent1,effectiveITTraining,0.5).
edge(increasedEmphasisOnITInHiringProcessOfCounsellors,increasedEmphasisOnITInHiringProcessOfCounsellors1,1).
edge(itBeUpgraded,adjustToSoftwareChanges,-0.5).
edge(getWebEventTechnology,manageAndImplementWebSite,1).
edge(callsBeRecordedIntoADataBase1,callsBeRecordedIntoADataBase,1).
edge(useInformalBuddySystemForTraining,itTrainingSupportBeGivenToEmployees,1).
edge(acquireSoftware,getWebEventTechnology,1).
edge(useT1,costEffectiveTechnology,-0.5).
edge(implementAndManageTechnologyInRegionalOffices,implementMaintainComputerSystemsForEmployeeUse,1).
edge(acquireWebServerForFree,webServerBeAcquired,1).
edge(upgrades,payForUpgrades,1).
edge(manageDonorAccountingDataBase,donorAccountingDataBase,1).
edge(telephonyBeImplementedAndManaged,telephonyBeImplementedAndManaged1,1).
edge(implementActivityManager,supportAnalysisCounsellorsTime1,0.5).
edge(itDeptProvidesOrientationAndTraining,effectiveITTraining,0.5).
edge(software,payForSoftware,1).
edge(callsBeRecordedIntoADataBase1,improveQualityAssuranceTechnology1,0.5).
edge(improveCallRecordingEquipment1,improveCallRecordingEquipment,1).
edge(aTrainingComputerBePresent1,increaseITTrainingForCounsellors1,0.5).
edge(implementBulletinBoard,implementBulletinBoard1,1).
edge(freeSoftware,acquireSoftwareForFree,1).
edge(acquireSoftware,installDesktopSoftware,1).
edge(hardwareBeAcquired,implementMaintainComputerSystemsForEmployeeUse,1).
edge(costEffectiveTraining,increaseITResources,0.5).
edge(itBeUpgraded,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(acquireTelephoneSwitch,telephonyBeImplementedAndManaged,1).
edge(manageDonorAccountingDataBase,properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,0.5).
edge(networkPCs,implementMaintainComputerSystemsForEmployeeUse,1).
edge(putContentOntoWebsite1,manageAndImplementWebSite,1).
edge(provideTechnologyToCreateAndSendDocuments,implementMaintainComputerSystemsForEmployeeUse,1).
edge(supportAnalysisCounsellorsTime1,supportAnalysisCounsellorsTime,1).
edge(useCurrentMethod,providePeerToPeerAccessRegionalOffices,1).
edge(implementBulletinBoard,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(implementBulletinBoard,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,-0.5).
edge(anITTrainerBePresent1,increaseITTrainingForCounsellors1,0.5).
edge(implementActivityManager,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(implementActivityManager,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,-0.5).
edge(implementCategorizationTool,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(webSoftwareBeAcquired,webSoftware,1).
edge(integrateITSystems,simpleTechnology1,0.5).
edge(improveCallRecordingEquipment1,improveQualityAssuranceTechnology1,0.5).
edge(installDesktopSoftware,acquireAndImplementEmployeeSoftware,1).
edge(acquireSoftwareForFree,webSoftwareBeAcquired,1).
edge(simpleTechnology1,simpleTechnology,1).
edge(acquireSoftwareForFree,acquireSoftware,1).
edge(increaseITResources,expandITDepartment,1).
edge(implementPhoneFeedback1,implementPhoneFeedback,1).
edge(provideDocumentLibrarySystem1,acquireAndImplementEmployeeSoftware,1).
edge(webServerBeAcquired,webServer,1).
edge(providePeerToPeerAccessRegionalOffices,implementAndManageTechnologyInRegionalOffices,1).
edge(oracle,useOracleForDataBase,1).
edge(freeUpgrades,acquireUpgradesForFree,1).
edge(payForHardware,hardwareBeAcquired,1).
edge(increaseITTrainingResources,effectiveITTraining,0.5).
edge(decreaseClumsinessTechnology1,decreaseClumsinessTechnology,1).
edge(payForSoftware,costEffectiveTechnology,-0.5).
edge(csBeNotForProfit,keepUpWithNewTechnology,-0.5).
edge(installDesktopSoftware,implementDesktops,1).
edge(acquireSoftware,feedbackFormBeImplemented,1).
edge(implementSymposiumSystem,telephonyBeImplementedAndManaged,1).
edge(provideOnlineDonorTechnology1,provideOnlineDonorTechnology,1).
edge(useCurrentMethod,costEffectiveTechnology,0.5).
edge(feedbackFormBeImplemented,increaseITMethodsToAcquireFeedback1,0.5).
edge(implementDesktops,implementMaintainComputerSystemsForEmployeeUse,1).
edge(useOracleForDataBase,manageDonorAccountingDataBase,1).
edge(increaseITResources,increaseITTrainingResources,0.5).
edge(considerationOfFeedbackFromCounsellors,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(payForWebServer,webServerBeAcquired,1).
edge(acquireSoftware,implementCategorizationTool,1).
edge(increaseITTrainingForCounsellors1,increaseITTrainingForCounsellors,1).
edge(callCenterServerAndSchedulingSystemBeIntegrated,integrateITSystems,1).
edge(implementCategorizationTool,provideCompiledCallData,1).
edge(easilyAccessableTechnologyInstructions1,easilyAccessableTechnologyInstructions,1).
edge(implementPhoneFeedback1,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(provideDocumentLibrarySystem1,provideDocumentLibrarySystem,1).
edge(costEffectiveTechnology,increaseITTrainingResources,0.5).
edge(useOracleForDataBase,costEffectiveTechnology,0.5).
edge(considerationOfFeedbackFromCounsellors,considerationOfFeedbackITProviders,1).
edge(payForSoftware,acquireSoftware,1).
edge(useT1,providePeerToPeerAccessRegionalOffices,1).
edge(acquireWebServerForFree,costEffectiveTechnology,0.5).
edge(increaseITResources1,increaseITResources,1).
edge(increaseITMethodsToAcquireFeedback1,increaseITMethodsToAcquireFeedback,1).
edge(webSoftwareBeAcquired,webCounsellingSoftwareBeImplemented,1).
edge(payForWebServer,costEffectiveTechnology,-0.5).
edge(implementBulletinBoard,acquireAndImplementEmployeeSoftware,1).
edge(costEffectiveTechnology,expandITDepartment,0.5).
edge(webServerBeAcquired,manageAndImplementWebSite,1).
edge(keepUpWithNewTechnology,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(getWebEventTechnology,getWebEventTechnology1,1).
