% CSITDepartment  (node/2 edge/3 dep/2 dec/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
node(easilyAccessableTechnologyInstructions1,softgoal).
leaf(easilyAccessableTechnologyInstructions1).
node(properlyAndSuitablyEquippedInITToAccomplishCSNeeds1,softgoal).
node(freeUpgrades,resource).
leaf(freeUpgrades).
node(provideOnlineDonorTechnology,task).
node(increaseAccessSpeedRegionalOfficesToDL,softgoal).
node(putContentOntoWebsite1,task).
leaf(putContentOntoWebsite1).
node(improveQualityAssuranceTechnology,softgoal).
node(hardwareBeAcquiredForFree,task).
node(useVPN,task).
leaf(useVPN).
node(sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,softgoal).
node(callsBeRecordedIntoADataBase1,goal).
leaf(callsBeRecordedIntoADataBase1).
topgoal(callsBeRecordedIntoADataBase1).
node(implementMaintainComputerSystemsForEmployeeUse,task).
node(itTrainingSupportBeGivenToEmployees,goal).
topgoal(itTrainingSupportBeGivenToEmployees).
node(itResources,resource).
leaf(itResources).
node(properlyAndSuitablyEquippedInITToAccomplishServiceGoals,softgoal).
node(oracle,resource).
leaf(oracle).
node(decreaseClumsinessTechnology,softgoal).
node(useOracleForDataBase,task).
node(provideDocumentLibrarySystem1,task).
node(costEffectiveTechnology,softgoal).
node(manageAndImplementWebSite,task).
node(provideCompiledCallData,task).
node(payForUpgrades,task).
node(callCenterServerAndSchedulingSystemBeIntegrated,goal).
leaf(callCenterServerAndSchedulingSystemBeIntegrated).
topgoal(callCenterServerAndSchedulingSystemBeIntegrated).
node(improveCallRecordingEquipment1,softgoal).
leaf(improveCallRecordingEquipment1).
node(fitBetweenSystemCapabilitiesAndCSRequirements,softgoal).
node(properlyAndSuitablyEquippedInITToAccomplishCSNeeds,softgoal).
node(integrateITSystems,goal).
topgoal(integrateITSystems).
node(feedbackFormSoftware,resource).
node(performanceReviewInformationBeCollectedInDataBase,goal).
topgoal(performanceReviewInformationBeCollectedInDataBase).
node(csBeNotForProfit,goal).
leaf(csBeNotForProfit).
topgoal(csBeNotForProfit).
node(webServer,resource).
node(acquireUpgradesForFree,task).
node(increaseITTrainingForCounsellors1,softgoal).
node(implementBulletinBoard1,task).
node(anITTrainerBePresent1,goal).
leaf(anITTrainerBePresent1).
topgoal(anITTrainerBePresent1).
node(costEffectiveTraining,softgoal).
node(itProvidersHaveKnowledgeOfFundraisingAndMarketing,goal).
leaf(itProvidersHaveKnowledgeOfFundraisingAndMarketing).
topgoal(itProvidersHaveKnowledgeOfFundraisingAndMarketing).
node(freeWebServer,resource).
leaf(freeWebServer).
node(easilyAccessableTechnologyInstructions,softgoal).
node(hardwareBeAcquired,goal).
topgoal(hardwareBeAcquired).
node(implementPhoneFeedback,task).
node(implementCategorizationTool,task).
node(anITTrainerBePresent,goal).
topgoal(anITTrainerBePresent).
node(feedbackFormBeImplemented,task).
node(implementPhoneFeedback1,task).
leaf(implementPhoneFeedback1).
node(supportAnalysisCounsellorsTime1,softgoal).
node(implementCategorizationTool1,task).
node(provideTechnologyToCreateAndSendDocuments,task).
leaf(provideTechnologyToCreateAndSendDocuments).
node(networkPCs,task).
leaf(networkPCs).
node(getWebEventTechnology1,task).
node(freeSoftware,resource).
leaf(freeSoftware).
node(simpleTechnology1,softgoal).
node(increaseITMethodsToAcquireFeedback,softgoal).
node(payForSoftware,task).
node(implementDirectorEnterpriseThroughBluePumpkin,task).
node(telephonyBeImplementedAndManaged1,goal).
topgoal(telephonyBeImplementedAndManaged1).
node(implementActivityManager,task).
node(adequatelyCustomizableCSTechnology,softgoal).
leaf(adequatelyCustomizableCSTechnology).
node(implementIVR,task).
node(simpleTechnology,softgoal).
node(useCurrentMethod,task).
leaf(useCurrentMethod).
node(properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,softgoal).
node(improveQualityAssuranceTechnology1,softgoal).
node(putContentOntoWebsite,task).
node(increasedEmphasisOnITInHiringProcessOfCounsellors,softgoal).
leaf(increasedEmphasisOnITInHiringProcessOfCounsellors).
node(increaseAccessSpeedRegionalOfficesToDL1,softgoal).
node(implementEmailForCounsellors,task).
leaf(implementEmailForCounsellors).
node(keepUpWithNewTechnology,softgoal).
node(acquireITResources,task).
node(useT1,task).
leaf(useT1).
node(effectiveITTraining,softgoal).
node(installDesktopSoftware,task).
node(decreaseClumsinessTechnology1,softgoal).
leaf(decreaseClumsinessTechnology1).
node(useInformalBuddySystemForTraining,task).
leaf(useInformalBuddySystemForTraining).
node(acquireSoftwareForFree,task).
node(aTrainingComputerBePresent1,goal).
leaf(aTrainingComputerBePresent1).
topgoal(aTrainingComputerBePresent1).
node(adjustToSoftwareChanges,softgoal).
node(freeHardware,resource).
leaf(freeHardware).
node(implementAndManageTechnologyInRegionalOffices,task).
node(acquireAndImplementEmployeeSoftware,task).
node(considerationOfFeedbackITProviders,softgoal).
node(donorAccountingDataBase,resource).
node(increaseITResources1,softgoal).
leaf(increaseITResources1).
node(implementDesktops,task).
node(telephonyBeImplementedAndManaged,task).
node(implementSymposiumSystem,task).
node(software,resource).
leaf(software).
node(payForHardware,task).
node(provideDocumentLibrarySystem,task).
node(manageDonorAccountingDataBase,task).
node(webServer1,resource).
leaf(webServer1).
node(implementEmailForCounsellors1,task).
node(itProvidersHaveKnowledgeOfCounselling,goal).
leaf(itProvidersHaveKnowledgeOfCounselling).
topgoal(itProvidersHaveKnowledgeOfCounselling).
node(performanceReviewInformationBeCollectedInDataBase1,goal).
leaf(performanceReviewInformationBeCollectedInDataBase1).
topgoal(performanceReviewInformationBeCollectedInDataBase1).
node(itSystemsBeIntegrated,goal).
topgoal(itSystemsBeIntegrated).
node(expandITDepartment,softgoal).
node(acquireSoftware,goal).
topgoal(acquireSoftware).
node(webServerBeAcquired,goal).
topgoal(webServerBeAcquired).
node(csBeNotForProfit1,goal).
leaf(csBeNotForProfit1).
topgoal(csBeNotForProfit1).
node(increasedEmphasisOnITInHiringProcessOfCounsellors1,softgoal).
node(webSoftware,resource).
node(webCounsellingSoftwareBeImplemented,task).
node(increaseITResources,softgoal).
node(acquireWebServerForFree,task).
node(improveCallRecordingEquipment,softgoal).
node(hardware,resource).
leaf(hardware).
node(upgrades,resource).
leaf(upgrades).
node(callsBeRecordedIntoADataBase,goal).
topgoal(callsBeRecordedIntoADataBase).
node(getWebEventTechnology,task).
node(implementBulletinBoard,task).
node(itBeUpgraded,goal).
topgoal(itBeUpgraded).
node(satisfyCSITNeeds,task).
node(performDonorAccountingDataBaseMaintenance,task).
leaf(performDonorAccountingDataBaseMaintenance).
node(acquireTelephoneSwitch,task).
node(considerationOfFeedbackFromCounsellors,softgoal).
leaf(considerationOfFeedbackFromCounsellors).
node(increaseITTrainingForCounsellors,softgoal).
node(payForWebServer,task).
node(supportAnalysisCounsellorsTime,softgoal).
node(provideOnlineDonorTechnology1,task).
leaf(provideOnlineDonorTechnology1).
node(itDeptProvidesOrientationAndTraining,task).
node(webSoftwareBeAcquired,goal).
topgoal(webSoftwareBeAcquired).
node(aTrainingComputerBePresent,goal).
topgoal(aTrainingComputerBePresent).
node(increaseITTrainingResources,softgoal).
node(providePeerToPeerAccessRegionalOffices,goal).
topgoal(providePeerToPeerAccessRegionalOffices).
node(increaseITMethodsToAcquireFeedback1,softgoal).
edge(properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(implementEmailForCounsellors,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(installDesktopSoftware,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
dec(acquireAndImplementEmployeeSoftware,implementMaintainComputerSystemsForEmployeeUse,or).
dec(acquireSoftware,implementBulletinBoard,or).
dep(integrateITSystems,itSystemsBeIntegrated).
dec(manageAndImplementWebSite,satisfyCSITNeeds,or).
edge(effectiveITTraining,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(hardwareBeAcquiredForFree,costEffectiveTechnology,0.5).
dep(freeHardware,hardwareBeAcquiredForFree).
dec(hardwareBeAcquired,acquireTelephoneSwitch,or).
edge(increaseITMethodsToAcquireFeedback1,improveQualityAssuranceTechnology1,0.5).
edge(performanceReviewInformationBeCollectedInDataBase1,improveQualityAssuranceTechnology1,0.5).
dep(feedbackFormBeImplemented,feedbackFormSoftware).
dec(telephonyBeImplementedAndManaged,satisfyCSITNeeds,or).
dep(improveQualityAssuranceTechnology1,improveQualityAssuranceTechnology).
dec(acquireSoftware,implementActivityManager,or).
edge(acquireITResources,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
dec(acquireSoftware,implementDirectorEnterpriseThroughBluePumpkin,or).
dep(webServer1,payForWebServer).
edge(implementDirectorEnterpriseThroughBluePumpkin,supportAnalysisCounsellorsTime1,0.5).
edge(acquireSoftwareForFree,costEffectiveTechnology,0.5).
dec(acquireSoftware,provideDocumentLibrarySystem1,or).
dec(implementDirectorEnterpriseThroughBluePumpkin,acquireAndImplementEmployeeSoftware,or).
dec(anITTrainerBePresent1,itDeptProvidesOrientationAndTraining,or).
dec(acquireSoftware,implementSymposiumSystem,or).
dec(implementMaintainComputerSystemsForEmployeeUse,satisfyCSITNeeds,or).
dep(anITTrainerBePresent1,anITTrainerBePresent).
dep(implementEmailForCounsellors,implementEmailForCounsellors1).
dec(payForSoftware,webSoftwareBeAcquired,or).
dec(hardwareBeAcquiredForFree,hardwareBeAcquired,or).
dec(useVPN,implementAndManageTechnologyInRegionalOffices,or).
edge(aTrainingComputerBePresent1,costEffectiveTraining,-0.5).
edge(useInformalBuddySystemForTraining,costEffectiveTraining,0.5).
dep(itResources,acquireITResources).
dep(freeWebServer,acquireWebServerForFree).
dep(putContentOntoWebsite1,putContentOntoWebsite).
edge(increaseITTrainingResources,increaseITTrainingForCounsellors1,0.5).
edge(adequatelyCustomizableCSTechnology,fitBetweenSystemCapabilitiesAndCSRequirements,0.5).
dep(hardware,payForHardware).
edge(increaseITResources,keepUpWithNewTechnology,0.5).
dec(acquireSoftware,implementIVR,or).
edge(payForHardware,costEffectiveTechnology,-0.5).
edge(itProvidersHaveKnowledgeOfCounselling,sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,0.5).
dec(manageDonorAccountingDataBase,satisfyCSITNeeds,or).
edge(itProvidersHaveKnowledgeOfFundraisingAndMarketing,sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,0.5).
dec(performDonorAccountingDataBaseMaintenance,manageDonorAccountingDataBase,or).
edge(anITTrainerBePresent1,costEffectiveTraining,-0.5).
dep(implementCategorizationTool,implementCategorizationTool1).
dep(performanceReviewInformationBeCollectedInDataBase1,performanceReviewInformationBeCollectedInDataBase).
dep(properlyAndSuitablyEquippedInITToAccomplishCSNeeds,properlyAndSuitablyEquippedInITToAccomplishCSNeeds1).
edge(provideDocumentLibrarySystem1,properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,0.5).
dep(increaseAccessSpeedRegionalOfficesToDL1,increaseAccessSpeedRegionalOfficesToDL).
dec(webCounsellingSoftwareBeImplemented,manageAndImplementWebSite,or).
edge(fitBetweenSystemCapabilitiesAndCSRequirements,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
dec(itTrainingSupportBeGivenToEmployees,satisfyCSITNeeds,or).
edge(expandITDepartment,increaseITTrainingResources,0.5).
edge(increasedEmphasisOnITInHiringProcessOfCounsellors1,effectiveITTraining,0.5).
dec(itDeptProvidesOrientationAndTraining,itTrainingSupportBeGivenToEmployees,or).
edge(itBeUpgraded,keepUpWithNewTechnology,0.5).
edge(adjustToSoftwareChanges,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
dec(provideOnlineDonorTechnology1,manageAndImplementWebSite,or).
dec(payForUpgrades,itBeUpgraded,or).
dec(implementActivityManager,acquireAndImplementEmployeeSoftware,or).
dec(implementEmailForCounsellors,acquireAndImplementEmployeeSoftware,or).
edge(implementDirectorEnterpriseThroughBluePumpkin,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,-0.5).
dec(implementIVR,telephonyBeImplementedAndManaged,or).
dec(implementCategorizationTool,acquireAndImplementEmployeeSoftware,or).
edge(useT1,increaseAccessSpeedRegionalOfficesToDL1,1).
dep(aTrainingComputerBePresent1,aTrainingComputerBePresent).
edge(properlyAndSuitablyEquippedInITToAccomplishServiceGoals,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(aTrainingComputerBePresent1,effectiveITTraining,0.5).
dep(increasedEmphasisOnITInHiringProcessOfCounsellors,increasedEmphasisOnITInHiringProcessOfCounsellors1).
edge(itBeUpgraded,adjustToSoftwareChanges,-0.5).
dec(getWebEventTechnology,manageAndImplementWebSite,or).
dep(callsBeRecordedIntoADataBase1,callsBeRecordedIntoADataBase).
dec(useInformalBuddySystemForTraining,itTrainingSupportBeGivenToEmployees,or).
dec(acquireSoftware,getWebEventTechnology,or).
edge(useT1,costEffectiveTechnology,-0.5).
dec(implementAndManageTechnologyInRegionalOffices,implementMaintainComputerSystemsForEmployeeUse,or).
dec(acquireWebServerForFree,webServerBeAcquired,or).
dep(upgrades,payForUpgrades).
dep(manageDonorAccountingDataBase,donorAccountingDataBase).
dep(telephonyBeImplementedAndManaged,telephonyBeImplementedAndManaged1).
edge(implementActivityManager,supportAnalysisCounsellorsTime1,0.5).
edge(itDeptProvidesOrientationAndTraining,effectiveITTraining,0.5).
dep(software,payForSoftware).
edge(callsBeRecordedIntoADataBase1,improveQualityAssuranceTechnology1,0.5).
dep(improveCallRecordingEquipment1,improveCallRecordingEquipment).
edge(aTrainingComputerBePresent1,increaseITTrainingForCounsellors1,0.5).
dep(implementBulletinBoard,implementBulletinBoard1).
dep(freeSoftware,acquireSoftwareForFree).
dec(acquireSoftware,installDesktopSoftware,or).
dec(hardwareBeAcquired,implementMaintainComputerSystemsForEmployeeUse,or).
edge(costEffectiveTraining,increaseITResources,0.5).
edge(itBeUpgraded,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
edge(sensitiveToTheEnvironmentITEquipmentWillBeIntroducedTo,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
dec(acquireTelephoneSwitch,telephonyBeImplementedAndManaged,or).
edge(manageDonorAccountingDataBase,properlyAndSuitablyEquippedInITToAccomplishFundraisingNeeds,0.5).
dec(networkPCs,implementMaintainComputerSystemsForEmployeeUse,or).
dec(putContentOntoWebsite1,manageAndImplementWebSite,or).
dec(provideTechnologyToCreateAndSendDocuments,implementMaintainComputerSystemsForEmployeeUse,or).
dep(supportAnalysisCounsellorsTime1,supportAnalysisCounsellorsTime).
dec(useCurrentMethod,providePeerToPeerAccessRegionalOffices,or).
edge(implementBulletinBoard,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(implementBulletinBoard,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,-0.5).
edge(anITTrainerBePresent1,increaseITTrainingForCounsellors1,0.5).
edge(implementActivityManager,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
edge(implementActivityManager,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,-0.5).
edge(implementCategorizationTool,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
dep(webSoftwareBeAcquired,webSoftware).
edge(integrateITSystems,simpleTechnology1,0.5).
edge(improveCallRecordingEquipment1,improveQualityAssuranceTechnology1,0.5).
dec(installDesktopSoftware,acquireAndImplementEmployeeSoftware,or).
dec(acquireSoftwareForFree,webSoftwareBeAcquired,or).
dep(simpleTechnology1,simpleTechnology).
dec(acquireSoftwareForFree,acquireSoftware,or).
edge(increaseITResources,expandITDepartment,1).
dep(implementPhoneFeedback1,implementPhoneFeedback).
dec(provideDocumentLibrarySystem1,acquireAndImplementEmployeeSoftware,or).
dep(webServerBeAcquired,webServer).
dec(providePeerToPeerAccessRegionalOffices,implementAndManageTechnologyInRegionalOffices,or).
dep(oracle,useOracleForDataBase).
dep(freeUpgrades,acquireUpgradesForFree).
dec(payForHardware,hardwareBeAcquired,or).
edge(increaseITTrainingResources,effectiveITTraining,0.5).
dep(decreaseClumsinessTechnology1,decreaseClumsinessTechnology).
edge(payForSoftware,costEffectiveTechnology,-0.5).
edge(csBeNotForProfit,keepUpWithNewTechnology,-0.5).
dec(installDesktopSoftware,implementDesktops,or).
dec(acquireSoftware,feedbackFormBeImplemented,or).
dec(implementSymposiumSystem,telephonyBeImplementedAndManaged,or).
dep(provideOnlineDonorTechnology1,provideOnlineDonorTechnology).
edge(useCurrentMethod,costEffectiveTechnology,0.5).
edge(feedbackFormBeImplemented,increaseITMethodsToAcquireFeedback1,0.5).
dec(implementDesktops,implementMaintainComputerSystemsForEmployeeUse,or).
dec(useOracleForDataBase,manageDonorAccountingDataBase,or).
edge(increaseITResources,increaseITTrainingResources,0.5).
edge(considerationOfFeedbackFromCounsellors,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
dec(payForWebServer,webServerBeAcquired,or).
dec(acquireSoftware,implementCategorizationTool,or).
dep(increaseITTrainingForCounsellors1,increaseITTrainingForCounsellors).
dec(callCenterServerAndSchedulingSystemBeIntegrated,integrateITSystems,or).
dep(implementCategorizationTool,provideCompiledCallData).
dep(easilyAccessableTechnologyInstructions1,easilyAccessableTechnologyInstructions).
edge(implementPhoneFeedback1,properlyAndSuitablyEquippedInITToAccomplishServiceGoals,0.5).
dep(provideDocumentLibrarySystem1,provideDocumentLibrarySystem).
edge(costEffectiveTechnology,increaseITTrainingResources,0.5).
edge(useOracleForDataBase,costEffectiveTechnology,0.5).
dep(considerationOfFeedbackFromCounsellors,considerationOfFeedbackITProviders).
dec(payForSoftware,acquireSoftware,or).
dec(useT1,providePeerToPeerAccessRegionalOffices,or).
edge(acquireWebServerForFree,costEffectiveTechnology,0.5).
dep(increaseITResources1,increaseITResources).
dep(increaseITMethodsToAcquireFeedback1,increaseITMethodsToAcquireFeedback).
dec(webSoftwareBeAcquired,webCounsellingSoftwareBeImplemented,or).
edge(payForWebServer,costEffectiveTechnology,-0.5).
dec(implementBulletinBoard,acquireAndImplementEmployeeSoftware,or).
edge(costEffectiveTechnology,expandITDepartment,0.5).
dec(webServerBeAcquired,manageAndImplementWebSite,or).
edge(keepUpWithNewTechnology,properlyAndSuitablyEquippedInITToAccomplishCSNeeds,0.5).
dep(getWebEventTechnology,getWebEventTechnology1).
