% CSSAProgram  (edit me: node/2 edge/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, leaf/1, topgoal/1.
node(acquireVolunteerOutreachSkills1,softgoal).
node(experienceForResume,softgoal).
node(speaches,resource).
node(improveImageToKids1,softgoal).
node(speakAtFundraisers,task).
node(acquirePublicSpeakingSkills1,softgoal).
node(attendSAMeetings,task).
leaf(attendSAMeetings).
node(increasedSAResources,softgoal).
node(acquireFundraisingSkills,softgoal).
node(increaseInvolvementOfSAS,softgoal).
node(makeNewFriends1,softgoal).
node(communityServiceHoursCompleted,goal).
topgoal(communityServiceHoursCompleted).
node(increaseSkills,softgoal).
node(trustOfKids,softgoal).
node(sendOutEmails1,task).
node(helpPutOnSATrainingConferences,task).
node(writeArticlesForNewspaper2,task).
node(providePromotionResources,task).
node(acquireFundraisingSkills2,softgoal).
node(createLifeLongVolunteerSpirit,softgoal).
node(saSAreOrganized1,softgoal).
node(expansionOfSAServices,softgoal).
node(runFundraiserInSchools,task).
node(schoolInitiatesPresenation1,task).
leaf(schoolInitiatesPresenation1).
node(createLifeLongVolunteerSpirit1,softgoal).
node(giveCSPresentations1,task).
node(planSocialEvents,task).
leaf(planSocialEvents).
node(getSpeaches,task).
node(runFundraiserInSchools2,task).
node(beConfident,softgoal).
node(getPromotionResources,task).
node(giveCSPresentations,task).
node(increasedSAResources1,softgoal).
leaf(increasedSAResources1).
node(saSAreOutgoing1,softgoal).
node(saSAreOrganized,softgoal).
node(happinessStudentAmbassadors,softgoal).
node(keepInTouchWithVolunteers,softgoal).
node(planAndPutOnReconnectionConferences1,task).
node(retrainSAS,task).
leaf(retrainSAS).
node(findHelpWithPresentations,task).
node(beEnthusiastic,softgoal).
node(haveTimeForSchool2,softgoal).
node(putOnSATrainingConferences,task).
node(improveImageToKids,softgoal).
node(positiveReputationCS,softgoal).
node(haveTimeForSchool1,softgoal).
node(putOnSATrainingConferences1,task).
node(writeArticlesForNewspaper1,task).
node(helpWithPresentations1,task).
node(askForHelpWithPresentations,task).
node(spreadAwareness1,softgoal).
node(sendOutEmails2,task).
node(trustOfKids1,softgoal).
node(acquireVolunteerOutreachSkills,softgoal).
node(planAndPutOnReconnectionConferences2,task).
node(saSAreOutgoing,softgoal).
node(happinessStudentAmbassadors2,softgoal).
node(promotionResources,resource).
node(beOutgoing,softgoal).
node(acquirePublicSpeakingSkills,softgoal).
node(communityServiceHoursCompleted2,goal).
topgoal(communityServiceHoursCompleted2).
node(saSAreConfident1,softgoal).
node(speakAtFundraisers3,task).
node(trainSAS,task).
leaf(trainSAS).
node(permissionForPresentationsBeGiven,goal).
leaf(permissionForPresentationsBeGiven).
topgoal(permissionForPresentationsBeGiven).
node(morePromotionResourcesAvailable,softgoal).
node(saSAreConfident,softgoal).
node(provideSpeaches,task).
leaf(provideSpeaches).
node(haveTimeForSchool,softgoal).
node(giveBackToCommunity2,softgoal).
node(runFundraiserInSchools1,task).
leaf(runFundraiserInSchools1).
node(increaseWritingSkills,softgoal).
node(kidsBeUsedToCommunicateWithOtherKids,goal).
leaf(kidsBeUsedToCommunicateWithOtherKids).
topgoal(kidsBeUsedToCommunicateWithOtherKids).
node(planAndPutOnReconnectionConferences,task).
node(helpPlanAndPutOnReconnectionConferences1,task).
node(increaseWritingSkills1,softgoal).
node(speakAtFundraisers2,task).
node(giveBackToCommunity1,softgoal).
node(increaseWritingSkills2,softgoal).
node(spreadAwareness,softgoal).
node(sendOutEmails,task).
leaf(sendOutEmails).
node(reduceMisconceptions,softgoal).
node(helpPutOnSATrainingConferences1,task).
node(helpWithPresentations,task).
leaf(helpWithPresentations).
node(attendCSMeetings,task).
leaf(attendCSMeetings).
node(beOrganized,softgoal).
node(makeNewFriends,softgoal).
node(qualitySAServices1,softgoal).
node(engagementStudentAmbassadorsInPromotingAwareness,softgoal).
node(acquireFundraisingSkills1,softgoal).
node(saSAreEnthusiastic1,softgoal).
node(promotionResources1,resource).
leaf(promotionResources1).
node(putOnSATrainingConferences2,task).
node(presenationBeInitiated,goal).
topgoal(presenationBeInitiated).
node(initiatePresentationWithSchools,task).
node(qualitySAServices,softgoal).
node(schoolInitiatesPresenation,task).
node(writeArticlesForNewspaper,task).
leaf(writeArticlesForNewspaper).
node(happinessStudentAmbassadors1,softgoal).
node(engageVolunteers,softgoal).
node(giveBackToCommunity,softgoal).
node(acquireVolunteerOutreachSkills2,softgoal).
node(giveCSPresentations2,task).
node(highPresentationAttendance,softgoal).
node(helpPlanAndPutOnReconnectionConferences,task).
node(communityServiceHoursCompleted1,goal).
topgoal(communityServiceHoursCompleted1).
node(acquirePublicSpeakingSkills2,softgoal).
node(positiveReputationCS1,softgoal).
leaf(positiveReputationCS1).
node(findHelpWithPresentations1,task).
node(makeNewFriends2,softgoal).
node(reduceMisconceptions1,softgoal).
node(saSAreEnthusiastic,softgoal).
node(speakAtFundraisers1,task).
node(giveCSPresentations3,task).
edge(saSAreOutgoing1,saSAreOutgoing,1).
edge(keepInTouchWithVolunteers,increaseInvolvementOfSAS,0.5).
edge(presenationBeInitiated,giveCSPresentations1,1).
edge(giveCSPresentations1,acquirePublicSpeakingSkills2,0.5).
edge(runFundraiserInSchools1,acquireFundraisingSkills2,0.5).
edge(speakAtFundraisers,speakAtFundraisers2,1).
edge(putOnSATrainingConferences,engageVolunteers,0.5).
edge(happinessStudentAmbassadors,saSAreEnthusiastic,0.5).
edge(retrainSAS,acquirePublicSpeakingSkills2,0.5).
edge(increaseSkills,happinessStudentAmbassadors2,0.5).
edge(saSAreConfident1,saSAreConfident,1).
edge(runFundraiserInSchools2,spreadAwareness,0.5).
edge(askForHelpWithPresentations,giveCSPresentations1,1).
edge(speakAtFundraisers,acquirePublicSpeakingSkills2,0.5).
edge(acquireVolunteerOutreachSkills,beOutgoing,0.5).
edge(planSocialEvents,makeNewFriends2,0.5).
edge(giveCSPresentations2,giveCSPresentations3,1).
edge(runFundraiserInSchools1,runFundraiserInSchools,1).
edge(makeNewFriends,happinessStudentAmbassadors2,0.5).
edge(acquireFundraisingSkills,beOrganized,0.5).
edge(providePromotionResources,promotionResources,1).
edge(saSAreEnthusiastic,engageVolunteers,0.5).
edge(acquireFundraisingSkills,beOutgoing,0.5).
edge(trainSAS,acquirePublicSpeakingSkills2,0.5).
edge(sendOutEmails1,sendOutEmails2,1).
edge(helpWithPresentations,helpWithPresentations1,1).
edge(writeArticlesForNewspaper1,spreadAwareness,0.5).
edge(reduceMisconceptions1,reduceMisconceptions,1).
edge(morePromotionResourcesAvailable,engageVolunteers,0.5).
edge(giveBackToCommunity1,giveBackToCommunity,1).
edge(speaches,getSpeaches,1).
edge(kidsBeUsedToCommunicateWithOtherKids,trustOfKids1,0.5).
edge(beOrganized,increaseSkills,0.5).
edge(helpPutOnSATrainingConferences1,putOnSATrainingConferences2,1).
edge(attendCSMeetings,acquireFundraisingSkills2,0.5).
edge(sendOutEmails,sendOutEmails1,1).
edge(planAndPutOnReconnectionConferences,increaseInvolvementOfSAS,0.5).
edge(trustOfKids1,trustOfKids,1).
edge(writeArticlesForNewspaper1,keepInTouchWithVolunteers,0.5).
edge(beOutgoing,saSAreOutgoing1,1).
edge(attendSAMeetings,makeNewFriends2,0.5).
edge(morePromotionResourcesAvailable,spreadAwareness,0.5).
edge(helpWithPresentations1,findHelpWithPresentations1,1).
edge(haveTimeForSchool2,haveTimeForSchool1,1).
edge(writeArticlesForNewspaper,writeArticlesForNewspaper2,1).
edge(haveTimeForSchool1,haveTimeForSchool,1).
edge(helpPutOnSATrainingConferences,makeNewFriends2,0.5).
edge(saSAreOrganized1,saSAreOrganized,1).
edge(planAndPutOnReconnectionConferences,keepInTouchWithVolunteers,0.5).
edge(writeArticlesForNewspaper2,writeArticlesForNewspaper1,1).
edge(happinessStudentAmbassadors,qualitySAServices1,0.5).
edge(sendOutEmails2,keepInTouchWithVolunteers,0.5).
edge(acquireVolunteerOutreachSkills,beConfident,0.5).
edge(provideSpeaches,qualitySAServices1,0.5).
edge(planAndPutOnReconnectionConferences1,planAndPutOnReconnectionConferences,1).
edge(initiatePresentationWithSchools,presenationBeInitiated,1).
edge(runFundraiserInSchools1,acquireVolunteerOutreachSkills2,0.5).
edge(retrainSAS,acquireFundraisingSkills2,0.5).
edge(helpPutOnSATrainingConferences,helpPutOnSATrainingConferences1,1).
edge(spreadAwareness,engagementStudentAmbassadorsInPromotingAwareness,1).
edge(trainSAS,acquireFundraisingSkills2,0.5).
edge(kidsBeUsedToCommunicateWithOtherKids,improveImageToKids1,0.5).
edge(spreadAwareness,spreadAwareness1,1).
edge(experienceForResume,happinessStudentAmbassadors2,0.5).
edge(highPresentationAttendance,expansionOfSAServices,0.5).
edge(happinessStudentAmbassadors,engageVolunteers,0.5).
edge(trainSAS,helpPutOnSATrainingConferences,1).
edge(acquirePublicSpeakingSkills,beOutgoing,0.5).
edge(planAndPutOnReconnectionConferences2,planAndPutOnReconnectionConferences1,1).
edge(speakAtFundraisers1,spreadAwareness,0.5).
edge(morePromotionResourcesAvailable,qualitySAServices1,0.5).
edge(giveBackToCommunity2,giveBackToCommunity1,1).
edge(qualitySAServices1,engageVolunteers,0.5).
edge(helpWithPresentations,giveBackToCommunity2,0.5).
edge(saSAreConfident,qualitySAServices1,0.5).
edge(writeArticlesForNewspaper,communityServiceHoursCompleted1,1).
edge(runFundraiserInSchools,runFundraiserInSchools2,1).
edge(happinessStudentAmbassadors2,happinessStudentAmbassadors1,1).
edge(increaseInvolvementOfSAS,expansionOfSAServices,0.5).
edge(acquireFundraisingSkills1,acquireFundraisingSkills,1).
edge(acquirePublicSpeakingSkills,beConfident,0.5).
edge(saSAreEnthusiastic1,saSAreEnthusiastic,1).
edge(attendCSMeetings,communityServiceHoursCompleted1,1).
edge(acquirePublicSpeakingSkills1,acquirePublicSpeakingSkills,1).
edge(promotionResources1,providePromotionResources,1).
edge(positiveReputationCS,engageVolunteers,0.5).
edge(attendSAMeetings,communityServiceHoursCompleted1,1).
edge(positiveReputationCS,highPresentationAttendance,0.5).
edge(provideSpeaches,speaches,1).
edge(helpPlanAndPutOnReconnectionConferences,helpPlanAndPutOnReconnectionConferences1,1).
edge(permissionForPresentationsBeGiven,initiatePresentationWithSchools,1).
edge(trainSAS,acquireVolunteerOutreachSkills2,0.5).
edge(beEnthusiastic,saSAreEnthusiastic1,1).
edge(happinessStudentAmbassadors1,happinessStudentAmbassadors,1).
edge(giveCSPresentations1,communityServiceHoursCompleted1,1).
edge(makeNewFriends1,makeNewFriends,1).
edge(sendOutEmails,findHelpWithPresentations1,1).
edge(communityServiceHoursCompleted1,haveTimeForSchool2,-0.5).
edge(beOrganized,saSAreOrganized1,1).
edge(increaseWritingSkills1,increaseWritingSkills,1).
edge(findHelpWithPresentations,askForHelpWithPresentations,1).
edge(writeArticlesForNewspaper,increaseWritingSkills2,0.5).
edge(qualitySAServices1,qualitySAServices,1).
edge(retrainSAS,acquireVolunteerOutreachSkills2,0.5).
edge(increaseSkills,experienceForResume,0.5).
edge(runFundraiserInSchools1,acquirePublicSpeakingSkills2,0.5).
edge(speakAtFundraisers1,speakAtFundraisers3,1).
edge(providePromotionResources,qualitySAServices1,0.5).
edge(happinessStudentAmbassadors,saSAreOutgoing,0.5).
edge(acquirePublicSpeakingSkills2,acquirePublicSpeakingSkills1,1).
edge(promotionResources,getPromotionResources,1).
edge(putOnSATrainingConferences1,putOnSATrainingConferences,1).
edge(speakAtFundraisers1,reduceMisconceptions1,0.5).
edge(putOnSATrainingConferences2,putOnSATrainingConferences1,1).
edge(haveTimeForSchool,happinessStudentAmbassadors2,0.5).
edge(communityServiceHoursCompleted1,communityServiceHoursCompleted,1).
edge(helpPutOnSATrainingConferences,communityServiceHoursCompleted1,1).
edge(beConfident,saSAreConfident1,1).
edge(giveBackToCommunity,happinessStudentAmbassadors2,0.5).
edge(communityServiceHoursCompleted2,happinessStudentAmbassadors2,0.5).
edge(acquireVolunteerOutreachSkills,beEnthusiastic,0.5).
edge(increasedSAResources1,morePromotionResourcesAvailable,0.5).
edge(saSAreOrganized,qualitySAServices1,0.5).
edge(acquireVolunteerOutreachSkills1,acquireVolunteerOutreachSkills,1).
edge(acquirePublicSpeakingSkills,beEnthusiastic,0.5).
edge(attendCSMeetings,acquireVolunteerOutreachSkills2,0.5).
edge(kidsBeUsedToCommunicateWithOtherKids,qualitySAServices1,0.5).
edge(acquireFundraisingSkills,beEnthusiastic,0.5).
edge(positiveReputationCS1,positiveReputationCS,1).
edge(communityServiceHoursCompleted,communityServiceHoursCompleted2,1).
edge(helpPlanAndPutOnReconnectionConferences,acquirePublicSpeakingSkills2,0.5).
edge(acquireFundraisingSkills2,acquireFundraisingSkills1,1).
edge(giveCSPresentations2,reduceMisconceptions1,0.5).
edge(improveImageToKids1,improveImageToKids,1).
edge(createLifeLongVolunteerSpirit1,createLifeLongVolunteerSpirit,1).
edge(helpPlanAndPutOnReconnectionConferences,acquireVolunteerOutreachSkills2,0.5).
edge(runFundraiserInSchools1,giveBackToCommunity2,0.5).
edge(getPromotionResources,giveCSPresentations1,1).
edge(acquireVolunteerOutreachSkills2,acquireVolunteerOutreachSkills1,1).
edge(makeNewFriends2,makeNewFriends1,1).
edge(spreadAwareness,expansionOfSAServices,0.5).
edge(engageVolunteers,createLifeLongVolunteerSpirit1,0.5).
edge(speakAtFundraisers,giveBackToCommunity2,0.5).
edge(helpPlanAndPutOnReconnectionConferences1,planAndPutOnReconnectionConferences2,1).
edge(runFundraiserInSchools1,communityServiceHoursCompleted1,1).
edge(beConfident,increaseSkills,0.5).
edge(askForHelpWithPresentations,speakAtFundraisers,1).
edge(retrainSAS,helpPlanAndPutOnReconnectionConferences,1).
edge(beOutgoing,makeNewFriends,0.5).
edge(writeArticlesForNewspaper,makeNewFriends2,0.5).
edge(findHelpWithPresentations1,findHelpWithPresentations,1).
edge(happinessStudentAmbassadors,increaseInvolvementOfSAS,0.5).
edge(giveCSPresentations,giveCSPresentations2,1).
edge(giveCSPresentations1,giveBackToCommunity2,0.5).
edge(schoolInitiatesPresenation,presenationBeInitiated,1).
edge(giveCSPresentations2,spreadAwareness,0.5).
edge(helpPlanAndPutOnReconnectionConferences,communityServiceHoursCompleted1,1).
edge(speakAtFundraisers2,speakAtFundraisers1,1).
edge(giveCSPresentations1,giveCSPresentations,1).
edge(helpWithPresentations,makeNewFriends2,0.5).
edge(speakAtFundraisers,acquireFundraisingSkills2,0.5).
edge(engageVolunteers,expansionOfSAServices,0.5).
edge(increaseWritingSkills2,increaseWritingSkills1,1).
edge(increasedSAResources1,increasedSAResources,1).
edge(giveCSPresentations1,acquireVolunteerOutreachSkills2,0.5).
edge(speakAtFundraisers,communityServiceHoursCompleted1,1).
edge(schoolInitiatesPresenation1,schoolInitiatesPresenation,1).
edge(providePromotionResources,morePromotionResourcesAvailable,-0.5).
