;;;; models/CSSAProgram.lisp : GENERATED from models/CSSAProgram.py by to-lisp.py
(<- acquireFundraisingSkills acquireFundraisingSkills1)
(<- acquireFundraisingSkills1 acquireFundraisingSkills2)
(<- acquirePublicSpeakingSkills acquirePublicSpeakingSkills1)
(<- acquirePublicSpeakingSkills1 acquirePublicSpeakingSkills2)
(<- acquireVolunteerOutreachSkills acquireVolunteerOutreachSkills1)
(<- acquireVolunteerOutreachSkills1 acquireVolunteerOutreachSkills2)
(<- askForHelpWithPresentations findHelpWithPresentations)
(<- communityServiceHoursCompleted communityServiceHoursCompleted1)
(<- communityServiceHoursCompleted1 (or writeArticlesForNewspaper attendCSMeetings attendSAMeetings giveCSPresentations1 helpPutOnSATrainingConferences runFundraiserInSchools1 helpPlanAndPutOnReconnectionConferences speakAtFundraisers))
(<- communityServiceHoursCompleted2 communityServiceHoursCompleted)
(<- createLifeLongVolunteerSpirit createLifeLongVolunteerSpirit1)
(<- engagementStudentAmbassadorsInPromotingAwareness spreadAwareness)
(<- findHelpWithPresentations findHelpWithPresentations1)
(<- findHelpWithPresentations1 (and helpWithPresentations1 sendOutEmails))
(<- getPromotionResources promotionResources)
(<- getSpeaches speaches)
(<- giveBackToCommunity giveBackToCommunity1)
(<- giveBackToCommunity1 giveBackToCommunity2)
(<- giveCSPresentations giveCSPresentations1)
(<- giveCSPresentations1 (or presenationBeInitiated askForHelpWithPresentations getPromotionResources))
(<- giveCSPresentations2 giveCSPresentations)
(<- giveCSPresentations3 giveCSPresentations2)
(<- happinessStudentAmbassadors happinessStudentAmbassadors1)
(<- happinessStudentAmbassadors1 happinessStudentAmbassadors2)
(<- haveTimeForSchool haveTimeForSchool1)
(<- haveTimeForSchool1 haveTimeForSchool2)
(<- helpPlanAndPutOnReconnectionConferences retrainSAS)
(<- helpPlanAndPutOnReconnectionConferences1 helpPlanAndPutOnReconnectionConferences)
(<- helpPutOnSATrainingConferences trainSAS)
(<- helpPutOnSATrainingConferences1 helpPutOnSATrainingConferences)
(<- helpWithPresentations1 helpWithPresentations)
(<- improveImageToKids improveImageToKids1)
(<- increaseWritingSkills increaseWritingSkills1)
(<- increaseWritingSkills1 increaseWritingSkills2)
(<- increasedSAResources increasedSAResources1)
(<- initiatePresentationWithSchools permissionForPresentationsBeGiven)
(<- makeNewFriends (or makeNewFriends1 (helps beOutgoing)))
(<- makeNewFriends1 makeNewFriends2)
(<- planAndPutOnReconnectionConferences planAndPutOnReconnectionConferences1)
(<- planAndPutOnReconnectionConferences1 planAndPutOnReconnectionConferences2)
(<- planAndPutOnReconnectionConferences2 helpPlanAndPutOnReconnectionConferences1)
(<- positiveReputationCS positiveReputationCS1)
(<- presenationBeInitiated (or initiatePresentationWithSchools schoolInitiatesPresenation))
(<- promotionResources providePromotionResources)
(<- providePromotionResources promotionResources1)
(<- putOnSATrainingConferences putOnSATrainingConferences1)
(<- putOnSATrainingConferences1 putOnSATrainingConferences2)
(<- putOnSATrainingConferences2 helpPutOnSATrainingConferences1)
(<- qualitySAServices qualitySAServices1)
(<- reduceMisconceptions reduceMisconceptions1)
(<- runFundraiserInSchools runFundraiserInSchools1)
(<- runFundraiserInSchools2 runFundraiserInSchools)
(<- saSAreConfident saSAreConfident1)
(<- saSAreConfident1 beConfident)
(<- saSAreEnthusiastic (or saSAreEnthusiastic1 (helps happinessStudentAmbassadors)))
(<- saSAreEnthusiastic1 beEnthusiastic)
(<- saSAreOrganized saSAreOrganized1)
(<- saSAreOrganized1 beOrganized)
(<- saSAreOutgoing (or saSAreOutgoing1 (helps happinessStudentAmbassadors)))
(<- saSAreOutgoing1 beOutgoing)
(<- schoolInitiatesPresenation schoolInitiatesPresenation1)
(<- sendOutEmails1 sendOutEmails)
(<- sendOutEmails2 sendOutEmails1)
(<- speaches provideSpeaches)
(<- speakAtFundraisers askForHelpWithPresentations)
(<- speakAtFundraisers1 speakAtFundraisers2)
(<- speakAtFundraisers2 speakAtFundraisers)
(<- speakAtFundraisers3 speakAtFundraisers1)
(<- spreadAwareness1 spreadAwareness)
(<- trustOfKids trustOfKids1)
(<- writeArticlesForNewspaper1 writeArticlesForNewspaper2)
(<- writeArticlesForNewspaper2 writeArticlesForNewspaper)
(<- acquireFundraisingSkills2 (and (helps runFundraiserInSchools1) (helps attendCSMeetings) (helps retrainSAS) (helps trainSAS) (helps speakAtFundraisers)))
(<- acquirePublicSpeakingSkills2 (and (helps giveCSPresentations1) (helps retrainSAS) (helps speakAtFundraisers) (helps trainSAS) (helps runFundraiserInSchools1) (helps helpPlanAndPutOnReconnectionConferences)))
(<- acquireVolunteerOutreachSkills2 (and (helps runFundraiserInSchools1) (helps trainSAS) (helps retrainSAS) (helps attendCSMeetings) (helps helpPlanAndPutOnReconnectionConferences) (helps giveCSPresentations1)))
(<- beConfident (and (helps acquireVolunteerOutreachSkills) (helps acquirePublicSpeakingSkills)))
(<- beEnthusiastic (and (helps acquireVolunteerOutreachSkills) (helps acquirePublicSpeakingSkills) (helps acquireFundraisingSkills)))
(<- beOrganized (helps acquireFundraisingSkills))
(<- beOutgoing (and (helps acquireVolunteerOutreachSkills) (helps acquireFundraisingSkills) (helps acquirePublicSpeakingSkills)))
(<- createLifeLongVolunteerSpirit1 (helps engageVolunteers))
(<- engageVolunteers (and (helps putOnSATrainingConferences) (helps saSAreEnthusiastic) (helps morePromotionResourcesAvailable) (helps happinessStudentAmbassadors) (helps qualitySAServices1) (helps positiveReputationCS)))
(<- expansionOfSAServices (and (helps highPresentationAttendance) (helps increaseInvolvementOfSAS) (helps spreadAwareness) (helps engageVolunteers)))
(<- experienceForResume (helps increaseSkills))
(<- giveBackToCommunity2 (and (helps helpWithPresentations) (helps runFundraiserInSchools1) (helps speakAtFundraisers) (helps giveCSPresentations1)))
(<- happinessStudentAmbassadors2 (and (helps increaseSkills) (helps makeNewFriends) (helps experienceForResume) (helps haveTimeForSchool) (helps giveBackToCommunity) (helps communityServiceHoursCompleted2)))
(<- haveTimeForSchool2 (hurts communityServiceHoursCompleted1))
(<- highPresentationAttendance (helps positiveReputationCS))
(<- improveImageToKids1 (helps kidsBeUsedToCommunicateWithOtherKids))
(<- increaseInvolvementOfSAS (and (helps keepInTouchWithVolunteers) (helps planAndPutOnReconnectionConferences) (helps happinessStudentAmbassadors)))
(<- increaseSkills (and (helps beOrganized) (helps beConfident)))
(<- increaseWritingSkills2 (helps writeArticlesForNewspaper))
(<- keepInTouchWithVolunteers (and (helps writeArticlesForNewspaper1) (helps planAndPutOnReconnectionConferences) (helps sendOutEmails2)))
(<- makeNewFriends2 (and (helps planSocialEvents) (helps attendSAMeetings) (helps helpPutOnSATrainingConferences) (helps writeArticlesForNewspaper) (helps helpWithPresentations)))
(<- morePromotionResourcesAvailable (and (helps increasedSAResources1) (hurts providePromotionResources)))
(<- qualitySAServices1 (and (helps happinessStudentAmbassadors) (helps provideSpeaches) (helps morePromotionResourcesAvailable) (helps saSAreConfident) (helps providePromotionResources) (helps saSAreOrganized) (helps kidsBeUsedToCommunicateWithOtherKids)))
(<- reduceMisconceptions1 (and (helps speakAtFundraisers1) (helps giveCSPresentations2)))
(<- spreadAwareness (and (helps runFundraiserInSchools2) (helps writeArticlesForNewspaper1) (helps morePromotionResourcesAvailable) (helps speakAtFundraisers1) (helps giveCSPresentations2)))
(<- trustOfKids1 (helps kidsBeUsedToCommunicateWithOtherKids))
(defparameter *hard* '(communityServiceHoursCompleted communityServiceHoursCompleted2 permissionForPresentationsBeGiven kidsBeUsedToCommunicateWithOtherKids presenationBeInitiated communityServiceHoursCompleted1))
(defparameter *soft* '(acquireVolunteerOutreachSkills1 experienceForResume improveImageToKids1 acquirePublicSpeakingSkills1 increasedSAResources acquireFundraisingSkills increaseInvolvementOfSAS makeNewFriends1 increaseSkills trustOfKids acquireFundraisingSkills2 createLifeLongVolunteerSpirit saSAreOrganized1 expansionOfSAServices createLifeLongVolunteerSpirit1 beConfident increasedSAResources1 saSAreOutgoing1 saSAreOrganized happinessStudentAmbassadors keepInTouchWithVolunteers beEnthusiastic haveTimeForSchool2 improveImageToKids positiveReputationCS haveTimeForSchool1 spreadAwareness1 trustOfKids1 acquireVolunteerOutreachSkills saSAreOutgoing happinessStudentAmbassadors2 beOutgoing acquirePublicSpeakingSkills saSAreConfident1 morePromotionResourcesAvailable saSAreConfident haveTimeForSchool giveBackToCommunity2 increaseWritingSkills increaseWritingSkills1 giveBackToCommunity1 increaseWritingSkills2 spreadAwareness reduceMisconceptions beOrganized makeNewFriends qualitySAServices1 engagementStudentAmbassadorsInPromotingAwareness acquireFundraisingSkills1 saSAreEnthusiastic1 qualitySAServices happinessStudentAmbassadors1 engageVolunteers giveBackToCommunity acquireVolunteerOutreachSkills2 highPresentationAttendance acquirePublicSpeakingSkills2 positiveReputationCS1 makeNewFriends2 reduceMisconceptions1 saSAreEnthusiastic))
