% CSSAProgram  (node/2 edge/3 dep/2 dec/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
node(acquireVolunteerOutreachSkills1,softgoal).
node(experienceForResume,softgoal).
node(speaches,resource).
node(improveImageToKids1,softgoal).
node(speakAtFundraisers,task).
node(acquirePublicSpeakingSkills1,softgoal).
node(attendSAMeetings,task).
leaf(attendSAMeetings).
node(increasedSAResources,softgoal).
node(acquireFundraisingSkills,softgoal).
node(increaseInvolvementOfSAS,softgoal).
node(makeNewFriends1,softgoal).
node(communityServiceHoursCompleted,goal).
topgoal(communityServiceHoursCompleted).
node(increaseSkills,softgoal).
node(trustOfKids,softgoal).
node(sendOutEmails1,task).
node(helpPutOnSATrainingConferences,task).
node(writeArticlesForNewspaper2,task).
node(providePromotionResources,task).
node(acquireFundraisingSkills2,softgoal).
node(createLifeLongVolunteerSpirit,softgoal).
node(saSAreOrganized1,softgoal).
node(expansionOfSAServices,softgoal).
node(runFundraiserInSchools,task).
node(schoolInitiatesPresenation1,task).
leaf(schoolInitiatesPresenation1).
node(createLifeLongVolunteerSpirit1,softgoal).
node(giveCSPresentations1,task).
node(planSocialEvents,task).
leaf(planSocialEvents).
node(getSpeaches,task).
node(runFundraiserInSchools2,task).
node(beConfident,softgoal).
node(getPromotionResources,task).
node(giveCSPresentations,task).
node(increasedSAResources1,softgoal).
leaf(increasedSAResources1).
node(saSAreOutgoing1,softgoal).
node(saSAreOrganized,softgoal).
node(happinessStudentAmbassadors,softgoal).
node(keepInTouchWithVolunteers,softgoal).
node(planAndPutOnReconnectionConferences1,task).
node(retrainSAS,task).
leaf(retrainSAS).
node(findHelpWithPresentations,task).
node(beEnthusiastic,softgoal).
node(haveTimeForSchool2,softgoal).
node(putOnSATrainingConferences,task).
node(improveImageToKids,softgoal).
node(positiveReputationCS,softgoal).
node(haveTimeForSchool1,softgoal).
node(putOnSATrainingConferences1,task).
node(writeArticlesForNewspaper1,task).
node(helpWithPresentations1,task).
node(askForHelpWithPresentations,task).
node(spreadAwareness1,softgoal).
node(sendOutEmails2,task).
node(trustOfKids1,softgoal).
node(acquireVolunteerOutreachSkills,softgoal).
node(planAndPutOnReconnectionConferences2,task).
node(saSAreOutgoing,softgoal).
node(happinessStudentAmbassadors2,softgoal).
node(promotionResources,resource).
node(beOutgoing,softgoal).
node(acquirePublicSpeakingSkills,softgoal).
node(communityServiceHoursCompleted2,goal).
topgoal(communityServiceHoursCompleted2).
node(saSAreConfident1,softgoal).
node(speakAtFundraisers3,task).
node(trainSAS,task).
leaf(trainSAS).
node(permissionForPresentationsBeGiven,goal).
leaf(permissionForPresentationsBeGiven).
topgoal(permissionForPresentationsBeGiven).
node(morePromotionResourcesAvailable,softgoal).
node(saSAreConfident,softgoal).
node(provideSpeaches,task).
leaf(provideSpeaches).
node(haveTimeForSchool,softgoal).
node(giveBackToCommunity2,softgoal).
node(runFundraiserInSchools1,task).
leaf(runFundraiserInSchools1).
node(increaseWritingSkills,softgoal).
node(kidsBeUsedToCommunicateWithOtherKids,goal).
leaf(kidsBeUsedToCommunicateWithOtherKids).
topgoal(kidsBeUsedToCommunicateWithOtherKids).
node(planAndPutOnReconnectionConferences,task).
node(helpPlanAndPutOnReconnectionConferences1,task).
node(increaseWritingSkills1,softgoal).
node(speakAtFundraisers2,task).
node(giveBackToCommunity1,softgoal).
node(increaseWritingSkills2,softgoal).
node(spreadAwareness,softgoal).
node(sendOutEmails,task).
leaf(sendOutEmails).
node(reduceMisconceptions,softgoal).
node(helpPutOnSATrainingConferences1,task).
node(helpWithPresentations,task).
leaf(helpWithPresentations).
node(attendCSMeetings,task).
leaf(attendCSMeetings).
node(beOrganized,softgoal).
node(makeNewFriends,softgoal).
node(qualitySAServices1,softgoal).
node(engagementStudentAmbassadorsInPromotingAwareness,softgoal).
node(acquireFundraisingSkills1,softgoal).
node(saSAreEnthusiastic1,softgoal).
node(promotionResources1,resource).
leaf(promotionResources1).
node(putOnSATrainingConferences2,task).
node(presenationBeInitiated,goal).
topgoal(presenationBeInitiated).
node(initiatePresentationWithSchools,task).
node(qualitySAServices,softgoal).
node(schoolInitiatesPresenation,task).
node(writeArticlesForNewspaper,task).
leaf(writeArticlesForNewspaper).
node(happinessStudentAmbassadors1,softgoal).
node(engageVolunteers,softgoal).
node(giveBackToCommunity,softgoal).
node(acquireVolunteerOutreachSkills2,softgoal).
node(giveCSPresentations2,task).
node(highPresentationAttendance,softgoal).
node(helpPlanAndPutOnReconnectionConferences,task).
node(communityServiceHoursCompleted1,goal).
topgoal(communityServiceHoursCompleted1).
node(acquirePublicSpeakingSkills2,softgoal).
node(positiveReputationCS1,softgoal).
leaf(positiveReputationCS1).
node(findHelpWithPresentations1,task).
node(makeNewFriends2,softgoal).
node(reduceMisconceptions1,softgoal).
node(saSAreEnthusiastic,softgoal).
node(speakAtFundraisers1,task).
node(giveCSPresentations3,task).
dep(saSAreOutgoing1,saSAreOutgoing).
edge(keepInTouchWithVolunteers,increaseInvolvementOfSAS,0.5).
dec(presenationBeInitiated,giveCSPresentations1,or).
edge(giveCSPresentations1,acquirePublicSpeakingSkills2,0.5).
edge(runFundraiserInSchools1,acquireFundraisingSkills2,0.5).
dep(speakAtFundraisers,speakAtFundraisers2).
edge(putOnSATrainingConferences,engageVolunteers,0.5).
edge(happinessStudentAmbassadors,saSAreEnthusiastic,0.5).
edge(retrainSAS,acquirePublicSpeakingSkills2,0.5).
edge(increaseSkills,happinessStudentAmbassadors2,0.5).
dep(saSAreConfident1,saSAreConfident).
edge(runFundraiserInSchools2,spreadAwareness,0.5).
dec(askForHelpWithPresentations,giveCSPresentations1,or).
edge(speakAtFundraisers,acquirePublicSpeakingSkills2,0.5).
edge(acquireVolunteerOutreachSkills,beOutgoing,0.5).
edge(planSocialEvents,makeNewFriends2,0.5).
dep(giveCSPresentations2,giveCSPresentations3).
dep(runFundraiserInSchools1,runFundraiserInSchools).
edge(makeNewFriends,happinessStudentAmbassadors2,0.5).
edge(acquireFundraisingSkills,beOrganized,0.5).
dep(providePromotionResources,promotionResources).
edge(saSAreEnthusiastic,engageVolunteers,0.5).
edge(acquireFundraisingSkills,beOutgoing,0.5).
edge(trainSAS,acquirePublicSpeakingSkills2,0.5).
dep(sendOutEmails1,sendOutEmails2).
dep(helpWithPresentations,helpWithPresentations1).
edge(writeArticlesForNewspaper1,spreadAwareness,0.5).
dep(reduceMisconceptions1,reduceMisconceptions).
edge(morePromotionResourcesAvailable,engageVolunteers,0.5).
dep(giveBackToCommunity1,giveBackToCommunity).
dep(speaches,getSpeaches).
edge(kidsBeUsedToCommunicateWithOtherKids,trustOfKids1,0.5).
edge(beOrganized,increaseSkills,0.5).
dep(helpPutOnSATrainingConferences1,putOnSATrainingConferences2).
edge(attendCSMeetings,acquireFundraisingSkills2,0.5).
dep(sendOutEmails,sendOutEmails1).
edge(planAndPutOnReconnectionConferences,increaseInvolvementOfSAS,0.5).
dep(trustOfKids1,trustOfKids).
edge(writeArticlesForNewspaper1,keepInTouchWithVolunteers,0.5).
dep(beOutgoing,saSAreOutgoing1).
edge(attendSAMeetings,makeNewFriends2,0.5).
edge(morePromotionResourcesAvailable,spreadAwareness,0.5).
dep(helpWithPresentations1,findHelpWithPresentations1).
dep(haveTimeForSchool2,haveTimeForSchool1).
dep(writeArticlesForNewspaper,writeArticlesForNewspaper2).
dep(haveTimeForSchool1,haveTimeForSchool).
edge(helpPutOnSATrainingConferences,makeNewFriends2,0.5).
dep(saSAreOrganized1,saSAreOrganized).
edge(planAndPutOnReconnectionConferences,keepInTouchWithVolunteers,0.5).
dep(writeArticlesForNewspaper2,writeArticlesForNewspaper1).
edge(happinessStudentAmbassadors,qualitySAServices1,0.5).
edge(sendOutEmails2,keepInTouchWithVolunteers,0.5).
edge(acquireVolunteerOutreachSkills,beConfident,0.5).
edge(provideSpeaches,qualitySAServices1,0.5).
dep(planAndPutOnReconnectionConferences1,planAndPutOnReconnectionConferences).
dec(initiatePresentationWithSchools,presenationBeInitiated,or).
edge(runFundraiserInSchools1,acquireVolunteerOutreachSkills2,0.5).
edge(retrainSAS,acquireFundraisingSkills2,0.5).
dep(helpPutOnSATrainingConferences,helpPutOnSATrainingConferences1).
dep(spreadAwareness,engagementStudentAmbassadorsInPromotingAwareness).
edge(trainSAS,acquireFundraisingSkills2,0.5).
edge(kidsBeUsedToCommunicateWithOtherKids,improveImageToKids1,0.5).
dep(spreadAwareness,spreadAwareness1).
edge(experienceForResume,happinessStudentAmbassadors2,0.5).
edge(highPresentationAttendance,expansionOfSAServices,0.5).
edge(happinessStudentAmbassadors,engageVolunteers,0.5).
dec(trainSAS,helpPutOnSATrainingConferences,or).
edge(acquirePublicSpeakingSkills,beOutgoing,0.5).
dep(planAndPutOnReconnectionConferences2,planAndPutOnReconnectionConferences1).
edge(speakAtFundraisers1,spreadAwareness,0.5).
edge(morePromotionResourcesAvailable,qualitySAServices1,0.5).
dep(giveBackToCommunity2,giveBackToCommunity1).
edge(qualitySAServices1,engageVolunteers,0.5).
edge(helpWithPresentations,giveBackToCommunity2,0.5).
edge(saSAreConfident,qualitySAServices1,0.5).
dec(writeArticlesForNewspaper,communityServiceHoursCompleted1,or).
dep(runFundraiserInSchools,runFundraiserInSchools2).
dep(happinessStudentAmbassadors2,happinessStudentAmbassadors1).
edge(increaseInvolvementOfSAS,expansionOfSAServices,0.5).
dep(acquireFundraisingSkills1,acquireFundraisingSkills).
edge(acquirePublicSpeakingSkills,beConfident,0.5).
dep(saSAreEnthusiastic1,saSAreEnthusiastic).
dec(attendCSMeetings,communityServiceHoursCompleted1,or).
dep(acquirePublicSpeakingSkills1,acquirePublicSpeakingSkills).
dep(promotionResources1,providePromotionResources).
edge(positiveReputationCS,engageVolunteers,0.5).
dec(attendSAMeetings,communityServiceHoursCompleted1,or).
edge(positiveReputationCS,highPresentationAttendance,0.5).
dep(provideSpeaches,speaches).
dep(helpPlanAndPutOnReconnectionConferences,helpPlanAndPutOnReconnectionConferences1).
dep(permissionForPresentationsBeGiven,initiatePresentationWithSchools).
edge(trainSAS,acquireVolunteerOutreachSkills2,0.5).
dep(beEnthusiastic,saSAreEnthusiastic1).
dep(happinessStudentAmbassadors1,happinessStudentAmbassadors).
dec(giveCSPresentations1,communityServiceHoursCompleted1,or).
dep(makeNewFriends1,makeNewFriends).
dec(sendOutEmails,findHelpWithPresentations1,or).
edge(communityServiceHoursCompleted1,haveTimeForSchool2,-0.5).
dep(beOrganized,saSAreOrganized1).
dep(increaseWritingSkills1,increaseWritingSkills).
dep(findHelpWithPresentations,askForHelpWithPresentations).
edge(writeArticlesForNewspaper,increaseWritingSkills2,0.5).
dep(qualitySAServices1,qualitySAServices).
edge(retrainSAS,acquireVolunteerOutreachSkills2,0.5).
edge(increaseSkills,experienceForResume,0.5).
edge(runFundraiserInSchools1,acquirePublicSpeakingSkills2,0.5).
dep(speakAtFundraisers1,speakAtFundraisers3).
edge(providePromotionResources,qualitySAServices1,0.5).
edge(happinessStudentAmbassadors,saSAreOutgoing,0.5).
dep(acquirePublicSpeakingSkills2,acquirePublicSpeakingSkills1).
dep(promotionResources,getPromotionResources).
dep(putOnSATrainingConferences1,putOnSATrainingConferences).
edge(speakAtFundraisers1,reduceMisconceptions1,0.5).
dep(putOnSATrainingConferences2,putOnSATrainingConferences1).
edge(haveTimeForSchool,happinessStudentAmbassadors2,0.5).
dep(communityServiceHoursCompleted1,communityServiceHoursCompleted).
dec(helpPutOnSATrainingConferences,communityServiceHoursCompleted1,or).
dep(beConfident,saSAreConfident1).
edge(giveBackToCommunity,happinessStudentAmbassadors2,0.5).
edge(communityServiceHoursCompleted2,happinessStudentAmbassadors2,0.5).
edge(acquireVolunteerOutreachSkills,beEnthusiastic,0.5).
edge(increasedSAResources1,morePromotionResourcesAvailable,0.5).
edge(saSAreOrganized,qualitySAServices1,0.5).
dep(acquireVolunteerOutreachSkills1,acquireVolunteerOutreachSkills).
edge(acquirePublicSpeakingSkills,beEnthusiastic,0.5).
edge(attendCSMeetings,acquireVolunteerOutreachSkills2,0.5).
edge(kidsBeUsedToCommunicateWithOtherKids,qualitySAServices1,0.5).
edge(acquireFundraisingSkills,beEnthusiastic,0.5).
dep(positiveReputationCS1,positiveReputationCS).
dep(communityServiceHoursCompleted,communityServiceHoursCompleted2).
edge(helpPlanAndPutOnReconnectionConferences,acquirePublicSpeakingSkills2,0.5).
dep(acquireFundraisingSkills2,acquireFundraisingSkills1).
edge(giveCSPresentations2,reduceMisconceptions1,0.5).
dep(improveImageToKids1,improveImageToKids).
dep(createLifeLongVolunteerSpirit1,createLifeLongVolunteerSpirit).
edge(helpPlanAndPutOnReconnectionConferences,acquireVolunteerOutreachSkills2,0.5).
edge(runFundraiserInSchools1,giveBackToCommunity2,0.5).
dec(getPromotionResources,giveCSPresentations1,or).
dep(acquireVolunteerOutreachSkills2,acquireVolunteerOutreachSkills1).
dep(makeNewFriends2,makeNewFriends1).
edge(spreadAwareness,expansionOfSAServices,0.5).
edge(engageVolunteers,createLifeLongVolunteerSpirit1,0.5).
edge(speakAtFundraisers,giveBackToCommunity2,0.5).
dep(helpPlanAndPutOnReconnectionConferences1,planAndPutOnReconnectionConferences2).
dec(runFundraiserInSchools1,communityServiceHoursCompleted1,or).
edge(beConfident,increaseSkills,0.5).
dec(askForHelpWithPresentations,speakAtFundraisers,or).
dec(retrainSAS,helpPlanAndPutOnReconnectionConferences,or).
edge(beOutgoing,makeNewFriends,0.5).
edge(writeArticlesForNewspaper,makeNewFriends2,0.5).
dep(findHelpWithPresentations1,findHelpWithPresentations).
edge(happinessStudentAmbassadors,increaseInvolvementOfSAS,0.5).
dep(giveCSPresentations,giveCSPresentations2).
edge(giveCSPresentations1,giveBackToCommunity2,0.5).
dec(schoolInitiatesPresenation,presenationBeInitiated,or).
edge(giveCSPresentations2,spreadAwareness,0.5).
dec(helpPlanAndPutOnReconnectionConferences,communityServiceHoursCompleted1,or).
dep(speakAtFundraisers2,speakAtFundraisers1).
dep(giveCSPresentations1,giveCSPresentations).
edge(helpWithPresentations,makeNewFriends2,0.5).
edge(speakAtFundraisers,acquireFundraisingSkills2,0.5).
edge(engageVolunteers,expansionOfSAServices,0.5).
dep(increaseWritingSkills2,increaseWritingSkills1).
dep(increasedSAResources1,increasedSAResources).
edge(giveCSPresentations1,acquireVolunteerOutreachSkills2,0.5).
dec(speakAtFundraisers,communityServiceHoursCompleted1,or).
dep(schoolInitiatesPresenation1,schoolInitiatesPresenation).
edge(providePromotionResources,morePromotionResourcesAvailable,-0.5).
