;;;; models/CSServices.lisp : GENERATED from models/CSServices.py by to-lisp.py
(<- acquireFeedback (and feedback1 feedback implementFeedbackCollection))
(<- acquireServiceResources serviceResources)
(<- acquireWebContent webSiteContent)
(<- anonymityCounsellors1 anonymityCounsellors)
(<- anonymityKids anonymityKids1)
(<- anonymityKids1 anonymityKids4)
(<- anonymityKids2 (and anonymityKids3 anonymityKids5))
(<- anonymityKids4 anonymityKids2)
(<- anonymityKids6 (and anonymityParents3 anonymityParents4))
(<- anonymityKids7 anonymityKids)
(<- anonymityParents anonymityParents1)
(<- anonymityParents1 anonymityParents2)
(<- anonymityParents2 (or anonymityKids6 (breaks traceCalls)))
(<- anonymityParents5 anonymityParents)
(<- anonymousTechnologyBeUsed (or kidsUseBulletinBoardWithReplies kidsUseVoiceCounselling kidsUseAskACounsellorSection))
(<- availabilityServices availableServices1)
(<- availableServices availableServices1)
(<- availableServices1 availableServices2)
(<- availableServices2 (and availableServices4 availableServices3))
(<- availableServices5 availableServices1)
(<- avoidBadAdvice1 avoidBadAdvice2)
(<- avoidBadAdvice2 (and avoidBadAdvice3 avoidBadAdvice))
(<- avoidBadAdvice4 avoidBadAdvice5)
(<- avoidBadAdvice5 avoidBadAdvice1)
(<- avoidDialogues avoidDialoguesBetweenKids)
(<- avoidPresenceOfPedofiles (or avoidPresenceOfPedofiles1 (and (helps controlWebServices) (breaks kidsUseBulletinBoardWithDelayedModeration))))
(<- avoidPresenceOfPedofiles2 avoidPresenceOfPedofiles1)
(<- confidentialTechnologyBeUsed (or kidsUseVideoCounselling kidsUseVoiceCounselling kidsUseOneOnOneChatRooms kidsUseEmailCounselling kidsUseTextMessaging))
(<- confidentialityKids2 confidentialityKids1)
(<- confidentialityKids3 confidentialityKids2)
(<- confidentialityKids4 confidentialityKids3)
(<- confidentialityKids5 confidentialityKids4)
(<- confidentialityKids6 (or confidentialityKids2 (helps kidsUsePhoneCounselling)))
(<- confidentialityKids7 confidentialityKids5)
(<- confidentialityParents confidentialityParents1)
(<- confidentialityParents1 confidentialityParents2)
(<- confidentialityParents2 (or confidentialityParents3 (hurts traceCalls)))
(<- confidentialityParents3 (and confidentialityParents5 confidentialityParents4))
(<- confidentialityServices confidentialityParents)
(<- connectBackToTheCommunity connectBackToTheCommunity9)
(<- connectBackToTheCommunity10 connectBackToTheCommunity9)
(<- connectBackToTheCommunity42 (and connectBackToTheCommunity2 connectBackToTheCommunity3))
(<- connectBackToTheCommunity5 connectBackToTheCommunity42)
(<- connectBackToTheCommunity6 connectBackToTheCommunity7)
(<- connectBackToTheCommunity7 (and connectBackToTheCommunity4 connectBackToTheCommunity1))
(<- connectBackToTheCommunity8 (and connectBackToTheCommunity6 connectBackToTheCommunity5))
(<- connectBackToTheCommunity9 connectBackToTheCommunity8)
(<- connectToOtherKids technologyThatAllowsDialoguesBetweenKidsBeUsed)
(<- controlOfCounsellingWork controlOfCounsellingWork1)
(<- controlWebServices1 (or controlWebServices2 (helps sufficientCounsellingResources)))
(<- controlWebServices2 controlWebServices)
(<- correctInterpretationOfCounsel (or correctInterpretationOfCounsel1 (and (hurts kidsUseBulletinBoardWithDelayedModeration) (helps kidsUseVoiceCounselling) (hurts kidsUseEmailCounselling) (hurts kidsUseOneOnOneChatRooms) (hurts kidsUseAskACounsellorSection) (hurts kidsUseCyberCafPortalChatRoom) (helps kidsUseVideoCounselling) (hurts kidsUseTextMessaging) (hurts kidsUseBulletinBoardWithReplies))))
(<- counsellorsBeProfessionallyTrained counsellorsBeProfessionallyTrained1)
(<- decreasePhoneWaitingTime accommodatePhoneTraffic)
(<- decreasePhoneWaitingTime1 decreasePhoneWaitingTime2)
(<- decreaseResponseTIme1 decreaseResponseTIme)
(<- decreaseResponseTIme2 (or (and decreaseResponseTIme1 decreaseResponseTIme3) (helps sufficientCounsellingResources)))
(<- decreaseResponseTIme3 decreaseResponseTIme4)
(<- directResponseToKids1 directResponseToKids)
(<- directResponseToKids2 directResponseToKids1)
(<- easierAccessToPostReply1 easierAccessToPostReply)
(<- easierNavigationCSWebServices easierNavigationCSWebServices1)
(<- easierNavigationCSWebServices2 easierNavigationCSWebServices)
(<- easierToFindPostsWebPostingTechnology1 easierToFindPostsWebPostingTechnology)
(<- easyAccessToPostReply1 easyAccessToPostReply)
(<- efficientPhoneServices efficientPhoneServices1)
(<- efficientPhoneServices1 efficientPhoneServices2)
(<- efficientServices efficientServices1)
(<- efficientWebServices efficientWebServices1)
(<- efficientWebServices1 efficientWebServices2)
(<- empoweringKidsToHelpThemselves1 empoweringKidsToHelpThemselves)
(<- encourageKidsUsingWebServicesToUsePhoneServices encourageKidsUsingWebServicesToUsePhoneServices1)
(<- friendlyWebSite friendlyWebSite12)
(<- friendlyWebSite1 friendlyWebSite2)
(<- highQualityServices1 highQualityServices)
(<- highQualityServices2 highQualityServices)
(<- immediacy immediacy1)
(<- immediacy1 (and immediacy2 immediacy3))
(<- immediacy3 (and immediacy5 immediacy4))
(<- immediacy4 immediacy6)
(<- immediacy5 immediacy7)
(<- immediacy8 immediacy)
(<- immediacyServices immediacy)
(<- implementBoardWithReplies1 implementBoardWithReplies)
(<- implementBulletinBoardWithDelayedModeration (and moderateDiscussionBoards implementBulletinBoardWithDelayedModeration1 createCounsellingPosts))
(<- implementBulletinBoardWithReplies (and implementBulletinBoardWithReplies1 createCounsellingPosts moderateDiscussionBoards))
(<- implementCyberCafPortalChatRoom (or (and provideWrittenCounselling moderateAChat implementFilters) (and provideWrittenCounselling moderateAChat blockKidsWhoDisplayInappropriateBehavoir) (and provideWrittenCounselling moderateAChat scheduleChatAtSpecificTimes) (and provideWrittenCounselling moderateAChat implementDelay)))
(<- implementCyberCafPortalChatRoom1 implementCyberCafPortalChatRoom)
(<- implementEmailCounselling implementEmailCounselling1)
(<- implementEmailCounselling1 performEmailCounselling)
(<- implementFeedbackCollection (or implementFeedbackForm2 implementPhoneFeedback2))
(<- implementFeedbackForm obtainNeededSoftware)
(<- implementFeedbackForm1 implementFeedbackForm)
(<- implementFeedbackForm2 implementFeedbackForm1)
(<- implementGeneralQuestionsAndAnswers putContentOntoWebsite)
(<- implementGeneralQuestionsAndAnswers1 implementGeneralQuestionsAndAnswers)
(<- implementGetInformedSectionOfWebSite putContentOntoWebsite)
(<- implementGetInformedSectionOfWebSite1 implementGetInformedSectionOfWebSite)
(<- implementInformationSection1 implementInformationSection)
(<- implementNToolToAllowParentsToTalkToEachOther1 implementNToolToAllowParentsToTalkToEachOther)
(<- implementOneOnOneChatRooms (and implementOneOnOneChatRooms1 provideWrittenCounselling))
(<- implementPhoneFeedback implementPhoneFeedback3)
(<- implementPhoneFeedback1 implementPhoneFeedback)
(<- implementPhoneFeedback2 implementPhoneFeedback1)
(<- implementPollsAboutKids putContentOntoWebsite)
(<- implementPollsAboutKids1 kidsReadPollsAboutKids)
(<- implementServices (or maintainImplementCSServices maintainImplementPHLServices2 maintainPhoneServices2 maintainWebServices1))
(<- implementTextMessaging (and implementTextMessaging1 provideWrittenCounselling))
(<- implementVideoCounselling implementVideoCounselling1)
(<- implementVideoCounselling1 provideWebCounsellingWithVideo)
(<- implementVoiceCounselling (and provideWebCounsellingWithAudio implementVoiceCounselling1))
(<- improveImageToKids1 improveImageToKids)
(<- improveWebsiteContent improveWebsiteContent1)
(<- improveWebsiteContent2 improveWebsiteContent)
(<- increaseEmphasisOnOnlineFeedbackForm increaseEmphasisOnOnlineFeedbackForm1)
(<- increaseNumberOfServices1 increaseNumberOfServices)
(<- increasePhoneResources1 increasePhoneResources2)
(<- increasePhoneResources2 increasePhoneResources)
(<- increaseResourcesServices (or increaseResourcesServices1 (and (helps increaseWebResources2) (helps increasePhoneResources))))
(<- increaseWebResources (or increaseWebResources1 (helps onlyOnlineRequestFromCanadiansAccepted)))
(<- increaseWebResources1 increaseWebResources2)
(<- increasedWebServices increasedWebServices1)
(<- increasedWebServices1 increasedWebServices2)
(<- increasedWebServices2 increasedWebServices3)
(<- increasedWebServices3 increasedWebServices4)
(<- informKidsAboutAnonymityKidsOfWebServices informKidsAboutAnonymityKidsOfWebServices1)
(<- kidsGetInformationThroughECounselling moderatedECounsellingBeUsed)
(<- kidsHaveOwnershipOfServices2 (and kidsHaveOwnershipOfServices1 kidsHaveOwnershipOfServices))
(<- kidsHaveOwnershipOfServices3 kidsHaveOwnershipOfServices2)
(<- kidsHaveOwnershipOfServices4 kidsHaveOwnershipOfServices3)
(<- kidsHaveOwnershipOfServices5 (and kidsHaveOwnershipOfServices6 kidsHaveOwnershipOfServices4))
(<- kidsReadGeneralQuestionsAndAnswers (and kidsReadGeneralQuestionsAndAnswers1 implementGeneralQuestionsAndAnswers))
(<- kidsReadGetInformedSectionOfWebSite (and kidsUseGetInformedSectionOfWebSite implementGetInformedSectionOfWebSite))
(<- kidsReadPollsAboutKids (and kidsReadPollsAboutKids1 implementPollsAboutKids))
(<- kidsUseAskACounsellorSection (and kidsUseAskACounsellorSection1 maintainAskACounsellorSection))
(<- kidsUseBulletinBoardWithDelayedModeration (and kidsUseBulletinBoardWithDelayedModeration1 implementBulletinBoardWithDelayedModeration))
(<- kidsUseBulletinBoardWithReplies (and kidsUseBulletinBoardWithReplies1 implementBulletinBoardWithReplies))
(<- kidsUseCyberCafPortalChatRoom (and kidsUseCyberCafPortalChatRoom1 implementCyberCafPortalChatRoom))
(<- kidsUseEmailCounselling (and kidsUseEmailCounselling1 implementEmailCounselling1))
(<- kidsUseOneOnOneChatRooms implementOneOnOneChatRooms)
(<- kidsUseOneOnOneChatRooms1 kidsUseOneOnOneChatRooms)
(<- kidsUseOnlineInformationProvided (or kidsReadPollsAboutKids kidsReadGeneralQuestionsAndAnswers kidsGetInformationThroughECounselling kidsReadGetInformedSectionOfWebSite))
(<- kidsUsePhoneCounselling (and kidsUsePhoneCounselling1 maintainCSPhoneServices2))
(<- kidsUseTextMessaging implementTextMessaging)
(<- kidsUseTextMessaging1 kidsUseTextMessaging)
(<- kidsUseVideoCounselling (and kidsUseVideoCounselling1 implementVideoCounselling1))
(<- kidsUseVoiceCounselling (and kidsUseVoiceCounselling1 implementVoiceCounselling))
(<- maintainAskACounsellorSection (and moderateDiscussionBoards maintainAskACounsellorSection1 createCounsellingPosts))
(<- maintainCSPhoneServices maintainCSPhoneServices1)
(<- maintainCSPhoneServices1 maintainCSPhoneServices2)
(<- maintainCSPhoneServices2 (and voiceCounsellingBePerformed answer80OfCallsWithin30SecondsOfMessageEnding))
(<- maintainCSPhoneServices3 maintainCSPhoneServices1)
(<- maintainImplementCSServices (and maintainImplementCSServices1 acquireServiceResources))
(<- maintainImplementCSServices1 maintainImplementCSServices2)
(<- maintainImplementCSServices2 (or maintainCSPhoneServices3 maintainImplementCSWebServices3))
(<- maintainImplementCSServices3 maintainImplementCSServices)
(<- maintainImplementCSWebServices (or kidsUseOnlineInformationProvided moderatedECounsellingBeUsed))
(<- maintainImplementCSWebServices1 maintainImplementCSWebServices2)
(<- maintainImplementCSWebServices2 maintainImplementCSWebServices)
(<- maintainImplementCSWebServices3 maintainImplementCSWebServices2)
(<- maintainImplementPHLServices (or maintainPHLPhoneServices3 maintainPHLWebServices3))
(<- maintainImplementPHLServices1 maintainImplementPHLServices)
(<- maintainImplementPHLServices2 (and maintainImplementPHLServices1 acquireServiceResources))
(<- maintainImplementPHLServices3 maintainImplementPHLServices2)
(<- maintainPHLPhoneServices maintainPHLPhoneServices1)
(<- maintainPHLPhoneServices1 maintainPHLPhoneServices2)
(<- maintainPHLPhoneServices2 (and voiceCounsellingBePerformed maintainPHLPhoneServices4 provideRecordedMessages))
(<- maintainPHLPhoneServices3 maintainPHLPhoneServices1)
(<- maintainPHLWebServices maintainPHLWebServices1)
(<- maintainPHLWebServices1 maintainPHLWebServices2)
(<- maintainPHLWebServices2 (or implementNToolToAllowParentsToTalkToEachOther implementBoardWithReplies implementInformationSection))
(<- maintainPHLWebServices3 maintainPHLWebServices1)
(<- maintainPhoneServices (or maintainCSPhoneServices maintainPHLPhoneServices telephonyBeImplementedAndManaged))
(<- maintainPhoneServices1 maintainCSPhoneServices2)
(<- maintainPhoneServices2 (and maintainPhoneServices3 acquireServiceResources))
(<- maintainPhoneServices3 maintainPhoneServices)
(<- maintainPhoneServices4 maintainPhoneServices2)
(<- maintainServicesAboveCompetition maintainServicesAboveCompetition1)
(<- maintainWebServices (or maintainPHLWebServices maintainImplementCSWebServices1 obtainSoftware))
(<- maintainWebServices1 (and maintainWebServices2 acquireServiceResources))
(<- maintainWebServices2 maintainWebServices)
(<- maintainWebServices3 maintainWebServices1)
(<- measureSuccessOfServices (and measureSuccessOfServices2 measureSuccessOfServices1))
(<- measureSuccessOfServices1 (or measureSuccessOfServices3 (helps implementFeedbackForm)))
(<- measureSuccessOfServices3 measureSuccessOfServices4)
(<- moderatedECounsellingBeUsed (or kidsUseVoiceCounselling kidsUseBulletinBoardWithDelayedModeration kidsUseEmailCounselling kidsUseTextMessaging kidsUseAskACounsellorSection kidsUseBulletinBoardWithReplies kidsUseCyberCafPortalChatRoom kidsUseOneOnOneChatRooms kidsUseVideoCounselling))
(<- nonAnonymousTechnologyBeUsed (or kidsUseEmailCounselling kidsUseCyberCafPortalChatRoom kidsUseOneOnOneChatRooms kidsUseVideoCounselling kidsUseTextMessaging))
(<- nonConfidentialTechnologyBeUsed (or kidsUseCyberCafPortalChatRoom kidsUseBulletinBoardWithReplies kidsUseBulletinBoardWithDelayedModeration kidsUseAskACounsellorSection))
(<- nonRealTimeECounsellingBeUsed (or kidsUseBulletinBoardWithReplies kidsUseAskACounsellorSection kidsUseEmailCounselling kidsUseBulletinBoardWithDelayedModeration))
(<- obtainNeededSoftware feedbackFormSoftware)
(<- obtainSoftware webSoftware)
(<- obtainWebServer webServer)
(<- parentsUseBulletinBoardWithReplies (and parentsUseBulletinBoardWithReplies1 implementBoardWithReplies))
(<- parentsUseInformationSection (and parentsUseInformationSection1 implementInformationSection))
(<- parentsUseNToolToAllowParentsToTalkToEachOther (and parentsUseNToolToAllowParentsToTalkToEachOther1 implementNToolToAllowParentsToTalkToEachOther))
(<- parentsUsePhoneCounselling parentsUsePhoneCounselling1)
(<- parentsUsePhoneCounselling1 maintainPHLPhoneServices2)
(<- phoneLibraryOfRecordedMessages provideRecordedMessages)
(<- putContentOntoWebsite (and putContentOntoWebsite1 acquireWebContent))
(<- qualityServices highQualityServices)
(<- realTimeECounsellingBeUsed (or kidsUseOneOnOneChatRooms kidsUseTextMessaging kidsUseVideoCounselling kidsUseCyberCafPortalChatRoom))
(<- reduceContagionEffectOfHarmfulActions1 reduceContagionEffectOfHarmfulActions)
(<- reduceNumberOfStepsWebPostingTechnology reduceNumberOfStepsWebPostingTechnology1)
(<- reducePrankCalls1 (or reducePrankCalls (and (hurts confidentialityKids) (helps implementAntiPrankingMessage))))
(<- relevanceInKidsLives (or relevanceInKidsLives1 (helps highQualityServices)))
(<- relevanceInKidsLives1 relevanceInKidsLives2)
(<- servicesBeBilingual servicesBeBilingual1)
(<- servicesBeProvidedForKidsBullyingLine maintainImplementCSServices)
(<- servicesBeProvidedForKidsBullyingLine1 servicesBeProvidedForKidsBullyingLine)
(<- similarityOfProblems1 similarityOfProblems)
(<- similarityWithOtherParentsProblems1 similarityWithOtherParentsProblems)
(<- strategicBluePrintForWebsiteBeFollowed strategicBluePrint)
(<- sufficientCounsellingResources sufficientCounsellingResources1)
(<- sufficientCounsellingResources2 sufficientCounsellingResources1)
(<- sufficientlyModeratedWebServices sufficientlyModeratedWebServices1)
(<- sufficientlyModeratedWebServices1 sufficientlyModeratedWebServices2)
(<- sufficientlyModeratedWebServices2 (or sufficientlyModeratedWebServices3 (helps sufficientCounsellingResources)))
(<- sufficientlyModeratedWebServices3 sufficientlyModeratedWebServices4)
(<- technologyThatAllowsDialoguesBetweenKidsBeUsed (or kidsUseCyberCafPortalChatRoom kidsUseBulletinBoardWithReplies kidsUseBulletinBoardWithDelayedModeration))
(<- technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed (or kidsUseOneOnOneChatRooms kidsUseTextMessaging kidsUseVideoCounselling kidsUseVoiceCounselling kidsUseAskACounsellorSection kidsUseEmailCounselling))
(<- telephonyBeImplementedAndManaged telephonyBeImplementedAndManaged1)
(<- webServicesSelfServe webServicesSelfServe1)
(<- webServicesSelfServe1 webServicesSelfServe2)
(<- webServicesSelfServe2 (or webServicesSelfServe3 (and (helps kidsReadGetInformedSectionOfWebSite) (helps kidsReadGeneralQuestionsAndAnswers) (helps kidsReadPollsAboutKids))))
(<- accommodatePhoneTraffic (and (helps sufficientCounsellingResources2) (helps increasePhoneResources1)))
(<- accommodateWebSiteTraffic (and (helps webServicesSelfServe) (makes sufficientCounsellingResources)))
(<- anonymity (and (helps anonymityParents) (helps anonymityKids) (hurts acquireFeedback)))
(<- anonymityCounsellors (and (helps kidsUseBulletinBoardWithReplies) (hurts kidsUseVideoCounselling) (helps kidsUseOneOnOneChatRooms) (hurts kidsUseEmailCounselling) (hurts directResponseToKids) (helps kidsUseBulletinBoardWithDelayedModeration) (helps kidsUseTextMessaging) (helps kidsUseAskACounsellorSection) (helps kidsUseCyberCafPortalChatRoom)))
(<- anonymityKids3 (and (breaks nonAnonymousTechnologyBeUsed) (makes anonymousTechnologyBeUsed)))
(<- anonymityKids5 (makes kidsUsePhoneCounselling))
(<- anonymityParents3 (helps parentsUseBulletinBoardWithReplies))
(<- anonymityParents4 (makes parentsUsePhoneCounselling1))
(<- availableServices3 (makes maintainPhoneServices))
(<- availableServices4 (hurts maintainWebServices))
(<- avoidBadAdvice (and (helps avoidPresenceOfPedofiles) (helps nonRealTimeECounsellingBeUsed) (hurts realTimeECounsellingBeUsed) (hurts technologyThatAllowsDialoguesBetweenKidsBeUsed) (helps technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed) (helps avoidDialoguesBetweenKids)))
(<- avoidBadAdvice3 (hurts parentsUseNToolToAllowParentsToTalkToEachOther))
(<- avoidDialoguesBetweenKids (and (makes technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed) (breaks technologyThatAllowsDialoguesBetweenKidsBeUsed)))
(<- avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb (and (hurts kidsUseVideoCounselling) (hurts kidsUseBulletinBoardWithReplies) (hurts kidsUseBulletinBoardWithDelayedModeration) (hurts kidsUseCyberCafPortalChatRoom) (hurts kidsUseTextMessaging) (hurts kidsUseEmailCounselling) (hurts kidsUseVoiceCounselling) (helps kidsUseAskACounsellorSection) (hurts kidsUseOneOnOneChatRooms)))
(<- confidentiality (and (hurts acquireFeedback) (helps confidentialityParents) (helps confidentialityKids5)))
(<- confidentialityKids1 (and (makes confidentialTechnologyBeUsed) (breaks nonConfidentialTechnologyBeUsed)))
(<- confidentialityParents4 (breaks parentsUseBulletinBoardWithReplies))
(<- confidentialityParents5 (helps parentsUsePhoneCounselling1))
(<- connectBackToTheCommunity1 (helps kidsUsePhoneCounselling))
(<- connectBackToTheCommunity2 (helps parentsUsePhoneCounselling1))
(<- connectBackToTheCommunity3 (and (helps parentsUseNToolToAllowParentsToTalkToEachOther) (helps parentsUseInformationSection) (helps parentsUseBulletinBoardWithReplies)))
(<- connectBackToTheCommunity4 (helps kidsUseOnlineInformationProvided))
(<- controlOfCounsellingWork1 (hurts moderatedECounsellingBeUsed))
(<- controlWebServices (and (hurts anonymousTechnologyBeUsed) (helps technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed) (hurts realTimeECounsellingBeUsed) (hurts kidsUseBulletinBoardWithDelayedModeration) (helps nonRealTimeECounsellingBeUsed) (helps nonAnonymousTechnologyBeUsed) (hurts technologyThatAllowsDialoguesBetweenKidsBeUsed)))
(<- decreasePhoneWaitingTime2 (helps answer80OfCallsWithin30SecondsOfMessageEnding))
(<- decreaseResponseTIme (and (makes realTimeECounsellingBeUsed) (hurts nonRealTimeECounsellingBeUsed)))
(<- directResponseToKids (and (breaks kidsUseBulletinBoardWithDelayedModeration) (helps easierAccessToPostReply) (makes kidsUseEmailCounselling) (makes realTimeECounsellingBeUsed) (breaks kidsUseAskACounsellorSection) (breaks kidsUseBulletinBoardWithReplies)))
(<- easierAccessToPostReply (helps kidsUseAskACounsellorSection))
(<- easierNavigationCSWebServices1 (helps easierAccessToPostReply))
(<- easierToFindPostsWebPostingTechnology (and (helps kidsUseAskACounsellorSection) (helps kidsUseBulletinBoardWithReplies) (hurts kidsUseBulletinBoardWithDelayedModeration)))
(<- easyAccessToPostReply (hurts parentsUseBulletinBoardWithReplies))
(<- efficientPhoneServices2 (helps accommodatePhoneTraffic))
(<- efficientServices1 (and (helps efficientPhoneServices) (helps serviceLevelsBeMet) (helps decreaseResponseTIme4)))
(<- efficientWebServices2 (and (helps easierNavigationCSWebServices2) (helps accommodateWebSiteTraffic)))
(<- empoweringKidsToHelpThemselves (helps kidsUseOnlineInformationProvided))
(<- encourageKidsUsingWebServicesToUsePhoneServices1 (helps avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb))
(<- friendlyWebSite12 (helps immediacy6))
(<- friendlyWebSite2 (and (helps easierNavigationCSWebServices1) (helps immediacy7) (helps increasedWebServices4) (helps directResponseToKids)))
(<- highQualityServices (and (helps serviceLevelsBeMet) (helps counsellorsBeProfessionallyTrained) (helps relevanceInKidsLives) (helps anonymity) (helps connectBackToTheCommunity9) (helps confidentialityKids5) (helps efficientServices1) (helps immediacy) (helps avoidBadAdvice4) (helps kidsHaveOwnershipOfServices5) (helps improveWebsiteContent2) (helps avoidPresenceOfPedofiles2) (helps directResponseToKids2) (helps sufficientlyModeratedWebServices)))
(<- immediacy2 (helps maintainPhoneServices))
(<- immediacy6 (and (helps parentsUseNToolToAllowParentsToTalkToEachOther) (hurts parentsUseBulletinBoardWithReplies)))
(<- immediacy7 (and (makes realTimeECounsellingBeUsed) (helps decreaseResponseTIme) (hurts nonRealTimeECounsellingBeUsed)))
(<- improveImageToKids (and (helps anonymityKids3) (helps confidentialityKids1) (helps avoidPresenceOfPedofiles) (helps decreaseResponseTIme) (helps relevanceInKidsLives2) (helps maintainServicesAboveCompetition1) (helps directResponseToKids) (helps moderatedECounsellingBeUsed) (helps kidsUseOnlineInformationProvided) (helps easierAccessToPostReply)))
(<- improveWebsiteContent1 (and (helps webSiteContentBeUpdatedDaily) (helps increaseWebResources)))
(<- increaseNumberOfServices (helps increasedWebServices))
(<- increasedWebServices4 (and (helps kidsUseTextMessaging) (helps kidsUseEmailCounselling) (helps kidsUseOneOnOneChatRooms) (helps kidsUseAskACounsellorSection) (helps kidsUseBulletinBoardWithDelayedModeration) (helps kidsUseVoiceCounselling) (helps kidsUseCyberCafPortalChatRoom) (helps kidsUseVideoCounselling) (helps kidsUseBulletinBoardWithReplies)))
(<- kidsHaveOwnershipOfServices (and (helps informKidsAboutAnonymityKidsOfWebServices1) (helps moderatedECounsellingBeUsed)))
(<- kidsHaveOwnershipOfServices1 (makes kidsUsePhoneCounselling))
(<- maintainServicesAboveCompetition1 (helps moderatedECounsellingBeUsed))
(<- measureSuccessOfServices2 (helps implementPhoneFeedback))
(<- measureSuccessOfServices4 (helps increaseEmphasisOnOnlineFeedbackForm1))
(<- reduceContagionEffectOfHarmfulActions (and (hurts kidsUseBulletinBoardWithDelayedModeration) (helps implementDelay) (helps effectiveChatRoomFilters) (helps avoidDialoguesBetweenKids) (helps scheduleChatAtSpecificTimes)))
(<- reduceNumberOfStepsWebPostingTechnology1 (and (helps kidsUseBulletinBoardWithDelayedModeration) (hurts kidsUseBulletinBoardWithReplies) (hurts maintainAskACounsellorSection)))
(<- similarityOfProblems (and (hurts technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed) (helps kidsReadPollsAboutKids) (helps technologyThatAllowsDialoguesBetweenKidsBeUsed) (helps kidsReadGeneralQuestionsAndAnswers) (helps kidsReadGetInformedSectionOfWebSite)))
(<- similarityWithOtherParentsProblems (and (helps parentsUseBulletinBoardWithReplies) (helps parentsUseNToolToAllowParentsToTalkToEachOther)))
(<- sufficientlyModeratedWebServices4 (hurts kidsUseBulletinBoardWithDelayedModeration))
(defparameter *hard* '(answer80OfCallsWithin30SecondsOfMessageEnding anonymousTechnologyBeUsed servicesBeBilingual1 counsellorsBeProfessionallyTrained nonRealTimeECounsellingBeUsed servicesBeBilingual nonAnonymousTechnologyBeUsed servicesBeProvidedForKidsBullyingLine confidentialTechnologyBeUsed technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed servicesBeProvidedForKidsBullyingLine1 onlyOnlineRequestFromCanadiansAccepted nonConfidentialTechnologyBeUsed kidsUseOnlineInformationProvided technologyThatAllowsDialoguesBetweenKidsBeUsed strategicBluePrintForWebsiteBeFollowed webSiteContentBeUpdatedDaily realTimeECounsellingBeUsed counsellorsBeProfessionallyTrained1 telephonyBeImplementedAndManaged1 moderatedECounsellingBeUsed telephonyBeImplementedAndManaged serviceLevelsBeMet))
(defparameter *soft* '(decreaseResponseTIme1 increasedWebServices3 increaseWebResources2 friendlyWebSite1 confidentialityKids6 connectBackToTheCommunity5 similarityOfProblems1 immediacy2 accommodatePhoneTraffic similarityWithOtherParentsProblems accommodateWebSiteTraffic kidsHaveOwnershipOfServices1 easierNavigationCSWebServices1 sufficientCounsellingResources1 measureSuccessOfServices4 anonymityKids3 highQualityServices2 easierToFindPostsWebPostingTechnology1 qualityServices webServicesSelfServe1 efficientPhoneServices connectBackToTheCommunity8 controlOfCounsellingWork1 increasedWebServices4 decreaseResponseTIme2 increaseWebResources1 connectBackToTheCommunity1 encourageKidsUsingWebServicesToUsePhoneServices1 decreaseResponseTIme anonymityParents4 confidentialityKids1 connectBackToTheCommunity6 avoidBadAdvice2 effectiveChatRoomFilters webServicesSelfServe availableServices2 kidsHaveOwnershipOfServices5 anonymityKids6 improveWebsiteContent1 efficientPhoneServices1 immediacy7 reducePrankCalls1 anonymityKids5 sufficientCounsellingResources2 controlWebServices2 confidentialityServices encourageKidsUsingWebServicesToUsePhoneServices increasePhoneResources2 efficientServices1 friendlyWebSite confidentialityParents5 confidentialityKids5 availableServices1 relevanceInKidsLives maintainServicesAboveCompetition anonymityCounsellors connectBackToTheCommunity2 connectToOtherKids immediacy3 directResponseToKids1 availableServices controlWebServices improveWebsiteContent efficientPhoneServices2 decreasePhoneWaitingTime improveWebsiteContent2 highQualityServices1 anonymityKids2 directResponseToKids immediacy4 sufficientlyModeratedWebServices1 sufficientCounsellingResources kidsHaveOwnershipOfServices6 connectBackToTheCommunity confidentialityParents1 anonymityParents2 efficientWebServices confidentiality decreaseResponseTIme3 decreaseResponseTIme4 avoidDialoguesBetweenKids anonymityParents5 connectBackToTheCommunity7 avoidBadAdvice3 similarityOfProblems availableServices5 increaseEmphasisOnOnlineFeedbackForm1 controlOfCounsellingWork avoidBadAdvice kidsHaveOwnershipOfServices4 measureSuccessOfServices1 reduceContagionEffectOfHarmfulActions1 anonymityKids1 improveImageToKids1 avoidPresenceOfPedofiles confidentialityParents measureSuccessOfServices similarityWithOtherParentsProblems1 avoidBadAdvice4 increaseResourcesServices1 controlWebServices1 anonymityCounsellors1 reduceNumberOfStepsWebPostingTechnology1 friendlyWebSite2 increaseWebResources increasePhoneResources1 highQualityServices increasedWebServices1 sufficientlyModeratedWebServices avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb friendlyWebSite12 confidentialityParents4 improveImageToKids increaseNumberOfServices1 confidentialityKids4 reduceContagionEffectOfHarmfulActions confidentialityParents2 kidsHaveOwnershipOfServices connectBackToTheCommunity3 empoweringKidsToHelpThemselves directResponseToKids2 confidentialityKids3 anonymityKids increaseResourcesServices reducePrankCalls correctInterpretationOfCounsel kidsHaveOwnershipOfServices3 anonymityKids4 measureSuccessOfServices2 easierAccessToPostReply connectBackToTheCommunity9 easierNavigationCSWebServices2 easierNavigationCSWebServices immediacy5 sufficientlyModeratedWebServices2 easierAccessToPostReply1 anonymityParents1 relevanceInKidsLives1 avoidPresenceOfPedofiles1 webServicesSelfServe3 increasePhoneResources increasedWebServices2 efficientWebServices2 increaseEmphasisOnOnlineFeedbackForm connectBackToTheCommunity4 confidentialityKids7 immediacy8 increaseNumberOfServices connectBackToTheCommunity42 confidentialityKids availableServices4 increasedWebServices maintainServicesAboveCompetition1 immediacy1 avoidBadAdvice5 reduceNumberOfStepsWebPostingTechnology anonymityParents empoweringKidsToHelpThemselves1 relevanceInKidsLives2 immediacyServices anonymityParents3 anonymity availableServices3 connectBackToTheCommunity10 easyAccessToPostReply avoidDialogues efficientWebServices1 decreasePhoneWaitingTime2 availabilityServices easierToFindPostsWebPostingTechnology confidentialityKids2 avoidBadAdvice1 kidsHaveOwnershipOfServices2 anonymityKids7 correctInterpretationOfCounsel1 decreasePhoneWaitingTime1 measureSuccessOfServices3 immediacy immediacy6 sufficientlyModeratedWebServices3 webServicesSelfServe2 confidentialityParents3 avoidPresenceOfPedofiles2 easyAccessToPostReply1 sufficientlyModeratedWebServices4 efficientServices))
