% CSServices  (node/2 edge/3 dep/2 dec/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
node(answer80OfCallsWithin30SecondsOfMessageEnding,goal).
leaf(answer80OfCallsWithin30SecondsOfMessageEnding).
topgoal(answer80OfCallsWithin30SecondsOfMessageEnding).
node(implementFeedbackForm,task).
node(decreaseResponseTIme1,softgoal).
node(increasedWebServices3,softgoal).
node(increaseWebResources2,softgoal).
leaf(increaseWebResources2).
node(implementNToolToAllowParentsToTalkToEachOther1,task).
node(informKidsAboutAnonymityKidsOfWebServices,task).
node(implementOneOnOneChatRooms1,task).
leaf(implementOneOnOneChatRooms1).
node(kidsReadGeneralQuestionsAndAnswers,task).
node(friendlyWebSite1,softgoal).
node(kidsUseVoiceCounselling,task).
node(kidsUseAskACounsellorSection,task).
node(maintainWebServices1,task).
node(confidentialityKids6,softgoal).
node(implementBoardWithReplies1,task).
node(kidsUseOneOnOneChatRooms,task).
node(connectBackToTheCommunity5,softgoal).
node(kidsUseCyberCafPortalChatRoom1,task).
leaf(kidsUseCyberCafPortalChatRoom1).
node(strategicBluePrint,resource).
leaf(strategicBluePrint).
node(implementPhoneFeedback,task).
node(similarityOfProblems1,softgoal).
node(immediacy2,softgoal).
node(maintainImplementCSServices,task).
node(accommodatePhoneTraffic,softgoal).
node(similarityWithOtherParentsProblems,softgoal).
node(implementTextMessaging,task).
node(anonymousTechnologyBeUsed,goal).
topgoal(anonymousTechnologyBeUsed).
node(maintainAskACounsellorSection1,task).
leaf(maintainAskACounsellorSection1).
node(accommodateWebSiteTraffic,softgoal).
node(maintainPHLPhoneServices4,task).
leaf(maintainPHLPhoneServices4).
node(kidsHaveOwnershipOfServices1,softgoal).
node(servicesBeBilingual1,goal).
leaf(servicesBeBilingual1).
topgoal(servicesBeBilingual1).
node(moderateDiscussionBoards,task).
leaf(moderateDiscussionBoards).
node(easierNavigationCSWebServices1,softgoal).
node(sufficientCounsellingResources1,softgoal).
leaf(sufficientCounsellingResources1).
node(measureSuccessOfServices4,softgoal).
node(anonymityKids3,softgoal).
node(highQualityServices2,softgoal).
node(maintainPhoneServices1,task).
node(implementEmailCounselling,task).
node(easierToFindPostsWebPostingTechnology1,softgoal).
node(kidsUseCyberCafPortalChatRoom,task).
node(implementPhoneFeedback3,task).
leaf(implementPhoneFeedback3).
node(qualityServices,softgoal).
node(kidsUsePhoneCounselling1,task).
leaf(kidsUsePhoneCounselling1).
node(webServicesSelfServe1,softgoal).
node(efficientPhoneServices,softgoal).
node(counsellorsBeProfessionallyTrained,goal).
topgoal(counsellorsBeProfessionallyTrained).
node(webSiteContent,resource).
leaf(webSiteContent).
node(maintainImplementCSServices3,task).
node(connectBackToTheCommunity8,softgoal).
node(provideWebCounsellingWithVideo,task).
leaf(provideWebCounsellingWithVideo).
node(nonRealTimeECounsellingBeUsed,goal).
topgoal(nonRealTimeECounsellingBeUsed).
node(controlOfCounsellingWork1,softgoal).
node(increasedWebServices4,softgoal).
node(decreaseResponseTIme2,softgoal).
node(implementGetInformedSectionOfWebSite,task).
node(increaseWebResources1,softgoal).
node(implementFeedbackCollection,task).
node(connectBackToTheCommunity1,softgoal).
node(encourageKidsUsingWebServicesToUsePhoneServices1,softgoal).
node(decreaseResponseTIme,softgoal).
node(parentsUseNToolToAllowParentsToTalkToEachOther,task).
node(implementBulletinBoardWithReplies,task).
node(provideWebCounsellingWithAudio,task).
leaf(provideWebCounsellingWithAudio).
node(anonymityParents4,softgoal).
node(servicesBeBilingual,goal).
topgoal(servicesBeBilingual).
node(confidentialityKids1,softgoal).
node(implementCyberCafPortalChatRoom,task).
node(connectBackToTheCommunity6,softgoal).
node(avoidBadAdvice2,softgoal).
node(obtainNeededSoftware,task).
node(effectiveChatRoomFilters,softgoal).
leaf(effectiveChatRoomFilters).
node(maintainImplementCSWebServices2,task).
node(webServicesSelfServe,softgoal).
node(availableServices2,softgoal).
node(nonAnonymousTechnologyBeUsed,goal).
topgoal(nonAnonymousTechnologyBeUsed).
node(kidsHaveOwnershipOfServices5,softgoal).
node(maintainPHLWebServices2,task).
node(anonymityKids6,softgoal).
node(improveWebsiteContent1,softgoal).
node(implementGeneralQuestionsAndAnswers,task).
node(servicesBeProvidedForKidsBullyingLine,goal).
topgoal(servicesBeProvidedForKidsBullyingLine).
node(confidentialTechnologyBeUsed,goal).
topgoal(confidentialTechnologyBeUsed).
node(efficientPhoneServices1,softgoal).
node(acquireFeedback,task).
node(maintainImplementPHLServices2,task).
node(kidsUseVideoCounselling,task).
node(immediacy7,softgoal).
node(reducePrankCalls1,softgoal).
node(anonymityKids5,softgoal).
node(sufficientCounsellingResources2,softgoal).
node(controlWebServices2,softgoal).
node(kidsUseEmailCounselling1,task).
leaf(kidsUseEmailCounselling1).
node(maintainAskACounsellorSection,task).
node(maintainPhoneServices,task).
node(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,goal).
topgoal(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed).
node(confidentialityServices,softgoal).
node(implementEmailCounselling1,task).
node(servicesBeProvidedForKidsBullyingLine1,goal).
topgoal(servicesBeProvidedForKidsBullyingLine1).
node(implementVoiceCounselling,task).
node(implementDelay,task).
leaf(implementDelay).
node(kidsReadGetInformedSectionOfWebSite,task).
node(implementAntiPrankingMessage,task).
leaf(implementAntiPrankingMessage).
node(encourageKidsUsingWebServicesToUsePhoneServices,softgoal).
node(feedbackFormSoftware,resource).
leaf(feedbackFormSoftware).
node(scheduleChatAtSpecificTimes,task).
leaf(scheduleChatAtSpecificTimes).
node(increasePhoneResources2,softgoal).
node(implementOneOnOneChatRooms,task).
node(efficientServices1,softgoal).
node(kidsUseBulletinBoardWithDelayedModeration,task).
node(friendlyWebSite,softgoal).
node(confidentialityParents5,softgoal).
node(implementFeedbackForm1,task).
node(confidentialityKids5,softgoal).
node(availableServices1,softgoal).
node(kidsReadGeneralQuestionsAndAnswers1,task).
leaf(kidsReadGeneralQuestionsAndAnswers1).
node(implementInformationSection1,task).
node(relevanceInKidsLives,softgoal).
node(maintainServicesAboveCompetition,softgoal).
node(acquireServiceResources,task).
node(onlyOnlineRequestFromCanadiansAccepted,goal).
leaf(onlyOnlineRequestFromCanadiansAccepted).
topgoal(onlyOnlineRequestFromCanadiansAccepted).
node(anonymityCounsellors,softgoal).
node(connectBackToTheCommunity2,softgoal).
node(implementVideoCounselling1,task).
node(implementServices,task).
node(connectToOtherKids,softgoal).
node(immediacy3,softgoal).
node(directResponseToKids1,softgoal).
node(maintainCSPhoneServices1,task).
node(availableServices,softgoal).
node(putContentOntoWebsite,task).
node(maintainPHLPhoneServices3,task).
node(controlWebServices,softgoal).
node(implementBulletinBoardWithReplies1,task).
leaf(implementBulletinBoardWithReplies1).
node(improveWebsiteContent,softgoal).
node(nonConfidentialTechnologyBeUsed,goal).
topgoal(nonConfidentialTechnologyBeUsed).
node(efficientPhoneServices2,softgoal).
node(maintainPHLWebServices1,task).
node(decreasePhoneWaitingTime,softgoal).
node(improveWebsiteContent2,softgoal).
node(highQualityServices1,softgoal).
node(implementGetInformedSectionOfWebSite1,task).
node(informKidsAboutAnonymityKidsOfWebServices1,task).
leaf(informKidsAboutAnonymityKidsOfWebServices1).
node(anonymityKids2,softgoal).
node(maintainCSPhoneServices2,task).
node(directResponseToKids,softgoal).
node(immediacy4,softgoal).
node(sufficientlyModeratedWebServices1,softgoal).
node(obtainSoftware,task).
node(sufficientCounsellingResources,softgoal).
node(kidsHaveOwnershipOfServices6,softgoal).
leaf(kidsHaveOwnershipOfServices6).
node(implementPhoneFeedback2,task).
node(implementNToolToAllowParentsToTalkToEachOther,task).
leaf(implementNToolToAllowParentsToTalkToEachOther).
node(kidsGetInformationThroughECounselling,task).
node(connectBackToTheCommunity,softgoal).
node(confidentialityParents1,softgoal).
node(anonymityParents2,softgoal).
node(efficientWebServices,softgoal).
node(maintainImplementCSServices2,task).
node(kidsReadPollsAboutKids,task).
node(kidsUsePhoneCounselling,task).
node(kidsUseOneOnOneChatRooms1,task).
node(voiceCounsellingBePerformed,task).
leaf(voiceCounsellingBePerformed).
node(confidentiality,softgoal).
node(maintainCSPhoneServices3,task).
node(maintainWebServices,task).
node(decreaseResponseTIme3,softgoal).
node(kidsUseGetInformedSectionOfWebSite,task).
leaf(kidsUseGetInformedSectionOfWebSite).
node(decreaseResponseTIme4,softgoal).
leaf(decreaseResponseTIme4).
node(avoidDialoguesBetweenKids,softgoal).
node(maintainPHLPhoneServices,task).
node(parentsUseBulletinBoardWithReplies,task).
node(anonymityParents5,softgoal).
node(kidsUseOnlineInformationProvided,goal).
topgoal(kidsUseOnlineInformationProvided).
node(maintainWebServices3,task).
node(performEmailCounselling,task).
leaf(performEmailCounselling).
node(connectBackToTheCommunity7,softgoal).
node(avoidBadAdvice3,softgoal).
node(similarityOfProblems,softgoal).
node(maintainImplementCSWebServices1,task).
node(implementBulletinBoardWithDelayedModeration1,task).
leaf(implementBulletinBoardWithDelayedModeration1).
node(availableServices5,softgoal).
node(increaseEmphasisOnOnlineFeedbackForm1,softgoal).
leaf(increaseEmphasisOnOnlineFeedbackForm1).
node(controlOfCounsellingWork,softgoal).
node(avoidBadAdvice,softgoal).
node(kidsHaveOwnershipOfServices4,softgoal).
node(measureSuccessOfServices1,softgoal).
node(reduceContagionEffectOfHarmfulActions1,softgoal).
node(anonymityKids1,softgoal).
node(improveImageToKids1,softgoal).
node(avoidPresenceOfPedofiles,softgoal).
node(confidentialityParents,softgoal).
node(maintainPhoneServices4,task).
node(measureSuccessOfServices,softgoal).
node(similarityWithOtherParentsProblems1,softgoal).
node(avoidBadAdvice4,softgoal).
node(maintainImplementPHLServices1,task).
node(increaseResourcesServices1,softgoal).
leaf(increaseResourcesServices1).
node(controlWebServices1,softgoal).
node(implementVideoCounselling,task).
node(webServer,resource).
leaf(webServer).
node(anonymityCounsellors1,softgoal).
node(blockKidsWhoDisplayInappropriateBehavoir,task).
leaf(blockKidsWhoDisplayInappropriateBehavoir).
node(maintainPhoneServices3,task).
node(reduceNumberOfStepsWebPostingTechnology1,softgoal).
node(friendlyWebSite2,softgoal).
node(increaseWebResources,softgoal).
node(increasePhoneResources1,softgoal).
node(feedback,resource).
leaf(feedback).
node(highQualityServices,softgoal).
node(implementPollsAboutKids1,task).
node(increasedWebServices1,softgoal).
node(implementInformationSection,task).
leaf(implementInformationSection).
node(implementPhoneFeedback1,task).
node(sufficientlyModeratedWebServices,softgoal).
node(technologyThatAllowsDialoguesBetweenKidsBeUsed,goal).
topgoal(technologyThatAllowsDialoguesBetweenKidsBeUsed).
node(strategicBluePrintForWebsiteBeFollowed,goal).
topgoal(strategicBluePrintForWebsiteBeFollowed).
node(avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,softgoal).
node(friendlyWebSite12,softgoal).
node(confidentialityParents4,softgoal).
node(obtainWebServer,task).
node(improveImageToKids,softgoal).
node(implementFeedbackForm2,task).
node(increaseNumberOfServices1,softgoal).
node(confidentialityKids4,softgoal).
node(reduceContagionEffectOfHarmfulActions,softgoal).
node(confidentialityParents2,softgoal).
node(kidsHaveOwnershipOfServices,softgoal).
node(webSiteContentBeUpdatedDaily,goal).
leaf(webSiteContentBeUpdatedDaily).
topgoal(webSiteContentBeUpdatedDaily).
node(implementVoiceCounselling1,task).
leaf(implementVoiceCounselling1).
node(connectBackToTheCommunity3,softgoal).
node(kidsReadPollsAboutKids1,task).
leaf(kidsReadPollsAboutKids1).
node(empoweringKidsToHelpThemselves,softgoal).
node(feedback1,resource).
leaf(feedback1).
node(directResponseToKids2,softgoal).
node(confidentialityKids3,softgoal).
node(anonymityKids,softgoal).
node(increaseResourcesServices,softgoal).
node(reducePrankCalls,softgoal).
leaf(reducePrankCalls).
node(maintainPHLWebServices,task).
node(correctInterpretationOfCounsel,softgoal).
node(maintainPHLPhoneServices2,task).
node(kidsHaveOwnershipOfServices3,softgoal).
node(anonymityKids4,softgoal).
node(measureSuccessOfServices2,softgoal).
node(easierAccessToPostReply,softgoal).
node(connectBackToTheCommunity9,softgoal).
node(realTimeECounsellingBeUsed,goal).
topgoal(realTimeECounsellingBeUsed).
node(easierNavigationCSWebServices2,softgoal).
node(easierNavigationCSWebServices,softgoal).
node(immediacy5,softgoal).
node(acquireWebContent,task).
node(webSoftware,resource).
leaf(webSoftware).
node(sufficientlyModeratedWebServices2,softgoal).
node(easierAccessToPostReply1,softgoal).
node(anonymityParents1,softgoal).
node(parentsUseInformationSection1,task).
leaf(parentsUseInformationSection1).
node(relevanceInKidsLives1,softgoal).
node(avoidPresenceOfPedofiles1,softgoal).
leaf(avoidPresenceOfPedofiles1).
node(webServicesSelfServe3,softgoal).
leaf(webServicesSelfServe3).
node(increasePhoneResources,softgoal).
leaf(increasePhoneResources).
node(maintainImplementCSServices1,task).
node(counsellorsBeProfessionallyTrained1,goal).
leaf(counsellorsBeProfessionallyTrained1).
topgoal(counsellorsBeProfessionallyTrained1).
node(implementCyberCafPortalChatRoom1,task).
node(traceCalls,task).
leaf(traceCalls).
node(increasedWebServices2,softgoal).
node(efficientWebServices2,softgoal).
node(increaseEmphasisOnOnlineFeedbackForm,softgoal).
node(provideWrittenCounselling,task).
leaf(provideWrittenCounselling).
node(connectBackToTheCommunity4,softgoal).
node(provideRecordedMessages,task).
leaf(provideRecordedMessages).
node(phoneLibraryOfRecordedMessages,resource).
node(putContentOntoWebsite1,task).
leaf(putContentOntoWebsite1).
node(confidentialityKids7,softgoal).
node(kidsUseVideoCounselling1,task).
leaf(kidsUseVideoCounselling1).
node(maintainWebServices2,task).
node(immediacy8,softgoal).
node(increaseNumberOfServices,softgoal).
node(connectBackToTheCommunity42,softgoal).
node(confidentialityKids,softgoal).
leaf(confidentialityKids).
node(availableServices4,softgoal).
node(implementPollsAboutKids,task).
node(increasedWebServices,softgoal).
node(maintainServicesAboveCompetition1,softgoal).
node(kidsUseTextMessaging,task).
node(parentsUsePhoneCounselling1,task).
node(kidsUseBulletinBoardWithReplies,task).
node(immediacy1,softgoal).
node(avoidBadAdvice5,softgoal).
node(implementBoardWithReplies,task).
leaf(implementBoardWithReplies).
node(implementTextMessaging1,task).
leaf(implementTextMessaging1).
node(kidsUseVoiceCounselling1,task).
leaf(kidsUseVoiceCounselling1).
node(kidsUseTextMessaging1,task).
node(maintainImplementPHLServices,task).
node(implementGeneralQuestionsAndAnswers1,task).
node(reduceNumberOfStepsWebPostingTechnology,softgoal).
node(anonymityParents,softgoal).
node(maintainPhoneServices2,task).
node(parentsUseInformationSection,task).
node(empoweringKidsToHelpThemselves1,softgoal).
node(serviceResources,resource).
leaf(serviceResources).
node(telephonyBeImplementedAndManaged1,goal).
leaf(telephonyBeImplementedAndManaged1).
topgoal(telephonyBeImplementedAndManaged1).
node(implementFilters,task).
leaf(implementFilters).
node(moderatedECounsellingBeUsed,goal).
topgoal(moderatedECounsellingBeUsed).
node(kidsUseEmailCounselling,task).
node(relevanceInKidsLives2,softgoal).
leaf(relevanceInKidsLives2).
node(immediacyServices,softgoal).
node(anonymityParents3,softgoal).
node(moderateAChat,task).
leaf(moderateAChat).
node(parentsUsePhoneCounselling,task).
node(anonymity,softgoal).
node(availableServices3,softgoal).
node(maintainCSPhoneServices,task).
node(connectBackToTheCommunity10,softgoal).
node(easyAccessToPostReply,softgoal).
node(avoidDialogues,softgoal).
node(createCounsellingPosts,task).
leaf(createCounsellingPosts).
node(efficientWebServices1,softgoal).
node(parentsUseNToolToAllowParentsToTalkToEachOther1,task).
leaf(parentsUseNToolToAllowParentsToTalkToEachOther1).
node(decreasePhoneWaitingTime2,softgoal).
node(telephonyBeImplementedAndManaged,goal).
topgoal(telephonyBeImplementedAndManaged).
node(availabilityServices,softgoal).
node(easierToFindPostsWebPostingTechnology,softgoal).
node(confidentialityKids2,softgoal).
node(maintainImplementCSWebServices,task).
node(maintainPHLPhoneServices1,task).
node(maintainImplementCSWebServices3,task).
node(avoidBadAdvice1,softgoal).
node(kidsHaveOwnershipOfServices2,softgoal).
node(anonymityKids7,softgoal).
node(maintainPHLWebServices3,task).
node(correctInterpretationOfCounsel1,softgoal).
leaf(correctInterpretationOfCounsel1).
node(decreasePhoneWaitingTime1,softgoal).
node(serviceLevelsBeMet,goal).
leaf(serviceLevelsBeMet).
topgoal(serviceLevelsBeMet).
node(measureSuccessOfServices3,softgoal).
node(kidsUseAskACounsellorSection1,task).
leaf(kidsUseAskACounsellorSection1).
node(implementBulletinBoardWithDelayedModeration,task).
node(immediacy,softgoal).
node(maintainImplementPHLServices3,task).
node(immediacy6,softgoal).
node(sufficientlyModeratedWebServices3,softgoal).
node(parentsUseBulletinBoardWithReplies1,task).
leaf(parentsUseBulletinBoardWithReplies1).
node(kidsUseBulletinBoardWithDelayedModeration1,task).
leaf(kidsUseBulletinBoardWithDelayedModeration1).
node(webServicesSelfServe2,softgoal).
node(confidentialityParents3,softgoal).
node(avoidPresenceOfPedofiles2,softgoal).
node(easyAccessToPostReply1,softgoal).
node(kidsUseBulletinBoardWithReplies1,task).
leaf(kidsUseBulletinBoardWithReplies1).
node(sufficientlyModeratedWebServices4,softgoal).
node(efficientServices,softgoal).
edge(kidsUseBulletinBoardWithDelayedModeration,correctInterpretationOfCounsel,-0.5).
edge(avoidPresenceOfPedofiles,avoidBadAdvice,0.5).
edge(kidsUseVideoCounselling,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dec(implementNToolToAllowParentsToTalkToEachOther,maintainPHLWebServices2,or).
dep(technologyThatAllowsDialoguesBetweenKidsBeUsed,connectToOtherKids).
dec(maintainCSPhoneServices3,maintainImplementCSServices2,or).
edge(answer80OfCallsWithin30SecondsOfMessageEnding,decreasePhoneWaitingTime2,0.5).
edge(easierAccessToPostReply,easierNavigationCSWebServices1,0.5).
dec(putContentOntoWebsite,implementPollsAboutKids,or).
dep(implementTextMessaging1,implementTextMessaging).
edge(kidsUseBulletinBoardWithReplies,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dep(empoweringKidsToHelpThemselves,empoweringKidsToHelpThemselves1).
dep(webServer,obtainWebServer).
dep(maintainPHLWebServices1,maintainPHLWebServices).
dep(maintainPhoneServices3,maintainPhoneServices2).
dep(anonymityParents1,anonymityParents).
dec(maintainPHLWebServices,maintainWebServices,or).
dec(maintainImplementCSServices,servicesBeProvidedForKidsBullyingLine,or).
dep(implementPhoneFeedback3,implementPhoneFeedback).
dep(increasePhoneResources2,increasePhoneResources1).
edge(informKidsAboutAnonymityKidsOfWebServices1,kidsHaveOwnershipOfServices,0.5).
dep(kidsHaveOwnershipOfServices6,kidsHaveOwnershipOfServices5).
dep(implementBulletinBoardWithReplies1,implementBulletinBoardWithReplies).
edge(kidsUseBulletinBoardWithReplies,anonymityCounsellors,0.5).
dec(obtainNeededSoftware,implementFeedbackForm,or).
edge(anonymityKids3,improveImageToKids,0.5).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,connectBackToTheCommunity3,0.5).
edge(serviceLevelsBeMet,highQualityServices,0.5).
edge(kidsUseOnlineInformationProvided,connectBackToTheCommunity4,0.5).
dec(implementFilters,implementCyberCafPortalChatRoom,or).
dep(anonymityKids1,anonymityKids).
edge(controlWebServices,avoidPresenceOfPedofiles,0.5).
dep(controlWebServices,controlWebServices2).
dep(kidsUseBulletinBoardWithDelayedModeration1,kidsUseBulletinBoardWithDelayedModeration).
edge(confidentialityKids1,improveImageToKids,0.5).
dep(maintainWebServices,maintainWebServices2).
edge(kidsUseVideoCounselling,anonymityCounsellors,-0.5).
dep(highQualityServices,highQualityServices2).
dep(similarityOfProblems,similarityOfProblems1).
edge(implementFeedbackForm,measureSuccessOfServices1,0.5).
dep(immediacy2,immediacy1).
edge(sufficientCounsellingResources2,accommodatePhoneTraffic,0.5).
edge(sufficientCounsellingResources,decreaseResponseTIme2,0.5).
edge(avoidPresenceOfPedofiles,improveImageToKids,0.5).
edge(kidsUseAskACounsellorSection,easierToFindPostsWebPostingTechnology,0.5).
dep(efficientWebServices2,efficientWebServices1).
dep(webServicesSelfServe1,webServicesSelfServe).
dec(implementFeedbackForm2,implementFeedbackCollection,or).
edge(webServicesSelfServe,accommodateWebSiteTraffic,0.5).
edge(increaseWebResources2,increaseResourcesServices,0.5).
edge(acquireFeedback,confidentiality,-0.5).
dep(easierNavigationCSWebServices,easierNavigationCSWebServices2).
dec(maintainPHLPhoneServices2,parentsUsePhoneCounselling1,or).
dep(connectBackToTheCommunity9,connectBackToTheCommunity).
edge(parentsUseBulletinBoardWithReplies,anonymityParents3,0.5).
edge(maintainPhoneServices,availableServices3,1).
dep(connectBackToTheCommunity2,connectBackToTheCommunity42).
edge(kidsUseBulletinBoardWithDelayedModeration,directResponseToKids,-1).
dec(implementBulletinBoardWithReplies,kidsUseBulletinBoardWithReplies,or).
dec(kidsReadPollsAboutKids,kidsUseOnlineInformationProvided,or).
edge(confidentialityKids,reducePrankCalls1,-0.5).
dep(anonymityKids3,anonymityKids2).
edge(kidsUseBulletinBoardWithReplies,easierToFindPostsWebPostingTechnology,0.5).
edge(kidsReadGetInformedSectionOfWebSite,webServicesSelfServe2,0.5).
dep(kidsHaveOwnershipOfServices1,kidsHaveOwnershipOfServices2).
dep(maintainPhoneServices,maintainPhoneServices3).
dep(maintainPHLWebServices1,maintainPHLWebServices3).
dep(reduceNumberOfStepsWebPostingTechnology1,reduceNumberOfStepsWebPostingTechnology).
edge(easierAccessToPostReply,directResponseToKids,0.5).
dep(anonymityCounsellors,anonymityCounsellors1).
edge(counsellorsBeProfessionallyTrained,highQualityServices,0.5).
edge(kidsUseEmailCounselling,directResponseToKids,1).
dec(maintainCSPhoneServices,maintainPhoneServices,or).
dep(webSiteContent,acquireWebContent).
edge(realTimeECounsellingBeUsed,decreaseResponseTIme,1).
dec(provideRecordedMessages,maintainPHLPhoneServices2,or).
dep(provideWrittenCounselling,implementCyberCafPortalChatRoom).
edge(kidsUseOneOnOneChatRooms,anonymityCounsellors,0.5).
dep(availableServices1,availableServices5).
dep(anonymityParents3,anonymityKids6).
dep(confidentialityKids4,confidentialityKids5).
dep(implementPhoneFeedback,implementPhoneFeedback1).
edge(parentsUseBulletinBoardWithReplies,similarityWithOtherParentsProblems,0.5).
dec(kidsUseOnlineInformationProvided,maintainImplementCSWebServices,or).
dep(maintainPHLPhoneServices1,maintainPHLPhoneServices3).
dep(maintainImplementPHLServices2,maintainImplementPHLServices3).
edge(anonymityParents,anonymity,0.5).
dep(webServicesSelfServe2,webServicesSelfServe1).
dec(implementVideoCounselling1,kidsUseVideoCounselling,or).
dec(moderatedECounsellingBeUsed,kidsGetInformationThroughECounselling,or).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,avoidBadAdvice3,-0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,reduceNumberOfStepsWebPostingTechnology1,0.5).
dep(implementInformationSection,implementInformationSection1).
dep(moderateAChat,implementCyberCafPortalChatRoom).
edge(increasePhoneResources,increaseResourcesServices,0.5).
dep(implementOneOnOneChatRooms1,implementOneOnOneChatRooms).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,similarityOfProblems,-0.5).
edge(realTimeECounsellingBeUsed,directResponseToKids,1).
edge(decreaseResponseTIme,improveImageToKids,0.5).
dec(implementBoardWithReplies,maintainPHLWebServices2,or).
dec(maintainPHLPhoneServices3,maintainImplementPHLServices,or).
edge(kidsUseTextMessaging,increasedWebServices4,0.5).
dec(kidsUseEmailCounselling,nonAnonymousTechnologyBeUsed,or).
edge(relevanceInKidsLives,highQualityServices,0.5).
dep(kidsReadGeneralQuestionsAndAnswers1,kidsReadGeneralQuestionsAndAnswers).
dep(informKidsAboutAnonymityKidsOfWebServices1,informKidsAboutAnonymityKidsOfWebServices).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,avoidDialoguesBetweenKids,1).
edge(easierNavigationCSWebServices1,friendlyWebSite2,0.5).
dec(kidsUseVideoCounselling,confidentialTechnologyBeUsed,or).
dec(implementInformationSection,parentsUseInformationSection,or).
dep(immediacy,immediacy8).
dep(kidsUseEmailCounselling1,kidsUseEmailCounselling).
dep(provideWebCounsellingWithAudio,implementVoiceCounselling).
edge(kidsReadGeneralQuestionsAndAnswers,webServicesSelfServe2,0.5).
edge(moderatedECounsellingBeUsed,maintainServicesAboveCompetition1,0.5).
edge(kidsUseEmailCounselling,anonymityCounsellors,-0.5).
dep(increaseEmphasisOnOnlineFeedbackForm1,increaseEmphasisOnOnlineFeedbackForm).
dep(decreaseResponseTIme1,decreaseResponseTIme2).
dep(sufficientlyModeratedWebServices4,sufficientlyModeratedWebServices3).
edge(relevanceInKidsLives2,improveImageToKids,0.5).
dep(moderateDiscussionBoards,maintainAskACounsellorSection).
dep(decreaseResponseTIme,decreaseResponseTIme1).
dep(counsellorsBeProfessionallyTrained1,counsellorsBeProfessionallyTrained).
dep(voiceCounsellingBePerformed,maintainPHLPhoneServices2).
dep(similarityWithOtherParentsProblems,similarityWithOtherParentsProblems1).
dep(efficientServices1,efficientServices).
dec(kidsUseCyberCafPortalChatRoom,nonConfidentialTechnologyBeUsed,or).
dep(anonymityKids,anonymityKids7).
dep(availableServices1,availabilityServices).
dep(availableServices1,availableServices).
dep(implementVideoCounselling1,implementVideoCounselling).
dep(increasedWebServices1,increasedWebServices).
dep(confidentialityKids2,confidentialityKids6).
edge(kidsUseBulletinBoardWithDelayedModeration,reduceContagionEffectOfHarmfulActions,-0.5).
dec(kidsUseBulletinBoardWithReplies,anonymousTechnologyBeUsed,or).
dep(maintainAskACounsellorSection1,maintainAskACounsellorSection).
dep(increasedWebServices4,increasedWebServices3).
dec(kidsUseBulletinBoardWithReplies,nonRealTimeECounsellingBeUsed,or).
dep(measureSuccessOfServices2,measureSuccessOfServices).
edge(moderatedECounsellingBeUsed,kidsHaveOwnershipOfServices,0.5).
dep(efficientPhoneServices2,efficientPhoneServices1).
dep(kidsReadPollsAboutKids1,kidsReadPollsAboutKids).
edge(maintainWebServices,availableServices4,-0.5).
dep(immediacy,immediacyServices).
edge(nonRealTimeECounsellingBeUsed,avoidBadAdvice,0.5).
dep(feedback1,acquireFeedback).
dep(increaseWebResources2,increaseWebResources1).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,avoidDialoguesBetweenKids,-1).
dec(implementEmailCounselling1,kidsUseEmailCounselling,or).
dep(kidsUseOneOnOneChatRooms,kidsUseOneOnOneChatRooms1).
dep(connectBackToTheCommunity4,connectBackToTheCommunity7).
edge(kidsUseEmailCounselling,increasedWebServices4,0.5).
dec(maintainPHLPhoneServices,maintainPhoneServices,or).
dep(sufficientlyModeratedWebServices2,sufficientlyModeratedWebServices1).
dep(avoidBadAdvice5,avoidBadAdvice4).
edge(kidsUseBulletinBoardWithDelayedModeration,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dep(kidsHaveOwnershipOfServices2,kidsHaveOwnershipOfServices3).
dec(blockKidsWhoDisplayInappropriateBehavoir,implementCyberCafPortalChatRoom,or).
dep(avoidDialoguesBetweenKids,avoidDialogues).
dep(anonymityKids5,anonymityKids2).
dep(decreaseResponseTIme3,decreaseResponseTIme2).
dec(kidsUseOneOnOneChatRooms,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,or).
edge(sufficientCounsellingResources,sufficientlyModeratedWebServices2,0.5).
edge(anonymity,highQualityServices,0.5).
edge(realTimeECounsellingBeUsed,avoidBadAdvice,-0.5).
dep(implementNToolToAllowParentsToTalkToEachOther,implementNToolToAllowParentsToTalkToEachOther1).
edge(onlyOnlineRequestFromCanadiansAccepted,increaseWebResources,0.5).
edge(confidentialityParents,confidentiality,0.5).
dec(kidsUseCyberCafPortalChatRoom,nonAnonymousTechnologyBeUsed,or).
dep(anonymityParents,anonymityParents5).
edge(connectBackToTheCommunity9,highQualityServices,0.5).
dep(connectBackToTheCommunity42,connectBackToTheCommunity5).
edge(kidsUseBulletinBoardWithReplies,reduceNumberOfStepsWebPostingTechnology1,-0.5).
dep(maintainWebServices2,maintainWebServices1).
dec(acquireWebContent,putContentOntoWebsite,or).
dep(accommodatePhoneTraffic,decreasePhoneWaitingTime).
dep(immediacy5,immediacy3).
edge(implementDelay,reduceContagionEffectOfHarmfulActions,0.5).
edge(effectiveChatRoomFilters,reduceContagionEffectOfHarmfulActions,0.5).
dep(efficientWebServices1,efficientWebServices).
dep(controlWebServices2,controlWebServices1).
dep(performEmailCounselling,implementEmailCounselling1).
dep(telephonyBeImplementedAndManaged1,telephonyBeImplementedAndManaged).
edge(confidentialityKids5,highQualityServices,0.5).
dep(sufficientlyModeratedWebServices1,sufficientlyModeratedWebServices).
dec(acquireServiceResources,maintainImplementPHLServices2,or).
dep(maintainPhoneServices2,maintainPhoneServices4).
dep(parentsUseBulletinBoardWithReplies1,parentsUseBulletinBoardWithReplies).
dep(kidsHaveOwnershipOfServices3,kidsHaveOwnershipOfServices4).
dec(kidsUseOneOnOneChatRooms,realTimeECounsellingBeUsed,or).
edge(kidsUseOneOnOneChatRooms,increasedWebServices4,0.5).
edge(nonRealTimeECounsellingBeUsed,decreaseResponseTIme,-0.5).
edge(increasedWebServices,increaseNumberOfServices,0.5).
edge(confidentialTechnologyBeUsed,confidentialityKids1,1).
dec(maintainPHLWebServices3,maintainImplementPHLServices,or).
edge(kidsUseVoiceCounselling,correctInterpretationOfCounsel,0.5).
dec(kidsUseCyberCafPortalChatRoom,technologyThatAllowsDialoguesBetweenKidsBeUsed,or).
dec(putContentOntoWebsite,implementGeneralQuestionsAndAnswers,or).
dep(confidentialityParents,confidentialityServices).
dep(avoidBadAdvice3,avoidBadAdvice2).
edge(kidsReadPollsAboutKids,similarityOfProblems,0.5).
dep(kidsUseVideoCounselling1,kidsUseVideoCounselling).
edge(directResponseToKids,anonymityCounsellors,-0.5).
dec(kidsUseBulletinBoardWithReplies,technologyThatAllowsDialoguesBetweenKidsBeUsed,or).
dec(kidsUseBulletinBoardWithReplies,nonConfidentialTechnologyBeUsed,or).
dec(kidsUseTextMessaging,realTimeECounsellingBeUsed,or).
dec(kidsUseVoiceCounselling,moderatedECounsellingBeUsed,or).
edge(increaseEmphasisOnOnlineFeedbackForm1,measureSuccessOfServices4,0.5).
edge(sufficientCounsellingResources,accommodateWebSiteTraffic,1).
dep(kidsUseTextMessaging,kidsUseTextMessaging1).
edge(efficientServices1,highQualityServices,0.5).
dep(improveImageToKids,improveImageToKids1).
edge(maintainServicesAboveCompetition1,improveImageToKids,0.5).
dep(directResponseToKids1,directResponseToKids2).
edge(kidsUseBulletinBoardWithDelayedModeration,avoidPresenceOfPedofiles,-1).
dep(implementPhoneFeedback1,implementPhoneFeedback2).
dep(immediacy3,immediacy1).
edge(accommodatePhoneTraffic,efficientPhoneServices2,0.5).
edge(kidsUseAskACounsellorSection,directResponseToKids,-1).
dep(connectBackToTheCommunity7,connectBackToTheCommunity6).
dep(avoidBadAdvice1,avoidBadAdvice5).
dep(increasePhoneResources,increasePhoneResources2).
dec(kidsUseVoiceCounselling,confidentialTechnologyBeUsed,or).
edge(traceCalls,anonymityParents2,-1).
edge(webSiteContentBeUpdatedDaily,improveWebsiteContent1,0.5).
edge(immediacy7,friendlyWebSite2,0.5).
edge(kidsUsePhoneCounselling,confidentialityKids6,0.5).
dec(maintainImplementCSServices,implementServices,or).
edge(increasePhoneResources1,accommodatePhoneTraffic,0.5).
dec(scheduleChatAtSpecificTimes,implementCyberCafPortalChatRoom,or).
dep(kidsUseCyberCafPortalChatRoom1,kidsUseCyberCafPortalChatRoom).
dec(maintainImplementPHLServices2,implementServices,or).
dep(parentsUsePhoneCounselling1,parentsUsePhoneCounselling).
dec(putContentOntoWebsite,implementGetInformedSectionOfWebSite,or).
dec(implementVoiceCounselling,kidsUseVoiceCounselling,or).
dep(maintainImplementPHLServices,maintainImplementPHLServices1).
edge(anonymityKids,anonymity,0.5).
dep(maintainImplementCSServices,maintainImplementCSServices3).
dep(availableServices2,availableServices1).
dep(implementFeedbackForm1,implementFeedbackForm2).
edge(immediacy,highQualityServices,0.5).
edge(easierNavigationCSWebServices2,efficientWebServices2,0.5).
edge(kidsUseCyberCafPortalChatRoom,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dec(kidsUseBulletinBoardWithDelayedModeration,moderatedECounsellingBeUsed,or).
dep(maintainCSPhoneServices1,maintainCSPhoneServices3).
dep(increaseNumberOfServices,increaseNumberOfServices1).
dec(kidsUseBulletinBoardWithDelayedModeration,nonConfidentialTechnologyBeUsed,or).
dep(kidsReadPollsAboutKids,implementPollsAboutKids1).
dec(kidsUseTextMessaging,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,or).
dep(sufficientlyModeratedWebServices3,sufficientlyModeratedWebServices2).
dep(highQualityServices,qualityServices).
edge(kidsUseBulletinBoardWithDelayedModeration,anonymityCounsellors,0.5).
edge(anonymousTechnologyBeUsed,controlWebServices,-0.5).
dep(maintainWebServices1,maintainWebServices3).
edge(avoidDialoguesBetweenKids,reduceContagionEffectOfHarmfulActions,0.5).
edge(avoidBadAdvice4,highQualityServices,0.5).
dep(createCounsellingPosts,implementBulletinBoardWithReplies).
dec(implementBoardWithReplies,parentsUseBulletinBoardWithReplies,or).
dep(avoidBadAdvice2,avoidBadAdvice1).
dec(implementTextMessaging,kidsUseTextMessaging,or).
dep(implementGetInformedSectionOfWebSite,implementGetInformedSectionOfWebSite1).
edge(kidsReadPollsAboutKids,webServicesSelfServe2,0.5).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,similarityWithOtherParentsProblems,0.5).
dep(easierAccessToPostReply,easierAccessToPostReply1).
dep(friendlyWebSite12,friendlyWebSite).
edge(realTimeECounsellingBeUsed,immediacy7,1).
dec(implementCyberCafPortalChatRoom,kidsUseCyberCafPortalChatRoom,or).
dec(maintainImplementCSWebServices1,maintainWebServices,or).
edge(kidsUseBulletinBoardWithDelayedModeration,sufficientlyModeratedWebServices4,-0.5).
edge(accommodateWebSiteTraffic,efficientWebServices2,0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,easierToFindPostsWebPostingTechnology,-0.5).
dep(connectBackToTheCommunity9,connectBackToTheCommunity10).
dec(implementGetInformedSectionOfWebSite,kidsReadGetInformedSectionOfWebSite,or).
dec(acquireServiceResources,maintainWebServices1,or).
edge(directResponseToKids,improveImageToKids,0.5).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,similarityOfProblems,0.5).
edge(kidsReadGeneralQuestionsAndAnswers,similarityOfProblems,0.5).
edge(kidsHaveOwnershipOfServices5,highQualityServices,0.5).
dec(kidsUseAskACounsellorSection,nonRealTimeECounsellingBeUsed,or).
edge(kidsUseTextMessaging,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dep(kidsUsePhoneCounselling1,kidsUsePhoneCounselling).
edge(kidsUseEmailCounselling,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dep(maintainPHLPhoneServices4,maintainPHLPhoneServices2).
dep(correctInterpretationOfCounsel1,correctInterpretationOfCounsel).
dec(implementPhoneFeedback2,implementFeedbackCollection,or).
edge(traceCalls,confidentialityParents2,-0.5).
edge(improveWebsiteContent2,highQualityServices,0.5).
dep(confidentialityKids5,confidentialityKids7).
dec(maintainAskACounsellorSection,kidsUseAskACounsellorSection,or).
edge(increasedWebServices4,friendlyWebSite2,0.5).
dep(feedback,acquireFeedback).
edge(kidsUseEmailCounselling,correctInterpretationOfCounsel,-0.5).
dec(implementOneOnOneChatRooms,kidsUseOneOnOneChatRooms,or).
dep(maintainPHLPhoneServices2,maintainPHLPhoneServices1).
dep(easierNavigationCSWebServices1,easierNavigationCSWebServices).
dec(kidsUseOneOnOneChatRooms,confidentialTechnologyBeUsed,or).
dec(implementDelay,implementCyberCafPortalChatRoom,or).
dec(maintainPhoneServices2,implementServices,or).
edge(directResponseToKids,friendlyWebSite2,0.5).
dec(kidsUseEmailCounselling,moderatedECounsellingBeUsed,or).
edge(moderatedECounsellingBeUsed,improveImageToKids,0.5).
dep(availableServices4,availableServices2).
dec(implementBulletinBoardWithDelayedModeration,kidsUseBulletinBoardWithDelayedModeration,or).
edge(kidsUseTextMessaging,anonymityCounsellors,0.5).
dep(servicesBeBilingual1,servicesBeBilingual).
dep(increasedWebServices3,increasedWebServices2).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,avoidBadAdvice,-0.5).
dec(acquireServiceResources,maintainPhoneServices2,or).
edge(avoidPresenceOfPedofiles2,highQualityServices,0.5).
dep(highQualityServices,highQualityServices1).
edge(efficientPhoneServices,efficientServices1,0.5).
dep(sufficientCounsellingResources1,sufficientCounsellingResources2).
dep(decreasePhoneWaitingTime2,decreasePhoneWaitingTime1).
dep(kidsHaveOwnershipOfServices4,kidsHaveOwnershipOfServices5).
dec(kidsUseVoiceCounselling,anonymousTechnologyBeUsed,or).
dep(avoidBadAdvice,avoidBadAdvice2).
dep(implementGeneralQuestionsAndAnswers,implementGeneralQuestionsAndAnswers1).
dep(anonymityParents4,anonymityKids6).
edge(kidsUseAskACounsellorSection,anonymityCounsellors,0.5).
edge(kidsUseOneOnOneChatRooms,correctInterpretationOfCounsel,-0.5).
edge(scheduleChatAtSpecificTimes,reduceContagionEffectOfHarmfulActions,0.5).
dep(maintainPHLWebServices2,maintainPHLWebServices1).
dep(maintainServicesAboveCompetition1,maintainServicesAboveCompetition).
dep(anonymityParents2,anonymityParents1).
dec(implementFeedbackCollection,acquireFeedback,or).
dep(moderateDiscussionBoards,implementBulletinBoardWithReplies).
edge(kidsUseAskACounsellorSection,correctInterpretationOfCounsel,-0.5).
dep(increaseWebResources1,increaseWebResources).
dep(immediacy1,immediacy).
dep(relevanceInKidsLives1,relevanceInKidsLives).
edge(avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,encourageKidsUsingWebServicesToUsePhoneServices1,0.5).
edge(parentsUseInformationSection,connectBackToTheCommunity3,0.5).
dep(confidentialityParents2,confidentialityParents1).
dep(increaseResourcesServices1,increaseResourcesServices).
dep(implementBoardWithReplies,implementBoardWithReplies1).
dep(provideWrittenCounselling,implementTextMessaging).
edge(parentsUseBulletinBoardWithReplies,connectBackToTheCommunity3,0.5).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,controlWebServices,0.5).
dep(feedbackFormSoftware,obtainNeededSoftware).
edge(maintainPhoneServices,immediacy2,0.5).
dec(kidsUseTextMessaging,moderatedECounsellingBeUsed,or).
edge(kidsUseCyberCafPortalChatRoom,correctInterpretationOfCounsel,-0.5).
edge(nonConfidentialTechnologyBeUsed,confidentialityKids1,-1).
dep(measureSuccessOfServices1,measureSuccessOfServices).
edge(confidentialityKids5,confidentiality,0.5).
dep(createCounsellingPosts,maintainAskACounsellorSection).
edge(implementAntiPrankingMessage,reducePrankCalls1,0.5).
edge(kidsUseCyberCafPortalChatRoom,anonymityCounsellors,0.5).
edge(moderatedECounsellingBeUsed,controlOfCounsellingWork1,-0.5).
dec(kidsReadGeneralQuestionsAndAnswers,kidsUseOnlineInformationProvided,or).
edge(parentsUsePhoneCounselling1,anonymityParents4,1).
dep(parentsUseInformationSection1,parentsUseInformationSection).
dep(immediacy4,immediacy3).
dec(kidsUseAskACounsellorSection,moderatedECounsellingBeUsed,or).
edge(highQualityServices,relevanceInKidsLives,0.5).
dep(connectBackToTheCommunity3,connectBackToTheCommunity42).
dep(efficientPhoneServices1,efficientPhoneServices).
edge(directResponseToKids2,highQualityServices,0.5).
dec(implementGeneralQuestionsAndAnswers,kidsReadGeneralQuestionsAndAnswers,or).
edge(kidsUseAskACounsellorSection,increasedWebServices4,0.5).
dep(avoidPresenceOfPedofiles1,avoidPresenceOfPedofiles2).
dep(implementVoiceCounselling1,implementVoiceCounselling).
edge(kidsUseOnlineInformationProvided,improveImageToKids,0.5).
edge(kidsUseVideoCounselling,correctInterpretationOfCounsel,0.5).
dep(connectBackToTheCommunity6,connectBackToTheCommunity8).
dep(kidsUseBulletinBoardWithReplies1,kidsUseBulletinBoardWithReplies).
edge(decreaseResponseTIme,immediacy7,0.5).
dep(maintainCSPhoneServices1,maintainCSPhoneServices).
dep(availableServices3,availableServices2).
dep(implementFeedbackForm,implementFeedbackForm1).
dep(connectBackToTheCommunity8,connectBackToTheCommunity9).
dec(implementInformationSection,maintainPHLWebServices2,or).
dec(implementPollsAboutKids,kidsReadPollsAboutKids,or).
dep(implementEmailCounselling1,implementEmailCounselling).
dec(moderatedECounsellingBeUsed,maintainImplementCSWebServices,or).
edge(realTimeECounsellingBeUsed,controlWebServices,-0.5).
edge(parentsUsePhoneCounselling1,connectBackToTheCommunity2,0.5).
dec(acquireServiceResources,maintainImplementCSServices,or).
edge(parentsUseBulletinBoardWithReplies,easyAccessToPostReply,-0.5).
edge(kidsUsePhoneCounselling,anonymityKids5,1).
dep(reducePrankCalls,reducePrankCalls1).
dep(maintainImplementCSWebServices2,maintainImplementCSWebServices3).
edge(serviceLevelsBeMet,efficientServices1,0.5).
dep(kidsUseGetInformedSectionOfWebSite,kidsReadGetInformedSectionOfWebSite).
dep(connectBackToTheCommunity1,connectBackToTheCommunity7).
dep(webServicesSelfServe3,webServicesSelfServe2).
dep(confidentialityParents1,confidentialityParents).
edge(nonAnonymousTechnologyBeUsed,anonymityKids3,-1).
edge(kidsUsePhoneCounselling,connectBackToTheCommunity1,0.5).
dep(avoidPresenceOfPedofiles1,avoidPresenceOfPedofiles).
dep(maintainImplementCSWebServices,maintainImplementCSWebServices2).
edge(kidsUseBulletinBoardWithDelayedModeration,increasedWebServices4,0.5).
dep(increasedWebServices2,increasedWebServices1).
dep(moderateDiscussionBoards,implementBulletinBoardWithDelayedModeration).
dep(confidentialityKids1,confidentialityKids2).
edge(immediacy6,friendlyWebSite12,0.5).
dep(confidentialityParents5,confidentialityParents3).
edge(easierAccessToPostReply,improveImageToKids,0.5).
dec(kidsUseBulletinBoardWithReplies,moderatedECounsellingBeUsed,or).
dep(strategicBluePrint,strategicBluePrintForWebsiteBeFollowed).
dep(parentsUseNToolToAllowParentsToTalkToEachOther1,parentsUseNToolToAllowParentsToTalkToEachOther).
dep(maintainImplementCSServices2,maintainImplementCSServices1).
edge(kidsUseTextMessaging,correctInterpretationOfCounsel,-0.5).
edge(kidsUseVoiceCounselling,increasedWebServices4,0.5).
dec(kidsUseAskACounsellorSection,nonConfidentialTechnologyBeUsed,or).
dep(immediacy6,immediacy4).
dep(voiceCounsellingBePerformed,maintainCSPhoneServices2).
dep(servicesBeProvidedForKidsBullyingLine,servicesBeProvidedForKidsBullyingLine1).
edge(kidsUseCyberCafPortalChatRoom,increasedWebServices4,0.5).
edge(kidsUseVideoCounselling,increasedWebServices4,0.5).
dep(friendlyWebSite2,friendlyWebSite1).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,avoidBadAdvice,0.5).
dep(implementBulletinBoardWithDelayedModeration1,implementBulletinBoardWithDelayedModeration).
edge(nonRealTimeECounsellingBeUsed,immediacy7,-0.5).
dep(maintainImplementCSWebServices2,maintainImplementCSWebServices1).
dep(confidentialityKids2,confidentialityKids3).
dec(kidsUseCyberCafPortalChatRoom,moderatedECounsellingBeUsed,or).
edge(kidsReadGetInformedSectionOfWebSite,similarityOfProblems,0.5).
dec(kidsUseVideoCounselling,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,or).
edge(sufficientCounsellingResources,controlWebServices1,0.5).
dep(provideWebCounsellingWithVideo,implementVideoCounselling1).
dep(maintainCSPhoneServices2,maintainPhoneServices1).
dep(kidsHaveOwnershipOfServices,kidsHaveOwnershipOfServices2).
edge(decreaseResponseTIme4,efficientServices1,0.5).
dep(measureSuccessOfServices4,measureSuccessOfServices3).
edge(kidsUseBulletinBoardWithDelayedModeration,controlWebServices,-0.5).
dep(maintainCSPhoneServices2,maintainCSPhoneServices1).
dep(immediacy7,immediacy5).
edge(nonRealTimeECounsellingBeUsed,controlWebServices,0.5).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,immediacy6,0.5).
dec(kidsUseBulletinBoardWithDelayedModeration,technologyThatAllowsDialoguesBetweenKidsBeUsed,or).
dec(kidsUseVoiceCounselling,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,or).
edge(kidsUseOnlineInformationProvided,empoweringKidsToHelpThemselves,0.5).
edge(avoidDialoguesBetweenKids,avoidBadAdvice,0.5).
dec(answer80OfCallsWithin30SecondsOfMessageEnding,maintainCSPhoneServices2,or).
dec(kidsUseOneOnOneChatRooms,moderatedECounsellingBeUsed,or).
dep(provideRecordedMessages,phoneLibraryOfRecordedMessages).
dep(measureSuccessOfServices3,measureSuccessOfServices1).
dep(controlOfCounsellingWork1,controlOfCounsellingWork).
dep(encourageKidsUsingWebServicesToUsePhoneServices1,encourageKidsUsingWebServicesToUsePhoneServices).
edge(parentsUsePhoneCounselling1,confidentialityParents5,0.5).
dep(anonymityKids6,anonymityParents2).
dec(maintainImplementCSWebServices3,maintainImplementCSServices2,or).
edge(acquireFeedback,anonymity,-0.5).
dep(putContentOntoWebsite1,putContentOntoWebsite).
dec(kidsUseOneOnOneChatRooms,nonAnonymousTechnologyBeUsed,or).
dep(maintainPHLPhoneServices1,maintainPHLPhoneServices).
dep(maintainImplementPHLServices1,maintainImplementPHLServices2).
edge(anonymousTechnologyBeUsed,anonymityKids3,1).
dep(relevanceInKidsLives2,relevanceInKidsLives1).
dec(kidsUseEmailCounselling,nonRealTimeECounsellingBeUsed,or).
dep(decreaseResponseTIme4,decreaseResponseTIme3).
edge(parentsUseBulletinBoardWithReplies,immediacy6,-0.5).
dec(kidsUseBulletinBoardWithDelayedModeration,nonRealTimeECounsellingBeUsed,or).
dec(kidsUseEmailCounselling,confidentialTechnologyBeUsed,or).
dep(sufficientCounsellingResources1,sufficientCounsellingResources).
dep(implementCyberCafPortalChatRoom,implementCyberCafPortalChatRoom1).
edge(kidsUseBulletinBoardWithReplies,directResponseToKids,-1).
edge(kidsUseAskACounsellorSection,easierAccessToPostReply,0.5).
dep(kidsUseVoiceCounselling1,kidsUseVoiceCounselling).
dec(implementNToolToAllowParentsToTalkToEachOther,parentsUseNToolToAllowParentsToTalkToEachOther,or).
edge(kidsUseBulletinBoardWithReplies,increasedWebServices4,0.5).
dep(easyAccessToPostReply,easyAccessToPostReply1).
edge(nonAnonymousTechnologyBeUsed,controlWebServices,0.5).
dec(kidsUseVideoCounselling,nonAnonymousTechnologyBeUsed,or).
dec(kidsGetInformationThroughECounselling,kidsUseOnlineInformationProvided,or).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,controlWebServices,-0.5).
dec(kidsUseVideoCounselling,realTimeECounsellingBeUsed,or).
dec(kidsUseTextMessaging,nonAnonymousTechnologyBeUsed,or).
dec(kidsUseCyberCafPortalChatRoom,realTimeECounsellingBeUsed,or).
dec(telephonyBeImplementedAndManaged,maintainPhoneServices,or).
edge(parentsUseBulletinBoardWithReplies,confidentialityParents4,-1).
dec(maintainCSPhoneServices2,kidsUsePhoneCounselling,or).
dep(confidentialityParents4,confidentialityParents3).
dec(kidsUseAskACounsellorSection,anonymousTechnologyBeUsed,or).
dep(confidentialityParents3,confidentialityParents2).
dep(improveWebsiteContent,improveWebsiteContent2).
dep(anonymityKids4,anonymityKids1).
edge(implementPhoneFeedback,measureSuccessOfServices2,0.5).
dep(serviceResources,acquireServiceResources).
dep(improveWebsiteContent1,improveWebsiteContent).
edge(kidsUseVoiceCounselling,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
dec(kidsUseAskACounsellorSection,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,or).
dep(createCounsellingPosts,implementBulletinBoardWithDelayedModeration).
edge(maintainAskACounsellorSection,reduceNumberOfStepsWebPostingTechnology1,-0.5).
dep(reduceContagionEffectOfHarmfulActions,reduceContagionEffectOfHarmfulActions1).
edge(kidsUsePhoneCounselling,kidsHaveOwnershipOfServices1,1).
dec(kidsUseTextMessaging,confidentialTechnologyBeUsed,or).
dep(provideWrittenCounselling,implementOneOnOneChatRooms).
dep(easierToFindPostsWebPostingTechnology,easierToFindPostsWebPostingTechnology1).
dep(webSoftware,obtainSoftware).
dec(obtainSoftware,maintainWebServices,or).
dep(confidentialityKids3,confidentialityKids4).
dep(directResponseToKids,directResponseToKids1).
dep(maintainImplementCSServices1,maintainImplementCSServices).
edge(increaseWebResources,improveWebsiteContent1,0.5).
edge(sufficientlyModeratedWebServices,highQualityServices,0.5).
dep(kidsUseAskACounsellorSection1,kidsUseAskACounsellorSection).
dec(kidsReadGetInformedSectionOfWebSite,kidsUseOnlineInformationProvided,or).
dec(maintainWebServices1,implementServices,or).
edge(kidsUseAskACounsellorSection,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,0.5).
dep(connectBackToTheCommunity5,connectBackToTheCommunity8).
dep(anonymityKids2,anonymityKids4).
dec(kidsUseVideoCounselling,moderatedECounsellingBeUsed,or).
dec(kidsUseEmailCounselling,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,or).
edge(kidsUseOneOnOneChatRooms,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(kidsUseBulletinBoardWithReplies,correctInterpretationOfCounsel,-0.5).
