% CSServices  (edit me: node/2 edge/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, leaf/1, topgoal/1.
node(answer80OfCallsWithin30SecondsOfMessageEnding,goal).
leaf(answer80OfCallsWithin30SecondsOfMessageEnding).
topgoal(answer80OfCallsWithin30SecondsOfMessageEnding).
node(implementFeedbackForm,task).
node(decreaseResponseTIme1,softgoal).
node(increasedWebServices3,softgoal).
node(increaseWebResources2,softgoal).
leaf(increaseWebResources2).
node(implementNToolToAllowParentsToTalkToEachOther1,task).
node(informKidsAboutAnonymityKidsOfWebServices,task).
node(implementOneOnOneChatRooms1,task).
leaf(implementOneOnOneChatRooms1).
node(kidsReadGeneralQuestionsAndAnswers,task).
node(friendlyWebSite1,softgoal).
node(kidsUseVoiceCounselling,task).
node(kidsUseAskACounsellorSection,task).
node(maintainWebServices1,task).
node(confidentialityKids6,softgoal).
node(implementBoardWithReplies1,task).
node(kidsUseOneOnOneChatRooms,task).
node(connectBackToTheCommunity5,softgoal).
node(kidsUseCyberCafPortalChatRoom1,task).
leaf(kidsUseCyberCafPortalChatRoom1).
node(strategicBluePrint,resource).
leaf(strategicBluePrint).
node(implementPhoneFeedback,task).
node(similarityOfProblems1,softgoal).
node(immediacy2,softgoal).
node(maintainImplementCSServices,task).
node(accommodatePhoneTraffic,softgoal).
node(similarityWithOtherParentsProblems,softgoal).
node(implementTextMessaging,task).
node(anonymousTechnologyBeUsed,goal).
topgoal(anonymousTechnologyBeUsed).
node(maintainAskACounsellorSection1,task).
leaf(maintainAskACounsellorSection1).
node(accommodateWebSiteTraffic,softgoal).
node(maintainPHLPhoneServices4,task).
leaf(maintainPHLPhoneServices4).
node(kidsHaveOwnershipOfServices1,softgoal).
node(servicesBeBilingual1,goal).
leaf(servicesBeBilingual1).
topgoal(servicesBeBilingual1).
node(moderateDiscussionBoards,task).
leaf(moderateDiscussionBoards).
node(easierNavigationCSWebServices1,softgoal).
node(sufficientCounsellingResources1,softgoal).
leaf(sufficientCounsellingResources1).
node(measureSuccessOfServices4,softgoal).
node(anonymityKids3,softgoal).
node(highQualityServices2,softgoal).
node(maintainPhoneServices1,task).
node(implementEmailCounselling,task).
node(easierToFindPostsWebPostingTechnology1,softgoal).
node(kidsUseCyberCafPortalChatRoom,task).
node(implementPhoneFeedback3,task).
leaf(implementPhoneFeedback3).
node(qualityServices,softgoal).
node(kidsUsePhoneCounselling1,task).
leaf(kidsUsePhoneCounselling1).
node(webServicesSelfServe1,softgoal).
node(efficientPhoneServices,softgoal).
node(counsellorsBeProfessionallyTrained,goal).
topgoal(counsellorsBeProfessionallyTrained).
node(webSiteContent,resource).
leaf(webSiteContent).
node(maintainImplementCSServices3,task).
node(connectBackToTheCommunity8,softgoal).
node(provideWebCounsellingWithVideo,task).
leaf(provideWebCounsellingWithVideo).
node(nonRealTimeECounsellingBeUsed,goal).
topgoal(nonRealTimeECounsellingBeUsed).
node(controlOfCounsellingWork1,softgoal).
node(increasedWebServices4,softgoal).
node(decreaseResponseTIme2,softgoal).
node(implementGetInformedSectionOfWebSite,task).
node(increaseWebResources1,softgoal).
node(implementFeedbackCollection,task).
node(connectBackToTheCommunity1,softgoal).
node(encourageKidsUsingWebServicesToUsePhoneServices1,softgoal).
node(decreaseResponseTIme,softgoal).
node(parentsUseNToolToAllowParentsToTalkToEachOther,task).
node(implementBulletinBoardWithReplies,task).
node(provideWebCounsellingWithAudio,task).
leaf(provideWebCounsellingWithAudio).
node(anonymityParents4,softgoal).
node(servicesBeBilingual,goal).
topgoal(servicesBeBilingual).
node(confidentialityKids1,softgoal).
node(implementCyberCafPortalChatRoom,task).
node(connectBackToTheCommunity6,softgoal).
node(avoidBadAdvice2,softgoal).
node(obtainNeededSoftware,task).
node(effectiveChatRoomFilters,softgoal).
leaf(effectiveChatRoomFilters).
node(maintainImplementCSWebServices2,task).
node(webServicesSelfServe,softgoal).
node(availableServices2,softgoal).
node(nonAnonymousTechnologyBeUsed,goal).
topgoal(nonAnonymousTechnologyBeUsed).
node(kidsHaveOwnershipOfServices5,softgoal).
node(maintainPHLWebServices2,task).
node(anonymityKids6,softgoal).
node(improveWebsiteContent1,softgoal).
node(implementGeneralQuestionsAndAnswers,task).
node(servicesBeProvidedForKidsBullyingLine,goal).
topgoal(servicesBeProvidedForKidsBullyingLine).
node(confidentialTechnologyBeUsed,goal).
topgoal(confidentialTechnologyBeUsed).
node(efficientPhoneServices1,softgoal).
node(acquireFeedback,task).
node(maintainImplementPHLServices2,task).
node(kidsUseVideoCounselling,task).
node(immediacy7,softgoal).
node(reducePrankCalls1,softgoal).
node(anonymityKids5,softgoal).
node(sufficientCounsellingResources2,softgoal).
node(controlWebServices2,softgoal).
node(kidsUseEmailCounselling1,task).
leaf(kidsUseEmailCounselling1).
node(maintainAskACounsellorSection,task).
node(maintainPhoneServices,task).
node(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,goal).
topgoal(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed).
node(confidentialityServices,softgoal).
node(implementEmailCounselling1,task).
node(servicesBeProvidedForKidsBullyingLine1,goal).
topgoal(servicesBeProvidedForKidsBullyingLine1).
node(implementVoiceCounselling,task).
node(implementDelay,task).
leaf(implementDelay).
node(kidsReadGetInformedSectionOfWebSite,task).
node(implementAntiPrankingMessage,task).
leaf(implementAntiPrankingMessage).
node(encourageKidsUsingWebServicesToUsePhoneServices,softgoal).
node(feedbackFormSoftware,resource).
leaf(feedbackFormSoftware).
node(scheduleChatAtSpecificTimes,task).
leaf(scheduleChatAtSpecificTimes).
node(increasePhoneResources2,softgoal).
node(implementOneOnOneChatRooms,task).
node(efficientServices1,softgoal).
node(kidsUseBulletinBoardWithDelayedModeration,task).
node(friendlyWebSite,softgoal).
node(confidentialityParents5,softgoal).
node(implementFeedbackForm1,task).
node(confidentialityKids5,softgoal).
node(availableServices1,softgoal).
node(kidsReadGeneralQuestionsAndAnswers1,task).
leaf(kidsReadGeneralQuestionsAndAnswers1).
node(implementInformationSection1,task).
node(relevanceInKidsLives,softgoal).
node(maintainServicesAboveCompetition,softgoal).
node(acquireServiceResources,task).
node(onlyOnlineRequestFromCanadiansAccepted,goal).
leaf(onlyOnlineRequestFromCanadiansAccepted).
topgoal(onlyOnlineRequestFromCanadiansAccepted).
node(anonymityCounsellors,softgoal).
node(connectBackToTheCommunity2,softgoal).
node(implementVideoCounselling1,task).
node(implementServices,task).
node(connectToOtherKids,softgoal).
node(immediacy3,softgoal).
node(directResponseToKids1,softgoal).
node(maintainCSPhoneServices1,task).
node(availableServices,softgoal).
node(putContentOntoWebsite,task).
node(maintainPHLPhoneServices3,task).
node(controlWebServices,softgoal).
node(implementBulletinBoardWithReplies1,task).
leaf(implementBulletinBoardWithReplies1).
node(improveWebsiteContent,softgoal).
node(nonConfidentialTechnologyBeUsed,goal).
topgoal(nonConfidentialTechnologyBeUsed).
node(efficientPhoneServices2,softgoal).
node(maintainPHLWebServices1,task).
node(decreasePhoneWaitingTime,softgoal).
node(improveWebsiteContent2,softgoal).
node(highQualityServices1,softgoal).
node(implementGetInformedSectionOfWebSite1,task).
node(informKidsAboutAnonymityKidsOfWebServices1,task).
leaf(informKidsAboutAnonymityKidsOfWebServices1).
node(anonymityKids2,softgoal).
node(maintainCSPhoneServices2,task).
node(directResponseToKids,softgoal).
node(immediacy4,softgoal).
node(sufficientlyModeratedWebServices1,softgoal).
node(obtainSoftware,task).
node(sufficientCounsellingResources,softgoal).
node(kidsHaveOwnershipOfServices6,softgoal).
leaf(kidsHaveOwnershipOfServices6).
node(implementPhoneFeedback2,task).
node(implementNToolToAllowParentsToTalkToEachOther,task).
leaf(implementNToolToAllowParentsToTalkToEachOther).
node(kidsGetInformationThroughECounselling,task).
node(connectBackToTheCommunity,softgoal).
node(confidentialityParents1,softgoal).
node(anonymityParents2,softgoal).
node(efficientWebServices,softgoal).
node(maintainImplementCSServices2,task).
node(kidsReadPollsAboutKids,task).
node(kidsUsePhoneCounselling,task).
node(kidsUseOneOnOneChatRooms1,task).
node(voiceCounsellingBePerformed,task).
leaf(voiceCounsellingBePerformed).
node(confidentiality,softgoal).
node(maintainCSPhoneServices3,task).
node(maintainWebServices,task).
node(decreaseResponseTIme3,softgoal).
node(kidsUseGetInformedSectionOfWebSite,task).
leaf(kidsUseGetInformedSectionOfWebSite).
node(decreaseResponseTIme4,softgoal).
leaf(decreaseResponseTIme4).
node(avoidDialoguesBetweenKids,softgoal).
node(maintainPHLPhoneServices,task).
node(parentsUseBulletinBoardWithReplies,task).
node(anonymityParents5,softgoal).
node(kidsUseOnlineInformationProvided,goal).
topgoal(kidsUseOnlineInformationProvided).
node(maintainWebServices3,task).
node(performEmailCounselling,task).
leaf(performEmailCounselling).
node(connectBackToTheCommunity7,softgoal).
node(avoidBadAdvice3,softgoal).
node(similarityOfProblems,softgoal).
node(maintainImplementCSWebServices1,task).
node(implementBulletinBoardWithDelayedModeration1,task).
leaf(implementBulletinBoardWithDelayedModeration1).
node(availableServices5,softgoal).
node(increaseEmphasisOnOnlineFeedbackForm1,softgoal).
leaf(increaseEmphasisOnOnlineFeedbackForm1).
node(controlOfCounsellingWork,softgoal).
node(avoidBadAdvice,softgoal).
node(kidsHaveOwnershipOfServices4,softgoal).
node(measureSuccessOfServices1,softgoal).
node(reduceContagionEffectOfHarmfulActions1,softgoal).
node(anonymityKids1,softgoal).
node(improveImageToKids1,softgoal).
node(avoidPresenceOfPedofiles,softgoal).
node(confidentialityParents,softgoal).
node(maintainPhoneServices4,task).
node(measureSuccessOfServices,softgoal).
node(similarityWithOtherParentsProblems1,softgoal).
node(avoidBadAdvice4,softgoal).
node(maintainImplementPHLServices1,task).
node(increaseResourcesServices1,softgoal).
leaf(increaseResourcesServices1).
node(controlWebServices1,softgoal).
node(implementVideoCounselling,task).
node(webServer,resource).
leaf(webServer).
node(anonymityCounsellors1,softgoal).
node(blockKidsWhoDisplayInappropriateBehavoir,task).
leaf(blockKidsWhoDisplayInappropriateBehavoir).
node(maintainPhoneServices3,task).
node(reduceNumberOfStepsWebPostingTechnology1,softgoal).
node(friendlyWebSite2,softgoal).
node(increaseWebResources,softgoal).
node(increasePhoneResources1,softgoal).
node(feedback,resource).
leaf(feedback).
node(highQualityServices,softgoal).
node(implementPollsAboutKids1,task).
node(increasedWebServices1,softgoal).
node(implementInformationSection,task).
leaf(implementInformationSection).
node(implementPhoneFeedback1,task).
node(sufficientlyModeratedWebServices,softgoal).
node(technologyThatAllowsDialoguesBetweenKidsBeUsed,goal).
topgoal(technologyThatAllowsDialoguesBetweenKidsBeUsed).
node(strategicBluePrintForWebsiteBeFollowed,goal).
topgoal(strategicBluePrintForWebsiteBeFollowed).
node(avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,softgoal).
node(friendlyWebSite12,softgoal).
node(confidentialityParents4,softgoal).
node(obtainWebServer,task).
node(improveImageToKids,softgoal).
node(implementFeedbackForm2,task).
node(increaseNumberOfServices1,softgoal).
node(confidentialityKids4,softgoal).
node(reduceContagionEffectOfHarmfulActions,softgoal).
node(confidentialityParents2,softgoal).
node(kidsHaveOwnershipOfServices,softgoal).
node(webSiteContentBeUpdatedDaily,goal).
leaf(webSiteContentBeUpdatedDaily).
topgoal(webSiteContentBeUpdatedDaily).
node(implementVoiceCounselling1,task).
leaf(implementVoiceCounselling1).
node(connectBackToTheCommunity3,softgoal).
node(kidsReadPollsAboutKids1,task).
leaf(kidsReadPollsAboutKids1).
node(empoweringKidsToHelpThemselves,softgoal).
node(feedback1,resource).
leaf(feedback1).
node(directResponseToKids2,softgoal).
node(confidentialityKids3,softgoal).
node(anonymityKids,softgoal).
node(increaseResourcesServices,softgoal).
node(reducePrankCalls,softgoal).
leaf(reducePrankCalls).
node(maintainPHLWebServices,task).
node(correctInterpretationOfCounsel,softgoal).
node(maintainPHLPhoneServices2,task).
node(kidsHaveOwnershipOfServices3,softgoal).
node(anonymityKids4,softgoal).
node(measureSuccessOfServices2,softgoal).
node(easierAccessToPostReply,softgoal).
node(connectBackToTheCommunity9,softgoal).
node(realTimeECounsellingBeUsed,goal).
topgoal(realTimeECounsellingBeUsed).
node(easierNavigationCSWebServices2,softgoal).
node(easierNavigationCSWebServices,softgoal).
node(immediacy5,softgoal).
node(acquireWebContent,task).
node(webSoftware,resource).
leaf(webSoftware).
node(sufficientlyModeratedWebServices2,softgoal).
node(easierAccessToPostReply1,softgoal).
node(anonymityParents1,softgoal).
node(parentsUseInformationSection1,task).
leaf(parentsUseInformationSection1).
node(relevanceInKidsLives1,softgoal).
node(avoidPresenceOfPedofiles1,softgoal).
leaf(avoidPresenceOfPedofiles1).
node(webServicesSelfServe3,softgoal).
leaf(webServicesSelfServe3).
node(increasePhoneResources,softgoal).
leaf(increasePhoneResources).
node(maintainImplementCSServices1,task).
node(counsellorsBeProfessionallyTrained1,goal).
leaf(counsellorsBeProfessionallyTrained1).
topgoal(counsellorsBeProfessionallyTrained1).
node(implementCyberCafPortalChatRoom1,task).
node(traceCalls,task).
leaf(traceCalls).
node(increasedWebServices2,softgoal).
node(efficientWebServices2,softgoal).
node(increaseEmphasisOnOnlineFeedbackForm,softgoal).
node(provideWrittenCounselling,task).
leaf(provideWrittenCounselling).
node(connectBackToTheCommunity4,softgoal).
node(provideRecordedMessages,task).
leaf(provideRecordedMessages).
node(phoneLibraryOfRecordedMessages,resource).
node(putContentOntoWebsite1,task).
leaf(putContentOntoWebsite1).
node(confidentialityKids7,softgoal).
node(kidsUseVideoCounselling1,task).
leaf(kidsUseVideoCounselling1).
node(maintainWebServices2,task).
node(immediacy8,softgoal).
node(increaseNumberOfServices,softgoal).
node(connectBackToTheCommunity42,softgoal).
node(confidentialityKids,softgoal).
leaf(confidentialityKids).
node(availableServices4,softgoal).
node(implementPollsAboutKids,task).
node(increasedWebServices,softgoal).
node(maintainServicesAboveCompetition1,softgoal).
node(kidsUseTextMessaging,task).
node(parentsUsePhoneCounselling1,task).
node(kidsUseBulletinBoardWithReplies,task).
node(immediacy1,softgoal).
node(avoidBadAdvice5,softgoal).
node(implementBoardWithReplies,task).
leaf(implementBoardWithReplies).
node(implementTextMessaging1,task).
leaf(implementTextMessaging1).
node(kidsUseVoiceCounselling1,task).
leaf(kidsUseVoiceCounselling1).
node(kidsUseTextMessaging1,task).
node(maintainImplementPHLServices,task).
node(implementGeneralQuestionsAndAnswers1,task).
node(reduceNumberOfStepsWebPostingTechnology,softgoal).
node(anonymityParents,softgoal).
node(maintainPhoneServices2,task).
node(parentsUseInformationSection,task).
node(empoweringKidsToHelpThemselves1,softgoal).
node(serviceResources,resource).
leaf(serviceResources).
node(telephonyBeImplementedAndManaged1,goal).
leaf(telephonyBeImplementedAndManaged1).
topgoal(telephonyBeImplementedAndManaged1).
node(implementFilters,task).
leaf(implementFilters).
node(moderatedECounsellingBeUsed,goal).
topgoal(moderatedECounsellingBeUsed).
node(kidsUseEmailCounselling,task).
node(relevanceInKidsLives2,softgoal).
leaf(relevanceInKidsLives2).
node(immediacyServices,softgoal).
node(anonymityParents3,softgoal).
node(moderateAChat,task).
leaf(moderateAChat).
node(parentsUsePhoneCounselling,task).
node(anonymity,softgoal).
node(availableServices3,softgoal).
node(maintainCSPhoneServices,task).
node(connectBackToTheCommunity10,softgoal).
node(easyAccessToPostReply,softgoal).
node(avoidDialogues,softgoal).
node(createCounsellingPosts,task).
leaf(createCounsellingPosts).
node(efficientWebServices1,softgoal).
node(parentsUseNToolToAllowParentsToTalkToEachOther1,task).
leaf(parentsUseNToolToAllowParentsToTalkToEachOther1).
node(decreasePhoneWaitingTime2,softgoal).
node(telephonyBeImplementedAndManaged,goal).
topgoal(telephonyBeImplementedAndManaged).
node(availabilityServices,softgoal).
node(easierToFindPostsWebPostingTechnology,softgoal).
node(confidentialityKids2,softgoal).
node(maintainImplementCSWebServices,task).
node(maintainPHLPhoneServices1,task).
node(maintainImplementCSWebServices3,task).
node(avoidBadAdvice1,softgoal).
node(kidsHaveOwnershipOfServices2,softgoal).
node(anonymityKids7,softgoal).
node(maintainPHLWebServices3,task).
node(correctInterpretationOfCounsel1,softgoal).
leaf(correctInterpretationOfCounsel1).
node(decreasePhoneWaitingTime1,softgoal).
node(serviceLevelsBeMet,goal).
leaf(serviceLevelsBeMet).
topgoal(serviceLevelsBeMet).
node(measureSuccessOfServices3,softgoal).
node(kidsUseAskACounsellorSection1,task).
leaf(kidsUseAskACounsellorSection1).
node(implementBulletinBoardWithDelayedModeration,task).
node(immediacy,softgoal).
node(maintainImplementPHLServices3,task).
node(immediacy6,softgoal).
node(sufficientlyModeratedWebServices3,softgoal).
node(parentsUseBulletinBoardWithReplies1,task).
leaf(parentsUseBulletinBoardWithReplies1).
node(kidsUseBulletinBoardWithDelayedModeration1,task).
leaf(kidsUseBulletinBoardWithDelayedModeration1).
node(webServicesSelfServe2,softgoal).
node(confidentialityParents3,softgoal).
node(avoidPresenceOfPedofiles2,softgoal).
node(easyAccessToPostReply1,softgoal).
node(kidsUseBulletinBoardWithReplies1,task).
leaf(kidsUseBulletinBoardWithReplies1).
node(sufficientlyModeratedWebServices4,softgoal).
node(efficientServices,softgoal).
edge(kidsUseBulletinBoardWithDelayedModeration,correctInterpretationOfCounsel,-0.5).
edge(avoidPresenceOfPedofiles,avoidBadAdvice,0.5).
edge(kidsUseVideoCounselling,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(implementNToolToAllowParentsToTalkToEachOther,maintainPHLWebServices2,1).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,connectToOtherKids,1).
edge(maintainCSPhoneServices3,maintainImplementCSServices2,1).
edge(answer80OfCallsWithin30SecondsOfMessageEnding,decreasePhoneWaitingTime2,0.5).
edge(easierAccessToPostReply,easierNavigationCSWebServices1,0.5).
edge(putContentOntoWebsite,implementPollsAboutKids,1).
edge(implementTextMessaging1,implementTextMessaging,1).
edge(kidsUseBulletinBoardWithReplies,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(empoweringKidsToHelpThemselves,empoweringKidsToHelpThemselves1,1).
edge(webServer,obtainWebServer,1).
edge(maintainPHLWebServices1,maintainPHLWebServices,1).
edge(maintainPhoneServices3,maintainPhoneServices2,1).
edge(anonymityParents1,anonymityParents,1).
edge(maintainPHLWebServices,maintainWebServices,1).
edge(maintainImplementCSServices,servicesBeProvidedForKidsBullyingLine,1).
edge(implementPhoneFeedback3,implementPhoneFeedback,1).
edge(increasePhoneResources2,increasePhoneResources1,1).
edge(informKidsAboutAnonymityKidsOfWebServices1,kidsHaveOwnershipOfServices,0.5).
edge(kidsHaveOwnershipOfServices6,kidsHaveOwnershipOfServices5,1).
edge(implementBulletinBoardWithReplies1,implementBulletinBoardWithReplies,1).
edge(kidsUseBulletinBoardWithReplies,anonymityCounsellors,0.5).
edge(obtainNeededSoftware,implementFeedbackForm,1).
edge(anonymityKids3,improveImageToKids,0.5).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,connectBackToTheCommunity3,0.5).
edge(serviceLevelsBeMet,highQualityServices,0.5).
edge(kidsUseOnlineInformationProvided,connectBackToTheCommunity4,0.5).
edge(implementFilters,implementCyberCafPortalChatRoom,1).
edge(anonymityKids1,anonymityKids,1).
edge(controlWebServices,avoidPresenceOfPedofiles,0.5).
edge(controlWebServices,controlWebServices2,1).
edge(kidsUseBulletinBoardWithDelayedModeration1,kidsUseBulletinBoardWithDelayedModeration,1).
edge(confidentialityKids1,improveImageToKids,0.5).
edge(maintainWebServices,maintainWebServices2,1).
edge(kidsUseVideoCounselling,anonymityCounsellors,-0.5).
edge(highQualityServices,highQualityServices2,1).
edge(similarityOfProblems,similarityOfProblems1,1).
edge(implementFeedbackForm,measureSuccessOfServices1,0.5).
edge(immediacy2,immediacy1,1).
edge(sufficientCounsellingResources2,accommodatePhoneTraffic,0.5).
edge(sufficientCounsellingResources,decreaseResponseTIme2,0.5).
edge(avoidPresenceOfPedofiles,improveImageToKids,0.5).
edge(kidsUseAskACounsellorSection,easierToFindPostsWebPostingTechnology,0.5).
edge(efficientWebServices2,efficientWebServices1,1).
edge(webServicesSelfServe1,webServicesSelfServe,1).
edge(implementFeedbackForm2,implementFeedbackCollection,1).
edge(webServicesSelfServe,accommodateWebSiteTraffic,0.5).
edge(increaseWebResources2,increaseResourcesServices,0.5).
edge(acquireFeedback,confidentiality,-0.5).
edge(easierNavigationCSWebServices,easierNavigationCSWebServices2,1).
edge(maintainPHLPhoneServices2,parentsUsePhoneCounselling1,1).
edge(connectBackToTheCommunity9,connectBackToTheCommunity,1).
edge(parentsUseBulletinBoardWithReplies,anonymityParents3,0.5).
edge(maintainPhoneServices,availableServices3,1).
edge(connectBackToTheCommunity2,connectBackToTheCommunity42,1).
edge(kidsUseBulletinBoardWithDelayedModeration,directResponseToKids,-1).
edge(implementBulletinBoardWithReplies,kidsUseBulletinBoardWithReplies,1).
edge(kidsReadPollsAboutKids,kidsUseOnlineInformationProvided,1).
edge(confidentialityKids,reducePrankCalls1,-0.5).
edge(anonymityKids3,anonymityKids2,1).
edge(kidsUseBulletinBoardWithReplies,easierToFindPostsWebPostingTechnology,0.5).
edge(kidsReadGetInformedSectionOfWebSite,webServicesSelfServe2,0.5).
edge(kidsHaveOwnershipOfServices1,kidsHaveOwnershipOfServices2,1).
edge(maintainPhoneServices,maintainPhoneServices3,1).
edge(maintainPHLWebServices1,maintainPHLWebServices3,1).
edge(reduceNumberOfStepsWebPostingTechnology1,reduceNumberOfStepsWebPostingTechnology,1).
edge(easierAccessToPostReply,directResponseToKids,0.5).
edge(anonymityCounsellors,anonymityCounsellors1,1).
edge(counsellorsBeProfessionallyTrained,highQualityServices,0.5).
edge(kidsUseEmailCounselling,directResponseToKids,1).
edge(maintainCSPhoneServices,maintainPhoneServices,1).
edge(webSiteContent,acquireWebContent,1).
edge(realTimeECounsellingBeUsed,decreaseResponseTIme,1).
edge(provideRecordedMessages,maintainPHLPhoneServices2,1).
edge(provideWrittenCounselling,implementCyberCafPortalChatRoom,1).
edge(kidsUseOneOnOneChatRooms,anonymityCounsellors,0.5).
edge(availableServices1,availableServices5,1).
edge(anonymityParents3,anonymityKids6,1).
edge(confidentialityKids4,confidentialityKids5,1).
edge(implementPhoneFeedback,implementPhoneFeedback1,1).
edge(parentsUseBulletinBoardWithReplies,similarityWithOtherParentsProblems,0.5).
edge(kidsUseOnlineInformationProvided,maintainImplementCSWebServices,1).
edge(maintainPHLPhoneServices1,maintainPHLPhoneServices3,1).
edge(maintainImplementPHLServices2,maintainImplementPHLServices3,1).
edge(anonymityParents,anonymity,0.5).
edge(webServicesSelfServe2,webServicesSelfServe1,1).
edge(implementVideoCounselling1,kidsUseVideoCounselling,1).
edge(moderatedECounsellingBeUsed,kidsGetInformationThroughECounselling,1).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,avoidBadAdvice3,-0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,reduceNumberOfStepsWebPostingTechnology1,0.5).
edge(implementInformationSection,implementInformationSection1,1).
edge(moderateAChat,implementCyberCafPortalChatRoom,1).
edge(increasePhoneResources,increaseResourcesServices,0.5).
edge(implementOneOnOneChatRooms1,implementOneOnOneChatRooms,1).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,similarityOfProblems,-0.5).
edge(realTimeECounsellingBeUsed,directResponseToKids,1).
edge(decreaseResponseTIme,improveImageToKids,0.5).
edge(implementBoardWithReplies,maintainPHLWebServices2,1).
edge(maintainPHLPhoneServices3,maintainImplementPHLServices,1).
edge(kidsUseTextMessaging,increasedWebServices4,0.5).
edge(kidsUseEmailCounselling,nonAnonymousTechnologyBeUsed,1).
edge(relevanceInKidsLives,highQualityServices,0.5).
edge(kidsReadGeneralQuestionsAndAnswers1,kidsReadGeneralQuestionsAndAnswers,1).
edge(informKidsAboutAnonymityKidsOfWebServices1,informKidsAboutAnonymityKidsOfWebServices,1).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,avoidDialoguesBetweenKids,1).
edge(easierNavigationCSWebServices1,friendlyWebSite2,0.5).
edge(kidsUseVideoCounselling,confidentialTechnologyBeUsed,1).
edge(implementInformationSection,parentsUseInformationSection,1).
edge(immediacy,immediacy8,1).
edge(kidsUseEmailCounselling1,kidsUseEmailCounselling,1).
edge(provideWebCounsellingWithAudio,implementVoiceCounselling,1).
edge(kidsReadGeneralQuestionsAndAnswers,webServicesSelfServe2,0.5).
edge(moderatedECounsellingBeUsed,maintainServicesAboveCompetition1,0.5).
edge(kidsUseEmailCounselling,anonymityCounsellors,-0.5).
edge(increaseEmphasisOnOnlineFeedbackForm1,increaseEmphasisOnOnlineFeedbackForm,1).
edge(decreaseResponseTIme1,decreaseResponseTIme2,1).
edge(sufficientlyModeratedWebServices4,sufficientlyModeratedWebServices3,1).
edge(relevanceInKidsLives2,improveImageToKids,0.5).
edge(moderateDiscussionBoards,maintainAskACounsellorSection,1).
edge(decreaseResponseTIme,decreaseResponseTIme1,1).
edge(counsellorsBeProfessionallyTrained1,counsellorsBeProfessionallyTrained,1).
edge(voiceCounsellingBePerformed,maintainPHLPhoneServices2,1).
edge(similarityWithOtherParentsProblems,similarityWithOtherParentsProblems1,1).
edge(efficientServices1,efficientServices,1).
edge(kidsUseCyberCafPortalChatRoom,nonConfidentialTechnologyBeUsed,1).
edge(anonymityKids,anonymityKids7,1).
edge(availableServices1,availabilityServices,1).
edge(availableServices1,availableServices,1).
edge(implementVideoCounselling1,implementVideoCounselling,1).
edge(increasedWebServices1,increasedWebServices,1).
edge(confidentialityKids2,confidentialityKids6,1).
edge(kidsUseBulletinBoardWithDelayedModeration,reduceContagionEffectOfHarmfulActions,-0.5).
edge(kidsUseBulletinBoardWithReplies,anonymousTechnologyBeUsed,1).
edge(maintainAskACounsellorSection1,maintainAskACounsellorSection,1).
edge(increasedWebServices4,increasedWebServices3,1).
edge(kidsUseBulletinBoardWithReplies,nonRealTimeECounsellingBeUsed,1).
edge(measureSuccessOfServices2,measureSuccessOfServices,1).
edge(moderatedECounsellingBeUsed,kidsHaveOwnershipOfServices,0.5).
edge(efficientPhoneServices2,efficientPhoneServices1,1).
edge(kidsReadPollsAboutKids1,kidsReadPollsAboutKids,1).
edge(maintainWebServices,availableServices4,-0.5).
edge(immediacy,immediacyServices,1).
edge(nonRealTimeECounsellingBeUsed,avoidBadAdvice,0.5).
edge(feedback1,acquireFeedback,1).
edge(increaseWebResources2,increaseWebResources1,1).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,avoidDialoguesBetweenKids,-1).
edge(implementEmailCounselling1,kidsUseEmailCounselling,1).
edge(kidsUseOneOnOneChatRooms,kidsUseOneOnOneChatRooms1,1).
edge(connectBackToTheCommunity4,connectBackToTheCommunity7,1).
edge(kidsUseEmailCounselling,increasedWebServices4,0.5).
edge(maintainPHLPhoneServices,maintainPhoneServices,1).
edge(sufficientlyModeratedWebServices2,sufficientlyModeratedWebServices1,1).
edge(avoidBadAdvice5,avoidBadAdvice4,1).
edge(kidsUseBulletinBoardWithDelayedModeration,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(kidsHaveOwnershipOfServices2,kidsHaveOwnershipOfServices3,1).
edge(blockKidsWhoDisplayInappropriateBehavoir,implementCyberCafPortalChatRoom,1).
edge(avoidDialoguesBetweenKids,avoidDialogues,1).
edge(anonymityKids5,anonymityKids2,1).
edge(decreaseResponseTIme3,decreaseResponseTIme2,1).
edge(kidsUseOneOnOneChatRooms,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,1).
edge(sufficientCounsellingResources,sufficientlyModeratedWebServices2,0.5).
edge(anonymity,highQualityServices,0.5).
edge(realTimeECounsellingBeUsed,avoidBadAdvice,-0.5).
edge(implementNToolToAllowParentsToTalkToEachOther,implementNToolToAllowParentsToTalkToEachOther1,1).
edge(onlyOnlineRequestFromCanadiansAccepted,increaseWebResources,0.5).
edge(confidentialityParents,confidentiality,0.5).
edge(kidsUseCyberCafPortalChatRoom,nonAnonymousTechnologyBeUsed,1).
edge(anonymityParents,anonymityParents5,1).
edge(connectBackToTheCommunity9,highQualityServices,0.5).
edge(connectBackToTheCommunity42,connectBackToTheCommunity5,1).
edge(kidsUseBulletinBoardWithReplies,reduceNumberOfStepsWebPostingTechnology1,-0.5).
edge(maintainWebServices2,maintainWebServices1,1).
edge(acquireWebContent,putContentOntoWebsite,1).
edge(accommodatePhoneTraffic,decreasePhoneWaitingTime,1).
edge(immediacy5,immediacy3,1).
edge(implementDelay,reduceContagionEffectOfHarmfulActions,0.5).
edge(effectiveChatRoomFilters,reduceContagionEffectOfHarmfulActions,0.5).
edge(efficientWebServices1,efficientWebServices,1).
edge(controlWebServices2,controlWebServices1,1).
edge(performEmailCounselling,implementEmailCounselling1,1).
edge(telephonyBeImplementedAndManaged1,telephonyBeImplementedAndManaged,1).
edge(confidentialityKids5,highQualityServices,0.5).
edge(sufficientlyModeratedWebServices1,sufficientlyModeratedWebServices,1).
edge(acquireServiceResources,maintainImplementPHLServices2,1).
edge(maintainPhoneServices2,maintainPhoneServices4,1).
edge(parentsUseBulletinBoardWithReplies1,parentsUseBulletinBoardWithReplies,1).
edge(kidsHaveOwnershipOfServices3,kidsHaveOwnershipOfServices4,1).
edge(kidsUseOneOnOneChatRooms,realTimeECounsellingBeUsed,1).
edge(kidsUseOneOnOneChatRooms,increasedWebServices4,0.5).
edge(nonRealTimeECounsellingBeUsed,decreaseResponseTIme,-0.5).
edge(increasedWebServices,increaseNumberOfServices,0.5).
edge(confidentialTechnologyBeUsed,confidentialityKids1,1).
edge(maintainPHLWebServices3,maintainImplementPHLServices,1).
edge(kidsUseVoiceCounselling,correctInterpretationOfCounsel,0.5).
edge(kidsUseCyberCafPortalChatRoom,technologyThatAllowsDialoguesBetweenKidsBeUsed,1).
edge(putContentOntoWebsite,implementGeneralQuestionsAndAnswers,1).
edge(confidentialityParents,confidentialityServices,1).
edge(avoidBadAdvice3,avoidBadAdvice2,1).
edge(kidsReadPollsAboutKids,similarityOfProblems,0.5).
edge(kidsUseVideoCounselling1,kidsUseVideoCounselling,1).
edge(directResponseToKids,anonymityCounsellors,-0.5).
edge(kidsUseBulletinBoardWithReplies,technologyThatAllowsDialoguesBetweenKidsBeUsed,1).
edge(kidsUseBulletinBoardWithReplies,nonConfidentialTechnologyBeUsed,1).
edge(kidsUseTextMessaging,realTimeECounsellingBeUsed,1).
edge(kidsUseVoiceCounselling,moderatedECounsellingBeUsed,1).
edge(increaseEmphasisOnOnlineFeedbackForm1,measureSuccessOfServices4,0.5).
edge(sufficientCounsellingResources,accommodateWebSiteTraffic,1).
edge(kidsUseTextMessaging,kidsUseTextMessaging1,1).
edge(efficientServices1,highQualityServices,0.5).
edge(improveImageToKids,improveImageToKids1,1).
edge(maintainServicesAboveCompetition1,improveImageToKids,0.5).
edge(directResponseToKids1,directResponseToKids2,1).
edge(kidsUseBulletinBoardWithDelayedModeration,avoidPresenceOfPedofiles,-1).
edge(implementPhoneFeedback1,implementPhoneFeedback2,1).
edge(immediacy3,immediacy1,1).
edge(accommodatePhoneTraffic,efficientPhoneServices2,0.5).
edge(kidsUseAskACounsellorSection,directResponseToKids,-1).
edge(connectBackToTheCommunity7,connectBackToTheCommunity6,1).
edge(avoidBadAdvice1,avoidBadAdvice5,1).
edge(increasePhoneResources,increasePhoneResources2,1).
edge(kidsUseVoiceCounselling,confidentialTechnologyBeUsed,1).
edge(traceCalls,anonymityParents2,-1).
edge(webSiteContentBeUpdatedDaily,improveWebsiteContent1,0.5).
edge(immediacy7,friendlyWebSite2,0.5).
edge(kidsUsePhoneCounselling,confidentialityKids6,0.5).
edge(maintainImplementCSServices,implementServices,1).
edge(increasePhoneResources1,accommodatePhoneTraffic,0.5).
edge(scheduleChatAtSpecificTimes,implementCyberCafPortalChatRoom,1).
edge(kidsUseCyberCafPortalChatRoom1,kidsUseCyberCafPortalChatRoom,1).
edge(maintainImplementPHLServices2,implementServices,1).
edge(parentsUsePhoneCounselling1,parentsUsePhoneCounselling,1).
edge(putContentOntoWebsite,implementGetInformedSectionOfWebSite,1).
edge(implementVoiceCounselling,kidsUseVoiceCounselling,1).
edge(maintainImplementPHLServices,maintainImplementPHLServices1,1).
edge(anonymityKids,anonymity,0.5).
edge(maintainImplementCSServices,maintainImplementCSServices3,1).
edge(availableServices2,availableServices1,1).
edge(implementFeedbackForm1,implementFeedbackForm2,1).
edge(immediacy,highQualityServices,0.5).
edge(easierNavigationCSWebServices2,efficientWebServices2,0.5).
edge(kidsUseCyberCafPortalChatRoom,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,moderatedECounsellingBeUsed,1).
edge(maintainCSPhoneServices1,maintainCSPhoneServices3,1).
edge(increaseNumberOfServices,increaseNumberOfServices1,1).
edge(kidsUseBulletinBoardWithDelayedModeration,nonConfidentialTechnologyBeUsed,1).
edge(kidsReadPollsAboutKids,implementPollsAboutKids1,1).
edge(kidsUseTextMessaging,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,1).
edge(sufficientlyModeratedWebServices3,sufficientlyModeratedWebServices2,1).
edge(highQualityServices,qualityServices,1).
edge(kidsUseBulletinBoardWithDelayedModeration,anonymityCounsellors,0.5).
edge(anonymousTechnologyBeUsed,controlWebServices,-0.5).
edge(maintainWebServices1,maintainWebServices3,1).
edge(avoidDialoguesBetweenKids,reduceContagionEffectOfHarmfulActions,0.5).
edge(avoidBadAdvice4,highQualityServices,0.5).
edge(createCounsellingPosts,implementBulletinBoardWithReplies,1).
edge(implementBoardWithReplies,parentsUseBulletinBoardWithReplies,1).
edge(avoidBadAdvice2,avoidBadAdvice1,1).
edge(implementTextMessaging,kidsUseTextMessaging,1).
edge(implementGetInformedSectionOfWebSite,implementGetInformedSectionOfWebSite1,1).
edge(kidsReadPollsAboutKids,webServicesSelfServe2,0.5).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,similarityWithOtherParentsProblems,0.5).
edge(easierAccessToPostReply,easierAccessToPostReply1,1).
edge(friendlyWebSite12,friendlyWebSite,1).
edge(realTimeECounsellingBeUsed,immediacy7,1).
edge(implementCyberCafPortalChatRoom,kidsUseCyberCafPortalChatRoom,1).
edge(maintainImplementCSWebServices1,maintainWebServices,1).
edge(kidsUseBulletinBoardWithDelayedModeration,sufficientlyModeratedWebServices4,-0.5).
edge(accommodateWebSiteTraffic,efficientWebServices2,0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,easierToFindPostsWebPostingTechnology,-0.5).
edge(connectBackToTheCommunity9,connectBackToTheCommunity10,1).
edge(implementGetInformedSectionOfWebSite,kidsReadGetInformedSectionOfWebSite,1).
edge(acquireServiceResources,maintainWebServices1,1).
edge(directResponseToKids,improveImageToKids,0.5).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,similarityOfProblems,0.5).
edge(kidsReadGeneralQuestionsAndAnswers,similarityOfProblems,0.5).
edge(kidsHaveOwnershipOfServices5,highQualityServices,0.5).
edge(kidsUseAskACounsellorSection,nonRealTimeECounsellingBeUsed,1).
edge(kidsUseTextMessaging,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(kidsUsePhoneCounselling1,kidsUsePhoneCounselling,1).
edge(kidsUseEmailCounselling,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(maintainPHLPhoneServices4,maintainPHLPhoneServices2,1).
edge(correctInterpretationOfCounsel1,correctInterpretationOfCounsel,1).
edge(implementPhoneFeedback2,implementFeedbackCollection,1).
edge(traceCalls,confidentialityParents2,-0.5).
edge(improveWebsiteContent2,highQualityServices,0.5).
edge(confidentialityKids5,confidentialityKids7,1).
edge(maintainAskACounsellorSection,kidsUseAskACounsellorSection,1).
edge(increasedWebServices4,friendlyWebSite2,0.5).
edge(feedback,acquireFeedback,1).
edge(kidsUseEmailCounselling,correctInterpretationOfCounsel,-0.5).
edge(implementOneOnOneChatRooms,kidsUseOneOnOneChatRooms,1).
edge(maintainPHLPhoneServices2,maintainPHLPhoneServices1,1).
edge(easierNavigationCSWebServices1,easierNavigationCSWebServices,1).
edge(kidsUseOneOnOneChatRooms,confidentialTechnologyBeUsed,1).
edge(implementDelay,implementCyberCafPortalChatRoom,1).
edge(maintainPhoneServices2,implementServices,1).
edge(directResponseToKids,friendlyWebSite2,0.5).
edge(kidsUseEmailCounselling,moderatedECounsellingBeUsed,1).
edge(moderatedECounsellingBeUsed,improveImageToKids,0.5).
edge(availableServices4,availableServices2,1).
edge(implementBulletinBoardWithDelayedModeration,kidsUseBulletinBoardWithDelayedModeration,1).
edge(kidsUseTextMessaging,anonymityCounsellors,0.5).
edge(servicesBeBilingual1,servicesBeBilingual,1).
edge(increasedWebServices3,increasedWebServices2,1).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,avoidBadAdvice,-0.5).
edge(acquireServiceResources,maintainPhoneServices2,1).
edge(avoidPresenceOfPedofiles2,highQualityServices,0.5).
edge(highQualityServices,highQualityServices1,1).
edge(efficientPhoneServices,efficientServices1,0.5).
edge(sufficientCounsellingResources1,sufficientCounsellingResources2,1).
edge(decreasePhoneWaitingTime2,decreasePhoneWaitingTime1,1).
edge(kidsHaveOwnershipOfServices4,kidsHaveOwnershipOfServices5,1).
edge(kidsUseVoiceCounselling,anonymousTechnologyBeUsed,1).
edge(avoidBadAdvice,avoidBadAdvice2,1).
edge(implementGeneralQuestionsAndAnswers,implementGeneralQuestionsAndAnswers1,1).
edge(anonymityParents4,anonymityKids6,1).
edge(kidsUseAskACounsellorSection,anonymityCounsellors,0.5).
edge(kidsUseOneOnOneChatRooms,correctInterpretationOfCounsel,-0.5).
edge(scheduleChatAtSpecificTimes,reduceContagionEffectOfHarmfulActions,0.5).
edge(maintainPHLWebServices2,maintainPHLWebServices1,1).
edge(maintainServicesAboveCompetition1,maintainServicesAboveCompetition,1).
edge(anonymityParents2,anonymityParents1,1).
edge(implementFeedbackCollection,acquireFeedback,1).
edge(moderateDiscussionBoards,implementBulletinBoardWithReplies,1).
edge(kidsUseAskACounsellorSection,correctInterpretationOfCounsel,-0.5).
edge(increaseWebResources1,increaseWebResources,1).
edge(immediacy1,immediacy,1).
edge(relevanceInKidsLives1,relevanceInKidsLives,1).
edge(avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,encourageKidsUsingWebServicesToUsePhoneServices1,0.5).
edge(parentsUseInformationSection,connectBackToTheCommunity3,0.5).
edge(confidentialityParents2,confidentialityParents1,1).
edge(increaseResourcesServices1,increaseResourcesServices,1).
edge(implementBoardWithReplies,implementBoardWithReplies1,1).
edge(provideWrittenCounselling,implementTextMessaging,1).
edge(parentsUseBulletinBoardWithReplies,connectBackToTheCommunity3,0.5).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,controlWebServices,0.5).
edge(feedbackFormSoftware,obtainNeededSoftware,1).
edge(maintainPhoneServices,immediacy2,0.5).
edge(kidsUseTextMessaging,moderatedECounsellingBeUsed,1).
edge(kidsUseCyberCafPortalChatRoom,correctInterpretationOfCounsel,-0.5).
edge(nonConfidentialTechnologyBeUsed,confidentialityKids1,-1).
edge(measureSuccessOfServices1,measureSuccessOfServices,1).
edge(confidentialityKids5,confidentiality,0.5).
edge(createCounsellingPosts,maintainAskACounsellorSection,1).
edge(implementAntiPrankingMessage,reducePrankCalls1,0.5).
edge(kidsUseCyberCafPortalChatRoom,anonymityCounsellors,0.5).
edge(moderatedECounsellingBeUsed,controlOfCounsellingWork1,-0.5).
edge(kidsReadGeneralQuestionsAndAnswers,kidsUseOnlineInformationProvided,1).
edge(parentsUsePhoneCounselling1,anonymityParents4,1).
edge(parentsUseInformationSection1,parentsUseInformationSection,1).
edge(immediacy4,immediacy3,1).
edge(kidsUseAskACounsellorSection,moderatedECounsellingBeUsed,1).
edge(highQualityServices,relevanceInKidsLives,0.5).
edge(connectBackToTheCommunity3,connectBackToTheCommunity42,1).
edge(efficientPhoneServices1,efficientPhoneServices,1).
edge(directResponseToKids2,highQualityServices,0.5).
edge(implementGeneralQuestionsAndAnswers,kidsReadGeneralQuestionsAndAnswers,1).
edge(kidsUseAskACounsellorSection,increasedWebServices4,0.5).
edge(avoidPresenceOfPedofiles1,avoidPresenceOfPedofiles2,1).
edge(implementVoiceCounselling1,implementVoiceCounselling,1).
edge(kidsUseOnlineInformationProvided,improveImageToKids,0.5).
edge(kidsUseVideoCounselling,correctInterpretationOfCounsel,0.5).
edge(connectBackToTheCommunity6,connectBackToTheCommunity8,1).
edge(kidsUseBulletinBoardWithReplies1,kidsUseBulletinBoardWithReplies,1).
edge(decreaseResponseTIme,immediacy7,0.5).
edge(maintainCSPhoneServices1,maintainCSPhoneServices,1).
edge(availableServices3,availableServices2,1).
edge(implementFeedbackForm,implementFeedbackForm1,1).
edge(connectBackToTheCommunity8,connectBackToTheCommunity9,1).
edge(implementInformationSection,maintainPHLWebServices2,1).
edge(implementPollsAboutKids,kidsReadPollsAboutKids,1).
edge(implementEmailCounselling1,implementEmailCounselling,1).
edge(moderatedECounsellingBeUsed,maintainImplementCSWebServices,1).
edge(realTimeECounsellingBeUsed,controlWebServices,-0.5).
edge(parentsUsePhoneCounselling1,connectBackToTheCommunity2,0.5).
edge(acquireServiceResources,maintainImplementCSServices,1).
edge(parentsUseBulletinBoardWithReplies,easyAccessToPostReply,-0.5).
edge(kidsUsePhoneCounselling,anonymityKids5,1).
edge(reducePrankCalls,reducePrankCalls1,1).
edge(maintainImplementCSWebServices2,maintainImplementCSWebServices3,1).
edge(serviceLevelsBeMet,efficientServices1,0.5).
edge(kidsUseGetInformedSectionOfWebSite,kidsReadGetInformedSectionOfWebSite,1).
edge(connectBackToTheCommunity1,connectBackToTheCommunity7,1).
edge(webServicesSelfServe3,webServicesSelfServe2,1).
edge(confidentialityParents1,confidentialityParents,1).
edge(nonAnonymousTechnologyBeUsed,anonymityKids3,-1).
edge(kidsUsePhoneCounselling,connectBackToTheCommunity1,0.5).
edge(avoidPresenceOfPedofiles1,avoidPresenceOfPedofiles,1).
edge(maintainImplementCSWebServices,maintainImplementCSWebServices2,1).
edge(kidsUseBulletinBoardWithDelayedModeration,increasedWebServices4,0.5).
edge(increasedWebServices2,increasedWebServices1,1).
edge(moderateDiscussionBoards,implementBulletinBoardWithDelayedModeration,1).
edge(confidentialityKids1,confidentialityKids2,1).
edge(immediacy6,friendlyWebSite12,0.5).
edge(confidentialityParents5,confidentialityParents3,1).
edge(easierAccessToPostReply,improveImageToKids,0.5).
edge(kidsUseBulletinBoardWithReplies,moderatedECounsellingBeUsed,1).
edge(strategicBluePrint,strategicBluePrintForWebsiteBeFollowed,1).
edge(parentsUseNToolToAllowParentsToTalkToEachOther1,parentsUseNToolToAllowParentsToTalkToEachOther,1).
edge(maintainImplementCSServices2,maintainImplementCSServices1,1).
edge(kidsUseTextMessaging,correctInterpretationOfCounsel,-0.5).
edge(kidsUseVoiceCounselling,increasedWebServices4,0.5).
edge(kidsUseAskACounsellorSection,nonConfidentialTechnologyBeUsed,1).
edge(immediacy6,immediacy4,1).
edge(voiceCounsellingBePerformed,maintainCSPhoneServices2,1).
edge(servicesBeProvidedForKidsBullyingLine,servicesBeProvidedForKidsBullyingLine1,1).
edge(kidsUseCyberCafPortalChatRoom,increasedWebServices4,0.5).
edge(kidsUseVideoCounselling,increasedWebServices4,0.5).
edge(friendlyWebSite2,friendlyWebSite1,1).
edge(technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,avoidBadAdvice,0.5).
edge(implementBulletinBoardWithDelayedModeration1,implementBulletinBoardWithDelayedModeration,1).
edge(nonRealTimeECounsellingBeUsed,immediacy7,-0.5).
edge(maintainImplementCSWebServices2,maintainImplementCSWebServices1,1).
edge(confidentialityKids2,confidentialityKids3,1).
edge(kidsUseCyberCafPortalChatRoom,moderatedECounsellingBeUsed,1).
edge(kidsReadGetInformedSectionOfWebSite,similarityOfProblems,0.5).
edge(kidsUseVideoCounselling,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,1).
edge(sufficientCounsellingResources,controlWebServices1,0.5).
edge(provideWebCounsellingWithVideo,implementVideoCounselling1,1).
edge(maintainCSPhoneServices2,maintainPhoneServices1,1).
edge(kidsHaveOwnershipOfServices,kidsHaveOwnershipOfServices2,1).
edge(decreaseResponseTIme4,efficientServices1,0.5).
edge(measureSuccessOfServices4,measureSuccessOfServices3,1).
edge(kidsUseBulletinBoardWithDelayedModeration,controlWebServices,-0.5).
edge(maintainCSPhoneServices2,maintainCSPhoneServices1,1).
edge(immediacy7,immediacy5,1).
edge(nonRealTimeECounsellingBeUsed,controlWebServices,0.5).
edge(parentsUseNToolToAllowParentsToTalkToEachOther,immediacy6,0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,technologyThatAllowsDialoguesBetweenKidsBeUsed,1).
edge(kidsUseVoiceCounselling,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,1).
edge(kidsUseOnlineInformationProvided,empoweringKidsToHelpThemselves,0.5).
edge(avoidDialoguesBetweenKids,avoidBadAdvice,0.5).
edge(answer80OfCallsWithin30SecondsOfMessageEnding,maintainCSPhoneServices2,1).
edge(kidsUseOneOnOneChatRooms,moderatedECounsellingBeUsed,1).
edge(provideRecordedMessages,phoneLibraryOfRecordedMessages,1).
edge(measureSuccessOfServices3,measureSuccessOfServices1,1).
edge(controlOfCounsellingWork1,controlOfCounsellingWork,1).
edge(encourageKidsUsingWebServicesToUsePhoneServices1,encourageKidsUsingWebServicesToUsePhoneServices,1).
edge(parentsUsePhoneCounselling1,confidentialityParents5,0.5).
edge(anonymityKids6,anonymityParents2,1).
edge(maintainImplementCSWebServices3,maintainImplementCSServices2,1).
edge(acquireFeedback,anonymity,-0.5).
edge(putContentOntoWebsite1,putContentOntoWebsite,1).
edge(kidsUseOneOnOneChatRooms,nonAnonymousTechnologyBeUsed,1).
edge(maintainPHLPhoneServices1,maintainPHLPhoneServices,1).
edge(maintainImplementPHLServices1,maintainImplementPHLServices2,1).
edge(anonymousTechnologyBeUsed,anonymityKids3,1).
edge(relevanceInKidsLives2,relevanceInKidsLives1,1).
edge(kidsUseEmailCounselling,nonRealTimeECounsellingBeUsed,1).
edge(decreaseResponseTIme4,decreaseResponseTIme3,1).
edge(parentsUseBulletinBoardWithReplies,immediacy6,-0.5).
edge(kidsUseBulletinBoardWithDelayedModeration,nonRealTimeECounsellingBeUsed,1).
edge(kidsUseEmailCounselling,confidentialTechnologyBeUsed,1).
edge(sufficientCounsellingResources1,sufficientCounsellingResources,1).
edge(implementCyberCafPortalChatRoom,implementCyberCafPortalChatRoom1,1).
edge(kidsUseBulletinBoardWithReplies,directResponseToKids,-1).
edge(kidsUseAskACounsellorSection,easierAccessToPostReply,0.5).
edge(kidsUseVoiceCounselling1,kidsUseVoiceCounselling,1).
edge(implementNToolToAllowParentsToTalkToEachOther,parentsUseNToolToAllowParentsToTalkToEachOther,1).
edge(kidsUseBulletinBoardWithReplies,increasedWebServices4,0.5).
edge(easyAccessToPostReply,easyAccessToPostReply1,1).
edge(nonAnonymousTechnologyBeUsed,controlWebServices,0.5).
edge(kidsUseVideoCounselling,nonAnonymousTechnologyBeUsed,1).
edge(kidsGetInformationThroughECounselling,kidsUseOnlineInformationProvided,1).
edge(technologyThatAllowsDialoguesBetweenKidsBeUsed,controlWebServices,-0.5).
edge(kidsUseVideoCounselling,realTimeECounsellingBeUsed,1).
edge(kidsUseTextMessaging,nonAnonymousTechnologyBeUsed,1).
edge(kidsUseCyberCafPortalChatRoom,realTimeECounsellingBeUsed,1).
edge(telephonyBeImplementedAndManaged,maintainPhoneServices,1).
edge(parentsUseBulletinBoardWithReplies,confidentialityParents4,-1).
edge(maintainCSPhoneServices2,kidsUsePhoneCounselling,1).
edge(confidentialityParents4,confidentialityParents3,1).
edge(kidsUseAskACounsellorSection,anonymousTechnologyBeUsed,1).
edge(confidentialityParents3,confidentialityParents2,1).
edge(improveWebsiteContent,improveWebsiteContent2,1).
edge(anonymityKids4,anonymityKids1,1).
edge(implementPhoneFeedback,measureSuccessOfServices2,0.5).
edge(serviceResources,acquireServiceResources,1).
edge(improveWebsiteContent1,improveWebsiteContent,1).
edge(kidsUseVoiceCounselling,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(kidsUseAskACounsellorSection,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,1).
edge(createCounsellingPosts,implementBulletinBoardWithDelayedModeration,1).
edge(maintainAskACounsellorSection,reduceNumberOfStepsWebPostingTechnology1,-0.5).
edge(reduceContagionEffectOfHarmfulActions,reduceContagionEffectOfHarmfulActions1,1).
edge(kidsUsePhoneCounselling,kidsHaveOwnershipOfServices1,1).
edge(kidsUseTextMessaging,confidentialTechnologyBeUsed,1).
edge(provideWrittenCounselling,implementOneOnOneChatRooms,1).
edge(easierToFindPostsWebPostingTechnology,easierToFindPostsWebPostingTechnology1,1).
edge(webSoftware,obtainSoftware,1).
edge(obtainSoftware,maintainWebServices,1).
edge(confidentialityKids3,confidentialityKids4,1).
edge(directResponseToKids,directResponseToKids1,1).
edge(maintainImplementCSServices1,maintainImplementCSServices,1).
edge(increaseWebResources,improveWebsiteContent1,0.5).
edge(sufficientlyModeratedWebServices,highQualityServices,0.5).
edge(kidsUseAskACounsellorSection1,kidsUseAskACounsellorSection,1).
edge(kidsReadGetInformedSectionOfWebSite,kidsUseOnlineInformationProvided,1).
edge(maintainWebServices1,implementServices,1).
edge(kidsUseAskACounsellorSection,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,0.5).
edge(connectBackToTheCommunity5,connectBackToTheCommunity8,1).
edge(anonymityKids2,anonymityKids4,1).
edge(kidsUseVideoCounselling,moderatedECounsellingBeUsed,1).
edge(kidsUseEmailCounselling,technologyThatDoesNotAllowDialoguesBetweenKidsBeUsed,1).
edge(kidsUseOneOnOneChatRooms,avoidDialoguesBetweenKidsAndCounsellorsOnTheWeb,-0.5).
edge(kidsUseBulletinBoardWithReplies,correctInterpretationOfCounsel,-0.5).
