% Kids and Youth  (edit me: node/2 edge/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, leaf/1, topgoal/1.
node(kidsUseAskACounsellorSection,task).
node(getEffectiveHelp,softgoal).
node(kidsUsePhoneCounselling,task).
node(helpBeAcquired,goal).
topgoal(helpBeAcquired).
node(usePhoneCounselling,task).
node(servicesBeFree,goal).
topgoal(servicesBeFree).
node(implementVoiceCounselling,task).
leaf(implementVoiceCounselling).
node(maintainPhoneCounselling,task).
leaf(maintainPhoneCounselling).
node(safetyOfServiceUsage,softgoal).
node(implementVideoCounselling,task).
leaf(implementVideoCounselling).
node(implementEmailCounselling,task).
leaf(implementEmailCounselling).
node(highQualityService,softgoal).
node(useVideoCounselling,task).
node(maintainAskACounsellorSection,task).
leaf(maintainAskACounsellorSection).
node(ownershipOfServiceKids,softgoal).
node(easyAccessToPostReply,softgoal).
node(ventEmotions,softgoal).
node(implementCyberCafPortalChatRoom,task).
leaf(implementCyberCafPortalChatRoom).
node(privacy,softgoal).
node(patientCounselor,softgoal).
leaf(patientCounselor).
node(contactCSAboutNonCrisisSituation,task).
leaf(contactCSAboutNonCrisisSituation).
node(confidentialityServices,softgoal).
leaf(confidentialityServices).
node(readPollsAboutKids,task).
node(decreasePhoneWaitingTime,softgoal).
node(confidentialityService,softgoal).
node(kidsUseGetInformedSectionOfWebSite,task).
node(implementTextMessaging,task).
leaf(implementTextMessaging).
node(useTextMessaging,task).
node(useEmailCounselling,task).
node(kidsUseCyberCafPortalChatRoom,task).
node(childrenDecideWhenToHangUpAndCall,softgoal).
node(maintainGetInformedSectionOfWebSite,task).
leaf(maintainGetInformedSectionOfWebSite).
node(useVoiceCounselling,task).
node(friendlyWebSite1,softgoal).
leaf(friendlyWebSite1).
node(highQualityServices,softgoal).
leaf(highQualityServices).
node(availabilityService,softgoal).
node(kidsUseVoiceCounselling,task).
node(connectBackToTheCommunity1,softgoal).
leaf(connectBackToTheCommunity1).
node(anonymityService,softgoal).
node(immediacyService,softgoal).
node(implementPollsAboutKids,task).
leaf(implementPollsAboutKids).
node(similarityWithOtherKidsProblems,softgoal).
leaf(similarityWithOtherKidsProblems).
node(implementBulletinBoardWithReplies,task).
leaf(implementBulletinBoardWithReplies).
node(kidsReadPollsAboutKids,task).
node(supportAndBeSupportedByOtherKids,softgoal).
node(readGeneralQuestionsAndAnswers,task).
node(similarityWithOtherKidsProblems1,softgoal).
node(ownershipOfServicesKids,softgoal).
leaf(ownershipOfServicesKids).
node(availabilityServices,softgoal).
leaf(availabilityServices).
node(decreasePhoneWaitingTime1,softgoal).
leaf(decreasePhoneWaitingTime1).
node(kidsReadGeneralQuestionsAndAnswers,task).
node(useCyberCafPortalChatRoom,task).
node(implementGeneralQuestionsAndAnswers,task).
leaf(implementGeneralQuestionsAndAnswers).
node(informationBeAcquiredOnWebsite,goal).
topgoal(informationBeAcquiredOnWebsite).
node(kidsUseTextMessaging,task).
node(implementOneOnOneChatRooms,task).
leaf(implementOneOnOneChatRooms).
node(provideFeedback,task).
leaf(provideFeedback).
node(useAskACounsellorSection,task).
node(anonymityServices,softgoal).
leaf(anonymityServices).
node(servicesBeFree1,goal).
leaf(servicesBeFree1).
topgoal(servicesBeFree1).
node(contactCSInCrisis,task).
leaf(contactCSInCrisis).
node(effectiveHelpInCrisis,softgoal).
node(effectiveHelpInNonCrisisSituation,softgoal).
node(connectBackToTheCommunity,softgoal).
node(kidsUseBulletinBoardWithReplies,task).
node(useOneOnOneChatRooms,task).
node(connectWithOtherKids1,softgoal).
leaf(connectWithOtherKids1).
node(friendlyWebSite,softgoal).
node(kidsUseOneOnOneChatRooms,task).
node(informKidsAboutAnonymityOfService,task).
node(immediacyServices,softgoal).
leaf(immediacyServices).
node(patientCounselor1,softgoal).
node(feedback,resource).
node(easyAccessToPostReply1,softgoal).
leaf(easyAccessToPostReply1).
node(beInformedOfServiceAnonymity,goal).
leaf(beInformedOfServiceAnonymity).
topgoal(beInformedOfServiceAnonymity).
node(kidsUseVideoCounselling,task).
node(kidsUseEmailCounselling,task).
node(comfortablenessWithService,softgoal).
node(useBulletinBoardWithReplies,task).
node(connectWithOtherKids,softgoal).
node(readGetInformedSectionOfWebSite,task).
edge(similarityWithOtherKidsProblems,similarityWithOtherKidsProblems1,1).
edge(patientCounselor1,getEffectiveHelp,0.5).
edge(useAskACounsellorSection,helpBeAcquired,1).
edge(useTextMessaging,kidsUseTextMessaging,1).
edge(confidentialityService,safetyOfServiceUsage,0.5).
edge(useCyberCafPortalChatRoom,helpBeAcquired,1).
edge(friendlyWebSite1,friendlyWebSite,1).
edge(ownershipOfServiceKids,comfortablenessWithService,0.5).
edge(patientCounselor,patientCounselor1,1).
edge(effectiveHelpInCrisis,getEffectiveHelp,0.5).
edge(highQualityService,getEffectiveHelp,0.5).
edge(implementPollsAboutKids,readPollsAboutKids,1).
edge(connectBackToTheCommunity1,connectBackToTheCommunity,1).
edge(decreasePhoneWaitingTime,effectiveHelpInCrisis,0.5).
edge(implementOneOnOneChatRooms,useOneOnOneChatRooms,1).
edge(useAskACounsellorSection,kidsUseAskACounsellorSection,1).
edge(provideFeedback,feedback,1).
edge(provideFeedback,privacy,-0.5).
edge(readGeneralQuestionsAndAnswers,kidsReadGeneralQuestionsAndAnswers,1).
edge(anonymityService,safetyOfServiceUsage,0.5).
edge(useCyberCafPortalChatRoom,kidsUseCyberCafPortalChatRoom,1).
edge(anonymityServices,anonymityService,1).
edge(availabilityService,getEffectiveHelp,0.5).
edge(easyAccessToPostReply,getEffectiveHelp,0.5).
edge(supportAndBeSupportedByOtherKids,comfortablenessWithService,0.5).
edge(ownershipOfServicesKids,ownershipOfServiceKids,1).
edge(usePhoneCounselling,helpBeAcquired,1).
edge(immediacyService,effectiveHelpInCrisis,0.5).
edge(servicesBeFree1,comfortablenessWithService,0.5).
edge(immediacyService,effectiveHelpInNonCrisisSituation,0.5).
edge(implementCyberCafPortalChatRoom,useCyberCafPortalChatRoom,1).
edge(servicesBeFree1,servicesBeFree,1).
edge(readPollsAboutKids,informationBeAcquiredOnWebsite,1).
edge(usePhoneCounselling,kidsUsePhoneCounselling,1).
edge(childrenDecideWhenToHangUpAndCall,privacy,0.5).
edge(implementGeneralQuestionsAndAnswers,readGeneralQuestionsAndAnswers,1).
edge(implementEmailCounselling,useEmailCounselling,1).
edge(maintainAskACounsellorSection,useAskACounsellorSection,1).
edge(immediacyService,safetyOfServiceUsage,0.5).
edge(readPollsAboutKids,kidsReadPollsAboutKids,1).
edge(implementVoiceCounselling,useVoiceCounselling,1).
edge(useVideoCounselling,helpBeAcquired,1).
edge(decreasePhoneWaitingTime1,decreasePhoneWaitingTime,1).
edge(anonymityService,comfortablenessWithService,0.5).
edge(useEmailCounselling,helpBeAcquired,1).
edge(readGeneralQuestionsAndAnswers,informationBeAcquiredOnWebsite,1).
edge(useBulletinBoardWithReplies,kidsUseBulletinBoardWithReplies,1).
edge(readGetInformedSectionOfWebSite,kidsUseGetInformedSectionOfWebSite,1).
edge(similarityWithOtherKidsProblems1,comfortablenessWithService,0.5).
edge(friendlyWebSite,getEffectiveHelp,0.5).
edge(useVoiceCounselling,helpBeAcquired,1).
edge(useVideoCounselling,kidsUseVideoCounselling,1).
edge(maintainPhoneCounselling,usePhoneCounselling,1).
edge(confidentialityService,privacy,0.5).
edge(ventEmotions,getEffectiveHelp,0.5).
edge(beInformedOfServiceAnonymity,comfortablenessWithService,0.5).
edge(availabilityServices,availabilityService,1).
edge(connectWithOtherKids,supportAndBeSupportedByOtherKids,0.5).
edge(provideFeedback,comfortablenessWithService,-0.5).
edge(beInformedOfServiceAnonymity,informKidsAboutAnonymityOfService,1).
edge(implementBulletinBoardWithReplies,useBulletinBoardWithReplies,1).
edge(readGetInformedSectionOfWebSite,informationBeAcquiredOnWebsite,1).
edge(confidentialityService,comfortablenessWithService,0.5).
edge(patientCounselor1,comfortablenessWithService,0.5).
edge(anonymityService,privacy,0.5).
edge(useOneOnOneChatRooms,kidsUseOneOnOneChatRooms,1).
edge(useVoiceCounselling,kidsUseVoiceCounselling,1).
edge(useTextMessaging,helpBeAcquired,1).
edge(useOneOnOneChatRooms,helpBeAcquired,1).
edge(highQualityServices,highQualityService,1).
edge(connectWithOtherKids1,connectWithOtherKids,1).
edge(easyAccessToPostReply1,easyAccessToPostReply,1).
edge(maintainGetInformedSectionOfWebSite,readGetInformedSectionOfWebSite,1).
edge(patientCounselor1,ventEmotions,0.5).
edge(ownershipOfServiceKids,childrenDecideWhenToHangUpAndCall,1).
edge(immediacyServices,immediacyService,1).
edge(implementVideoCounselling,useVideoCounselling,1).
edge(useEmailCounselling,kidsUseEmailCounselling,1).
edge(confidentialityServices,confidentialityService,1).
edge(implementTextMessaging,useTextMessaging,1).
edge(effectiveHelpInNonCrisisSituation,getEffectiveHelp,0.5).
