% Kids and Youth  (node/2 edge/3 dep/2 dec/3 leaf/1 topgoal/1)
:- discontiguous node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
:- dynamic node/2, edge/3, dep/2, dec/3, leaf/1, topgoal/1.
node(kidsUseAskACounsellorSection,task).
node(getEffectiveHelp,softgoal).
node(kidsUsePhoneCounselling,task).
node(helpBeAcquired,goal).
topgoal(helpBeAcquired).
node(usePhoneCounselling,task).
node(servicesBeFree,goal).
topgoal(servicesBeFree).
node(implementVoiceCounselling,task).
leaf(implementVoiceCounselling).
node(maintainPhoneCounselling,task).
leaf(maintainPhoneCounselling).
node(safetyOfServiceUsage,softgoal).
node(implementVideoCounselling,task).
leaf(implementVideoCounselling).
node(implementEmailCounselling,task).
leaf(implementEmailCounselling).
node(highQualityService,softgoal).
node(useVideoCounselling,task).
node(maintainAskACounsellorSection,task).
leaf(maintainAskACounsellorSection).
node(ownershipOfServiceKids,softgoal).
node(easyAccessToPostReply,softgoal).
node(ventEmotions,softgoal).
node(implementCyberCafPortalChatRoom,task).
leaf(implementCyberCafPortalChatRoom).
node(privacy,softgoal).
node(patientCounselor,softgoal).
leaf(patientCounselor).
node(contactCSAboutNonCrisisSituation,task).
leaf(contactCSAboutNonCrisisSituation).
node(confidentialityServices,softgoal).
leaf(confidentialityServices).
node(readPollsAboutKids,task).
node(decreasePhoneWaitingTime,softgoal).
node(confidentialityService,softgoal).
node(kidsUseGetInformedSectionOfWebSite,task).
node(implementTextMessaging,task).
leaf(implementTextMessaging).
node(useTextMessaging,task).
node(useEmailCounselling,task).
node(kidsUseCyberCafPortalChatRoom,task).
node(childrenDecideWhenToHangUpAndCall,softgoal).
node(maintainGetInformedSectionOfWebSite,task).
leaf(maintainGetInformedSectionOfWebSite).
node(useVoiceCounselling,task).
node(friendlyWebSite1,softgoal).
leaf(friendlyWebSite1).
node(highQualityServices,softgoal).
leaf(highQualityServices).
node(availabilityService,softgoal).
node(kidsUseVoiceCounselling,task).
node(connectBackToTheCommunity1,softgoal).
leaf(connectBackToTheCommunity1).
node(anonymityService,softgoal).
node(immediacyService,softgoal).
node(implementPollsAboutKids,task).
leaf(implementPollsAboutKids).
node(similarityWithOtherKidsProblems,softgoal).
leaf(similarityWithOtherKidsProblems).
node(implementBulletinBoardWithReplies,task).
leaf(implementBulletinBoardWithReplies).
node(kidsReadPollsAboutKids,task).
node(supportAndBeSupportedByOtherKids,softgoal).
node(readGeneralQuestionsAndAnswers,task).
node(similarityWithOtherKidsProblems1,softgoal).
node(ownershipOfServicesKids,softgoal).
leaf(ownershipOfServicesKids).
node(availabilityServices,softgoal).
leaf(availabilityServices).
node(decreasePhoneWaitingTime1,softgoal).
leaf(decreasePhoneWaitingTime1).
node(kidsReadGeneralQuestionsAndAnswers,task).
node(useCyberCafPortalChatRoom,task).
node(implementGeneralQuestionsAndAnswers,task).
leaf(implementGeneralQuestionsAndAnswers).
node(informationBeAcquiredOnWebsite,goal).
topgoal(informationBeAcquiredOnWebsite).
node(kidsUseTextMessaging,task).
node(implementOneOnOneChatRooms,task).
leaf(implementOneOnOneChatRooms).
node(provideFeedback,task).
leaf(provideFeedback).
node(useAskACounsellorSection,task).
node(anonymityServices,softgoal).
leaf(anonymityServices).
node(servicesBeFree1,goal).
leaf(servicesBeFree1).
topgoal(servicesBeFree1).
node(contactCSInCrisis,task).
leaf(contactCSInCrisis).
node(effectiveHelpInCrisis,softgoal).
node(effectiveHelpInNonCrisisSituation,softgoal).
node(connectBackToTheCommunity,softgoal).
node(kidsUseBulletinBoardWithReplies,task).
node(useOneOnOneChatRooms,task).
node(connectWithOtherKids1,softgoal).
leaf(connectWithOtherKids1).
node(friendlyWebSite,softgoal).
node(kidsUseOneOnOneChatRooms,task).
node(informKidsAboutAnonymityOfService,task).
node(immediacyServices,softgoal).
leaf(immediacyServices).
node(patientCounselor1,softgoal).
node(feedback,resource).
node(easyAccessToPostReply1,softgoal).
leaf(easyAccessToPostReply1).
node(beInformedOfServiceAnonymity,goal).
leaf(beInformedOfServiceAnonymity).
topgoal(beInformedOfServiceAnonymity).
node(kidsUseVideoCounselling,task).
node(kidsUseEmailCounselling,task).
node(comfortablenessWithService,softgoal).
node(useBulletinBoardWithReplies,task).
node(connectWithOtherKids,softgoal).
node(readGetInformedSectionOfWebSite,task).
dep(similarityWithOtherKidsProblems,similarityWithOtherKidsProblems1).
edge(patientCounselor1,getEffectiveHelp,0.5).
dec(useAskACounsellorSection,helpBeAcquired,or).
dep(useTextMessaging,kidsUseTextMessaging).
edge(confidentialityService,safetyOfServiceUsage,0.5).
dec(useCyberCafPortalChatRoom,helpBeAcquired,or).
dep(friendlyWebSite1,friendlyWebSite).
edge(ownershipOfServiceKids,comfortablenessWithService,0.5).
dep(patientCounselor,patientCounselor1).
edge(effectiveHelpInCrisis,getEffectiveHelp,0.5).
edge(highQualityService,getEffectiveHelp,0.5).
dep(implementPollsAboutKids,readPollsAboutKids).
dep(connectBackToTheCommunity1,connectBackToTheCommunity).
edge(decreasePhoneWaitingTime,effectiveHelpInCrisis,0.5).
dep(implementOneOnOneChatRooms,useOneOnOneChatRooms).
dep(useAskACounsellorSection,kidsUseAskACounsellorSection).
dep(provideFeedback,feedback).
edge(provideFeedback,privacy,-0.5).
dep(readGeneralQuestionsAndAnswers,kidsReadGeneralQuestionsAndAnswers).
edge(anonymityService,safetyOfServiceUsage,0.5).
dep(useCyberCafPortalChatRoom,kidsUseCyberCafPortalChatRoom).
dep(anonymityServices,anonymityService).
edge(availabilityService,getEffectiveHelp,0.5).
edge(easyAccessToPostReply,getEffectiveHelp,0.5).
edge(supportAndBeSupportedByOtherKids,comfortablenessWithService,0.5).
dep(ownershipOfServicesKids,ownershipOfServiceKids).
dec(usePhoneCounselling,helpBeAcquired,or).
edge(immediacyService,effectiveHelpInCrisis,0.5).
edge(servicesBeFree1,comfortablenessWithService,0.5).
edge(immediacyService,effectiveHelpInNonCrisisSituation,0.5).
dep(implementCyberCafPortalChatRoom,useCyberCafPortalChatRoom).
dep(servicesBeFree1,servicesBeFree).
dec(readPollsAboutKids,informationBeAcquiredOnWebsite,or).
dep(usePhoneCounselling,kidsUsePhoneCounselling).
edge(childrenDecideWhenToHangUpAndCall,privacy,0.5).
dep(implementGeneralQuestionsAndAnswers,readGeneralQuestionsAndAnswers).
dep(implementEmailCounselling,useEmailCounselling).
dep(maintainAskACounsellorSection,useAskACounsellorSection).
edge(immediacyService,safetyOfServiceUsage,0.5).
dep(readPollsAboutKids,kidsReadPollsAboutKids).
dep(implementVoiceCounselling,useVoiceCounselling).
dec(useVideoCounselling,helpBeAcquired,or).
dep(decreasePhoneWaitingTime1,decreasePhoneWaitingTime).
edge(anonymityService,comfortablenessWithService,0.5).
dec(useEmailCounselling,helpBeAcquired,or).
dec(readGeneralQuestionsAndAnswers,informationBeAcquiredOnWebsite,or).
dep(useBulletinBoardWithReplies,kidsUseBulletinBoardWithReplies).
dep(readGetInformedSectionOfWebSite,kidsUseGetInformedSectionOfWebSite).
edge(similarityWithOtherKidsProblems1,comfortablenessWithService,0.5).
edge(friendlyWebSite,getEffectiveHelp,0.5).
dec(useVoiceCounselling,helpBeAcquired,or).
dep(useVideoCounselling,kidsUseVideoCounselling).
dep(maintainPhoneCounselling,usePhoneCounselling).
edge(confidentialityService,privacy,0.5).
edge(ventEmotions,getEffectiveHelp,0.5).
edge(beInformedOfServiceAnonymity,comfortablenessWithService,0.5).
dep(availabilityServices,availabilityService).
edge(connectWithOtherKids,supportAndBeSupportedByOtherKids,0.5).
edge(provideFeedback,comfortablenessWithService,-0.5).
dep(beInformedOfServiceAnonymity,informKidsAboutAnonymityOfService).
dep(implementBulletinBoardWithReplies,useBulletinBoardWithReplies).
dec(readGetInformedSectionOfWebSite,informationBeAcquiredOnWebsite,or).
edge(confidentialityService,comfortablenessWithService,0.5).
edge(patientCounselor1,comfortablenessWithService,0.5).
edge(anonymityService,privacy,0.5).
dep(useOneOnOneChatRooms,kidsUseOneOnOneChatRooms).
dep(useVoiceCounselling,kidsUseVoiceCounselling).
dec(useTextMessaging,helpBeAcquired,or).
dec(useOneOnOneChatRooms,helpBeAcquired,or).
dep(highQualityServices,highQualityService).
dep(connectWithOtherKids1,connectWithOtherKids).
dep(easyAccessToPostReply1,easyAccessToPostReply).
dep(maintainGetInformedSectionOfWebSite,readGetInformedSectionOfWebSite).
edge(patientCounselor1,ventEmotions,0.5).
edge(ownershipOfServiceKids,childrenDecideWhenToHangUpAndCall,1).
dep(immediacyServices,immediacyService).
dep(implementVideoCounselling,useVideoCounselling).
dep(useEmailCounselling,kidsUseEmailCounselling).
dep(confidentialityServices,confidentialityService).
dep(implementTextMessaging,useTextMessaging).
edge(effectiveHelpInNonCrisisSituation,getEffectiveHelp,0.5).
