;;;; models/Modernize.lisp : GENERATED from models/Modernize.py by to-lisp.py
(<- modernize (or incrementalRewrite bigBangRewrite))
(<- bigBangRewrite (and layerSequence (hurts trackFeatureDelivery)))
(<- layerSequence (and portInternalClients portExternalClients))
(<- incrementalRewrite (and support existingApps dataService dataModel appFramework monitor (helps trackFeatureDelivery) (helps goodExampleAgileGov)))
(<- support (and documentation regressionTest))
(<- documentation chooseDocTool)
(<- chooseDocTool documentationTool)
(<- regressionTest (and serviceLayer createTestEnv numberTiers))
(<- serviceLayer (or svcLayerBizLogicInDb svcLayerExtractedBizLogic))
(<- numberTiers (or twoTier threeTier))
(<- createTestEnv (or dbVendorTestEnv generalTestEnv bakeoffResult))
(<- existingApps chooseCandidateSystem)
(<- dataService dataServiceSpec)
(<- dataServiceSpec dataServicePilot)
(<- dataModel (or comprehensiveDataModel extensibleDataModel specificDataModel))
(<- comprehensiveDataModel (and provideLogicalSchemaInternally defineDataModelSharedData buildInternalExtensibleModel (helps easyShareDataInternally)))
(<- buildInternalExtensibleModel dataModelPilot)
(<- extensibleDataModel (and defineExtMandatoryData externalDataModelExtendable (helps easyShareDataPartners) (helps easyShareDataInternally)))
(<- specificDataModel (and (or externalClientsGetExactRequest internalClientCoordinates externalClientCoordinates) (hurts easyShareDataPartners)))
(<- appFramework (and j2eeSpecification (helps goodExampleAgileGov)))
(<- appFramework (and dotNetFramework customFramework))
(<- monitor (or accessControlAssessed accessControlPilot monitoringPilot))
(defparameter *hard* '(modernize))
(defparameter *soft* '(trackFeatureDelivery goodExampleAgileGov easyShareDataPartners easyShareDataInternally))
