name: luamine
on:
  push:
    branches: [main]
    paths:
      - "luamine/**"
      - ".github/workflows/tests-luamine.yml"
  workflow_dispatch:
jobs:
  eg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: timm/moot
          path: moot
      - run: |
          sudo apt-get update -q
          sudo apt-get install -y lua5.4
          sudo ln -sf /usr/bin/lua5.4 /usr/local/bin/lua
      - run: cd luamine && lua luamine-eg.lua --all
        env:
          MOOT: ${{ github.workspace }}/moot
