name: ezr-py
on:
  push:
    branches: [main]
    paths:
      - "ezr-py/**"
      - ".github/workflows/tests-ezr-py.yml"
  workflow_dispatch:
jobs:
  eg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: timm/moot
          path: moot
      - run: cd ezr-py && python3 ezr2-eg.py all
        env:
          MOOT: ${{ github.workspace }}/moot
